function JPb(){}
function fAd(){}
function cAd(a){this.a=a}
function iAd(a){this.a=a}
function lAd(a){this.a=a}
function tAd(a){this.a=a}
function bAd(a){a.a.a=false}
function kAd(a){HY(a.a,null)}
function SLc(a,b){a.a.Pl(a,b)}
function pAd(a,b){this.a=a;this.b=b}
function TLc(a,b){SLc(a,(Mzc(),new Jzc(b)))}
function IPb(){IPb=FBe;HPb=new wPb(xdf,new JPb)}
function ULc(){PLc();QLc(this,new mMc(this));this.cd[BIe]=tff}
function wAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function Xzd(a,b,c,d,e,g,i,j){Tid(uid(),b,c,d,e,g,i,j,new wAd(a,b,c,d,e,g,i))}
function Zzd(b,c){try{var d=$wnd.jQuery(sxg).data(txg);var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function sAd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){Zzd(CXb(t9(a.a.i),286).Rl(),CXb(t9(a.a.b),286).Rl());!!a.a.f&&$cb(a.a.f)}}
function Yzd(b){thisic=b;$wnd.jQuery(sxg).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function oAd(a){CXb(t9(a.a.i),286).Rl()>0&&CXb(t9(a.a.b),286).Rl()>0&&Xzd(a.a,CXb(No(a.b,Skf),1),CXb(a.a.e.le(),1),CXb(t9(a.a.g),286).Rl(),CXb(t9(a.a.c),286).Rl(),CXb(t9(a.a.i),286).Rl(),CXb(t9(a.a.b),286).Rl(),false)}
function Tid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new oGc(b,Imf,rxg);try{q=nGc(p,Kmf,7);CFc(q,yFc(q,shf));CFc(q,yFc(q,shf));CFc(q,yFc(q,nmf));CFc(q,yFc(q,nmf));CFc(q,yFc(q,nmf));CFc(q,yFc(q,nmf));CFc(q,yFc(q,Umf));CFc(q,yFc(q,c));CFc(q,yFc(q,d));$Fc(q.a,jEe+e);$Fc(q.a,jEe+g);$Fc(q.a,jEe+i);$Fc(q.a,jEe+j);$Fc(q.a,k?SLe:vJe);mGc(p,n,(GGc(),FGc))}catch(a){a=iyc(a);if(EXb(a,255)){o=a;z1c(n,o)}else throw a}}
function $zd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,Ehd(uxg,uxg));this.Cc=vxg;!!this.uc&&(ix(this).id=vxg,undefined);p=new Szb(IKe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),gLe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,dHe,wxg):(y.Sc+=xxg);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(yxg);Rx(this.e,yxg);C9(this.e,Ehd(zxg,Axg));n=CXb(No(c,jOe),1).lastIndexOf(wJe);if(n>0){k=TSc(CXb(No(c,jOe),1),n);this.e.Qi(QSc(CXb(No(c,jOe),1),k,Bxg+k))}else{this.e.Qi(CXb(No(c,jOe),1)+Bxg)}Uw(this.e,(NE(),VC),new cAd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,dHe,wxg):(z.Sc+=xxg);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Wbc);this.b=new dkb;Ujb(this.b,Wbc);v=CXb(No(c,_kf),1);t=CXb(No(c,alf),1);u=0;s=0;try{u=v!=null?cQc(v,10,-2147483648,2147483647):0;s=t!=null?cQc(t,10,-2147483648,2147483647):0}catch(a){a=iyc(a);if(!EXb(a,287))throw a}if(!!d&&!d.Rd()){C=new KIc;for(j=d.be();j.he();){i=CXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+FAf+i[1];E=new K2c(w,w);Qo(E,rHe,i[0]);Qo(E,qHe,i[1]);tXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,vHe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new fAd);ecb(this.f,Ehd(Cxg,Dxg));bT(B,this.f,new szb(0.6))}}C9(this.i,Ehd(xAf,yAf));E9(this.i,rHe);Rx(this.i,rHe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,bHe,wxg):(x.Sc+=Exg);q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,Ehd(CAf,DAf));E9(this.b,qHe);Rx(this.b,qHe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(IKe));r=new ULc;Aw(r,new iAd(this),(IPb(),IPb(),HPb));r.cd.id=Fxg;TLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Wbc);E9(this.g,_Ge);Rx(this.g,_Ge);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Wbc);E9(this.c,$Ge);Rx(this.c,$Ge);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(Ehd(Hvf,Hvf),new lAd(this));D=new YX(Ehd(Gvf,Gvf),new pAd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new tAd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var sxg='#cropbox',Bxg='-crop',wxg='10px',Hxg='ImageCrop',Ixg='ImageCrop$1',Jxg='ImageCrop$2',Kxg='ImageCrop$3',Lxg='ImageCrop$4',Mxg='ImageCrop$5',Nxg='ImageCrop$6',Oxg='ImageCrop$7',vxg='JahiaGxtImageCrop',txg='Jcrop',Axg='New name',rxg='cropImage',Fxg='cropbox',Gxg='failure.crop.label',uxg='label.crop',zxg='newName.label',Exg='paddingLeft:10px;',xxg='paddingRight:10px;';fzc(789,777,{},JPb);_.Hk=function KPb(a){Yzd(CXb(CXb(a,226),391).a)};_.Kk=function LPb(){return HPb};var HPb;fzc(1034,183,dCe,ULc);fzc(1035,1036,{});_.Pl=function hMc(a,b){QLc(a,new mMc(a));a.a.Pl(a,b)};fzc(1038,1036,{});_.Pl=function qMc(a,b){!!a.a&&(a.a.Ml(a)[uff]=jEe,undefined);kNb(a.cd,b.a)};fzc(1581,364,DCe,$zd);_.Mm=function _zd(a,b,c,d){var e,g,i;jcb(this.c,ERc(a));jcb(this.g,ERc(b));H9(this.i,jEe+c);H9(this.b,jEe+d);if(this.a){g=CXb(this.e.le(),1);e=MSc(g,bTc(46));this.e.Qi(USc(g,0,g.lastIndexOf(Bxg))+Bxg+c+jMe+d+(e!=-1?USc(g,e,g.length):jEe))}i=this.f?CXb(hdb(this.f),331):null;!!i&&(c!=CXb(No(i,rHe),283).a||d!=CXb(No(i,qHe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;fzc(1582,1,YBe,cAd);_.Ad=function dAd(a){bAd(this,CXb(a,62))};_.a=null;fzc(1583,235,YBe,fAd);_.sg=function gAd(a){var b;b=CXb(XF(a),331);Zzd(CXb(No(b,rHe),283).a,CXb(No(b,qHe),283).a)};fzc(1584,1,{226:1,231:1,391:1},iAd);_.a=null;fzc(1585,237,YBe,lAd);_.tg=function mAd(a){kAd(this,CXb(a,59))};_.a=null;fzc(1586,237,YBe,pAd);_.tg=function qAd(a){oAd(this,CXb(a,59))};_.a=null;_.b=null;fzc(1587,1,YBe,tAd);_.Ad=function uAd(a){sAd(this,CXb(a,62))};_.a=null;fzc(1588,1204,{},wAd);_.em=function xAd(a){if(EXb(a,380)){tBc(Ehd(Gyf,Gyf)+XDe+Ehd(yUf,yUf))&&Xzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{sBc(Ehd(Gxg,Gxg)+XDe+a.kd());rb(Ehd(Gxg,Gxg),a)}};_.He=function yAd(a){var b;HY(this.a,null);b=new XYc;b.Td(Gsf,(RPc(),RPc(),QPc));iCd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;fzc(2133,1,BDe);_.Ck=function Ffe(){$Y(new $zd(this.a.o,this.a.o.n.q,this.a.a))};var hic=GQc(P1f,Hxg,1581),aic=GQc(P1f,Ixg,1582),bic=GQc(P1f,Jxg,1583),cic=GQc(P1f,Kxg,1584),dic=GQc(P1f,Lxg,1585),eic=GQc(P1f,Mxg,1586),fic=GQc(P1f,Nxg,1587),gic=GQc(P1f,Oxg,1588),e8b=GQc(Dfg,Erg,789);TDe(EKb)(2);