function Yyd(a){this.a=a}
function bzd(a){this.a=a}
function Oge(a){this.a=a}
function azd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function Nge(a){$Y(new Pyd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function Vyd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function Ryd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Uyd(a){var b,c;HY(a.a,null);eCd(a.b,Ehd(SPf,SPf));b=uid();c=new Yyd(a.b);a.c?Wid(b,a.d,c):Wjd(b,a.d,CXb(t9(a.e),1),c)}
function Wjd(b,c,d,e){var g,i,j;i=new oGc(b,Imf,Pxg);try{j=nGc(i,Kmf,2);CFc(j,yFc(j,Omf));CFc(j,yFc(j,shf));DFc(j,c);CFc(j,yFc(j,d));mGc(i,e,(GGc(),FGc))}catch(a){a=iyc(a);if(EXb(a,255)){g=a;z1c(e,g)}else throw a}}
function Oyd(a,b){var c;b>1?(c=Fhd(Qxg,Rxg,sXb(Xwc,OBe,1,[jEe+b]))):CXb(No(CXb(a.i.Bl(0),349),tlf),303)._d(Psf)?(c=Fhd(Sxg,Txg,sXb(Xwc,OBe,1,[CXb(No(a.q,jOe),1)]))):(c=Fhd(lGf,mGf,sXb(Xwc,OBe,1,[CXb(No(a.q,jOe),1)])));return c}
function Pyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,Uxg);!!this.G&&Bk(rk(this.G,MXe),Uxg);YY(this,false);this.a=new _hb;RT(this.a,Ehd(kvf,kvf));this.a.zb=false;Jx(this.a,false);Rx(this.a,Vxg);BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new KIc;p=new KIc;for(k=b.i.be();k.he();){j=CXb(k.ie(),349);tXb(o.c,o.d++,j);yIc(p,CXb(No(j,Skf),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),gLe),false);g.zb=false;this.b=pDd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$(Wxg+Ehd(bOf,cOf)+Xxg));aT(this.a,r)}i=o.d;jq(this.b.H.e,new Ryd(this,b,i,g,r,c,s));if(c){n=Ehd(RUf,Yxg);aT(this.a,new q$(n));ST(this,(Jod(),Iod(),Fod))}q=new YX(Ehd(gQf,gQf),new Vyd(this,a,c,p,r));e=new YX(Ehd(iQf,iQf),new bzd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var cyg='620',dyg='70%',Xxg=': <br />',Wxg='<br />',Zxg='<br /><br />',Yxg='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',eyg='DeleteActionItem$1$1',fyg='DeleteItemWindow',gyg='DeleteItemWindow$1',hyg='DeleteItemWindow$2',iyg='DeleteItemWindow$2$1',jyg='DeleteItemWindow$3',Txg='Do you really want to remove the selected PAGE {0}?',Rxg='Do you really want to remove the {0} selected resources?',Uxg='Informations',Vxg='JahiaGxtDeleteItem',byg='This node is still used by:',_xg='Those nodes are still used in:',Pxg='markForDeletion',Qxg='message.remove.multiple.confirm',$xg='message.remove.multiple.usage',Sxg='message.remove.single.page.confirm',ayg='message.remove.single.usage';fzc(1564,364,DCe,Pyd);_.a=null;_.b=null;fzc(1565,226,YBe,Ryd);_.og=function Syd(a){var b,c,d;b=CXb(a.c,303);c=b.Wd();d=Oyd(this.c,this.d);if(c>0){d+=Zxg+(this.d>1?Ehd($xg,_xg):Ehd(ayg,byg))}else{jT(this.a.a,this.b);jz(this.f,cyg,dyg);if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;fzc(1566,237,YBe,Vyd);_.tg=function Wyd(a){Uyd(this,CXb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;fzc(1567,1204,{},Yyd);_.em=function Zyd(a){dCd(this.a);rb(a.ld(),a);j2(Ehd(eof,rkf),a.ld(),null)};_.He=function $yd(a){var b;dCd(this.a);b=new XYc;b.Td(Fsf,(RPc(),RPc(),QPc));iCd(this.a,b);lCd(this.a)};_.a=null;fzc(1568,237,YBe,bzd);_.tg=function czd(a){azd(this,CXb(a,59))};_.a=null;fzc(2150,1,BDe);_.Ck=function Lge(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new KIc;for(e=c.i.be();e.he();){d=CXb(e.ie(),349);yIc(b,CXb(No(d,Skf),1))}a=uid();Djd(a,b,new Oge(this))}};fzc(2151,1204,{},Oge);_.em=function Pge(a){sBc(_Rf+a.ld())};_.He=function Qge(a){Nge(this,CXb(a,303))};_.a=null;var jrc=GQc(S2f,eyg,2151),Phc=GQc(P1f,fyg,1564),Lhc=GQc(P1f,gyg,1565),Nhc=GQc(P1f,hyg,1566),Mhc=GQc(P1f,iyg,1567),Ohc=GQc(P1f,jyg,1568);TDe(EKb)(3);