function mPb(){}
function Gzd(){}
function Dzd(a){this.b=a}
function Jzd(a){this.b=a}
function Mzd(a){this.b=a}
function Uzd(a){this.b=a}
function Czd(a){a.b.b=false}
function Lzd(a){HY(a.b,null)}
function ALc(a,b){a.b.Pl(a,b)}
function Qzd(a,b){this.b=a;this.c=b}
function BLc(a,b){ALc(a,(lzc(),new izc(b)))}
function lPb(){lPb=fBe;kPb=new _Ob(hQe,new mPb)}
function CLc(){xLc();yLc(this,new WLc(this));this.dd[UFe]=IQe}
function wzd(a,b,c,d,e,g,i,j){sid(Vhd(),b,c,d,e,g,i,j,new Xzd(a,b,c,d,e,g,i))}
function Xzd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function Tzd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){yzd(dXb(t9(a.b.j),286).Rl(),dXb(t9(a.b.c),286).Rl());!!a.b.g&&$cb(a.b.g)}}
function yzd(b,c){try{var d=$wnd.jQuery(Vbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function xzd(b){thisic=b;$wnd.jQuery(Vbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Pzd(a){dXb(t9(a.b.j),286).Rl()>0&&dXb(t9(a.b.c),286).Rl()>0&&wzd(a.b,dXb(Mo(a.c,rUe),1),dXb(a.b.f.me(),1),dXb(t9(a.b.i),286).Rl(),dXb(t9(a.b.d),286).Rl(),dXb(t9(a.b.j),286).Rl(),dXb(t9(a.b.c),286).Rl(),false)}
function sid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new UFc(b,GVe,'cropImage');try{q=TFc(p,HVe,7);gFc(q,cFc(q,WRe));gFc(q,cFc(q,WRe));gFc(q,cFc(q,nVe));gFc(q,cFc(q,nVe));gFc(q,cFc(q,nVe));gFc(q,cFc(q,nVe));gFc(q,cFc(q,JVe));gFc(q,cFc(q,c));gFc(q,cFc(q,d));EFc(q.b,HDe+e);EFc(q.b,HDe+g);EFc(q.b,HDe+i);EFc(q.b,HDe+j);EFc(q.b,k?KHe:uGe);SFc(p,n,(kGc(),jGc))}catch(a){a=Jxc(a);if(fXb(a,255)){o=a;$0c(n,o)}else throw a}}
function zzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,dhd(Wbf,Wbf));this.Dc=Xbf;!!this.vc&&(ix(this).id=Xbf,undefined);p=new Szb(dHe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),nHe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,YEe,Ybf):(y.Tc+=Zbf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi($bf);Rx(this.f,$bf);C9(this.f,dhd('newName.label','New name'));n=dXb(Mo(c,sIe),1).lastIndexOf(vGe);if(n>0){k=sSc(dXb(Mo(c,sIe),1),n);this.f.Ri(pSc(dXb(Mo(c,sIe),1),k,_bf+k))}else{this.f.Ri(dXb(Mo(c,sIe),1)+_bf)}Uw(this.f,(NE(),VC),new Dzd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,YEe,Ybf):(z.Tc+=Zbf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,vbc);this.c=new dkb;Ujb(this.c,vbc);v=dXb(Mo(c,zUe),1);t=dXb(Mo(c,AUe),1);u=0;s=0;try{u=v!=null?DPc(v,10,-2147483648,2147483647):0;s=t!=null?DPc(t,10,-2147483648,2147483647):0}catch(a){a=Jxc(a);if(!fXb(a,287))throw a}if(!!d&&!d.Sd()){C=new oIc;for(j=d.ce();j.ie();){i=dXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+u1e+i[1];E=new j2c(w,w);Po(E,jFe,i[0]);Po(E,iFe,i[1]);WWb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,mFe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new Gzd);ecb(this.g,dhd(acf,bcf));bT(B,this.g,new szb(0.6))}}C9(this.j,dhd(o1e,p1e));E9(this.j,jFe);Rx(this.j,jFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,WEe,Ybf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,dhd(s1e,t1e));E9(this.c,iFe);Rx(this.c,iFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(dHe));r=new CLc;Aw(r,new Jzd(this),(lPb(),lPb(),kPb));r.dd.id='cropbox';BLc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,vbc);E9(this.i,UEe);Rx(this.i,UEe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,vbc);E9(this.d,TEe);Rx(this.d,TEe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(dhd(D_e,D_e),new Mzd(this));D=new YX(dhd(C_e,C_e),new Qzd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new Uzd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var Vbf='#cropbox',_bf='-crop',Ybf='10px',Xbf='JahiaGxtImageCrop',ccf='failure.crop.label',Wbf='label.crop',Zbf='paddingRight:10px;';Gyc(785,773,{},mPb);_.Hk=function nPb(a){xzd(dXb(dXb(a,226),391).b)};_.Kk=function oPb(){return kPb};var kPb;Gyc(1029,182,FBe,CLc);Gyc(1030,1031,{});_.Pl=function RLc(a,b){yLc(a,new WLc(a));a.b.Pl(a,b)};Gyc(1033,1031,{});_.Pl=function $Lc(a,b){!!a.b&&(a.b.Ml(a)[JQe]=HDe,undefined);IMb(a.dd,b.b)};Gyc(1573,363,dCe,zzd);_.Mm=function Azd(a,b,c,d){var e,g,i;jcb(this.d,dRc(a));jcb(this.i,dRc(b));H9(this.j,HDe+c);H9(this.c,HDe+d);if(this.b){g=dXb(this.f.me(),1);e=lSc(g,CSc(46));this.f.Ri(tSc(g,0,g.lastIndexOf(_bf))+_bf+c+QHe+d+(e!=-1?tSc(g,e,g.length):HDe))}i=this.g?dXb(hdb(this.g),331):null;!!i&&(c!=dXb(Mo(i,jFe),283).b||d!=dXb(Mo(i,iFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;Gyc(1574,1,yBe,Dzd);_.Bd=function Ezd(a){Czd(this,dXb(a,62))};_.b=null;Gyc(1575,234,yBe,Gzd);_.tg=function Hzd(a){var b;b=dXb(XF(a),331);yzd(dXb(Mo(b,jFe),283).b,dXb(Mo(b,iFe),283).b)};Gyc(1576,1,{226:1,231:1,391:1},Jzd);_.b=null;Gyc(1577,236,yBe,Mzd);_.ug=function Nzd(a){Lzd(this,dXb(a,59))};_.b=null;Gyc(1578,236,yBe,Qzd);_.ug=function Rzd(a){Pzd(this,dXb(a,59))};_.b=null;_.c=null;Gyc(1579,1,yBe,Uzd);_.Bd=function Vzd(a){Tzd(this,dXb(a,62))};_.b=null;Gyc(1580,1196,{},Xzd);_.em=function Yzd(a){if(fXb(a,380)){$Ac(dhd(q0e,q0e)+xDe+dhd(Z8e,Z8e))&&wzd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{ZAc(dhd(ccf,ccf)+xDe+a.ld());rb(dhd(ccf,ccf),a)}};_.Ie=function Zzd(a){var b;HY(this.b,null);b=new wYc;b.Ud(QZe,(qPc(),qPc(),pPc));JBd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;Gyc(2125,1,bDe);_.Dk=function ffe(){$Y(new zzd(this.b.p,this.b.p.o.r,this.b.b))};var Ihc=fQc(saf,'ImageCrop',1573),Bhc=fQc(saf,'ImageCrop$1',1574),Chc=fQc(saf,'ImageCrop$2',1575),Dhc=fQc(saf,'ImageCrop$3',1576),Ehc=fQc(saf,'ImageCrop$4',1577),Fhc=fQc(saf,'ImageCrop$5',1578),Ghc=fQc(saf,'ImageCrop$6',1579),Hhc=fQc(saf,'ImageCrop$7',1580),I7b=fQc(bbf,Jbf,785);tDe(EKb)(2);