function xyd(a){this.b=a}
function Cyd(a){this.b=a}
function oge(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function Byd(a){HY(a.b,null)}
function nge(a){$Y(new oyd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function uyd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function qyd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function tyd(a){var b,c;HY(a.b,null);FBd(a.c,dhd(r7e,r7e));b=Vhd();c=new xyd(a.c);a.d?vid(b,a.e,c):vjd(b,a.e,dXb(t9(a.f),1),c)}
function vjd(b,c,d,e){var g,i,j;i=new UFc(b,GVe,'markForDeletion');try{j=TFc(i,HVe,2);gFc(j,cFc(j,IVe));gFc(j,cFc(j,WRe));hFc(j,c);gFc(j,cFc(j,d));SFc(i,e,(kGc(),jGc))}catch(a){a=Jxc(a);if(fXb(a,255)){g=a;$0c(e,g)}else throw a}}
function nyd(a,b){var c;b>1?(c=ehd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',VWb(wwc,oBe,1,[HDe+b]))):dXb(Mo(dXb(a.j.Bl(0),349),NUe),303).ae(XZe)?(c=ehd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',VWb(wwc,oBe,1,[dXb(Mo(a.r,sIe),1)]))):(c=ehd(L3e,M3e,VWb(wwc,oBe,1,[dXb(Mo(a.r,sIe),1)])));return c}
function oyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,dcf);!!this.H&&Bk(rk(this.H,UKe),dcf);YY(this,false);this.b=new _hb;RT(this.b,dhd(r_e,r_e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new oIc;p=new oIc;for(k=b.j.ce();k.ie();){j=dXb(k.je(),349);WWb(o.d,o.e++,j);cIc(p,dXb(Mo(j,rUe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),nHe),false);g.Ab=false;this.c=QCd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+dhd(x6e,y6e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new qyd(this,b,i,g,r,c,s));if(c){n=dhd(d9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(iod(),hod(),eod))}q=new YX(dhd(u7e,u7e),new uyd(this,a,c,p,r));e=new YX(dhd(v7e,v7e),new Cyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var dcf='Informations';Gyc(1556,363,dCe,oyd);_.b=null;_.c=null;Gyc(1557,225,yBe,qyd);_.pg=function ryd(a){var b,c,d;b=dXb(a.d,303);c=b.Xd();d=nyd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?dhd('message.remove.multiple.usage','Those nodes are still used in:'):dhd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;Gyc(1558,236,yBe,uyd);_.ug=function vyd(a){tyd(this,dXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;Gyc(1559,1196,{},xyd);_.em=function yyd(a){EBd(this.b);rb(a.md(),a);j2(dhd(NVe,$Te),a.md(),null)};_.Ie=function zyd(a){var b;EBd(this.b);b=new wYc;b.Ud(PZe,(qPc(),qPc(),pPc));JBd(this.b,b);MBd(this.b)};_.b=null;Gyc(1560,236,yBe,Cyd);_.ug=function Dyd(a){Byd(this,dXb(a,59))};_.b=null;Gyc(2142,1,bDe);_.Dk=function lge(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new oIc;for(e=c.j.ce();e.ie();){d=dXb(e.je(),349);cIc(b,dXb(Mo(d,rUe),1))}a=Vhd();cjd(a,b,new oge(this))}};Gyc(2143,1196,{},oge);_.em=function pge(a){ZAc(h8e+a.md())};_.Ie=function qge(a){nge(this,dXb(a,303))};_.b=null;var Kqc=fQc(xaf,'DeleteActionItem$1$1',2143),ohc=fQc(saf,'DeleteItemWindow',1556),khc=fQc(saf,'DeleteItemWindow$1',1557),mhc=fQc(saf,'DeleteItemWindow$2',1558),lhc=fQc(saf,'DeleteItemWindow$2$1',1559),nhc=fQc(saf,'DeleteItemWindow$3',1560);tDe(EKb)(3);