function uPb(){}
function Pzd(){}
function Mzd(a){this.a=a}
function Szd(a){this.a=a}
function Vzd(a){this.a=a}
function bAd(a){this.a=a}
function Lzd(a){a.a.a=false}
function Uzd(a){HY(a.a,null)}
function JLc(a,b){a.a.Ql(a,b)}
function Zzd(a,b){this.a=a;this.b=b}
function KLc(a,b){JLc(a,(xzc(),new uzc(b)))}
function tPb(){tPb=oBe;sPb=new hPb(hQe,new uPb)}
function LLc(){GLc();HLc(this,new dMc(this));this.cd[bGe]=zQe}
function Fzd(a,b,c,d,e,g,i,j){Bid(cid(),b,c,d,e,g,i,j,new eAd(a,b,c,d,e,g,i))}
function eAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function aAd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){Hzd(pXb(t9(a.a.i),286).Sl(),pXb(t9(a.a.b),286).Sl());!!a.a.f&&$cb(a.a.f)}}
function Hzd(b,c){try{var d=$wnd.jQuery(Lbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Gzd(b){thisic=b;$wnd.jQuery(Lbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Yzd(a){pXb(t9(a.a.i),286).Sl()>0&&pXb(t9(a.a.b),286).Sl()>0&&Fzd(a.a,pXb(No(a.b,jUe),1),pXb(a.a.e.le(),1),pXb(t9(a.a.g),286).Sl(),pXb(t9(a.a.c),286).Sl(),pXb(t9(a.a.i),286).Sl(),pXb(t9(a.a.b),286).Sl(),false)}
function Bid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new fGc(b,yVe,'cropImage');try{q=eGc(p,zVe,7);tFc(q,pFc(q,ORe));tFc(q,pFc(q,ORe));tFc(q,pFc(q,fVe));tFc(q,pFc(q,fVe));tFc(q,pFc(q,fVe));tFc(q,pFc(q,fVe));tFc(q,pFc(q,BVe));tFc(q,pFc(q,c));tFc(q,pFc(q,d));RFc(q.a,QDe+e);RFc(q.a,QDe+g);RFc(q.a,QDe+i);RFc(q.a,QDe+j);RFc(q.a,k?THe:DGe);dGc(p,n,(xGc(),wGc))}catch(a){a=Vxc(a);if(rXb(a,255)){o=a;h1c(n,o)}else throw a}}
function Izd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,mhd(Mbf,Mbf));this.Cc=Nbf;!!this.uc&&(ix(this).id=Nbf,undefined);p=new Szb(mHe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),xHe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,fFe,Obf):(y.Sc+=Pbf);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(Qbf);Rx(this.e,Qbf);C9(this.e,mhd('newName.label','New name'));n=pXb(No(c,AIe),1).lastIndexOf(EGe);if(n>0){k=BSc(pXb(No(c,AIe),1),n);this.e.Qi(ySc(pXb(No(c,AIe),1),k,Rbf+k))}else{this.e.Qi(pXb(No(c,AIe),1)+Rbf)}Uw(this.e,(NE(),VC),new Mzd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,fFe,Obf):(z.Sc+=Pbf);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Hbc);this.b=new dkb;Ujb(this.b,Hbc);v=pXb(No(c,rUe),1);t=pXb(No(c,sUe),1);u=0;s=0;try{u=v!=null?MPc(v,10,-2147483648,2147483647):0;s=t!=null?MPc(t,10,-2147483648,2147483647):0}catch(a){a=Vxc(a);if(!rXb(a,287))throw a}if(!!d&&!d.Rd()){C=new BIc;for(j=d.be();j.he();){i=pXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+k1e+i[1];E=new s2c(w,w);Qo(E,sFe,i[0]);Qo(E,rFe,i[1]);gXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,vFe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new Pzd);ecb(this.f,mhd(Sbf,Tbf));bT(B,this.f,new szb(0.6))}}C9(this.i,mhd(e1e,f1e));E9(this.i,sFe);Rx(this.i,sFe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,dFe,Obf):(x.Sc+='paddingLeft:10px;');q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,mhd(i1e,j1e));E9(this.b,rFe);Rx(this.b,rFe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(mHe));r=new LLc;Aw(r,new Szd(this),(tPb(),tPb(),sPb));r.cd.id='cropbox';KLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Hbc);E9(this.g,bFe);Rx(this.g,bFe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Hbc);E9(this.c,aFe);Rx(this.c,aFe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(mhd(t_e,t_e),new Vzd(this));D=new YX(mhd(s_e,s_e),new Zzd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new bAd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var Lbf='#cropbox',Rbf='-crop',Obf='10px',Nbf='JahiaGxtImageCrop',Ubf='failure.crop.label',Mbf='label.crop',Pbf='paddingRight:10px;';Syc(787,775,{},uPb);_.Hk=function vPb(a){Gzd(pXb(pXb(a,226),391).a)};_.Kk=function wPb(){return sPb};var sPb;Syc(1033,183,OBe,LLc);Syc(1034,1035,{});_.Ql=function $Lc(a,b){HLc(a,new dMc(a));a.a.Ql(a,b)};Syc(1037,1035,{});_.Ql=function hMc(a,b){!!a.a&&(a.a.Nl(a)[AQe]=QDe,undefined);HMb(a.cd,b.a)};Syc(1579,364,mCe,Izd);_.Nm=function Jzd(a,b,c,d){var e,g,i;jcb(this.c,mRc(a));jcb(this.g,mRc(b));H9(this.i,QDe+c);H9(this.b,QDe+d);if(this.a){g=pXb(this.e.le(),1);e=uSc(g,LSc(46));this.e.Qi(CSc(g,0,g.lastIndexOf(Rbf))+Rbf+c+ZHe+d+(e!=-1?CSc(g,e,g.length):QDe))}i=this.f?pXb(hdb(this.f),331):null;!!i&&(c!=pXb(No(i,sFe),283).a||d!=pXb(No(i,rFe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;Syc(1580,1,HBe,Mzd);_.Ad=function Nzd(a){Lzd(this,pXb(a,62))};_.a=null;Syc(1581,235,HBe,Pzd);_.sg=function Qzd(a){var b;b=pXb(XF(a),331);Hzd(pXb(No(b,sFe),283).a,pXb(No(b,rFe),283).a)};Syc(1582,1,{226:1,231:1,391:1},Szd);_.a=null;Syc(1583,237,HBe,Vzd);_.tg=function Wzd(a){Uzd(this,pXb(a,59))};_.a=null;Syc(1584,237,HBe,Zzd);_.tg=function $zd(a){Yzd(this,pXb(a,59))};_.a=null;_.b=null;Syc(1585,1,HBe,bAd);_.Ad=function cAd(a){aAd(this,pXb(a,62))};_.a=null;Syc(1586,1202,{},eAd);_.fm=function fAd(a){if(rXb(a,380)){kBc(mhd(g0e,g0e)+GDe+mhd(O8e,O8e))&&Fzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{jBc(mhd(Ubf,Ubf)+GDe+a.kd());rb(mhd(Ubf,Ubf),a)}};_.He=function gAd(a){var b;HY(this.a,null);b=new FYc;b.Td(HZe,(zPc(),zPc(),yPc));SBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;Syc(2131,1,kDe);_.Ck=function ofe(){$Y(new Izd(this.a.o,this.a.o.n.q,this.a.a))};var Uhc=oQc(haf,'ImageCrop',1579),Nhc=oQc(haf,'ImageCrop$1',1580),Ohc=oQc(haf,'ImageCrop$2',1581),Phc=oQc(haf,'ImageCrop$3',1582),Qhc=oQc(haf,'ImageCrop$4',1583),Rhc=oQc(haf,'ImageCrop$5',1584),Shc=oQc(haf,'ImageCrop$6',1585),Thc=oQc(haf,'ImageCrop$7',1586),T7b=oQc(Uaf,Abf,787);CDe(EKb)(2);