function Gyd(a){this.a=a}
function Lyd(a){this.a=a}
function xge(a){this.a=a}
function Kyd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function wge(a){$Y(new xyd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function Dyd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function zyd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Cyd(a){var b,c;HY(a.a,null);OBd(a.b,mhd(g7e,g7e));b=cid();c=new Gyd(a.b);a.c?Eid(b,a.d,c):Ejd(b,a.d,pXb(t9(a.e),1),c)}
function Ejd(b,c,d,e){var g,i,j;i=new fGc(b,yVe,'markForDeletion');try{j=eGc(i,zVe,2);tFc(j,pFc(j,AVe));tFc(j,pFc(j,ORe));uFc(j,c);tFc(j,pFc(j,d));dGc(i,e,(xGc(),wGc))}catch(a){a=Vxc(a);if(rXb(a,255)){g=a;h1c(e,g)}else throw a}}
function wyd(a,b){var c;b>1?(c=nhd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',fXb(Iwc,xBe,1,[QDe+b]))):pXb(No(pXb(a.i.Cl(0),349),FUe),303)._d(OZe)?(c=nhd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',fXb(Iwc,xBe,1,[pXb(No(a.q,AIe),1)]))):(c=nhd(A3e,B3e,fXb(Iwc,xBe,1,[pXb(No(a.q,AIe),1)])));return c}
function xyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,Vbf);!!this.G&&Bk(rk(this.G,$Ke),Vbf);YY(this,false);this.a=new _hb;RT(this.a,mhd(h_e,h_e));this.a.zb=false;Jx(this.a,false);Rx(this.a,'JahiaGxtDeleteItem');BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new BIc;p=new BIc;for(k=b.i.be();k.he();){j=pXb(k.ie(),349);gXb(o.c,o.d++,j);pIc(p,pXb(No(j,jUe),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),xHe),false);g.zb=false;this.b=ZCd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$('<br />'+mhd(m6e,n6e)+': <br />'));aT(this.a,r)}i=o.d;jq(this.b.H.e,new zyd(this,b,i,g,r,c,s));if(c){n=mhd(U8e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.a,new q$(n));ST(this,(rod(),qod(),nod))}q=new YX(mhd(j7e,j7e),new Dyd(this,a,c,p,r));e=new YX(mhd(k7e,k7e),new Lyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var Vbf='Informations';Syc(1562,364,mCe,xyd);_.a=null;_.b=null;Syc(1563,226,HBe,zyd);_.og=function Ayd(a){var b,c,d;b=pXb(a.c,303);c=b.Wd();d=wyd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?mhd('message.remove.multiple.usage','Those nodes are still used in:'):mhd('message.remove.single.usage','This node is still used by:'))}else{jT(this.a.a,this.b);jz(this.f,'620','70%');if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;Syc(1564,237,HBe,Dyd);_.tg=function Eyd(a){Cyd(this,pXb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;Syc(1565,1202,{},Gyd);_.fm=function Hyd(a){NBd(this.a);rb(a.ld(),a);j2(mhd(FVe,_Ne),a.ld(),null)};_.He=function Iyd(a){var b;NBd(this.a);b=new FYc;b.Td(GZe,(zPc(),zPc(),yPc));SBd(this.a,b);VBd(this.a)};_.a=null;Syc(1566,237,HBe,Lyd);_.tg=function Myd(a){Kyd(this,pXb(a,59))};_.a=null;Syc(2148,1,kDe);_.Ck=function uge(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new BIc;for(e=c.i.be();e.he();){d=pXb(e.ie(),349);pIc(b,pXb(No(d,jUe),1))}a=cid();ljd(a,b,new xge(this))}};Syc(2149,1202,{},xge);_.fm=function yge(a){jBc(Y7e+a.ld())};_.He=function zge(a){wge(this,pXb(a,303))};_.a=null;var Wqc=oQc(maf,'DeleteActionItem$1$1',2149),Ahc=oQc(haf,'DeleteItemWindow',1562),whc=oQc(haf,'DeleteItemWindow$1',1563),yhc=oQc(haf,'DeleteItemWindow$2',1564),xhc=oQc(haf,'DeleteItemWindow$2$1',1565),zhc=oQc(haf,'DeleteItemWindow$3',1566);CDe(EKb)(3);