function IPb(){}
function XBd(){}
function UBd(a){this.a=a}
function $Bd(a){this.a=a}
function bCd(a){this.a=a}
function jCd(a){this.a=a}
function TBd(a){a.a.a=false}
function aCd(a){UY(a.a,null)}
function fCd(a,b){this.a=a;this.b=b}
function GOc(a,b){FOc(a,(hCc(),new eCc(b)))}
function HPb(){HPb=$Re;GPb=new vPb(e5e,new IPb)}
function NBd(a,b,c,d,e,g,i,j){Kld(lld(),b,c,d,e,g,i,j,new mCd(a,b,c,d,e,g,i))}
function mCd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function PBd(b,c){try{var d=$wnd.jQuery(Utf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function iCd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){PBd(BXb(y9(a.a.i),287).bm(),BXb(y9(a.a.b),287).bm());!!a.a.f&&ddb(a.a.f)}}
function OBd(b){thisic=b;$wnd.jQuery(Utf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function eCd(a){BXb(y9(a.a.i),287).bm()>0&&BXb(y9(a.a.b),287).bm()>0&&NBd(a.a,BXb(Eo(a.b,t9e),1),BXb(a.a.e.ne(),1),BXb(y9(a.a.g),287).bm(),BXb(y9(a.a.c),287).bm(),BXb(y9(a.a.i),287).bm(),BXb(y9(a.a.b),287).bm(),false)}
function Kld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new $Ic(b,Kaf,'cropImage');try{q=ZIc(p,Laf,7);mIc(q,iIc(q,W6e));mIc(q,iIc(q,W6e));mIc(q,iIc(q,raf));mIc(q,iIc(q,raf));mIc(q,iIc(q,raf));mIc(q,iIc(q,raf));mIc(q,iIc(q,Naf));mIc(q,iIc(q,c));mIc(q,iIc(q,d));KIc(q.a,EUe+e);KIc(q.a,EUe+g);KIc(q.a,EUe+i);KIc(q.a,EUe+j);KIc(q.a,k?IYe:sXe);YIc(p,n,(qJc(),pJc))}catch(a){a=FAc(a);if(DXb(a,256)){o=a;d4c(n,o)}else throw a}}
function QBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,ukd(Vtf,Vtf));this.Dc=Wtf;!!this.vc&&(gx(this).id=Wtf,undefined);p=new _zb(bYe);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),mYe),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,UVe,Xtf):(y.Tc+=Ytf);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(Ztf);Px(this.e,Ztf);H9(this.e,ukd('newName.label','New name'));n=BXb(Eo(c,qZe),1).lastIndexOf(tXe);if(n>0){k=yVc(BXb(Eo(c,qZe),1),n);this.e.$i(uVc(BXb(Eo(c,qZe),1),k,$tf+k))}else{this.e.$i(BXb(Eo(c,qZe),1)+$tf)}Sw(this.e,(RE(),ZC),new UBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,UVe,Xtf):(z.Tc+=Ytf);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,Rbc);this.b=new ikb;Zjb(this.b,Rbc);v=BXb(Eo(c,A9e),1);t=BXb(Eo(c,B9e),1);u=0;s=0;try{u=v!=null?ISc(v,10,-2147483648,2147483647):0;s=t!=null?ISc(t,10,-2147483648,2147483647):0}catch(a){a=FAc(a);if(!DXb(a,288))throw a}if(!!d&&!d.Td()){C=new uLc;for(j=d.de();j.je();){i=BXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+rif+i[1];E=new s5c(w,w);Ho(E,fWe,i[0]);Ho(E,eWe,i[1]);sXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,iWe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new XBd);kcb(this.f,ukd(_tf,auf));oT(B,this.f,new Bzb(0.6))}}H9(this.i,ukd(lif,mif));J9(this.i,fWe);Px(this.i,fWe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,SVe,Xtf):(x.Tc+='paddingLeft:10px;');q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,ukd(pif,qif));J9(this.b,eWe);Px(this.b,eWe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(bYe));r=new HOc;yw(r,new $Bd(this),(HPb(),HPb(),GPb));r.dd.id='cropbox';GOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,Rbc);J9(this.g,OVe);Px(this.g,OVe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,Rbc);J9(this.c,NVe);Px(this.c,NVe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(ukd(qgf,qgf),new bCd(this));D=new jY(ukd(vgf,vgf),new fCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new jCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var Utf='#cropbox',$tf='-crop',Xtf='10px',Wtf='JahiaGxtImageCrop',buf='failure.crop.label',Vtf='label.crop',Ytf='paddingRight:10px;';CBc(787,775,{},IPb);_.Sk=function JPb(a){OBd(BXb(BXb(a,227),393).a)};_.Vk=function KPb(){return GPb};var GPb;CBc(1566,364,$Se,QBd);_.Mm=function RBd(a,b,c,d){var e,g,i;ocb(this.c,iUc(a));ocb(this.g,iUc(b));M9(this.i,EUe+c);M9(this.b,EUe+d);if(this.a){g=BXb(this.e.ne(),1);e=qVc(g,IVc(46));this.e.$i(zVc(g,0,g.lastIndexOf($tf))+$tf+c+OYe+d+(e!=-1?zVc(g,e,g.length):EUe))}i=this.f?BXb(mdb(this.f),333):null;!!i&&(c!=BXb(Eo(i,fWe),284).a||d!=BXb(Eo(i,eWe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;CBc(1567,1,rSe,UBd);_.Bd=function VBd(a){TBd(this,BXb(a,61))};_.a=null;CBc(1568,235,rSe,XBd);_.wg=function YBd(a){var b;b=BXb(fG(a),333);PBd(BXb(Eo(b,fWe),284).a,BXb(Eo(b,eWe),284).a)};CBc(1569,1,{227:1,232:1,393:1},$Bd);_.a=null;CBc(1570,237,rSe,bCd);_.xg=function cCd(a){aCd(this,BXb(a,58))};_.a=null;CBc(1571,237,rSe,fCd);_.xg=function gCd(a){eCd(this,BXb(a,58))};_.a=null;_.b=null;CBc(1572,1,rSe,jCd);_.Bd=function kCd(a){iCd(this,BXb(a,61))};_.a=null;CBc(1573,1203,{},mCd);_.qm=function nCd(a){if(DXb(a,382)){XDc(ukd(Hhf,Hhf)+uUe+ukd(Vqf,Vqf))&&NBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{WDc(ukd(buf,buf)+uUe+a.ld());rb(ukd(buf,buf),a)}};_.Je=function oCd(a){var b;UY(this.a,null);b=new B_c;b.Vd(Gef,(vSc(),vSc(),uSc));this.a.d.Dm(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;CBc(2261,1,ZTe);_.Nk=function Eve(){mZ(new QBd(this.a.o,this.a.o.zm().q,this.a.a))};var Thc=kTc(wsf,'ImageCrop',1566),Mhc=kTc(wsf,'ImageCrop$1',1567),Nhc=kTc(wsf,'ImageCrop$2',1568),Ohc=kTc(wsf,'ImageCrop$3',1569),Phc=kTc(wsf,'ImageCrop$4',1570),Qhc=kTc(wsf,'ImageCrop$5',1571),Rhc=kTc(wsf,'ImageCrop$6',1572),Shc=kTc(wsf,'ImageCrop$7',1573),b8b=kTc(gtf,ftf,787);qUe(VKb)(2);