function TAd(a){this.a=a}
function Nwe(a){this.a=a}
function SAd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function OAd(a,b){this.a=a;this.b=b}
function LAd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function HAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Mwe(a){mZ(new FAd(a.a.a.o,a.a.a.o.zm(),a.a.a.b))}
function KAd(a){var b,c;UY(a.a,null);a.b.Cm(ukd(mpf,mpf));b=lld();c=new OAd(a.b,a.d);a.c?Nld(b,a.d,c):Qmd(b,a.d,BXb(y9(a.e),1),c)}
function Qmd(b,c,d,e){var g,i,j;i=new $Ic(b,Kaf,'markForDeletion');try{j=ZIc(i,Laf,2);mIc(j,iIc(j,Maf));mIc(j,iIc(j,W6e));nIc(j,c);mIc(j,iIc(j,d));YIc(i,e,(qJc(),pJc))}catch(a){a=FAc(a);if(DXb(a,256)){g=a;d4c(e,g)}else throw a}}
function EAd(a,b){var c;b>1?(c=vkd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',rXb(szc,hSe,1,[EUe+b]))):BXb(Eo(BXb(a.i.Ml(0),351),R9e),304).be(Ref)?(c=vkd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',rXb(szc,hSe,1,[BXb(Eo(a.q,qZe),1)]))):(c=vkd(brf,crf,rXb(szc,hSe,1,[BXb(Eo(a.q,qZe),1)])));return c}
function FAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,cuf);!!this.G&&sk(ik(this.G,S_e),cuf);kZ(this,false);this.a=new eib;cU(this.a,ukd(Thf,Thf));this.a.Ab=false;Hx(this.a,false);Px(this.a,'JahiaGxtDeleteItem');MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new uLc;p=new uLc;for(k=b.i.de();k.je();){j=BXb(k.ke(),351);sXb(o.c,o.d++,j);iLc(p,BXb(Eo(j,t9e),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),mYe),false);g.Ab=false;this.b=gFd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$('<br />'+ukd(uof,vof)+': <br />'));nT(this.a,r)}i=o.d;aq(this.b.H.e,new HAd(this,b,i,g,r,c,s));if(c){n=ukd(drf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.a,new I$(n));dU(this,(Qrd(),Prd(),Mrd))}q=new jY(ukd(ppf,ppf),new LAd(this,a,c,p,r));e=new jY(ukd(qpf,qpf),new TAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var cuf='Informations';CBc(1549,364,$Se,FAd);_.a=null;_.b=null;CBc(1550,225,rSe,HAd);_.rg=function IAd(a){var b,c,d;b=BXb(a.c,304);c=b.Yd();d=EAd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?ukd('message.remove.multiple.usage','Those nodes are still used in:'):ukd('message.remove.single.usage','This node is still used by:'))}else{wT(this.a.a,this.b);hz(this.f,'620','70%');if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;CBc(1551,237,rSe,LAd);_.xg=function MAd(a){KAd(this,BXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;CBc(1552,1203,{},OAd);_.qm=function PAd(a){this.a.Bm();rb(a.md(),a);H2(ukd(Qaf,$8e),a.md(),null)};_.Je=function QAd(a){var b,c;this.a.Bm();c=null;DXb(this.a,431)?(c=BXb(this.a,431).c.t):DXb(this.a,418)&&(c=BXb(this.a,418));b=new B_c;!!c&&nLc(this.b,BXb(Eo(c.o.g,t9e),1),0)!=-1?b.Vd(Def,c.o.g):b.Vd(Fef,(vSc(),vSc(),uSc));this.a.Dm(b);this.a.Em(null)};_.a=null;_.b=null;CBc(1553,237,rSe,TAd);_.xg=function UAd(a){SAd(this,BXb(a,58))};_.a=null;CBc(2278,1,ZTe);_.Nk=function Kwe(){var a,b,c,d,e;c=this.a.o.zm();if(!c.i.Td()){b=new uLc;for(e=c.i.de();e.je();){d=BXb(e.ke(),351);iLc(b,BXb(Eo(d,t9e),1))}a=lld();ymd(a,b,new Nwe(this))}};CBc(2279,1203,{},Nwe);_.qm=function Owe(a){WDc(_pf+a.md())};_.Je=function Pwe(a){Mwe(this,BXb(a,304))};_.a=null;var Ftc=kTc(Bsf,'DeleteActionItem$1$1',2279),zhc=kTc(wsf,'DeleteItemWindow',1549),vhc=kTc(wsf,'DeleteItemWindow$1',1550),xhc=kTc(wsf,'DeleteItemWindow$2',1551),whc=kTc(wsf,'DeleteItemWindow$2$1',1552),yhc=kTc(wsf,'DeleteItemWindow$3',1553);qUe(VKb)(3);