function $Pb(){}
function vAd(){}
function sAd(a){this.b=a}
function yAd(a){this.b=a}
function BAd(a){this.b=a}
function JAd(a){this.b=a}
function rAd(a){a.b.b=false}
function AAd(a){HY(a.b,null)}
function oMc(a,b){a.b.Yl(a,b)}
function FAd(a,b){this.b=a;this.c=b}
function pMc(a,b){oMc(a,(dAc(),new aAc(b)))}
function ZPb(){ZPb=WBe;YPb=new NPb(XQe,new $Pb)}
function qMc(){lMc();mMc(this,new KMc(this));this.dd[KGe]=wRe}
function lAd(a,b,c,d,e,g,i,j){hjd(Kid(),b,c,d,e,g,i,j,new MAd(a,b,c,d,e,g,i))}
function MAd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function nAd(b,c){try{var d=$wnd.jQuery(Ecf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function IAd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){nAd(TXb(t9(a.b.j),286).$l(),TXb(t9(a.b.c),286).$l());!!a.b.g&&$cb(a.b.g)}}
function mAd(b){thisic=b;$wnd.jQuery(Ecf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Vm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function EAd(a){TXb(t9(a.b.j),286).$l()>0&&TXb(t9(a.b.c),286).$l()>0&&lAd(a.b,TXb(Mo(a.c,eVe),1),TXb(a.b.f.me(),1),TXb(t9(a.b.i),286).$l(),TXb(t9(a.b.d),286).$l(),TXb(t9(a.b.j),286).$l(),TXb(t9(a.b.c),286).$l(),false)}
function hjd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new MGc(b,tWe,'cropImage');try{q=LGc(p,uWe,7);$Fc(q,WFc(q,KSe));$Fc(q,WFc(q,KSe));$Fc(q,WFc(q,aWe));$Fc(q,WFc(q,aWe));$Fc(q,WFc(q,aWe));$Fc(q,WFc(q,aWe));$Fc(q,WFc(q,wWe));$Fc(q,WFc(q,c));$Fc(q,WFc(q,d));wGc(q.b,xEe+e);wGc(q.b,xEe+g);wGc(q.b,xEe+i);wGc(q.b,xEe+j);wGc(q.b,k?AIe:kHe);KGc(p,n,(cHc(),bHc))}catch(a){a=Byc(a);if(VXb(a,255)){o=a;P1c(n,o)}else throw a}}
function oAd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,Uhd(Fcf,Fcf));this.Dc=Gcf;!!this.vc&&(ix(this).id=Gcf,undefined);p=new Szb(VHe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),dIe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,OFe,Hcf):(y.Tc+=Icf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(Jcf);Rx(this.f,Jcf);C9(this.f,Uhd('newName.label','New name'));n=TXb(Mo(c,iJe),1).lastIndexOf(lHe);if(n>0){k=hTc(TXb(Mo(c,iJe),1),n);this.f.Ri(eTc(TXb(Mo(c,iJe),1),k,Kcf+k))}else{this.f.Ri(TXb(Mo(c,iJe),1)+Kcf)}Uw(this.f,(NE(),VC),new sAd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,OFe,Hcf):(z.Tc+=Icf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,ncc);this.c=new dkb;Ujb(this.c,ncc);v=TXb(Mo(c,mVe),1);t=TXb(Mo(c,nVe),1);u=0;s=0;try{u=v!=null?rQc(v,10,-2147483648,2147483647):0;s=t!=null?rQc(t,10,-2147483648,2147483647):0}catch(a){a=Byc(a);if(!VXb(a,287))throw a}if(!!d&&!d.Sd()){C=new gJc;for(j=d.ce();j.ie();){i=TXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+f2e+i[1];E=new $2c(w,w);Po(E,_Fe,i[0]);Po(E,$Fe,i[1]);KXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,cGe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new vAd);ecb(this.g,Uhd(Lcf,Mcf));bT(B,this.g,new szb(0.6))}}C9(this.j,Uhd(_1e,a2e));E9(this.j,_Fe);Rx(this.j,_Fe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,MFe,Hcf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,Uhd(d2e,e2e));E9(this.c,$Fe);Rx(this.c,$Fe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(VHe));r=new qMc;Aw(r,new yAd(this),(ZPb(),ZPb(),YPb));r.dd.id='cropbox';pMc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,ncc);E9(this.i,KFe);Rx(this.i,KFe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,ncc);E9(this.d,JFe);Rx(this.d,JFe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(Uhd(o0e,o0e),new BAd(this));D=new YX(Uhd(n0e,n0e),new FAd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new JAd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var Ecf='#cropbox',Kcf='-crop',Hcf='10px',Gcf='JahiaGxtImageCrop',Ncf='failure.crop.label',Fcf='label.crop',Icf='paddingRight:10px;';yzc(790,778,{},$Pb);_.Pk=function _Pb(a){mAd(TXb(TXb(a,226),391).b)};_.Sk=function aQb(){return YPb};var YPb;yzc(1032,182,uCe,qMc);yzc(1033,1034,{});_.Yl=function FMc(a,b){mMc(a,new KMc(a));a.b.Yl(a,b)};yzc(1036,1034,{});_.Yl=function OMc(a,b){!!a.b&&(a.b.Vl(a)[xRe]=xEe,undefined);nNb(a.dd,b.b)};yzc(1576,363,UCe,oAd);_.Vm=function pAd(a,b,c,d){var e,g,i;jcb(this.d,TRc(a));jcb(this.i,TRc(b));H9(this.j,xEe+c);H9(this.c,xEe+d);if(this.b){g=TXb(this.f.me(),1);e=_Sc(g,rTc(46));this.f.Ri(iTc(g,0,g.lastIndexOf(Kcf))+Kcf+c+GIe+d+(e!=-1?iTc(g,e,g.length):xEe))}i=this.g?TXb(hdb(this.g),331):null;!!i&&(c!=TXb(Mo(i,_Fe),283).b||d!=TXb(Mo(i,$Fe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;yzc(1577,1,nCe,sAd);_.Bd=function tAd(a){rAd(this,TXb(a,62))};_.b=null;yzc(1578,234,nCe,vAd);_.tg=function wAd(a){var b;b=TXb(XF(a),331);nAd(TXb(Mo(b,_Fe),283).b,TXb(Mo(b,$Fe),283).b)};yzc(1579,1,{226:1,231:1,391:1},yAd);_.b=null;yzc(1580,236,nCe,BAd);_.ug=function CAd(a){AAd(this,TXb(a,59))};_.b=null;yzc(1581,236,nCe,FAd);_.ug=function GAd(a){EAd(this,TXb(a,59))};_.b=null;_.c=null;yzc(1582,1,nCe,JAd);_.Bd=function KAd(a){IAd(this,TXb(a,62))};_.b=null;yzc(1583,1199,{},MAd);_.nm=function NAd(a){if(VXb(a,380)){SBc(Uhd(b1e,b1e)+nEe+Uhd(I9e,I9e))&&lAd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{RBc(Uhd(Ncf,Ncf)+nEe+a.ld());rb(Uhd(Ncf,Ncf),a)}};_.Ie=function OAd(a){var b;HY(this.b,null);b=new lZc;b.Ud(C$e,(eQc(),eQc(),dQc));yCd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;yzc(2128,1,TDe);_.Hk=function Wfe(){$Y(new oAd(this.b.p,this.b.p.o.r,this.b.b))};var Aic=VQc(bbf,'ImageCrop',1576),tic=VQc(bbf,'ImageCrop$1',1577),uic=VQc(bbf,'ImageCrop$2',1578),vic=VQc(bbf,'ImageCrop$3',1579),wic=VQc(bbf,'ImageCrop$4',1580),xic=VQc(bbf,'ImageCrop$5',1581),yic=VQc(bbf,'ImageCrop$6',1582),zic=VQc(bbf,'ImageCrop$7',1583),C8b=VQc(Mbf,scf,790);jEe(PKb)(2);