function mzd(a){this.b=a}
function rzd(a){this.b=a}
function dhe(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function qzd(a){HY(a.b,null)}
function che(a){$Y(new dzd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function jzd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function fzd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function izd(a){var b,c;HY(a.b,null);uCd(a.c,Uhd(a8e,a8e));b=Kid();c=new mzd(a.c);a.d?kjd(b,a.e,c):kkd(b,a.e,TXb(t9(a.f),1),c)}
function kkd(b,c,d,e){var g,i,j;i=new MGc(b,tWe,'markForDeletion');try{j=LGc(i,uWe,2);$Fc(j,WFc(j,vWe));$Fc(j,WFc(j,KSe));_Fc(j,c);$Fc(j,WFc(j,d));KGc(i,e,(cHc(),bHc))}catch(a){a=Byc(a);if(VXb(a,255)){g=a;P1c(e,g)}else throw a}}
function czd(a,b){var c;b>1?(c=Vhd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',JXb(oxc,dCe,1,[xEe+b]))):TXb(Mo(TXb(a.j.Kl(0),349),AVe),303).ae(J$e)?(c=Vhd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',JXb(oxc,dCe,1,[TXb(Mo(a.r,iJe),1)]))):(c=Vhd(v4e,w4e,JXb(oxc,dCe,1,[TXb(Mo(a.r,iJe),1)])));return c}
function dzd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,Ocf);!!this.H&&Bk(rk(this.H,ILe),Ocf);YY(this,false);this.b=new _hb;RT(this.b,Uhd(c0e,c0e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new gJc;p=new gJc;for(k=b.j.ce();k.ie();){j=TXb(k.je(),349);KXb(o.d,o.e++,j);WIc(p,TXb(Mo(j,eVe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),dIe),false);g.Ab=false;this.c=FDd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+Uhd(g7e,h7e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new fzd(this,b,i,g,r,c,s));if(c){n=Uhd(O9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(Zod(),Yod(),Vod))}q=new YX(Uhd(d8e,d8e),new jzd(this,a,c,p,r));e=new YX(Uhd(e8e,e8e),new rzd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var Ocf='Informations';yzc(1559,363,UCe,dzd);_.b=null;_.c=null;yzc(1560,225,nCe,fzd);_.pg=function gzd(a){var b,c,d;b=TXb(a.d,303);c=b.Xd();d=czd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Uhd('message.remove.multiple.usage','Those nodes are still used in:'):Uhd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;yzc(1561,236,nCe,jzd);_.ug=function kzd(a){izd(this,TXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;yzc(1562,1199,{},mzd);_.nm=function nzd(a){tCd(this.b);rb(a.md(),a);j2(Uhd(AWe,LOe),a.md(),null)};_.Ie=function ozd(a){var b;tCd(this.b);b=new lZc;b.Ud(B$e,(eQc(),eQc(),dQc));yCd(this.b,b);BCd(this.b)};_.b=null;yzc(1563,236,nCe,rzd);_.ug=function szd(a){qzd(this,TXb(a,59))};_.b=null;yzc(2145,1,TDe);_.Hk=function ahe(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new gJc;for(e=c.j.ce();e.ie();){d=TXb(e.je(),349);WIc(b,TXb(Mo(d,eVe),1))}a=Kid();Tjd(a,b,new dhe(this))}};yzc(2146,1199,{},dhe);_.nm=function ehe(a){RBc(S8e+a.md())};_.Ie=function fhe(a){che(this,TXb(a,303))};_.b=null;var Crc=VQc(gbf,'DeleteActionItem$1$1',2146),gic=VQc(bbf,'DeleteItemWindow',1559),cic=VQc(bbf,'DeleteItemWindow$1',1560),eic=VQc(bbf,'DeleteItemWindow$2',1561),dic=VQc(bbf,'DeleteItemWindow$2$1',1562),fic=VQc(bbf,'DeleteItemWindow$3',1563);jEe(PKb)(3);