function VPb(){}
function aCd(){}
function dCd(a){this.b=a}
function gCd(a){this.b=a}
function oCd(a){this.b=a}
function ZBd(a){this.b=a}
function YBd(a){a.b.b=false}
function fCd(a){UY(a.b,null)}
function kCd(a,b){this.b=a;this.c=b}
function LOc(a,b){KOc(a,(vCc(),new sCc(b)))}
function UPb(){UPb=dSe;TPb=new IPb(f5e,new VPb)}
function SBd(a,b,c,d,e,g,i,j){Pld(qld(),b,c,d,e,g,i,j,new rCd(a,b,c,d,e,g,i))}
function rCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function UBd(b,c){try{var d=$wnd.jQuery(Vtf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function nCd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){UBd(OXb(y9(a.b.j),287).gm(),OXb(y9(a.b.c),287).gm());!!a.b.g&&ddb(a.b.g)}}
function TBd(b){thisic=b;$wnd.jQuery(Vtf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Rm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function jCd(a){OXb(y9(a.b.j),287).gm()>0&&OXb(y9(a.b.c),287).gm()>0&&SBd(a.b,OXb(Eo(a.c,u9e),1),OXb(a.b.f.oe(),1),OXb(y9(a.b.i),287).gm(),OXb(y9(a.b.d),287).gm(),OXb(y9(a.b.j),287).gm(),OXb(y9(a.b.c),287).gm(),false)}
function Pld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new dJc(b,Laf,'cropImage');try{q=cJc(p,Maf,7);rIc(q,nIc(q,Y6e));rIc(q,nIc(q,Y6e));rIc(q,nIc(q,saf));rIc(q,nIc(q,saf));rIc(q,nIc(q,saf));rIc(q,nIc(q,saf));rIc(q,nIc(q,Oaf));rIc(q,nIc(q,c));rIc(q,nIc(q,d));PIc(q.b,KUe+e);PIc(q.b,KUe+g);PIc(q.b,KUe+i);PIc(q.b,KUe+j);PIc(q.b,k?OYe:yXe);bJc(p,n,(vJc(),uJc))}catch(a){a=TAc(a);if(QXb(a,256)){o=a;i4c(n,o)}else throw a}}
function VBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,zkd(Wtf,Wtf));this.Ec=Xtf;!!this.wc&&(gx(this).id=Xtf,undefined);p=new _zb(hYe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),sYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,$Ve,Ytf):(y.Uc+=Ztf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi($tf);Px(this.f,$tf);H9(this.f,zkd('newName.label','New name'));n=OXb(Eo(c,wZe),1).lastIndexOf(zXe);if(n>0){k=DVc(OXb(Eo(c,wZe),1),n);this.f._i(zVc(OXb(Eo(c,wZe),1),k,_tf+k))}else{this.f._i(OXb(Eo(c,wZe),1)+_tf)}Sw(this.f,(RE(),ZC),new ZBd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,$Ve,Ytf):(z.Uc+=Ztf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,dcc);this.c=new ikb;Zjb(this.c,dcc);v=OXb(Eo(c,B9e),1);t=OXb(Eo(c,C9e),1);u=0;s=0;try{u=v!=null?NSc(v,10,-2147483648,2147483647):0;s=t!=null?NSc(t,10,-2147483648,2147483647):0}catch(a){a=TAc(a);if(!QXb(a,288))throw a}if(!!d&&!d.Ud()){C=new zLc;for(j=d.ee();j.ke();){i=OXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+rif+i[1];E=new x5c(w,w);Ho(E,lWe,i[0]);Ho(E,kWe,i[1]);FXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,oWe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new aCd);kcb(this.g,zkd(auf,buf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,zkd(lif,mif));J9(this.j,lWe);Px(this.j,lWe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,YVe,Ytf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,zkd(pif,qif));J9(this.c,kWe);Px(this.c,kWe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(hYe));r=new MOc;yw(r,new dCd(this),(UPb(),UPb(),TPb));r.ed.id='cropbox';LOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,dcc);J9(this.i,UVe);Px(this.i,UVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,dcc);J9(this.d,TVe);Px(this.d,TVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(zkd(qgf,qgf),new gCd(this));D=new jY(zkd(vgf,vgf),new kCd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new oCd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var Vtf='#cropbox',_tf='-crop',Ytf='10px',Xtf='JahiaGxtImageCrop',cuf='failure.crop.label',Wtf='label.crop',Ztf='paddingRight:10px;';QBc(786,774,{},VPb);_.Wk=function WPb(a){TBd(OXb(OXb(a,227),393).b)};_.Zk=function XPb(){return TPb};var TPb;QBc(1561,364,dTe,VBd);_.Rm=function WBd(a,b,c,d){var e,g,i;ocb(this.d,nUc(a));ocb(this.i,nUc(b));M9(this.j,KUe+c);M9(this.c,KUe+d);if(this.b){g=OXb(this.f.oe(),1);e=vVc(g,NVc(46));this.f._i(EVc(g,0,g.lastIndexOf(_tf))+_tf+c+UYe+d+(e!=-1?EVc(g,e,g.length):KUe))}i=this.g?OXb(mdb(this.g),333):null;!!i&&(c!=OXb(Eo(i,lWe),284).b||d!=OXb(Eo(i,kWe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;QBc(1562,1,wSe,ZBd);_.Cd=function $Bd(a){YBd(this,OXb(a,61))};_.b=null;QBc(1563,235,wSe,aCd);_.xg=function bCd(a){var b;b=OXb(fG(a),333);UBd(OXb(Eo(b,lWe),284).b,OXb(Eo(b,kWe),284).b)};QBc(1564,1,{227:1,232:1,393:1},dCd);_.b=null;QBc(1565,237,wSe,gCd);_.yg=function hCd(a){fCd(this,OXb(a,58))};_.b=null;QBc(1566,237,wSe,kCd);_.yg=function lCd(a){jCd(this,OXb(a,58))};_.b=null;_.c=null;QBc(1567,1,wSe,oCd);_.Cd=function pCd(a){nCd(this,OXb(a,61))};_.b=null;QBc(1568,1198,{},rCd);_.vm=function sCd(a){if(QXb(a,382)){hEc(zkd(Hhf,Hhf)+AUe+zkd(Wqf,Wqf))&&SBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{gEc(zkd(cuf,cuf)+AUe+a.md());rb(zkd(cuf,cuf),a)}};_.Ke=function tCd(a){var b;UY(this.b,null);b=new G_c;b.Wd(Hef,(ASc(),ASc(),zSc));this.b.e.Im(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;QBc(2256,1,dUe);_.Sk=function Jve(){mZ(new VBd(this.b.p,this.b.p.Em().r,this.b.b))};var fic=pTc(wsf,'ImageCrop',1561),$hc=pTc(wsf,'ImageCrop$1',1562),_hc=pTc(wsf,'ImageCrop$2',1563),aic=pTc(wsf,'ImageCrop$3',1564),bic=pTc(wsf,'ImageCrop$4',1565),cic=pTc(wsf,'ImageCrop$5',1566),dic=pTc(wsf,'ImageCrop$6',1567),eic=pTc(wsf,'ImageCrop$7',1568),s8b=pTc(gtf,ftf,786);wUe(dLb)(2);