function YAd(a){this.b=a}
function Swe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function XAd(a){UY(a.b,null)}
function TAd(a,b){this.b=a;this.c=b}
function QAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function MAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Rwe(a){mZ(new KAd(a.b.b.p,a.b.b.p.Em(),a.b.b.c))}
function PAd(a){var b,c;UY(a.b,null);a.c.Hm(zkd(npf,npf));b=qld();c=new TAd(a.c,a.e);a.d?Sld(b,a.e,c):Vmd(b,a.e,OXb(y9(a.f),1),c)}
function Vmd(b,c,d,e){var g,i,j;i=new dJc(b,Laf,'markForDeletion');try{j=cJc(i,Maf,2);rIc(j,nIc(j,Naf));rIc(j,nIc(j,Y6e));sIc(j,c);rIc(j,nIc(j,d));bJc(i,e,(vJc(),uJc))}catch(a){a=TAc(a);if(QXb(a,256)){g=a;i4c(e,g)}else throw a}}
function JAd(a,b){var c;b>1?(c=Akd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',EXb(Gzc,mSe,1,[KUe+b]))):OXb(Eo(OXb(a.j.Rl(0),351),S9e),304).ce(Sef)?(c=Akd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',EXb(Gzc,mSe,1,[OXb(Eo(a.r,wZe),1)]))):(c=Akd(crf,drf,EXb(Gzc,mSe,1,[OXb(Eo(a.r,wZe),1)])));return c}
function KAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,duf);!!this.H&&sk(ik(this.H,X_e),duf);kZ(this,false);this.b=new eib;cU(this.b,zkd(Thf,Thf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new zLc;p=new zLc;for(k=b.j.ee();k.ke();){j=OXb(k.le(),351);FXb(o.d,o.e++,j);nLc(p,OXb(Eo(j,u9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),sYe),false);g.Bb=false;this.c=lFd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+zkd(vof,wof)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new MAd(this,b,i,g,r,c,s));if(c){n=zkd(erf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(Vrd(),Urd(),Rrd))}q=new jY(zkd(qpf,qpf),new QAd(this,a,c,p,r));e=new jY(zkd(rpf,rpf),new YAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var duf='Informations';QBc(1544,364,dTe,KAd);_.b=null;_.c=null;QBc(1545,225,wSe,MAd);_.sg=function NAd(a){var b,c,d;b=OXb(a.d,304);c=b.Zd();d=JAd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?zkd('message.remove.multiple.usage','Those nodes are still used in:'):zkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;QBc(1546,237,wSe,QAd);_.yg=function RAd(a){PAd(this,OXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;QBc(1547,1198,{},TAd);_.vm=function UAd(a){this.b.Gm();rb(a.nd(),a);H2(zkd(Raf,a9e),a.nd(),null)};_.Ke=function VAd(a){var b,c;this.b.Gm();c=null;QXb(this.b,431)?(c=OXb(this.b,431).d.u):QXb(this.b,418)&&(c=OXb(this.b,418));b=new G_c;!!c&&sLc(this.c,OXb(Eo(c.p.i,u9e),1),0)!=-1?b.Wd(Eef,c.p.i):b.Wd(Gef,(ASc(),ASc(),zSc));this.b.Im(b);this.b.Jm(null)};_.b=null;_.c=null;QBc(1548,237,wSe,YAd);_.yg=function ZAd(a){XAd(this,OXb(a,58))};_.b=null;QBc(2273,1,dUe);_.Sk=function Pwe(){var a,b,c,d,e;c=this.b.p.Em();if(!c.j.Ud()){b=new zLc;for(e=c.j.ee();e.ke();){d=OXb(e.le(),351);nLc(b,OXb(Eo(d,u9e),1))}a=qld();Dmd(a,b,new Swe(this))}};QBc(2274,1198,{},Swe);_.vm=function Twe(a){gEc(aqf+a.nd())};_.Ke=function Uwe(a){Rwe(this,OXb(a,304))};_.b=null;var Ttc=pTc(Bsf,'DeleteActionItem$1$1',2274),Nhc=pTc(wsf,'DeleteItemWindow',1544),Jhc=pTc(wsf,'DeleteItemWindow$1',1545),Lhc=pTc(wsf,'DeleteItemWindow$2',1546),Khc=pTc(wsf,'DeleteItemWindow$2$1',1547),Mhc=pTc(wsf,'DeleteItemWindow$3',1548);wUe(dLb)(3);