function IPb(){}
function CBd(){}
function zBd(a){this.a=a}
function FBd(a){this.a=a}
function IBd(a){this.a=a}
function QBd(a){this.a=a}
function yBd(a){a.a.a=false}
function HBd(a){UY(a.a,null)}
function MBd(a,b){this.a=a;this.b=b}
function lOc(a,b){kOc(a,(OBc(),new LBc(b)))}
function HPb(){HPb=FRe;GPb=new vPb(u4e,new IPb)}
function sBd(a,b,c,d,e,g,i,j){pld(Skd(),b,c,d,e,g,i,j,new TBd(a,b,c,d,e,g,i))}
function TBd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function uBd(b,c){try{var d=$wnd.jQuery(gtf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function PBd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){uBd(hXb(y9(a.a.i),287).Ul(),hXb(y9(a.a.b),287).Ul());!!a.a.f&&ddb(a.a.f)}}
function tBd(b){thisic=b;$wnd.jQuery(gtf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function LBd(a){hXb(y9(a.a.i),287).Ul()>0&&hXb(y9(a.a.b),287).Ul()>0&&sBd(a.a,hXb(Eo(a.b,J8e),1),hXb(a.a.e.ne(),1),hXb(y9(a.a.g),287).Ul(),hXb(y9(a.a.c),287).Ul(),hXb(y9(a.a.i),287).Ul(),hXb(y9(a.a.b),287).Ul(),false)}
function pld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new FIc(b,$9e,'cropImage');try{q=EIc(p,_9e,7);THc(q,PHc(q,k6e));THc(q,PHc(q,k6e));THc(q,PHc(q,H9e));THc(q,PHc(q,H9e));THc(q,PHc(q,H9e));THc(q,PHc(q,H9e));THc(q,PHc(q,baf));THc(q,PHc(q,c));THc(q,PHc(q,d));pIc(q.a,jUe+e);pIc(q.a,jUe+g);pIc(q.a,jUe+i);pIc(q.a,jUe+j);pIc(q.a,k?nYe:ZWe);DIc(p,n,(XIc(),WIc))}catch(a){a=kAc(a);if(jXb(a,256)){o=a;K3c(n,o)}else throw a}}
function vBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,_jd(htf,htf));this.Dc=itf;!!this.vc&&(gx(this).id=itf,undefined);p=new _zb(IXe);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),TXe),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,zVe,jtf):(y.Tc+=ktf);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(ltf);Px(this.e,ltf);H9(this.e,_jd('newName.label','New name'));n=hXb(Eo(c,XYe),1).lastIndexOf($We);if(n>0){k=dVc(hXb(Eo(c,XYe),1),n);this.e.$i(_Uc(hXb(Eo(c,XYe),1),k,mtf+k))}else{this.e.$i(hXb(Eo(c,XYe),1)+mtf)}Sw(this.e,(RE(),ZC),new zBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,zVe,jtf):(z.Tc+=ktf);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,wbc);this.b=new ikb;Zjb(this.b,wbc);v=hXb(Eo(c,Q8e),1);t=hXb(Eo(c,R8e),1);u=0;s=0;try{u=v!=null?nSc(v,10,-2147483648,2147483647):0;s=t!=null?nSc(t,10,-2147483648,2147483647):0}catch(a){a=kAc(a);if(!jXb(a,288))throw a}if(!!d&&!d.Td()){C=new _Kc;for(j=d.de();j.je();){i=hXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+Ghf+i[1];E=new Z4c(w,w);Ho(E,MVe,i[0]);Ho(E,LVe,i[1]);$Wb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,PVe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new CBd);kcb(this.f,_jd(ntf,otf));oT(B,this.f,new Bzb(0.6))}}H9(this.i,_jd(Ahf,Bhf));J9(this.i,MVe);Px(this.i,MVe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,xVe,jtf):(x.Tc+='paddingLeft:10px;');q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,_jd(Ehf,Fhf));J9(this.b,LVe);Px(this.b,LVe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(IXe));r=new mOc;yw(r,new FBd(this),(HPb(),HPb(),GPb));r.dd.id='cropbox';lOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,wbc);J9(this.g,tVe);Px(this.g,tVe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,wbc);J9(this.c,sVe);Px(this.c,sVe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(_jd(Fff,Fff),new IBd(this));D=new jY(_jd(Kff,Kff),new MBd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new QBd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var gtf='#cropbox',mtf='-crop',jtf='10px',itf='JahiaGxtImageCrop',ptf='failure.crop.label',htf='label.crop',ktf='paddingRight:10px;';hBc(787,775,{},IPb);_.Sk=function JPb(a){tBd(hXb(hXb(a,227),393).a)};_.Vk=function KPb(){return GPb};var GPb;hBc(1565,364,FSe,vBd);_.Dm=function wBd(a,b,c,d){var e,g,i;ocb(this.c,PTc(a));ocb(this.g,PTc(b));M9(this.i,jUe+c);M9(this.b,jUe+d);if(this.a){g=hXb(this.e.ne(),1);e=XUc(g,nVc(46));this.e.$i(eVc(g,0,g.lastIndexOf(mtf))+mtf+c+tYe+d+(e!=-1?eVc(g,e,g.length):jUe))}i=this.f?hXb(mdb(this.f),333):null;!!i&&(c!=hXb(Eo(i,MVe),284).a||d!=hXb(Eo(i,LVe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;hBc(1566,1,YRe,zBd);_.Bd=function ABd(a){yBd(this,hXb(a,61))};_.a=null;hBc(1567,235,YRe,CBd);_.wg=function DBd(a){var b;b=hXb(fG(a),333);uBd(hXb(Eo(b,MVe),284).a,hXb(Eo(b,LVe),284).a)};hBc(1568,1,{227:1,232:1,393:1},FBd);_.a=null;hBc(1569,237,YRe,IBd);_.xg=function JBd(a){HBd(this,hXb(a,58))};_.a=null;hBc(1570,237,YRe,MBd);_.xg=function NBd(a){LBd(this,hXb(a,58))};_.a=null;_.b=null;hBc(1571,1,YRe,QBd);_.Bd=function RBd(a){PBd(this,hXb(a,61))};_.a=null;hBc(1572,1202,{},TBd);_.hm=function UBd(a){if(jXb(a,382)){CDc(_jd(Wgf,Wgf)+_Te+_jd(hqf,hqf))&&sBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{BDc(_jd(ptf,ptf)+_Te+a.ld());rb(_jd(ptf,ptf),a)}};_.Je=function VBd(a){var b;UY(this.a,null);b=new g_c;b.Vd(Wdf,(aSc(),aSc(),_Rc));this.a.d.um(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;hBc(2260,1,ETe);_.Nk=function jve(){mZ(new vBd(this.a.o,this.a.o.qm().q,this.a.a))};var yhc=RSc(Krf,'ImageCrop',1565),rhc=RSc(Krf,'ImageCrop$1',1566),shc=RSc(Krf,'ImageCrop$2',1567),thc=RSc(Krf,'ImageCrop$3',1568),uhc=RSc(Krf,'ImageCrop$4',1569),vhc=RSc(Krf,'ImageCrop$5',1570),whc=RSc(Krf,'ImageCrop$6',1571),xhc=RSc(Krf,'ImageCrop$7',1572),J7b=RSc(usf,tsf,787);XTe(VKb)(2);