function yAd(a){this.a=a}
function swe(a){this.a=a}
function xAd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function tAd(a,b){this.a=a;this.b=b}
function qAd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function mAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function rwe(a){mZ(new kAd(a.a.a.o,a.a.a.o.qm(),a.a.a.b))}
function pAd(a){var b,c;UY(a.a,null);a.b.tm(_jd(Aof,Aof));b=Skd();c=new tAd(a.b,a.d);a.c?sld(b,a.d,c):vmd(b,a.d,hXb(y9(a.e),1),c)}
function vmd(b,c,d,e){var g,i,j;i=new FIc(b,$9e,'markForDeletion');try{j=EIc(i,_9e,2);THc(j,PHc(j,aaf));THc(j,PHc(j,k6e));UHc(j,c);THc(j,PHc(j,d));DIc(i,e,(XIc(),WIc))}catch(a){a=kAc(a);if(jXb(a,256)){g=a;K3c(e,g)}else throw a}}
function jAd(a,b){var c;b>1?(c=akd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',ZWb(Zyc,ORe,1,[jUe+b]))):hXb(Eo(hXb(a.i.Dl(0),351),f9e),304).be(fef)?(c=akd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',ZWb(Zyc,ORe,1,[hXb(Eo(a.q,XYe),1)]))):(c=akd(pqf,qqf,ZWb(Zyc,ORe,1,[hXb(Eo(a.q,XYe),1)])));return c}
function kAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,qtf);!!this.G&&sk(ik(this.G,w_e),qtf);kZ(this,false);this.a=new eib;cU(this.a,_jd(ghf,ghf));this.a.Ab=false;Hx(this.a,false);Px(this.a,'JahiaGxtDeleteItem');MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new _Kc;p=new _Kc;for(k=b.i.de();k.je();){j=hXb(k.ke(),351);$Wb(o.c,o.d++,j);PKc(p,hXb(Eo(j,J8e),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),TXe),false);g.Ab=false;this.b=NEd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$('<br />'+_jd(Inf,Jnf)+': <br />'));nT(this.a,r)}i=o.d;aq(this.b.H.e,new mAd(this,b,i,g,r,c,s));if(c){n=_jd(rqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.a,new I$(n));dU(this,(vrd(),urd(),rrd))}q=new jY(_jd(Dof,Dof),new qAd(this,a,c,p,r));e=new jY(_jd(Eof,Eof),new yAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var qtf='Informations';hBc(1548,364,FSe,kAd);_.a=null;_.b=null;hBc(1549,225,YRe,mAd);_.rg=function nAd(a){var b,c,d;b=hXb(a.c,304);c=b.Yd();d=jAd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?_jd('message.remove.multiple.usage','Those nodes are still used in:'):_jd('message.remove.single.usage','This node is still used by:'))}else{wT(this.a.a,this.b);hz(this.f,'620','70%');if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;hBc(1550,237,YRe,qAd);_.xg=function rAd(a){pAd(this,hXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;hBc(1551,1202,{},tAd);_.hm=function uAd(a){this.a.sm();rb(a.md(),a);H2(_jd(eaf,o8e),a.md(),null)};_.Je=function vAd(a){var b,c;this.a.sm();c=null;jXb(this.a,431)?(c=hXb(this.a,431).c.t):jXb(this.a,418)&&(c=hXb(this.a,418));b=new g_c;!!c&&UKc(this.b,hXb(Eo(c.o.g,J8e),1),0)!=-1?b.Vd(Tdf,c.o.g):b.Vd(Vdf,(aSc(),aSc(),_Rc));this.a.um(b);this.a.vm(null)};_.a=null;_.b=null;hBc(1552,237,YRe,yAd);_.xg=function zAd(a){xAd(this,hXb(a,58))};_.a=null;hBc(2277,1,ETe);_.Nk=function pwe(){var a,b,c,d,e;c=this.a.o.qm();if(!c.i.Td()){b=new _Kc;for(e=c.i.de();e.je();){d=hXb(e.ke(),351);PKc(b,hXb(Eo(d,J8e),1))}a=Skd();dmd(a,b,new swe(this))}};hBc(2278,1202,{},swe);_.hm=function twe(a){BDc(npf+a.md())};_.Je=function uwe(a){rwe(this,hXb(a,304))};_.a=null;var ktc=RSc(Prf,'DeleteActionItem$1$1',2278),ehc=RSc(Krf,'DeleteItemWindow',1548),ahc=RSc(Krf,'DeleteItemWindow$1',1549),chc=RSc(Krf,'DeleteItemWindow$2',1550),bhc=RSc(Krf,'DeleteItemWindow$2$1',1551),dhc=RSc(Krf,'DeleteItemWindow$3',1552);XTe(VKb)(3);