function _Pb(){}
function UBd(){}
function RBd(a){this.a=a}
function XBd(a){this.a=a}
function $Bd(a){this.a=a}
function gCd(a){this.a=a}
function QBd(a){a.a.a=false}
function ZBd(a){UY(a.a,null)}
function cCd(a,b){this.a=a;this.b=b}
function uOc(a,b){tOc(a,(iCc(),new fCc(b)))}
function $Pb(){$Pb=WRe;ZPb=new OPb(msf,new _Pb)}
function KBd(a,b,c,d,e,g,i,j){Hld(ild(),b,c,d,e,g,i,j,new jCd(a,b,c,d,e,g,i))}
function jCd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function MBd(b,c){try{var d=$wnd.jQuery(dLg).data(eLg);var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function fCd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){MBd(AXb(y9(a.a.i),287).Ul(),AXb(y9(a.a.b),287).Ul());!!a.a.f&&ddb(a.a.f)}}
function LBd(b){thisic=b;$wnd.jQuery(dLg).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function bCd(a){AXb(y9(a.a.i),287).Ul()>0&&AXb(y9(a.a.b),287).Ul()>0&&KBd(a.a,AXb(Fo(a.b,Gzf),1),AXb(a.a.e.ne(),1),AXb(y9(a.a.g),287).Ul(),AXb(y9(a.a.c),287).Ul(),AXb(y9(a.a.i),287).Ul(),AXb(y9(a.a.b),287).Ul(),false)}
function Hld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new OIc(b,vBf,cLg);try{q=NIc(p,xBf,7);aIc(q,YHc(q,hwf));aIc(q,YHc(q,hwf));aIc(q,YHc(q,aBf));aIc(q,YHc(q,aBf));aIc(q,YHc(q,aBf));aIc(q,YHc(q,aBf));aIc(q,YHc(q,GBf));aIc(q,YHc(q,c));aIc(q,YHc(q,d));yIc(q.a,EUe+e);yIc(q.a,EUe+g);yIc(q.a,EUe+i);yIc(q.a,EUe+j);yIc(q.a,k?k0e:OZe);MIc(p,n,(eJc(),dJc))}catch(a){a=GAc(a);if(CXb(a,256)){o=a;a4c(n,o)}else throw a}}
function NBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,rkd(fLg,fLg));this.Dc=gLg;!!this.vc&&(gx(this).id=gLg,undefined);p=new _zb(_$e);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),A_e),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,vXe,hLg):(y.Tc+=iLg);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(jLg);Px(this.e,jLg);H9(this.e,rkd(kLg,lLg));n=AXb(Fo(c,C2e),1).lastIndexOf(PZe);if(n>0){k=vVc(AXb(Fo(c,C2e),1),n);this.e.$i(rVc(AXb(Fo(c,C2e),1),k,mLg+k))}else{this.e.$i(AXb(Fo(c,C2e),1)+mLg)}Sw(this.e,(RE(),ZC),new RBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,vXe,hLg):(z.Tc+=iLg);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,Sbc);this.b=new ikb;Zjb(this.b,Sbc);v=AXb(Fo(c,Ozf),1);t=AXb(Fo(c,Pzf),1);u=0;s=0;try{u=v!=null?FSc(v,10,-2147483648,2147483647):0;s=t!=null?FSc(t,10,-2147483648,2147483647):0}catch(a){a=GAc(a);if(!CXb(a,288))throw a}if(!!d&&!d.Td()){C=new iLc;for(j=d.de();j.je();){i=AXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+mOf+i[1];E=new p5c(w,w);Io(E,JXe,i[0]);Io(E,IXe,i[1]);rXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,NXe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new UBd);kcb(this.f,rkd(nLg,oLg));oT(B,this.f,new Bzb(0.6))}}H9(this.i,rkd(eOf,fOf));J9(this.i,JXe);Px(this.i,JXe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,tXe,hLg):(x.Tc+=pLg);q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,rkd(jOf,kOf));J9(this.b,IXe);Px(this.b,IXe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(_$e));r=new vOc;yw(r,new XBd(this),($Pb(),$Pb(),ZPb));r.dd.id=qLg;uOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,Sbc);J9(this.g,pXe);Px(this.g,pXe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,Sbc);J9(this.c,oXe);Px(this.c,oXe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(rkd(RJf,RJf),new $Bd(this));D=new jY(rkd(_Jf,_Jf),new cCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new gCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var dLg='#cropbox',mLg='-crop',hLg='10px',sLg='ImageCrop',tLg='ImageCrop$1',uLg='ImageCrop$2',vLg='ImageCrop$3',wLg='ImageCrop$4',xLg='ImageCrop$5',yLg='ImageCrop$6',zLg='ImageCrop$7',gLg='JahiaGxtImageCrop',eLg='Jcrop',lLg='New name',cLg='cropImage',qLg='cropbox',rLg='failure.crop.label',fLg='label.crop',kLg='newName.label',pLg='paddingLeft:10px;',iLg='paddingRight:10px;';DBc(789,777,{},_Pb);_.Sk=function aQb(a){LBd(AXb(AXb(a,227),393).a)};_.Vk=function bQb(){return ZPb};var ZPb;DBc(1567,365,WSe,NBd);_.Dm=function OBd(a,b,c,d){var e,g,i;ocb(this.c,fUc(a));ocb(this.g,fUc(b));M9(this.i,EUe+c);M9(this.b,EUe+d);if(this.a){g=AXb(this.e.ne(),1);e=nVc(g,FVc(46));this.e.$i(wVc(g,0,g.lastIndexOf(mLg))+mLg+c+D0e+d+(e!=-1?wVc(g,e,g.length):EUe))}i=this.f?AXb(mdb(this.f),333):null;!!i&&(c!=AXb(Fo(i,JXe),284).a||d!=AXb(Fo(i,IXe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;DBc(1568,1,nSe,RBd);_.Bd=function SBd(a){QBd(this,AXb(a,61))};_.a=null;DBc(1569,236,nSe,UBd);_.wg=function VBd(a){var b;b=AXb(fG(a),333);MBd(AXb(Fo(b,JXe),284).a,AXb(Fo(b,IXe),284).a)};DBc(1570,1,{227:1,232:1,393:1},XBd);_.a=null;DBc(1571,238,nSe,$Bd);_.xg=function _Bd(a){ZBd(this,AXb(a,58))};_.a=null;DBc(1572,238,nSe,cCd);_.xg=function dCd(a){bCd(this,AXb(a,58))};_.a=null;_.b=null;DBc(1573,1,nSe,gCd);_.Bd=function hCd(a){fCd(this,AXb(a,61))};_.a=null;DBc(1574,1204,{},jCd);_.hm=function kCd(a){if(CXb(a,382)){RDc(rkd(TMf,TMf)+qUe+rkd(Z6f,Z6f))&&KBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{QDc(rkd(rLg,rLg)+qUe+a.ld());rb(rkd(rLg,rLg),a)}};_.Je=function lCd(a){var b;UY(this.a,null);b=new y_c;b.Vd(_Gf,(sSc(),sSc(),rSc));this.a.d.um(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;DBc(2262,1,VTe);_.Nk=function Ave(){mZ(new NBd(this.a.o,this.a.o.qm().q,this.a.a))};var Uhc=hTc(thg,sLg,1567),Nhc=hTc(thg,tLg,1568),Ohc=hTc(thg,uLg,1569),Phc=hTc(thg,vLg,1570),Qhc=hTc(thg,wLg,1571),Rhc=hTc(thg,xLg,1572),Shc=hTc(thg,yLg,1573),Thc=hTc(thg,zLg,1574),b8b=hTc(Gvg,yvg,789);mUe(VKb)(2);