function QAd(a){this.a=a}
function Jwe(a){this.a=a}
function PAd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function LAd(a,b){this.a=a;this.b=b}
function IAd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function EAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Iwe(a){mZ(new CAd(a.a.a.o,a.a.a.o.qm(),a.a.a.b))}
function HAd(a){var b,c;UY(a.a,null);a.b.tm(rkd(s2f,s2f));b=ild();c=new LAd(a.b,a.d);a.c?Kld(b,a.d,c):Nmd(b,a.d,AXb(y9(a.e),1),c)}
function Nmd(b,c,d,e){var g,i,j;i=new OIc(b,vBf,ALg);try{j=NIc(i,xBf,2);aIc(j,YHc(j,BBf));aIc(j,YHc(j,hwf));bIc(j,c);aIc(j,YHc(j,d));MIc(i,e,(eJc(),dJc))}catch(a){a=GAc(a);if(CXb(a,256)){g=a;a4c(e,g)}else throw a}}
function BAd(a,b){var c;b>1?(c=skd(BLg,CLg,qXb(tzc,dSe,1,[EUe+b]))):AXb(Fo(AXb(a.i.Dl(0),351),gAf),304).be(kHf)?(c=skd(DLg,ELg,qXb(tzc,dSe,1,[AXb(Fo(a.q,C2e),1)]))):(c=skd(s7f,t7f,qXb(tzc,dSe,1,[AXb(Fo(a.q,C2e),1)])));return c}
function CAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,FLg);!!this.G&&sk(ik(this.G,acf),FLg);kZ(this,false);this.a=new eib;cU(this.a,rkd(rNf,rNf));this.a.Ab=false;Hx(this.a,false);Px(this.a,GLg);MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new iLc;p=new iLc;for(k=b.i.de();k.je();){j=AXb(k.ke(),351);rXb(o.c,o.d++,j);YKc(p,AXb(Fo(j,Gzf),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),A_e),false);g.Ab=false;this.b=dFd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$(HLg+rkd(G0f,H0f)+ILg));nT(this.a,r)}i=o.d;bq(this.b.H.e,new EAd(this,b,i,g,r,c,s));if(c){n=rkd(u7f,JLg);nT(this.a,new I$(n));dU(this,(Nrd(),Mrd(),Jrd))}q=new jY(rkd(I2f,I2f),new IAd(this,a,c,p,r));e=new jY(rkd(J2f,J2f),new QAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var PLg='620',QLg='70%',ILg=': <br />',HLg='<br />',KLg='<br /><br />',JLg='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',RLg='DeleteActionItem$1$1',SLg='DeleteItemWindow',TLg='DeleteItemWindow$1',ULg='DeleteItemWindow$2',VLg='DeleteItemWindow$2$1',WLg='DeleteItemWindow$3',ELg='Do you really want to remove the selected PAGE {0}?',CLg='Do you really want to remove the {0} selected resources?',FLg='Informations',GLg='JahiaGxtDeleteItem',OLg='This node is still used by:',MLg='Those nodes are still used in:',ALg='markForDeletion',BLg='message.remove.multiple.confirm',LLg='message.remove.multiple.usage',DLg='message.remove.single.page.confirm',NLg='message.remove.single.usage';DBc(1550,365,WSe,CAd);_.a=null;_.b=null;DBc(1551,226,nSe,EAd);_.rg=function FAd(a){var b,c,d;b=AXb(a.c,304);c=b.Yd();d=BAd(this.c,this.d);if(c>0){d+=KLg+(this.d>1?rkd(LLg,MLg):rkd(NLg,OLg))}else{wT(this.a.a,this.b);hz(this.f,PLg,QLg);if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;DBc(1552,238,nSe,IAd);_.xg=function JAd(a){HAd(this,AXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;DBc(1553,1204,{},LAd);_.hm=function MAd(a){this.a.sm();rb(a.md(),a);H2(rkd(MCf,fzf),a.md(),null)};_.Je=function NAd(a){var b,c;this.a.sm();c=null;CXb(this.a,431)?(c=AXb(this.a,431).c.t):CXb(this.a,418)&&(c=AXb(this.a,418));b=new y_c;!!c&&bLc(this.b,AXb(Fo(c.o.g,Gzf),1),0)!=-1?b.Vd(YGf,c.o.g):b.Vd($Gf,(sSc(),sSc(),rSc));this.a.um(b);this.a.vm(null)};_.a=null;_.b=null;DBc(1554,238,nSe,QAd);_.xg=function RAd(a){PAd(this,AXb(a,58))};_.a=null;DBc(2279,1,VTe);_.Nk=function Gwe(){var a,b,c,d,e;c=this.a.o.qm();if(!c.i.Td()){b=new iLc;for(e=c.i.de();e.je();){d=AXb(e.ke(),351);YKc(b,AXb(Fo(d,Gzf),1))}a=ild();vmd(a,b,new Jwe(this))}};DBc(2280,1204,{},Jwe);_.hm=function Kwe(a){QDc(z4f+a.md())};_.Je=function Lwe(a){Iwe(this,AXb(a,304))};_.a=null;var Gtc=hTc(wig,RLg,2280),Ahc=hTc(thg,SLg,1550),whc=hTc(thg,TLg,1551),yhc=hTc(thg,ULg,1552),xhc=hTc(thg,VLg,1553),zhc=hTc(thg,WLg,1554);mUe(VKb)(3);