function pQb(){}
function eCd(){}
function bCd(a){this.b=a}
function hCd(a){this.b=a}
function kCd(a){this.b=a}
function sCd(a){this.b=a}
function aCd(a){a.b.b=false}
function jCd(a){UY(a.b,null)}
function oCd(a,b){this.b=a;this.c=b}
function OOc(a,b){NOc(a,(yCc(),new vCc(b)))}
function oQb(){oQb=hSe;nQb=new cQb(b5e,new pQb)}
function WBd(a,b,c,d,e,g,i,j){Tld(uld(),b,c,d,e,g,i,j,new vCd(a,b,c,d,e,g,i))}
function vCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function YBd(b,c){try{var d=$wnd.jQuery(Mtf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function rCd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){YBd(OXb(y9(a.b.j),287).am(),OXb(y9(a.b.c),287).am());!!a.b.g&&ddb(a.b.g)}}
function XBd(b){thisic=b;$wnd.jQuery(Mtf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Lm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function nCd(a){OXb(y9(a.b.j),287).am()>0&&OXb(y9(a.b.c),287).am()>0&&WBd(a.b,OXb(Eo(a.c,n9e),1),OXb(a.b.f.oe(),1),OXb(y9(a.b.i),287).am(),OXb(y9(a.b.d),287).am(),OXb(y9(a.b.j),287).am(),OXb(y9(a.b.c),287).am(),false)}
function Tld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new gJc(b,Eaf,'cropImage');try{q=fJc(p,Faf,7);uIc(q,qIc(q,R6e));uIc(q,qIc(q,R6e));uIc(q,qIc(q,laf));uIc(q,qIc(q,laf));uIc(q,qIc(q,laf));uIc(q,qIc(q,laf));uIc(q,qIc(q,Haf));uIc(q,qIc(q,c));uIc(q,qIc(q,d));SIc(q.b,OUe+e);SIc(q.b,OUe+g);SIc(q.b,OUe+i);SIc(q.b,OUe+j);SIc(q.b,k?SYe:CXe);eJc(p,n,(yJc(),xJc))}catch(a){a=WAc(a);if(QXb(a,256)){o=a;m4c(n,o)}else throw a}}
function ZBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,Dkd(Ntf,Ntf));this.Ec=Otf;!!this.wc&&(gx(this).id=Otf,undefined);p=new _zb(lYe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),wYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,cWe,Ptf):(y.Uc+=Qtf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(Rtf);Px(this.f,Rtf);H9(this.f,Dkd('newName.label','New name'));n=OXb(Eo(c,AZe),1).lastIndexOf(DXe);if(n>0){k=HVc(OXb(Eo(c,AZe),1),n);this.f._i(DVc(OXb(Eo(c,AZe),1),k,Stf+k))}else{this.f._i(OXb(Eo(c,AZe),1)+Stf)}Sw(this.f,(RE(),ZC),new bCd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,cWe,Ptf):(z.Uc+=Qtf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,gcc);this.c=new ikb;Zjb(this.c,gcc);v=OXb(Eo(c,u9e),1);t=OXb(Eo(c,v9e),1);u=0;s=0;try{u=v!=null?QSc(v,10,-2147483648,2147483647):0;s=t!=null?QSc(t,10,-2147483648,2147483647):0}catch(a){a=WAc(a);if(!QXb(a,288))throw a}if(!!d&&!d.Ud()){C=new CLc;for(j=d.ee();j.ke();){i=OXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+kif+i[1];E=new B5c(w,w);Ho(E,pWe,i[0]);Ho(E,oWe,i[1]);FXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,sWe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new eCd);kcb(this.g,Dkd(Ttf,Utf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,Dkd(eif,fif));J9(this.j,pWe);Px(this.j,pWe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,aWe,Ptf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,Dkd(iif,jif));J9(this.c,oWe);Px(this.c,oWe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(lYe));r=new POc;yw(r,new hCd(this),(oQb(),oQb(),nQb));r.ed.id='cropbox';OOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,gcc);J9(this.i,YVe);Px(this.i,YVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,gcc);J9(this.d,XVe);Px(this.d,XVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(Dkd(jgf,jgf),new kCd(this));D=new jY(Dkd(ogf,ogf),new oCd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new sCd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var Mtf='#cropbox',Stf='-crop',Ptf='10px',Otf='JahiaGxtImageCrop',Vtf='failure.crop.label',Ntf='label.crop',Qtf='paddingRight:10px;';TBc(790,778,{},pQb);_.$k=function qQb(a){XBd(OXb(OXb(a,227),393).b)};_.bl=function rQb(){return nQb};var nQb;TBc(1562,364,hTe,ZBd);_.Lm=function $Bd(a,b,c,d){var e,g,i;ocb(this.d,qUc(a));ocb(this.i,qUc(b));M9(this.j,OUe+c);M9(this.c,OUe+d);if(this.b){g=OXb(this.f.oe(),1);e=yVc(g,RVc(46));this.f._i(IVc(g,0,g.lastIndexOf(Stf))+Stf+c+YYe+d+(e!=-1?IVc(g,e,g.length):OUe))}i=this.g?OXb(mdb(this.g),333):null;!!i&&(c!=OXb(Eo(i,pWe),284).b||d!=OXb(Eo(i,oWe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;TBc(1563,1,ASe,bCd);_.Cd=function cCd(a){aCd(this,OXb(a,61))};_.b=null;TBc(1564,235,ASe,eCd);_.xg=function fCd(a){var b;b=OXb(fG(a),333);YBd(OXb(Eo(b,pWe),284).b,OXb(Eo(b,oWe),284).b)};TBc(1565,1,{227:1,232:1,393:1},hCd);_.b=null;TBc(1566,237,ASe,kCd);_.yg=function lCd(a){jCd(this,OXb(a,58))};_.b=null;TBc(1567,237,ASe,oCd);_.yg=function pCd(a){nCd(this,OXb(a,58))};_.b=null;_.c=null;TBc(1568,1,ASe,sCd);_.Cd=function tCd(a){rCd(this,OXb(a,61))};_.b=null;TBc(1569,1199,{},vCd);_.pm=function wCd(a){if(QXb(a,382)){mEc(Dkd(Ahf,Ahf)+EUe+Dkd(Nqf,Nqf))&&WBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{lEc(Dkd(Vtf,Vtf)+EUe+a.md());rb(Dkd(Vtf,Vtf),a)}};_.Ke=function xCd(a){var b;UY(this.b,null);b=new K_c;b.Wd(Aef,(DSc(),DSc(),CSc));this.b.e.Cm(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;TBc(2257,1,hUe);_.Sk=function Nve(){mZ(new ZBd(this.b.p,this.b.p.ym().r,this.b.b))};var iic=sTc(nsf,'ImageCrop',1562),bic=sTc(nsf,'ImageCrop$1',1563),cic=sTc(nsf,'ImageCrop$2',1564),dic=sTc(nsf,'ImageCrop$3',1565),eic=sTc(nsf,'ImageCrop$4',1566),fic=sTc(nsf,'ImageCrop$5',1567),gic=sTc(nsf,'ImageCrop$6',1568),hic=sTc(nsf,'ImageCrop$7',1569),w8b=sTc(Zsf,Ysf,790);AUe(eLb)(2);