function aBd(a){this.b=a}
function Wwe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function _Ad(a){UY(a.b,null)}
function XAd(a,b){this.b=a;this.c=b}
function UAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function QAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Vwe(a){mZ(new OAd(a.b.b.p,a.b.b.p.ym(),a.b.b.c))}
function TAd(a){var b,c;UY(a.b,null);a.c.Bm(Dkd(epf,epf));b=uld();c=new XAd(a.c,a.e);a.d?Wld(b,a.e,c):Zmd(b,a.e,OXb(y9(a.f),1),c)}
function Zmd(b,c,d,e){var g,i,j;i=new gJc(b,Eaf,'markForDeletion');try{j=fJc(i,Faf,2);uIc(j,qIc(j,Gaf));uIc(j,qIc(j,R6e));vIc(j,c);uIc(j,qIc(j,d));eJc(i,e,(yJc(),xJc))}catch(a){a=WAc(a);if(QXb(a,256)){g=a;m4c(e,g)}else throw a}}
function NAd(a,b){var c;b>1?(c=Ekd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',EXb(Jzc,qSe,1,[OUe+b]))):OXb(Eo(OXb(a.j.Ll(0),351),L9e),304).ce(Lef)?(c=Ekd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',EXb(Jzc,qSe,1,[OXb(Eo(a.r,AZe),1)]))):(c=Ekd(Vqf,Wqf,EXb(Jzc,qSe,1,[OXb(Eo(a.r,AZe),1)])));return c}
function OAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,Wtf);!!this.H&&sk(ik(this.H,__e),Wtf);kZ(this,false);this.b=new eib;cU(this.b,Dkd(Mhf,Mhf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new CLc;p=new CLc;for(k=b.j.ee();k.ke();){j=OXb(k.le(),351);FXb(o.d,o.e++,j);qLc(p,OXb(Eo(j,n9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),wYe),false);g.Bb=false;this.c=pFd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+Dkd(mof,nof)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new QAd(this,b,i,g,r,c,s));if(c){n=Dkd(Xqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(Zrd(),Yrd(),Vrd))}q=new jY(Dkd(hpf,hpf),new UAd(this,a,c,p,r));e=new jY(Dkd(ipf,ipf),new aBd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var Wtf='Informations';TBc(1545,364,hTe,OAd);_.b=null;_.c=null;TBc(1546,225,ASe,QAd);_.sg=function RAd(a){var b,c,d;b=OXb(a.d,304);c=b.Zd();d=NAd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Dkd('message.remove.multiple.usage','Those nodes are still used in:'):Dkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;TBc(1547,237,ASe,UAd);_.yg=function VAd(a){TAd(this,OXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;TBc(1548,1199,{},XAd);_.pm=function YAd(a){this.b.Am();rb(a.nd(),a);H2(Dkd(Kaf,V8e),a.nd(),null)};_.Ke=function ZAd(a){var b,c;this.b.Am();c=null;QXb(this.b,431)?(c=OXb(this.b,431).d.u):QXb(this.b,418)&&(c=OXb(this.b,418));b=new K_c;!!c&&vLc(this.c,OXb(Eo(c.p.i,n9e),1),0)!=-1?b.Wd(xef,c.p.i):b.Wd(zef,(DSc(),DSc(),CSc));this.b.Cm(b);this.b.Dm(null)};_.b=null;_.c=null;TBc(1549,237,ASe,aBd);_.yg=function bBd(a){_Ad(this,OXb(a,58))};_.b=null;TBc(2274,1,hUe);_.Sk=function Twe(){var a,b,c,d,e;c=this.b.p.ym();if(!c.j.Ud()){b=new CLc;for(e=c.j.ee();e.ke();){d=OXb(e.le(),351);qLc(b,OXb(Eo(d,n9e),1))}a=uld();Hmd(a,b,new Wwe(this))}};TBc(2275,1199,{},Wwe);_.pm=function Xwe(a){lEc(Tpf+a.nd())};_.Ke=function Ywe(a){Vwe(this,OXb(a,304))};_.b=null;var Wtc=sTc(ssf,'DeleteActionItem$1$1',2275),Qhc=sTc(nsf,'DeleteItemWindow',1545),Mhc=sTc(nsf,'DeleteItemWindow$1',1546),Ohc=sTc(nsf,'DeleteItemWindow$2',1547),Nhc=sTc(nsf,'DeleteItemWindow$2$1',1548),Phc=sTc(nsf,'DeleteItemWindow$3',1549);AUe(eLb)(3);