function MPb(){}
function WBd(){}
function TBd(a){this.a=a}
function ZBd(a){this.a=a}
function aCd(a){this.a=a}
function iCd(a){this.a=a}
function SBd(a){a.a.a=false}
function _Bd(a){UY(a.a,null)}
function eCd(a,b){this.a=a;this.b=b}
function FOc(a,b){EOc(a,(mCc(),new jCc(b)))}
function LPb(){LPb=ZRe;KPb=new zPb(d5e,new MPb)}
function MBd(a,b,c,d,e,g,i,j){Jld(kld(),b,c,d,e,g,i,j,new lCd(a,b,c,d,e,g,i))}
function lCd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function OBd(b,c){try{var d=$wnd.jQuery(Ktf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function hCd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){OBd(FXb(y9(a.a.i),287).bm(),FXb(y9(a.a.b),287).bm());!!a.a.f&&ddb(a.a.f)}}
function NBd(b){thisic=b;$wnd.jQuery(Ktf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function dCd(a){FXb(y9(a.a.i),287).bm()>0&&FXb(y9(a.a.b),287).bm()>0&&MBd(a.a,FXb(Fo(a.b,i9e),1),FXb(a.a.e.ne(),1),FXb(y9(a.a.g),287).bm(),FXb(y9(a.a.c),287).bm(),FXb(y9(a.a.i),287).bm(),FXb(y9(a.a.b),287).bm(),false)}
function Jld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new ZIc(b,zaf,'cropImage');try{q=YIc(p,Aaf,7);lIc(q,hIc(q,L6e));lIc(q,hIc(q,L6e));lIc(q,hIc(q,gaf));lIc(q,hIc(q,gaf));lIc(q,hIc(q,gaf));lIc(q,hIc(q,gaf));lIc(q,hIc(q,Caf));lIc(q,hIc(q,c));lIc(q,hIc(q,d));JIc(q.a,DUe+e);JIc(q.a,DUe+g);JIc(q.a,DUe+i);JIc(q.a,DUe+j);JIc(q.a,k?HYe:rXe);XIc(p,n,(pJc(),oJc))}catch(a){a=KAc(a);if(HXb(a,256)){o=a;c4c(n,o)}else throw a}}
function PBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,tkd(Ltf,Ltf));this.Dc=Mtf;!!this.vc&&(gx(this).id=Mtf,undefined);p=new _zb(aYe);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),mYe),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,TVe,Ntf):(y.Tc+=Otf);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(Ptf);Px(this.e,Ptf);H9(this.e,tkd('newName.label','New name'));n=FXb(Fo(c,qZe),1).lastIndexOf(sXe);if(n>0){k=xVc(FXb(Fo(c,qZe),1),n);this.e.$i(tVc(FXb(Fo(c,qZe),1),k,Qtf+k))}else{this.e.$i(FXb(Fo(c,qZe),1)+Qtf)}Sw(this.e,(RE(),ZC),new TBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,TVe,Ntf):(z.Tc+=Otf);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,Wbc);this.b=new ikb;Zjb(this.b,Wbc);v=FXb(Fo(c,p9e),1);t=FXb(Fo(c,q9e),1);u=0;s=0;try{u=v!=null?HSc(v,10,-2147483648,2147483647):0;s=t!=null?HSc(t,10,-2147483648,2147483647):0}catch(a){a=KAc(a);if(!HXb(a,288))throw a}if(!!d&&!d.Td()){C=new tLc;for(j=d.de();j.je();){i=FXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+gif+i[1];E=new r5c(w,w);Io(E,eWe,i[0]);Io(E,dWe,i[1]);wXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,hWe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new WBd);kcb(this.f,tkd(Rtf,Stf));oT(B,this.f,new Bzb(0.6))}}H9(this.i,tkd(aif,bif));J9(this.i,eWe);Px(this.i,eWe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,RVe,Ntf):(x.Tc+='paddingLeft:10px;');q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,tkd(eif,fif));J9(this.b,dWe);Px(this.b,dWe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(aYe));r=new GOc;yw(r,new ZBd(this),(LPb(),LPb(),KPb));r.dd.id='cropbox';FOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,Wbc);J9(this.g,NVe);Px(this.g,NVe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,Wbc);J9(this.c,MVe);Px(this.c,MVe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(tkd(fgf,fgf),new aCd(this));D=new jY(tkd(kgf,kgf),new eCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new iCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var Ktf='#cropbox',Qtf='-crop',Ntf='10px',Mtf='JahiaGxtImageCrop',Ttf='failure.crop.label',Ltf='label.crop',Otf='paddingRight:10px;';HBc(787,775,{},MPb);_.Sk=function NPb(a){NBd(FXb(FXb(a,227),393).a)};_.Vk=function OPb(){return KPb};var KPb;HBc(1566,365,ZSe,PBd);_.Mm=function QBd(a,b,c,d){var e,g,i;ocb(this.c,hUc(a));ocb(this.g,hUc(b));M9(this.i,DUe+c);M9(this.b,DUe+d);if(this.a){g=FXb(this.e.ne(),1);e=pVc(g,HVc(46));this.e.$i(yVc(g,0,g.lastIndexOf(Qtf))+Qtf+c+NYe+d+(e!=-1?yVc(g,e,g.length):DUe))}i=this.f?FXb(mdb(this.f),333):null;!!i&&(c!=FXb(Fo(i,eWe),284).a||d!=FXb(Fo(i,dWe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;HBc(1567,1,qSe,TBd);_.Bd=function UBd(a){SBd(this,FXb(a,61))};_.a=null;HBc(1568,236,qSe,WBd);_.wg=function XBd(a){var b;b=FXb(fG(a),333);OBd(FXb(Fo(b,eWe),284).a,FXb(Fo(b,dWe),284).a)};HBc(1569,1,{227:1,232:1,393:1},ZBd);_.a=null;HBc(1570,238,qSe,aCd);_.xg=function bCd(a){_Bd(this,FXb(a,58))};_.a=null;HBc(1571,238,qSe,eCd);_.xg=function fCd(a){dCd(this,FXb(a,58))};_.a=null;_.b=null;HBc(1572,1,qSe,iCd);_.Bd=function jCd(a){hCd(this,FXb(a,61))};_.a=null;HBc(1573,1203,{},lCd);_.qm=function mCd(a){if(HXb(a,382)){aEc(tkd(whf,whf)+tUe+tkd(Kqf,Kqf))&&MBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{_Dc(tkd(Ttf,Ttf)+tUe+a.ld());rb(tkd(Ttf,Ttf),a)}};_.Je=function nCd(a){var b;UY(this.a,null);b=new A_c;b.Vd(vef,(uSc(),uSc(),tSc));this.a.d.Dm(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;HBc(2261,1,YTe);_.Nk=function Dve(){mZ(new PBd(this.a.o,this.a.o.zm().q,this.a.a))};var Yhc=jTc(lsf,'ImageCrop',1566),Rhc=jTc(lsf,'ImageCrop$1',1567),Shc=jTc(lsf,'ImageCrop$2',1568),Thc=jTc(lsf,'ImageCrop$3',1569),Uhc=jTc(lsf,'ImageCrop$4',1570),Vhc=jTc(lsf,'ImageCrop$5',1571),Whc=jTc(lsf,'ImageCrop$6',1572),Xhc=jTc(lsf,'ImageCrop$7',1573),g8b=jTc(Ysf,Xsf,787);pUe(VKb)(2);