function SAd(a){this.a=a}
function Mwe(a){this.a=a}
function RAd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function NAd(a,b){this.a=a;this.b=b}
function KAd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function GAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Lwe(a){mZ(new EAd(a.a.a.o,a.a.a.o.zm(),a.a.a.b))}
function JAd(a){var b,c;UY(a.a,null);a.b.Cm(tkd(bpf,bpf));b=kld();c=new NAd(a.b,a.d);a.c?Mld(b,a.d,c):Pmd(b,a.d,FXb(y9(a.e),1),c)}
function Pmd(b,c,d,e){var g,i,j;i=new ZIc(b,zaf,'markForDeletion');try{j=YIc(i,Aaf,2);lIc(j,hIc(j,Baf));lIc(j,hIc(j,L6e));mIc(j,c);lIc(j,hIc(j,d));XIc(i,e,(pJc(),oJc))}catch(a){a=KAc(a);if(HXb(a,256)){g=a;c4c(e,g)}else throw a}}
function DAd(a,b){var c;b>1?(c=ukd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',vXb(xzc,gSe,1,[DUe+b]))):FXb(Fo(FXb(a.i.Ml(0),351),G9e),304).be(Gef)?(c=ukd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',vXb(xzc,gSe,1,[FXb(Fo(a.q,qZe),1)]))):(c=ukd(Sqf,Tqf,vXb(xzc,gSe,1,[FXb(Fo(a.q,qZe),1)])));return c}
function EAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,Utf);!!this.G&&sk(ik(this.G,S_e),Utf);kZ(this,false);this.a=new eib;cU(this.a,tkd(Ihf,Ihf));this.a.Ab=false;Hx(this.a,false);Px(this.a,'JahiaGxtDeleteItem');MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new tLc;p=new tLc;for(k=b.i.de();k.je();){j=FXb(k.ke(),351);wXb(o.c,o.d++,j);hLc(p,FXb(Fo(j,i9e),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),mYe),false);g.Ab=false;this.b=fFd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$('<br />'+tkd(jof,kof)+': <br />'));nT(this.a,r)}i=o.d;bq(this.b.H.e,new GAd(this,b,i,g,r,c,s));if(c){n=tkd(Uqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.a,new I$(n));dU(this,(Prd(),Ord(),Lrd))}q=new jY(tkd(epf,epf),new KAd(this,a,c,p,r));e=new jY(tkd(fpf,fpf),new SAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var Utf='Informations';HBc(1549,365,ZSe,EAd);_.a=null;_.b=null;HBc(1550,226,qSe,GAd);_.rg=function HAd(a){var b,c,d;b=FXb(a.c,304);c=b.Yd();d=DAd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?tkd('message.remove.multiple.usage','Those nodes are still used in:'):tkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.a.a,this.b);hz(this.f,'620','70%');if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;HBc(1551,238,qSe,KAd);_.xg=function LAd(a){JAd(this,FXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;HBc(1552,1203,{},NAd);_.qm=function OAd(a){this.a.Bm();rb(a.md(),a);H2(tkd(Faf,P8e),a.md(),null)};_.Je=function PAd(a){var b,c;this.a.Bm();c=null;HXb(this.a,431)?(c=FXb(this.a,431).c.t):HXb(this.a,418)&&(c=FXb(this.a,418));b=new A_c;!!c&&mLc(this.b,FXb(Fo(c.o.g,i9e),1),0)!=-1?b.Vd(sef,c.o.g):b.Vd(uef,(uSc(),uSc(),tSc));this.a.Dm(b);this.a.Em(null)};_.a=null;_.b=null;HBc(1553,238,qSe,SAd);_.xg=function TAd(a){RAd(this,FXb(a,58))};_.a=null;HBc(2278,1,YTe);_.Nk=function Jwe(){var a,b,c,d,e;c=this.a.o.zm();if(!c.i.Td()){b=new tLc;for(e=c.i.de();e.je();){d=FXb(e.ke(),351);hLc(b,FXb(Fo(d,i9e),1))}a=kld();xmd(a,b,new Mwe(this))}};HBc(2279,1203,{},Mwe);_.qm=function Nwe(a){_Dc(Qpf+a.md())};_.Je=function Owe(a){Lwe(this,FXb(a,304))};_.a=null;var Ktc=jTc(qsf,'DeleteActionItem$1$1',2279),Ehc=jTc(lsf,'DeleteItemWindow',1549),Ahc=jTc(lsf,'DeleteItemWindow$1',1550),Chc=jTc(lsf,'DeleteItemWindow$2',1551),Bhc=jTc(lsf,'DeleteItemWindow$2$1',1552),Dhc=jTc(lsf,'DeleteItemWindow$3',1553);pUe(VKb)(3);