function VPb(){}
function FBd(){}
function CBd(a){this.b=a}
function IBd(a){this.b=a}
function LBd(a){this.b=a}
function TBd(a){this.b=a}
function BBd(a){a.b.b=false}
function KBd(a){UY(a.b,null)}
function PBd(a,b){this.b=a;this.c=b}
function oOc(a,b){nOc(a,($Bc(),new XBc(b)))}
function UPb(){UPb=IRe;TPb=new IPb(A4e,new VPb)}
function vBd(a,b,c,d,e,g,i,j){sld(Vkd(),b,c,d,e,g,i,j,new WBd(a,b,c,d,e,g,i))}
function WBd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function xBd(b,c){try{var d=$wnd.jQuery(mtf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function SBd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){xBd(sXb(y9(a.b.j),287).Yl(),sXb(y9(a.b.c),287).Yl());!!a.b.g&&ddb(a.b.g)}}
function wBd(b){thisic=b;$wnd.jQuery(mtf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Hm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function OBd(a){sXb(y9(a.b.j),287).Yl()>0&&sXb(y9(a.b.c),287).Yl()>0&&vBd(a.b,sXb(Eo(a.c,P8e),1),sXb(a.b.f.oe(),1),sXb(y9(a.b.i),287).Yl(),sXb(y9(a.b.d),287).Yl(),sXb(y9(a.b.j),287).Yl(),sXb(y9(a.b.c),287).Yl(),false)}
function sld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new IIc(b,eaf,'cropImage');try{q=HIc(p,faf,7);WHc(q,SHc(q,r6e));WHc(q,SHc(q,r6e));WHc(q,SHc(q,N9e));WHc(q,SHc(q,N9e));WHc(q,SHc(q,N9e));WHc(q,SHc(q,N9e));WHc(q,SHc(q,haf));WHc(q,SHc(q,c));WHc(q,SHc(q,d));sIc(q.b,nUe+e);sIc(q.b,nUe+g);sIc(q.b,nUe+i);sIc(q.b,nUe+j);sIc(q.b,k?rYe:bXe);GIc(p,n,($Ic(),ZIc))}catch(a){a=wAc(a);if(uXb(a,256)){o=a;N3c(n,o)}else throw a}}
function yBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,ckd(ntf,ntf));this.Ec=otf;!!this.wc&&(gx(this).id=otf,undefined);p=new _zb(MXe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),XXe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,DVe,ptf):(y.Uc+=qtf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(rtf);Px(this.f,rtf);H9(this.f,ckd('newName.label','New name'));n=sXb(Eo(c,_Ye),1).lastIndexOf(cXe);if(n>0){k=gVc(sXb(Eo(c,_Ye),1),n);this.f._i(cVc(sXb(Eo(c,_Ye),1),k,stf+k))}else{this.f._i(sXb(Eo(c,_Ye),1)+stf)}Sw(this.f,(RE(),ZC),new CBd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,DVe,ptf):(z.Uc+=qtf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,Ibc);this.c=new ikb;Zjb(this.c,Ibc);v=sXb(Eo(c,W8e),1);t=sXb(Eo(c,X8e),1);u=0;s=0;try{u=v!=null?qSc(v,10,-2147483648,2147483647):0;s=t!=null?qSc(t,10,-2147483648,2147483647):0}catch(a){a=wAc(a);if(!uXb(a,288))throw a}if(!!d&&!d.Ud()){C=new cLc;for(j=d.ee();j.ke();){i=sXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+Mhf+i[1];E=new a5c(w,w);Ho(E,QVe,i[0]);Ho(E,PVe,i[1]);jXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,TVe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new FBd);kcb(this.g,ckd(ttf,utf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,ckd(Ghf,Hhf));J9(this.j,QVe);Px(this.j,QVe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,BVe,ptf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,ckd(Khf,Lhf));J9(this.c,PVe);Px(this.c,PVe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(MXe));r=new pOc;yw(r,new IBd(this),(UPb(),UPb(),TPb));r.ed.id='cropbox';oOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,Ibc);J9(this.i,xVe);Px(this.i,xVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,Ibc);J9(this.d,wVe);Px(this.d,wVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(ckd(Lff,Lff),new LBd(this));D=new jY(ckd(Qff,Qff),new PBd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new TBd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var mtf='#cropbox',stf='-crop',ptf='10px',otf='JahiaGxtImageCrop',vtf='failure.crop.label',ntf='label.crop',qtf='paddingRight:10px;';tBc(786,774,{},VPb);_.Wk=function WPb(a){wBd(sXb(sXb(a,227),393).b)};_.Zk=function XPb(){return TPb};var TPb;tBc(1560,364,ISe,yBd);_.Hm=function zBd(a,b,c,d){var e,g,i;ocb(this.d,STc(a));ocb(this.i,STc(b));M9(this.j,nUe+c);M9(this.c,nUe+d);if(this.b){g=sXb(this.f.oe(),1);e=$Uc(g,qVc(46));this.f._i(hVc(g,0,g.lastIndexOf(stf))+stf+c+xYe+d+(e!=-1?hVc(g,e,g.length):nUe))}i=this.g?sXb(mdb(this.g),333):null;!!i&&(c!=sXb(Eo(i,QVe),284).b||d!=sXb(Eo(i,PVe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;tBc(1561,1,_Re,CBd);_.Cd=function DBd(a){BBd(this,sXb(a,61))};_.b=null;tBc(1562,235,_Re,FBd);_.xg=function GBd(a){var b;b=sXb(fG(a),333);xBd(sXb(Eo(b,QVe),284).b,sXb(Eo(b,PVe),284).b)};tBc(1563,1,{227:1,232:1,393:1},IBd);_.b=null;tBc(1564,237,_Re,LBd);_.yg=function MBd(a){KBd(this,sXb(a,58))};_.b=null;tBc(1565,237,_Re,PBd);_.yg=function QBd(a){OBd(this,sXb(a,58))};_.b=null;_.c=null;tBc(1566,1,_Re,TBd);_.Cd=function UBd(a){SBd(this,sXb(a,61))};_.b=null;tBc(1567,1197,{},WBd);_.lm=function XBd(a){if(uXb(a,382)){MDc(ckd(ahf,ahf)+dUe+ckd(nqf,nqf))&&vBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{LDc(ckd(vtf,vtf)+dUe+a.md());rb(ckd(vtf,vtf),a)}};_.Ke=function YBd(a){var b;UY(this.b,null);b=new j_c;b.Wd(aef,(dSc(),dSc(),cSc));this.b.e.ym(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;tBc(2255,1,ITe);_.Sk=function mve(){mZ(new yBd(this.b.p,this.b.p.um().r,this.b.b))};var Khc=USc(Prf,'ImageCrop',1560),Dhc=USc(Prf,'ImageCrop$1',1561),Ehc=USc(Prf,'ImageCrop$2',1562),Fhc=USc(Prf,'ImageCrop$3',1563),Ghc=USc(Prf,'ImageCrop$4',1564),Hhc=USc(Prf,'ImageCrop$5',1565),Ihc=USc(Prf,'ImageCrop$6',1566),Jhc=USc(Prf,'ImageCrop$7',1567),Y7b=USc(zsf,ysf,786);_Te(dLb)(2);