function BAd(a){this.b=a}
function vwe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function AAd(a){UY(a.b,null)}
function wAd(a,b){this.b=a;this.c=b}
function tAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function pAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function uwe(a){mZ(new nAd(a.b.b.p,a.b.b.p.um(),a.b.b.c))}
function sAd(a){var b,c;UY(a.b,null);a.c.xm(ckd(Gof,Gof));b=Vkd();c=new wAd(a.c,a.e);a.d?vld(b,a.e,c):ymd(b,a.e,sXb(y9(a.f),1),c)}
function ymd(b,c,d,e){var g,i,j;i=new IIc(b,eaf,'markForDeletion');try{j=HIc(i,faf,2);WHc(j,SHc(j,gaf));WHc(j,SHc(j,r6e));XHc(j,c);WHc(j,SHc(j,d));GIc(i,e,($Ic(),ZIc))}catch(a){a=wAc(a);if(uXb(a,256)){g=a;N3c(e,g)}else throw a}}
function mAd(a,b){var c;b>1?(c=dkd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',iXb(jzc,RRe,1,[nUe+b]))):sXb(Eo(sXb(a.j.Hl(0),351),l9e),304).ce(lef)?(c=dkd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',iXb(jzc,RRe,1,[sXb(Eo(a.r,_Ye),1)]))):(c=dkd(vqf,wqf,iXb(jzc,RRe,1,[sXb(Eo(a.r,_Ye),1)])));return c}
function nAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,wtf);!!this.H&&sk(ik(this.H,B_e),wtf);kZ(this,false);this.b=new eib;cU(this.b,ckd(mhf,mhf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new cLc;p=new cLc;for(k=b.j.ee();k.ke();){j=sXb(k.le(),351);jXb(o.d,o.e++,j);SKc(p,sXb(Eo(j,P8e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),XXe),false);g.Bb=false;this.c=QEd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+ckd(Onf,Pnf)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new pAd(this,b,i,g,r,c,s));if(c){n=ckd(xqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(yrd(),xrd(),urd))}q=new jY(ckd(Jof,Jof),new tAd(this,a,c,p,r));e=new jY(ckd(Kof,Kof),new BAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var wtf='Informations';tBc(1543,364,ISe,nAd);_.b=null;_.c=null;tBc(1544,225,_Re,pAd);_.sg=function qAd(a){var b,c,d;b=sXb(a.d,304);c=b.Zd();d=mAd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?ckd('message.remove.multiple.usage','Those nodes are still used in:'):ckd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;tBc(1545,237,_Re,tAd);_.yg=function uAd(a){sAd(this,sXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;tBc(1546,1197,{},wAd);_.lm=function xAd(a){this.b.wm();rb(a.nd(),a);H2(ckd(kaf,v8e),a.nd(),null)};_.Ke=function yAd(a){var b,c;this.b.wm();c=null;uXb(this.b,431)?(c=sXb(this.b,431).d.u):uXb(this.b,418)&&(c=sXb(this.b,418));b=new j_c;!!c&&XKc(this.c,sXb(Eo(c.p.i,P8e),1),0)!=-1?b.Wd(Zdf,c.p.i):b.Wd(_df,(dSc(),dSc(),cSc));this.b.ym(b);this.b.zm(null)};_.b=null;_.c=null;tBc(1547,237,_Re,BAd);_.yg=function CAd(a){AAd(this,sXb(a,58))};_.b=null;tBc(2272,1,ITe);_.Sk=function swe(){var a,b,c,d,e;c=this.b.p.um();if(!c.j.Ud()){b=new cLc;for(e=c.j.ee();e.ke();){d=sXb(e.le(),351);SKc(b,sXb(Eo(d,P8e),1))}a=Vkd();gmd(a,b,new vwe(this))}};tBc(2273,1197,{},vwe);_.lm=function wwe(a){LDc(tpf+a.nd())};_.Ke=function xwe(a){uwe(this,sXb(a,304))};_.b=null;var wtc=USc(Urf,'DeleteActionItem$1$1',2273),qhc=USc(Prf,'DeleteItemWindow',1543),mhc=USc(Prf,'DeleteItemWindow$1',1544),ohc=USc(Prf,'DeleteItemWindow$2',1545),nhc=USc(Prf,'DeleteItemWindow$2$1',1546),phc=USc(Prf,'DeleteItemWindow$3',1547);_Te(dLb)(3);