function DPb(){}
function rBd(){}
function oBd(a){this.b=a}
function uBd(a){this.b=a}
function xBd(a){this.b=a}
function FBd(a){this.b=a}
function nBd(a){a.b.b=false}
function wBd(a){UY(a.b,null)}
function BBd(a,b){this.b=a;this.c=b}
function aOc(a,b){_Nc(a,(IBc(),new FBc(b)))}
function CPb(){CPb=uRe;BPb=new qPb(l4e,new DPb)}
function hBd(a,b,c,d,e,g,i,j){eld(Hkd(),b,c,d,e,g,i,j,new IBd(a,b,c,d,e,g,i))}
function IBd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function jBd(b,c){try{var d=$wnd.jQuery(Wsf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function EBd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){jBd(aXb(y9(a.b.j),287).Ul(),aXb(y9(a.b.c),287).Ul());!!a.b.g&&ddb(a.b.g)}}
function iBd(b){thisic=b;$wnd.jQuery(Wsf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function ABd(a){aXb(y9(a.b.j),287).Ul()>0&&aXb(y9(a.b.c),287).Ul()>0&&hBd(a.b,aXb(Eo(a.c,x8e),1),aXb(a.b.f.oe(),1),aXb(y9(a.b.i),287).Ul(),aXb(y9(a.b.d),287).Ul(),aXb(y9(a.b.j),287).Ul(),aXb(y9(a.b.c),287).Ul(),false)}
function eld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new qIc(b,O9e,'cropImage');try{q=pIc(p,P9e,7);EHc(q,AHc(q,_5e));EHc(q,AHc(q,_5e));EHc(q,AHc(q,v9e));EHc(q,AHc(q,v9e));EHc(q,AHc(q,v9e));EHc(q,AHc(q,v9e));EHc(q,AHc(q,R9e));EHc(q,AHc(q,c));EHc(q,AHc(q,d));aIc(q.b,$Te+e);aIc(q.b,$Te+g);aIc(q.b,$Te+i);aIc(q.b,$Te+j);aIc(q.b,k?cYe:OWe);oIc(p,n,(IIc(),HIc))}catch(a){a=eAc(a);if(cXb(a,256)){o=a;z3c(n,o)}else throw a}}
function kBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,Qjd(Xsf,Xsf));this.Ec=Ysf;!!this.wc&&(gx(this).id=Ysf,undefined);p=new _zb(xXe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),IXe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,oVe,Zsf):(y.Uc+=$sf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(_sf);Px(this.f,_sf);H9(this.f,Qjd('newName.label','New name'));n=aXb(Eo(c,MYe),1).lastIndexOf(PWe);if(n>0){k=UUc(aXb(Eo(c,MYe),1),n);this.f._i(QUc(aXb(Eo(c,MYe),1),k,atf+k))}else{this.f._i(aXb(Eo(c,MYe),1)+atf)}Sw(this.f,(RE(),ZC),new oBd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,oVe,Zsf):(z.Uc+=$sf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,qbc);this.c=new ikb;Zjb(this.c,qbc);v=aXb(Eo(c,E8e),1);t=aXb(Eo(c,F8e),1);u=0;s=0;try{u=v!=null?cSc(v,10,-2147483648,2147483647):0;s=t!=null?cSc(t,10,-2147483648,2147483647):0}catch(a){a=eAc(a);if(!cXb(a,288))throw a}if(!!d&&!d.Ud()){C=new MKc;for(j=d.ee();j.ke();){i=aXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+uhf+i[1];E=new O4c(w,w);Ho(E,BVe,i[0]);Ho(E,AVe,i[1]);TWb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,EVe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new rBd);kcb(this.g,Qjd(btf,ctf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,Qjd(ohf,phf));J9(this.j,BVe);Px(this.j,BVe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,mVe,Zsf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,Qjd(shf,thf));J9(this.c,AVe);Px(this.c,AVe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(xXe));r=new bOc;yw(r,new uBd(this),(CPb(),CPb(),BPb));r.ed.id='cropbox';aOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,qbc);J9(this.i,iVe);Px(this.i,iVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,qbc);J9(this.d,hVe);Px(this.d,hVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(Qjd(tff,tff),new xBd(this));D=new jY(Qjd(yff,yff),new BBd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new FBd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var Wsf='#cropbox',atf='-crop',Zsf='10px',Ysf='JahiaGxtImageCrop',dtf='failure.crop.label',Xsf='label.crop',$sf='paddingRight:10px;';bBc(785,773,{},DPb);_.Sk=function EPb(a){iBd(aXb(aXb(a,227),393).b)};_.Vk=function FPb(){return BPb};var BPb;bBc(1559,364,uSe,kBd);_.Dm=function lBd(a,b,c,d){var e,g,i;ocb(this.d,ETc(a));ocb(this.i,ETc(b));M9(this.j,$Te+c);M9(this.c,$Te+d);if(this.b){g=aXb(this.f.oe(),1);e=MUc(g,cVc(46));this.f._i(VUc(g,0,g.lastIndexOf(atf))+atf+c+iYe+d+(e!=-1?VUc(g,e,g.length):$Te))}i=this.g?aXb(mdb(this.g),333):null;!!i&&(c!=aXb(Eo(i,BVe),284).b||d!=aXb(Eo(i,AVe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;bBc(1560,1,NRe,oBd);_.Cd=function pBd(a){nBd(this,aXb(a,61))};_.b=null;bBc(1561,235,NRe,rBd);_.xg=function sBd(a){var b;b=aXb(fG(a),333);jBd(aXb(Eo(b,BVe),284).b,aXb(Eo(b,AVe),284).b)};bBc(1562,1,{227:1,232:1,393:1},uBd);_.b=null;bBc(1563,237,NRe,xBd);_.yg=function yBd(a){wBd(this,aXb(a,58))};_.b=null;bBc(1564,237,NRe,BBd);_.yg=function CBd(a){ABd(this,aXb(a,58))};_.b=null;_.c=null;bBc(1565,1,NRe,FBd);_.Cd=function GBd(a){EBd(this,aXb(a,61))};_.b=null;bBc(1566,1196,{},IBd);_.hm=function JBd(a){if(cXb(a,382)){wDc(Qjd(Kgf,Kgf)+QTe+Qjd(Xpf,Xpf))&&hBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{vDc(Qjd(dtf,dtf)+QTe+a.md());rb(Qjd(dtf,dtf),a)}};_.Ke=function KBd(a){var b;UY(this.b,null);b=new X$c;b.Wd(Kdf,(RRc(),RRc(),QRc));this.b.e.um(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;bBc(2254,1,tTe);_.Ok=function $ue(){mZ(new kBd(this.b.p,this.b.p.qm().r,this.b.b))};var shc=GSc(xrf,'ImageCrop',1559),lhc=GSc(xrf,'ImageCrop$1',1560),mhc=GSc(xrf,'ImageCrop$2',1561),nhc=GSc(xrf,'ImageCrop$3',1562),ohc=GSc(xrf,'ImageCrop$4',1563),phc=GSc(xrf,'ImageCrop$5',1564),qhc=GSc(xrf,'ImageCrop$6',1565),rhc=GSc(xrf,'ImageCrop$7',1566),E7b=GSc(hsf,gsf,785);MTe(VKb)(2);