function nAd(a){this.b=a}
function hwe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function mAd(a){UY(a.b,null)}
function iAd(a,b){this.b=a;this.c=b}
function fAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function bAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function gwe(a){mZ(new _zd(a.b.b.p,a.b.b.p.qm(),a.b.b.c))}
function eAd(a){var b,c;UY(a.b,null);a.c.tm(Qjd(oof,oof));b=Hkd();c=new iAd(a.c,a.e);a.d?hld(b,a.e,c):kmd(b,a.e,aXb(y9(a.f),1),c)}
function kmd(b,c,d,e){var g,i,j;i=new qIc(b,O9e,'markForDeletion');try{j=pIc(i,P9e,2);EHc(j,AHc(j,Q9e));EHc(j,AHc(j,_5e));FHc(j,c);EHc(j,AHc(j,d));oIc(i,e,(IIc(),HIc))}catch(a){a=eAc(a);if(cXb(a,256)){g=a;z3c(e,g)}else throw a}}
function $zd(a,b){var c;b>1?(c=Rjd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',SWb(Tyc,DRe,1,[$Te+b]))):aXb(Eo(aXb(a.j.Dl(0),351),V8e),304).ce(Vdf)?(c=Rjd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',SWb(Tyc,DRe,1,[aXb(Eo(a.r,MYe),1)]))):(c=Rjd(dqf,eqf,SWb(Tyc,DRe,1,[aXb(Eo(a.r,MYe),1)])));return c}
function _zd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,etf);!!this.H&&sk(ik(this.H,l_e),etf);kZ(this,false);this.b=new eib;cU(this.b,Qjd(Wgf,Wgf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new MKc;p=new MKc;for(k=b.j.ee();k.ke();){j=aXb(k.le(),351);TWb(o.d,o.e++,j);AKc(p,aXb(Eo(j,x8e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),IXe),false);g.Bb=false;this.c=CEd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+Qjd(wnf,xnf)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new bAd(this,b,i,g,r,c,s));if(c){n=Qjd(fqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(krd(),jrd(),grd))}q=new jY(Qjd(rof,rof),new fAd(this,a,c,p,r));e=new jY(Qjd(sof,sof),new nAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var etf='Informations';bBc(1542,364,uSe,_zd);_.b=null;_.c=null;bBc(1543,225,NRe,bAd);_.sg=function cAd(a){var b,c,d;b=aXb(a.d,304);c=b.Zd();d=$zd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Qjd('message.remove.multiple.usage','Those nodes are still used in:'):Qjd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;bBc(1544,237,NRe,fAd);_.yg=function gAd(a){eAd(this,aXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;bBc(1545,1196,{},iAd);_.hm=function jAd(a){this.b.sm();rb(a.nd(),a);H2(Qjd(U9e,d8e),a.nd(),null)};_.Ke=function kAd(a){var b,c;this.b.sm();c=null;cXb(this.b,431)?(c=aXb(this.b,431).d.u):cXb(this.b,418)&&(c=aXb(this.b,418));b=new X$c;!!c&&FKc(this.c,aXb(Eo(c.p.i,x8e),1),0)!=-1?b.Wd(Hdf,c.p.i):b.Wd(Jdf,(RRc(),RRc(),QRc));this.b.um(b);this.b.vm(null)};_.b=null;_.c=null;bBc(1546,237,NRe,nAd);_.yg=function oAd(a){mAd(this,aXb(a,58))};_.b=null;bBc(2271,1,tTe);_.Ok=function ewe(){var a,b,c,d,e;c=this.b.p.qm();if(!c.j.Ud()){b=new MKc;for(e=c.j.ee();e.ke();){d=aXb(e.le(),351);AKc(b,aXb(Eo(d,x8e),1))}a=Hkd();Uld(a,b,new hwe(this))}};bBc(2272,1196,{},hwe);_.hm=function iwe(a){vDc(bpf+a.nd())};_.Ke=function jwe(a){gwe(this,aXb(a,304))};_.b=null;var etc=GSc(Crf,'DeleteActionItem$1$1',2272),$gc=GSc(xrf,'DeleteItemWindow',1542),Wgc=GSc(xrf,'DeleteItemWindow$1',1543),Ygc=GSc(xrf,'DeleteItemWindow$2',1544),Xgc=GSc(xrf,'DeleteItemWindow$2$1',1545),Zgc=GSc(xrf,'DeleteItemWindow$3',1546);MTe(VKb)(3);