function rPb(){}
function Pzd(){}
function Mzd(a){this.a=a}
function Szd(a){this.a=a}
function Vzd(a){this.a=a}
function bAd(a){this.a=a}
function Lzd(a){a.a.a=false}
function Uzd(a){HY(a.a,null)}
function JLc(a,b){a.a.Pl(a,b)}
function Zzd(a,b){this.a=a;this.b=b}
function KLc(a,b){JLc(a,(rzc(),new ozc(b)))}
function qPb(){qPb=oBe;pPb=new ePb(lQe,new rPb)}
function LLc(){GLc();HLc(this,new dMc(this));this.cd[bGe]=OQe}
function Fzd(a,b,c,d,e,g,i,j){Bid(cid(),b,c,d,e,g,i,j,new eAd(a,b,c,d,e,g,i))}
function eAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function aAd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){Hzd(kXb(t9(a.a.i),286).Rl(),kXb(t9(a.a.b),286).Rl());!!a.a.f&&$cb(a.a.f)}}
function Hzd(b,c){try{var d=$wnd.jQuery(acf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Gzd(b){thisic=b;$wnd.jQuery(acf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Yzd(a){kXb(t9(a.a.i),286).Rl()>0&&kXb(t9(a.a.b),286).Rl()>0&&Fzd(a.a,kXb(Mo(a.b,yUe),1),kXb(a.a.e.le(),1),kXb(t9(a.a.g),286).Rl(),kXb(t9(a.a.c),286).Rl(),kXb(t9(a.a.i),286).Rl(),kXb(t9(a.a.b),286).Rl(),false)}
function Bid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new fGc(b,NVe,'cropImage');try{q=eGc(p,OVe,7);tFc(q,pFc(q,aSe));tFc(q,pFc(q,aSe));tFc(q,pFc(q,uVe));tFc(q,pFc(q,uVe));tFc(q,pFc(q,uVe));tFc(q,pFc(q,uVe));tFc(q,pFc(q,QVe));tFc(q,pFc(q,c));tFc(q,pFc(q,d));RFc(q.a,QDe+e);RFc(q.a,QDe+g);RFc(q.a,QDe+i);RFc(q.a,QDe+j);RFc(q.a,k?THe:DGe);dGc(p,n,(xGc(),wGc))}catch(a){a=Pxc(a);if(mXb(a,255)){o=a;h1c(n,o)}else throw a}}
function Izd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,mhd(bcf,bcf));this.Cc=ccf;!!this.uc&&(ix(this).id=ccf,undefined);p=new Szb(mHe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),wHe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,fFe,dcf):(y.Sc+=ecf);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(fcf);Rx(this.e,fcf);C9(this.e,mhd('newName.label','New name'));n=kXb(Mo(c,zIe),1).lastIndexOf(EGe);if(n>0){k=BSc(kXb(Mo(c,zIe),1),n);this.e.Qi(ySc(kXb(Mo(c,zIe),1),k,gcf+k))}else{this.e.Qi(kXb(Mo(c,zIe),1)+gcf)}Uw(this.e,(NE(),VC),new Mzd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,fFe,dcf):(z.Sc+=ecf);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Bbc);this.b=new dkb;Ujb(this.b,Bbc);v=kXb(Mo(c,GUe),1);t=kXb(Mo(c,HUe),1);u=0;s=0;try{u=v!=null?MPc(v,10,-2147483648,2147483647):0;s=t!=null?MPc(t,10,-2147483648,2147483647):0}catch(a){a=Pxc(a);if(!mXb(a,287))throw a}if(!!d&&!d.Rd()){C=new BIc;for(j=d.be();j.he();){i=kXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+B1e+i[1];E=new s2c(w,w);Po(E,sFe,i[0]);Po(E,rFe,i[1]);bXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,vFe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new Pzd);ecb(this.f,mhd(hcf,icf));bT(B,this.f,new szb(0.6))}}C9(this.i,mhd(v1e,w1e));E9(this.i,sFe);Rx(this.i,sFe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,dFe,dcf):(x.Sc+='paddingLeft:10px;');q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,mhd(z1e,A1e));E9(this.b,rFe);Rx(this.b,rFe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(mHe));r=new LLc;Aw(r,new Szd(this),(qPb(),qPb(),pPb));r.cd.id='cropbox';KLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Bbc);E9(this.g,bFe);Rx(this.g,bFe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Bbc);E9(this.c,aFe);Rx(this.c,aFe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(mhd(K_e,K_e),new Vzd(this));D=new YX(mhd(J_e,J_e),new Zzd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new bAd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var acf='#cropbox',gcf='-crop',dcf='10px',ccf='JahiaGxtImageCrop',jcf='failure.crop.label',bcf='label.crop',ecf='paddingRight:10px;';Myc(787,775,{},rPb);_.Hk=function sPb(a){Gzd(kXb(kXb(a,226),391).a)};_.Kk=function tPb(){return pPb};var pPb;Myc(1035,182,OBe,LLc);Myc(1036,1037,{});_.Pl=function $Lc(a,b){HLc(a,new dMc(a));a.a.Pl(a,b)};Myc(1039,1037,{});_.Pl=function hMc(a,b){!!a.a&&(a.a.Ml(a)[PQe]=QDe,undefined);HMb(a.cd,b.a)};Myc(1579,363,mCe,Izd);_.Mm=function Jzd(a,b,c,d){var e,g,i;jcb(this.c,mRc(a));jcb(this.g,mRc(b));H9(this.i,QDe+c);H9(this.b,QDe+d);if(this.a){g=kXb(this.e.le(),1);e=uSc(g,LSc(46));this.e.Qi(CSc(g,0,g.lastIndexOf(gcf))+gcf+c+ZHe+d+(e!=-1?CSc(g,e,g.length):QDe))}i=this.f?kXb(hdb(this.f),331):null;!!i&&(c!=kXb(Mo(i,sFe),283).a||d!=kXb(Mo(i,rFe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;Myc(1580,1,HBe,Mzd);_.Ad=function Nzd(a){Lzd(this,kXb(a,62))};_.a=null;Myc(1581,234,HBe,Pzd);_.sg=function Qzd(a){var b;b=kXb(XF(a),331);Hzd(kXb(Mo(b,sFe),283).a,kXb(Mo(b,rFe),283).a)};Myc(1582,1,{226:1,231:1,391:1},Szd);_.a=null;Myc(1583,236,HBe,Vzd);_.tg=function Wzd(a){Uzd(this,kXb(a,59))};_.a=null;Myc(1584,236,HBe,Zzd);_.tg=function $zd(a){Yzd(this,kXb(a,59))};_.a=null;_.b=null;Myc(1585,1,HBe,bAd);_.Ad=function cAd(a){aAd(this,kXb(a,62))};_.a=null;Myc(1586,1202,{},eAd);_.em=function fAd(a){if(mXb(a,380)){eBc(mhd(x0e,x0e)+GDe+mhd(e9e,e9e))&&Fzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{dBc(mhd(jcf,jcf)+GDe+a.kd());rb(mhd(jcf,jcf),a)}};_.He=function gAd(a){var b;HY(this.a,null);b=new FYc;b.Td(XZe,(zPc(),zPc(),yPc));SBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;Myc(2131,1,kDe);_.Ck=function ofe(){$Y(new Izd(this.a.o,this.a.o.n.q,this.a.a))};var Ohc=oQc(zaf,'ImageCrop',1579),Hhc=oQc(zaf,'ImageCrop$1',1580),Ihc=oQc(zaf,'ImageCrop$2',1581),Jhc=oQc(zaf,'ImageCrop$3',1582),Khc=oQc(zaf,'ImageCrop$4',1583),Lhc=oQc(zaf,'ImageCrop$5',1584),Mhc=oQc(zaf,'ImageCrop$6',1585),Nhc=oQc(zaf,'ImageCrop$7',1586),N7b=oQc(jbf,Rbf,787);CDe(EKb)(2);