function IPb(){}
function ZBd(){}
function WBd(a){this.a=a}
function aCd(a){this.a=a}
function dCd(a){this.a=a}
function lCd(a){this.a=a}
function VBd(a){a.a.a=false}
function cCd(a){UY(a.a,null)}
function hCd(a,b){this.a=a;this.b=b}
function IOc(a,b){HOc(a,(jCc(),new gCc(b)))}
function HPb(){HPb=aSe;GPb=new vPb(_4e,new IPb)}
function PBd(a,b,c,d,e,g,i,j){Mld(nld(),b,c,d,e,g,i,j,new oCd(a,b,c,d,e,g,i))}
function oCd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function kCd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){RBd(DXb(y9(a.a.i),287).cm(),DXb(y9(a.a.b),287).cm());!!a.a.f&&ddb(a.a.f)}}
function RBd(b,c){try{var d=$wnd.jQuery(Ptf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function QBd(b){thisic=b;$wnd.jQuery(Ptf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function gCd(a){DXb(y9(a.a.i),287).cm()>0&&DXb(y9(a.a.b),287).cm()>0&&PBd(a.a,DXb(Eo(a.b,o9e),1),DXb(a.a.e.ne(),1),DXb(y9(a.a.g),287).cm(),DXb(y9(a.a.c),287).cm(),DXb(y9(a.a.i),287).cm(),DXb(y9(a.a.b),287).cm(),false)}
function Mld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new aJc(b,Faf,'cropImage');try{q=_Ic(p,Gaf,7);oIc(q,kIc(q,R6e));oIc(q,kIc(q,R6e));oIc(q,kIc(q,maf));oIc(q,kIc(q,maf));oIc(q,kIc(q,maf));oIc(q,kIc(q,maf));oIc(q,kIc(q,Iaf));oIc(q,kIc(q,c));oIc(q,kIc(q,d));MIc(q.a,GUe+e);MIc(q.a,GUe+g);MIc(q.a,GUe+i);MIc(q.a,GUe+j);MIc(q.a,k?KYe:uXe);$Ic(p,n,(sJc(),rJc))}catch(a){a=HAc(a);if(FXb(a,256)){o=a;f4c(n,o)}else throw a}}
function SBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,wkd(Qtf,Qtf));this.Dc=Rtf;!!this.vc&&(gx(this).id=Rtf,undefined);p=new _zb(dYe);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),oYe),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,WVe,Stf):(y.Tc+=Ttf);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(Utf);Px(this.e,Utf);H9(this.e,wkd('newName.label','New name'));n=DXb(Eo(c,sZe),1).lastIndexOf(vXe);if(n>0){k=AVc(DXb(Eo(c,sZe),1),n);this.e.$i(wVc(DXb(Eo(c,sZe),1),k,Vtf+k))}else{this.e.$i(DXb(Eo(c,sZe),1)+Vtf)}Sw(this.e,(RE(),ZC),new WBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,WVe,Stf):(z.Tc+=Ttf);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,Tbc);this.b=new ikb;Zjb(this.b,Tbc);v=DXb(Eo(c,v9e),1);t=DXb(Eo(c,w9e),1);u=0;s=0;try{u=v!=null?KSc(v,10,-2147483648,2147483647):0;s=t!=null?KSc(t,10,-2147483648,2147483647):0}catch(a){a=HAc(a);if(!FXb(a,288))throw a}if(!!d&&!d.Td()){C=new wLc;for(j=d.de();j.je();){i=DXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+lif+i[1];E=new u5c(w,w);Ho(E,hWe,i[0]);Ho(E,gWe,i[1]);uXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,kWe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new ZBd);kcb(this.f,wkd(Wtf,Xtf));oT(B,this.f,new Bzb(0.6))}}H9(this.i,wkd(fif,gif));J9(this.i,hWe);Px(this.i,hWe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,UVe,Stf):(x.Tc+='paddingLeft:10px;');q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,wkd(jif,kif));J9(this.b,gWe);Px(this.b,gWe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(dYe));r=new JOc;yw(r,new aCd(this),(HPb(),HPb(),GPb));r.dd.id='cropbox';IOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,Tbc);J9(this.g,QVe);Px(this.g,QVe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,Tbc);J9(this.c,PVe);Px(this.c,PVe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(wkd(kgf,kgf),new dCd(this));D=new jY(wkd(pgf,pgf),new hCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new lCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var Ptf='#cropbox',Vtf='-crop',Stf='10px',Rtf='JahiaGxtImageCrop',Ytf='failure.crop.label',Qtf='label.crop',Ttf='paddingRight:10px;';EBc(787,775,{},IPb);_.Sk=function JPb(a){QBd(DXb(DXb(a,227),393).a)};_.Vk=function KPb(){return GPb};var GPb;EBc(1566,364,aTe,SBd);_.Nm=function TBd(a,b,c,d){var e,g,i;ocb(this.c,kUc(a));ocb(this.g,kUc(b));M9(this.i,GUe+c);M9(this.b,GUe+d);if(this.a){g=DXb(this.e.ne(),1);e=sVc(g,KVc(46));this.e.$i(BVc(g,0,g.lastIndexOf(Vtf))+Vtf+c+QYe+d+(e!=-1?BVc(g,e,g.length):GUe))}i=this.f?DXb(mdb(this.f),333):null;!!i&&(c!=DXb(Eo(i,hWe),284).a||d!=DXb(Eo(i,gWe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;EBc(1567,1,tSe,WBd);_.Bd=function XBd(a){VBd(this,DXb(a,61))};_.a=null;EBc(1568,235,tSe,ZBd);_.wg=function $Bd(a){var b;b=DXb(fG(a),333);RBd(DXb(Eo(b,hWe),284).a,DXb(Eo(b,gWe),284).a)};EBc(1569,1,{227:1,232:1,393:1},aCd);_.a=null;EBc(1570,237,tSe,dCd);_.xg=function eCd(a){cCd(this,DXb(a,58))};_.a=null;EBc(1571,237,tSe,hCd);_.xg=function iCd(a){gCd(this,DXb(a,58))};_.a=null;_.b=null;EBc(1572,1,tSe,lCd);_.Bd=function mCd(a){kCd(this,DXb(a,61))};_.a=null;EBc(1573,1203,{},oCd);_.rm=function pCd(a){if(FXb(a,382)){ZDc(wkd(Bhf,Bhf)+wUe+wkd(Qqf,Qqf))&&PBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{YDc(wkd(Ytf,Ytf)+wUe+a.ld());rb(wkd(Ytf,Ytf),a)}};_.Je=function qCd(a){var b;UY(this.a,null);b=new D_c;b.Vd(Bef,(xSc(),xSc(),wSc));this.a.d.Em(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;EBc(2261,1,_Te);_.Nk=function Gve(){mZ(new SBd(this.a.o,this.a.o.Am().q,this.a.a))};var Vhc=mTc(rsf,'ImageCrop',1566),Ohc=mTc(rsf,'ImageCrop$1',1567),Phc=mTc(rsf,'ImageCrop$2',1568),Qhc=mTc(rsf,'ImageCrop$3',1569),Rhc=mTc(rsf,'ImageCrop$4',1570),Shc=mTc(rsf,'ImageCrop$5',1571),Thc=mTc(rsf,'ImageCrop$6',1572),Uhc=mTc(rsf,'ImageCrop$7',1573),d8b=mTc(btf,atf,787);sUe(VKb)(2);