function JPb(){}
function hAd(){}
function eAd(a){this.a=a}
function kAd(a){this.a=a}
function nAd(a){this.a=a}
function vAd(a){this.a=a}
function dAd(a){a.a.a=false}
function mAd(a){HY(a.a,null)}
function ULc(a,b){a.a.Ql(a,b)}
function rAd(a,b){this.a=a;this.b=b}
function VLc(a,b){ULc(a,(Ozc(),new Lzc(b)))}
function IPb(){IPb=HBe;HPb=new wPb(xdf,new JPb)}
function WLc(){RLc();SLc(this,new oMc(this));this.cd[DIe]=tff}
function yAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function Zzd(a,b,c,d,e,g,i,j){Vid(wid(),b,c,d,e,g,i,j,new yAd(a,b,c,d,e,g,i))}
function _zd(b,c){try{var d=$wnd.jQuery(oxg).data(pxg);var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function uAd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){_zd(EXb(t9(a.a.i),286).Sl(),EXb(t9(a.a.b),286).Sl());!!a.a.f&&$cb(a.a.f)}}
function $zd(b){thisic=b;$wnd.jQuery(oxg).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function qAd(a){EXb(t9(a.a.i),286).Sl()>0&&EXb(t9(a.a.b),286).Sl()>0&&Zzd(a.a,EXb(No(a.b,Rkf),1),EXb(a.a.e.le(),1),EXb(t9(a.a.g),286).Sl(),EXb(t9(a.a.c),286).Sl(),EXb(t9(a.a.i),286).Sl(),EXb(t9(a.a.b),286).Sl(),false)}
function Vid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new qGc(b,Hmf,nxg);try{q=pGc(p,Jmf,7);EFc(q,AFc(q,shf));EFc(q,AFc(q,shf));EFc(q,AFc(q,mmf));EFc(q,AFc(q,mmf));EFc(q,AFc(q,mmf));EFc(q,AFc(q,mmf));EFc(q,AFc(q,Tmf));EFc(q,AFc(q,c));EFc(q,AFc(q,d));aGc(q.a,lEe+e);aGc(q.a,lEe+g);aGc(q.a,lEe+i);aGc(q.a,lEe+j);aGc(q.a,k?ULe:xJe);oGc(p,n,(IGc(),HGc))}catch(a){a=kyc(a);if(GXb(a,255)){o=a;B1c(n,o)}else throw a}}
function aAd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,Ghd(qxg,qxg));this.Cc=rxg;!!this.uc&&(ix(this).id=rxg,undefined);p=new Szb(KKe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),iLe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,fHe,sxg):(y.Sc+=txg);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(uxg);Rx(this.e,uxg);C9(this.e,Ghd(vxg,wxg));n=EXb(No(c,lOe),1).lastIndexOf(yJe);if(n>0){k=VSc(EXb(No(c,lOe),1),n);this.e.Qi(SSc(EXb(No(c,lOe),1),k,xxg+k))}else{this.e.Qi(EXb(No(c,lOe),1)+xxg)}Uw(this.e,(NE(),VC),new eAd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,fHe,sxg):(z.Sc+=txg);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Ybc);this.b=new dkb;Ujb(this.b,Ybc);v=EXb(No(c,$kf),1);t=EXb(No(c,_kf),1);u=0;s=0;try{u=v!=null?eQc(v,10,-2147483648,2147483647):0;s=t!=null?eQc(t,10,-2147483648,2147483647):0}catch(a){a=kyc(a);if(!GXb(a,287))throw a}if(!!d&&!d.Rd()){C=new MIc;for(j=d.be();j.he();){i=EXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+CAf+i[1];E=new M2c(w,w);Qo(E,tHe,i[0]);Qo(E,sHe,i[1]);vXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,xHe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new hAd);ecb(this.f,Ghd(yxg,zxg));bT(B,this.f,new szb(0.6))}}C9(this.i,Ghd(uAf,vAf));E9(this.i,tHe);Rx(this.i,tHe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,dHe,sxg):(x.Sc+=Axg);q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,Ghd(zAf,AAf));E9(this.b,sHe);Rx(this.b,sHe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(KKe));r=new WLc;Aw(r,new kAd(this),(IPb(),IPb(),HPb));r.cd.id=Bxg;VLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Ybc);E9(this.g,bHe);Rx(this.g,bHe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Ybc);E9(this.c,aHe);Rx(this.c,aHe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(Ghd(Evf,Evf),new nAd(this));D=new YX(Ghd(Dvf,Dvf),new rAd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new vAd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var oxg='#cropbox',xxg='-crop',sxg='10px',Dxg='ImageCrop',Exg='ImageCrop$1',Fxg='ImageCrop$2',Gxg='ImageCrop$3',Hxg='ImageCrop$4',Ixg='ImageCrop$5',Jxg='ImageCrop$6',Kxg='ImageCrop$7',rxg='JahiaGxtImageCrop',pxg='Jcrop',wxg='New name',nxg='cropImage',Bxg='cropbox',Cxg='failure.crop.label',qxg='label.crop',vxg='newName.label',Axg='paddingLeft:10px;',txg='paddingRight:10px;';hzc(789,777,{},JPb);_.Hk=function KPb(a){$zd(EXb(EXb(a,226),391).a)};_.Kk=function LPb(){return HPb};var HPb;hzc(1034,183,fCe,WLc);hzc(1035,1036,{});_.Ql=function jMc(a,b){SLc(a,new oMc(a));a.a.Ql(a,b)};hzc(1038,1036,{});_.Ql=function sMc(a,b){!!a.a&&(a.a.Nl(a)[uff]=lEe,undefined);kNb(a.cd,b.a)};hzc(1581,364,FCe,aAd);_.Nm=function bAd(a,b,c,d){var e,g,i;jcb(this.c,GRc(a));jcb(this.g,GRc(b));H9(this.i,lEe+c);H9(this.b,lEe+d);if(this.a){g=EXb(this.e.le(),1);e=OSc(g,dTc(46));this.e.Qi(WSc(g,0,g.lastIndexOf(xxg))+xxg+c+lMe+d+(e!=-1?WSc(g,e,g.length):lEe))}i=this.f?EXb(hdb(this.f),331):null;!!i&&(c!=EXb(No(i,tHe),283).a||d!=EXb(No(i,sHe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;hzc(1582,1,$Be,eAd);_.Ad=function fAd(a){dAd(this,EXb(a,62))};_.a=null;hzc(1583,235,$Be,hAd);_.sg=function iAd(a){var b;b=EXb(XF(a),331);_zd(EXb(No(b,tHe),283).a,EXb(No(b,sHe),283).a)};hzc(1584,1,{226:1,231:1,391:1},kAd);_.a=null;hzc(1585,237,$Be,nAd);_.tg=function oAd(a){mAd(this,EXb(a,59))};_.a=null;hzc(1586,237,$Be,rAd);_.tg=function sAd(a){qAd(this,EXb(a,59))};_.a=null;_.b=null;hzc(1587,1,$Be,vAd);_.Ad=function wAd(a){uAd(this,EXb(a,62))};_.a=null;hzc(1588,1204,{},yAd);_.fm=function zAd(a){if(GXb(a,380)){vBc(Ghd(Dyf,Dyf)+ZDe+Ghd(uUf,uUf))&&Zzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{uBc(Ghd(Cxg,Cxg)+ZDe+a.kd());rb(Ghd(Cxg,Cxg),a)}};_.He=function AAd(a){var b;HY(this.a,null);b=new ZYc;b.Td(Esf,(TPc(),TPc(),SPc));kCd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;hzc(2133,1,DDe);_.Ck=function Hfe(){$Y(new aAd(this.a.o,this.a.o.n.q,this.a.a))};var jic=IQc(L1f,Dxg,1581),cic=IQc(L1f,Exg,1582),dic=IQc(L1f,Fxg,1583),eic=IQc(L1f,Gxg,1584),fic=IQc(L1f,Hxg,1585),gic=IQc(L1f,Ixg,1586),hic=IQc(L1f,Jxg,1587),iic=IQc(L1f,Kxg,1588),g8b=IQc(zfg,Arg,789);VDe(EKb)(2);