function $yd(a){this.a=a}
function dzd(a){this.a=a}
function Qge(a){this.a=a}
function czd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function Pge(a){$Y(new Ryd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function Xyd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function Tyd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Wyd(a){var b,c;HY(a.a,null);gCd(a.b,Ghd(OPf,OPf));b=wid();c=new $yd(a.b);a.c?Yid(b,a.d,c):Yjd(b,a.d,EXb(t9(a.e),1),c)}
function Yjd(b,c,d,e){var g,i,j;i=new qGc(b,Hmf,Lxg);try{j=pGc(i,Jmf,2);EFc(j,AFc(j,Nmf));EFc(j,AFc(j,shf));FFc(j,c);EFc(j,AFc(j,d));oGc(i,e,(IGc(),HGc))}catch(a){a=kyc(a);if(GXb(a,255)){g=a;B1c(e,g)}else throw a}}
function Qyd(a,b){var c;b>1?(c=Hhd(Mxg,Nxg,uXb(Zwc,QBe,1,[lEe+b]))):EXb(No(EXb(a.i.Cl(0),349),slf),303)._d(Nsf)?(c=Hhd(Oxg,Pxg,uXb(Zwc,QBe,1,[EXb(No(a.q,lOe),1)]))):(c=Hhd(hGf,iGf,uXb(Zwc,QBe,1,[EXb(No(a.q,lOe),1)])));return c}
function Ryd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,Qxg);!!this.G&&Bk(rk(this.G,NXe),Qxg);YY(this,false);this.a=new _hb;RT(this.a,Ghd(hvf,hvf));this.a.zb=false;Jx(this.a,false);Rx(this.a,Rxg);BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new MIc;p=new MIc;for(k=b.i.be();k.he();){j=EXb(k.ie(),349);vXb(o.c,o.d++,j);AIc(p,EXb(No(j,Rkf),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),iLe),false);g.zb=false;this.b=rDd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$(Sxg+Ghd(ZNf,$Nf)+Txg));aT(this.a,r)}i=o.d;jq(this.b.H.e,new Tyd(this,b,i,g,r,c,s));if(c){n=Ghd(NUf,Uxg);aT(this.a,new q$(n));ST(this,(Lod(),Kod(),Hod))}q=new YX(Ghd(cQf,cQf),new Xyd(this,a,c,p,r));e=new YX(Ghd(eQf,eQf),new dzd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var $xg='620',_xg='70%',Txg=': <br />',Sxg='<br />',Vxg='<br /><br />',Uxg='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',ayg='DeleteActionItem$1$1',byg='DeleteItemWindow',cyg='DeleteItemWindow$1',dyg='DeleteItemWindow$2',eyg='DeleteItemWindow$2$1',fyg='DeleteItemWindow$3',Pxg='Do you really want to remove the selected PAGE {0}?',Nxg='Do you really want to remove the {0} selected resources?',Qxg='Informations',Rxg='JahiaGxtDeleteItem',Zxg='This node is still used by:',Xxg='Those nodes are still used in:',Lxg='markForDeletion',Mxg='message.remove.multiple.confirm',Wxg='message.remove.multiple.usage',Oxg='message.remove.single.page.confirm',Yxg='message.remove.single.usage';hzc(1564,364,FCe,Ryd);_.a=null;_.b=null;hzc(1565,226,$Be,Tyd);_.og=function Uyd(a){var b,c,d;b=EXb(a.c,303);c=b.Wd();d=Qyd(this.c,this.d);if(c>0){d+=Vxg+(this.d>1?Ghd(Wxg,Xxg):Ghd(Yxg,Zxg))}else{jT(this.a.a,this.b);jz(this.f,$xg,_xg);if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;hzc(1566,237,$Be,Xyd);_.tg=function Yyd(a){Wyd(this,EXb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;hzc(1567,1204,{},$yd);_.fm=function _yd(a){fCd(this.a);rb(a.ld(),a);j2(Ghd(dof,W3e),a.ld(),null)};_.He=function azd(a){var b;fCd(this.a);b=new ZYc;b.Td(Dsf,(TPc(),TPc(),SPc));kCd(this.a,b);nCd(this.a)};_.a=null;hzc(1568,237,$Be,dzd);_.tg=function ezd(a){czd(this,EXb(a,59))};_.a=null;hzc(2150,1,DDe);_.Ck=function Nge(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new MIc;for(e=c.i.be();e.he();){d=EXb(e.ie(),349);AIc(b,EXb(No(d,Rkf),1))}a=wid();Fjd(a,b,new Qge(this))}};hzc(2151,1204,{},Qge);_.fm=function Rge(a){uBc(XRf+a.ld())};_.He=function Sge(a){Pge(this,EXb(a,303))};_.a=null;var lrc=IQc(O2f,ayg,2151),Rhc=IQc(L1f,byg,1564),Nhc=IQc(L1f,cyg,1565),Phc=IQc(L1f,dyg,1566),Ohc=IQc(L1f,eyg,1567),Qhc=IQc(L1f,fyg,1568);VDe(EKb)(3);