function $Pb(){}
function tAd(){}
function qAd(a){this.b=a}
function wAd(a){this.b=a}
function zAd(a){this.b=a}
function HAd(a){this.b=a}
function pAd(a){a.b.b=false}
function yAd(a){HY(a.b,null)}
function mMc(a,b){a.b.Xl(a,b)}
function DAd(a,b){this.b=a;this.c=b}
function nMc(a,b){mMc(a,(bAc(),new $zc(b)))}
function ZPb(){ZPb=UBe;YPb=new NPb(ZQe,new $Pb)}
function oMc(){jMc();kMc(this,new IMc(this));this.dd[IGe]=yRe}
function jAd(a,b,c,d,e,g,i,j){fjd(Iid(),b,c,d,e,g,i,j,new KAd(a,b,c,d,e,g,i))}
function KAd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function lAd(b,c){try{var d=$wnd.jQuery(Kcf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function GAd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){lAd(RXb(t9(a.b.j),286).Zl(),RXb(t9(a.b.c),286).Zl());!!a.b.g&&$cb(a.b.g)}}
function kAd(b){thisic=b;$wnd.jQuery(Kcf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Um(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function CAd(a){RXb(t9(a.b.j),286).Zl()>0&&RXb(t9(a.b.c),286).Zl()>0&&jAd(a.b,RXb(Mo(a.c,hVe),1),RXb(a.b.f.me(),1),RXb(t9(a.b.i),286).Zl(),RXb(t9(a.b.d),286).Zl(),RXb(t9(a.b.j),286).Zl(),RXb(t9(a.b.c),286).Zl(),false)}
function fjd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new KGc(b,wWe,'cropImage');try{q=JGc(p,xWe,7);YFc(q,UFc(q,MSe));YFc(q,UFc(q,MSe));YFc(q,UFc(q,dWe));YFc(q,UFc(q,dWe));YFc(q,UFc(q,dWe));YFc(q,UFc(q,dWe));YFc(q,UFc(q,zWe));YFc(q,UFc(q,c));YFc(q,UFc(q,d));uGc(q.b,vEe+e);uGc(q.b,vEe+g);uGc(q.b,vEe+i);uGc(q.b,vEe+j);uGc(q.b,k?yIe:iHe);IGc(p,n,(aHc(),_Gc))}catch(a){a=zyc(a);if(TXb(a,255)){o=a;N1c(n,o)}else throw a}}
function mAd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,Shd(Lcf,Lcf));this.Dc=Mcf;!!this.vc&&(ix(this).id=Mcf,undefined);p=new Szb(THe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),bIe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,MFe,Ncf):(y.Tc+=Ocf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(Pcf);Rx(this.f,Pcf);C9(this.f,Shd('newName.label','New name'));n=RXb(Mo(c,gJe),1).lastIndexOf(jHe);if(n>0){k=fTc(RXb(Mo(c,gJe),1),n);this.f.Ri(cTc(RXb(Mo(c,gJe),1),k,Qcf+k))}else{this.f.Ri(RXb(Mo(c,gJe),1)+Qcf)}Uw(this.f,(NE(),VC),new qAd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,MFe,Ncf):(z.Tc+=Ocf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,lcc);this.c=new dkb;Ujb(this.c,lcc);v=RXb(Mo(c,pVe),1);t=RXb(Mo(c,qVe),1);u=0;s=0;try{u=v!=null?pQc(v,10,-2147483648,2147483647):0;s=t!=null?pQc(t,10,-2147483648,2147483647):0}catch(a){a=zyc(a);if(!TXb(a,287))throw a}if(!!d&&!d.Sd()){C=new eJc;for(j=d.ce();j.ie();){i=RXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+k2e+i[1];E=new Y2c(w,w);Po(E,ZFe,i[0]);Po(E,YFe,i[1]);IXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,aGe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new tAd);ecb(this.g,Shd(Rcf,Scf));bT(B,this.g,new szb(0.6))}}C9(this.j,Shd(e2e,f2e));E9(this.j,ZFe);Rx(this.j,ZFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,KFe,Ncf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,Shd(i2e,j2e));E9(this.c,YFe);Rx(this.c,YFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(THe));r=new oMc;Aw(r,new wAd(this),(ZPb(),ZPb(),YPb));r.dd.id='cropbox';nMc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,lcc);E9(this.i,IFe);Rx(this.i,IFe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,lcc);E9(this.d,HFe);Rx(this.d,HFe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(Shd(t0e,t0e),new zAd(this));D=new YX(Shd(s0e,s0e),new DAd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new HAd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var Kcf='#cropbox',Qcf='-crop',Ncf='10px',Mcf='JahiaGxtImageCrop',Tcf='failure.crop.label',Lcf='label.crop',Ocf='paddingRight:10px;';wzc(790,778,{},$Pb);_.Pk=function _Pb(a){kAd(RXb(RXb(a,226),391).b)};_.Sk=function aQb(){return YPb};var YPb;wzc(1032,182,sCe,oMc);wzc(1033,1034,{});_.Xl=function DMc(a,b){kMc(a,new IMc(a));a.b.Xl(a,b)};wzc(1036,1034,{});_.Xl=function MMc(a,b){!!a.b&&(a.b.Ul(a)[zRe]=vEe,undefined);nNb(a.dd,b.b)};wzc(1576,363,SCe,mAd);_.Um=function nAd(a,b,c,d){var e,g,i;jcb(this.d,RRc(a));jcb(this.i,RRc(b));H9(this.j,vEe+c);H9(this.c,vEe+d);if(this.b){g=RXb(this.f.me(),1);e=ZSc(g,pTc(46));this.f.Ri(gTc(g,0,g.lastIndexOf(Qcf))+Qcf+c+EIe+d+(e!=-1?gTc(g,e,g.length):vEe))}i=this.g?RXb(hdb(this.g),331):null;!!i&&(c!=RXb(Mo(i,ZFe),283).b||d!=RXb(Mo(i,YFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;wzc(1577,1,lCe,qAd);_.Bd=function rAd(a){pAd(this,RXb(a,62))};_.b=null;wzc(1578,234,lCe,tAd);_.tg=function uAd(a){var b;b=RXb(XF(a),331);lAd(RXb(Mo(b,ZFe),283).b,RXb(Mo(b,YFe),283).b)};wzc(1579,1,{226:1,231:1,391:1},wAd);_.b=null;wzc(1580,236,lCe,zAd);_.ug=function AAd(a){yAd(this,RXb(a,59))};_.b=null;wzc(1581,236,lCe,DAd);_.ug=function EAd(a){CAd(this,RXb(a,59))};_.b=null;_.c=null;wzc(1582,1,lCe,HAd);_.Bd=function IAd(a){GAd(this,RXb(a,62))};_.b=null;wzc(1583,1199,{},KAd);_.mm=function LAd(a){if(TXb(a,380)){QBc(Shd(g1e,g1e)+lEe+Shd(O9e,O9e))&&jAd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{PBc(Shd(Tcf,Tcf)+lEe+a.ld());rb(Shd(Tcf,Tcf),a)}};_.Ie=function MAd(a){var b;HY(this.b,null);b=new jZc;b.Ud(G$e,(cQc(),cQc(),bQc));wCd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;wzc(2128,1,RDe);_.Hk=function Ufe(){$Y(new mAd(this.b.p,this.b.p.o.r,this.b.b))};var yic=TQc(hbf,'ImageCrop',1576),ric=TQc(hbf,'ImageCrop$1',1577),sic=TQc(hbf,'ImageCrop$2',1578),tic=TQc(hbf,'ImageCrop$3',1579),uic=TQc(hbf,'ImageCrop$4',1580),vic=TQc(hbf,'ImageCrop$5',1581),wic=TQc(hbf,'ImageCrop$6',1582),xic=TQc(hbf,'ImageCrop$7',1583),A8b=TQc(Sbf,ycf,790);hEe(PKb)(2);