function kzd(a){this.b=a}
function pzd(a){this.b=a}
function bhe(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function ozd(a){HY(a.b,null)}
function ahe(a){$Y(new bzd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function hzd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function dzd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function gzd(a){var b,c;HY(a.b,null);sCd(a.c,Shd(g8e,g8e));b=Iid();c=new kzd(a.c);a.d?ijd(b,a.e,c):ikd(b,a.e,RXb(t9(a.f),1),c)}
function ikd(b,c,d,e){var g,i,j;i=new KGc(b,wWe,'markForDeletion');try{j=JGc(i,xWe,2);YFc(j,UFc(j,yWe));YFc(j,UFc(j,MSe));ZFc(j,c);YFc(j,UFc(j,d));IGc(i,e,(aHc(),_Gc))}catch(a){a=zyc(a);if(TXb(a,255)){g=a;N1c(e,g)}else throw a}}
function azd(a,b){var c;b>1?(c=Thd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',HXb(mxc,bCe,1,[vEe+b]))):RXb(Mo(RXb(a.j.Jl(0),349),DVe),303).ae(N$e)?(c=Thd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',HXb(mxc,bCe,1,[RXb(Mo(a.r,gJe),1)]))):(c=Thd(B4e,C4e,HXb(mxc,bCe,1,[RXb(Mo(a.r,gJe),1)])));return c}
function bzd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,Ucf);!!this.H&&Bk(rk(this.H,ILe),Ucf);YY(this,false);this.b=new _hb;RT(this.b,Shd(h0e,h0e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new eJc;p=new eJc;for(k=b.j.ce();k.ie();){j=RXb(k.je(),349);IXb(o.d,o.e++,j);UIc(p,RXb(Mo(j,hVe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),bIe),false);g.Ab=false;this.c=DDd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+Shd(m7e,n7e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new dzd(this,b,i,g,r,c,s));if(c){n=Shd(U9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(Xod(),Wod(),Tod))}q=new YX(Shd(j8e,j8e),new hzd(this,a,c,p,r));e=new YX(Shd(k8e,k8e),new pzd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var Ucf='Informations';wzc(1559,363,SCe,bzd);_.b=null;_.c=null;wzc(1560,225,lCe,dzd);_.pg=function ezd(a){var b,c,d;b=RXb(a.d,303);c=b.Xd();d=azd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Shd('message.remove.multiple.usage','Those nodes are still used in:'):Shd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;wzc(1561,236,lCe,hzd);_.ug=function izd(a){gzd(this,RXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;wzc(1562,1199,{},kzd);_.mm=function lzd(a){rCd(this.b);rb(a.md(),a);j2(Shd(DWe,QUe),a.md(),null)};_.Ie=function mzd(a){var b;rCd(this.b);b=new jZc;b.Ud(F$e,(cQc(),cQc(),bQc));wCd(this.b,b);zCd(this.b)};_.b=null;wzc(1563,236,lCe,pzd);_.ug=function qzd(a){ozd(this,RXb(a,59))};_.b=null;wzc(2145,1,RDe);_.Hk=function $ge(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new eJc;for(e=c.j.ce();e.ie();){d=RXb(e.je(),349);UIc(b,RXb(Mo(d,hVe),1))}a=Iid();Rjd(a,b,new bhe(this))}};wzc(2146,1199,{},bhe);_.mm=function che(a){PBc(Y8e+a.md())};_.Ie=function dhe(a){ahe(this,RXb(a,303))};_.b=null;var Arc=TQc(mbf,'DeleteActionItem$1$1',2146),eic=TQc(hbf,'DeleteItemWindow',1559),aic=TQc(hbf,'DeleteItemWindow$1',1560),cic=TQc(hbf,'DeleteItemWindow$2',1561),bic=TQc(hbf,'DeleteItemWindow$2$1',1562),dic=TQc(hbf,'DeleteItemWindow$3',1563);hEe(PKb)(3);