function _Pb(){}
function pCd(){}
function mCd(a){this.a=a}
function sCd(a){this.a=a}
function vCd(a){this.a=a}
function DCd(a){this.a=a}
function lCd(a){a.a.a=false}
function uCd(a){UY(a.a,null)}
function zCd(a,b){this.a=a;this.b=b}
function ROc(a,b){QOc(a,(FCc(),new CCc(b)))}
function $Pb(){$Pb=rSe;ZPb=new OPb(Dtf,new _Pb)}
function fCd(a,b,c,d,e,g,i,j){cmd(Fld(),b,c,d,e,g,i,j,new GCd(a,b,c,d,e,g,i))}
function GCd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function hCd(b,c){try{var d=$wnd.jQuery(AMg).data(BMg);var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function CCd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){hCd(WXb(y9(a.a.i),287).cm(),WXb(y9(a.a.b),287).cm());!!a.a.f&&ddb(a.a.f)}}
function gCd(b){thisic=b;$wnd.jQuery(AMg).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function yCd(a){WXb(y9(a.a.i),287).cm()>0&&WXb(y9(a.a.b),287).cm()>0&&fCd(a.a,WXb(Fo(a.b,XAf),1),WXb(a.a.e.ne(),1),WXb(y9(a.a.g),287).cm(),WXb(y9(a.a.c),287).cm(),WXb(y9(a.a.i),287).cm(),WXb(y9(a.a.b),287).cm(),false)}
function cmd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new jJc(b,MCf,zMg);try{q=iJc(p,OCf,7);xIc(q,tIc(q,yxf));xIc(q,tIc(q,yxf));xIc(q,tIc(q,rCf));xIc(q,tIc(q,rCf));xIc(q,tIc(q,rCf));xIc(q,tIc(q,rCf));xIc(q,tIc(q,XCf));xIc(q,tIc(q,c));xIc(q,tIc(q,d));VIc(q.a,_Ue+e);VIc(q.a,_Ue+g);VIc(q.a,_Ue+i);VIc(q.a,_Ue+j);VIc(q.a,k?H0e:j$e);hJc(p,n,(BJc(),AJc))}catch(a){a=bBc(a);if(YXb(a,256)){o=a;x4c(n,o)}else throw a}}
function iCd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,Okd(CMg,CMg));this.Dc=DMg;!!this.vc&&(gx(this).id=DMg,undefined);p=new _zb(w_e);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),X_e),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,SXe,EMg):(y.Tc+=FMg);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(GMg);Px(this.e,GMg);H9(this.e,Okd(HMg,IMg));n=WXb(Fo(c,Z2e),1).lastIndexOf(k$e);if(n>0){k=SVc(WXb(Fo(c,Z2e),1),n);this.e.$i(OVc(WXb(Fo(c,Z2e),1),k,JMg+k))}else{this.e.$i(WXb(Fo(c,Z2e),1)+JMg)}Sw(this.e,(RE(),ZC),new mCd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,SXe,EMg):(z.Tc+=FMg);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,ncc);this.b=new ikb;Zjb(this.b,ncc);v=WXb(Fo(c,dBf),1);t=WXb(Fo(c,eBf),1);u=0;s=0;try{u=v!=null?aTc(v,10,-2147483648,2147483647):0;s=t!=null?aTc(t,10,-2147483648,2147483647):0}catch(a){a=bBc(a);if(!YXb(a,288))throw a}if(!!d&&!d.Td()){C=new FLc;for(j=d.de();j.je();){i=WXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+EPf+i[1];E=new M5c(w,w);Io(E,eYe,i[0]);Io(E,dYe,i[1]);NXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,iYe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new pCd);kcb(this.f,Okd(KMg,LMg));oT(B,this.f,new Bzb(0.6))}}H9(this.i,Okd(wPf,xPf));J9(this.i,eYe);Px(this.i,eYe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,QXe,EMg):(x.Tc+=MMg);q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,Okd(BPf,CPf));J9(this.b,dYe);Px(this.b,dYe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(w_e));r=new SOc;yw(r,new sCd(this),($Pb(),$Pb(),ZPb));r.dd.id=NMg;ROc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,ncc);J9(this.g,MXe);Px(this.g,MXe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,ncc);J9(this.c,LXe);Px(this.c,LXe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(Okd(hLf,hLf),new vCd(this));D=new jY(Okd(rLf,rLf),new zCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new DCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var AMg='#cropbox',JMg='-crop',EMg='10px',PMg='ImageCrop',QMg='ImageCrop$1',RMg='ImageCrop$2',SMg='ImageCrop$3',TMg='ImageCrop$4',UMg='ImageCrop$5',VMg='ImageCrop$6',WMg='ImageCrop$7',DMg='JahiaGxtImageCrop',BMg='Jcrop',IMg='New name',zMg='cropImage',NMg='cropbox',OMg='failure.crop.label',CMg='label.crop',HMg='newName.label',MMg='paddingLeft:10px;',FMg='paddingRight:10px;';$Bc(789,777,{},_Pb);_.Sk=function aQb(a){gCd(WXb(WXb(a,227),393).a)};_.Vk=function bQb(){return ZPb};var ZPb;$Bc(1568,365,rTe,iCd);_.Nm=function jCd(a,b,c,d){var e,g,i;ocb(this.c,CUc(a));ocb(this.g,CUc(b));M9(this.i,_Ue+c);M9(this.b,_Ue+d);if(this.a){g=WXb(this.e.ne(),1);e=KVc(g,aWc(46));this.e.$i(TVc(g,0,g.lastIndexOf(JMg))+JMg+c+$0e+d+(e!=-1?TVc(g,e,g.length):_Ue))}i=this.f?WXb(mdb(this.f),333):null;!!i&&(c!=WXb(Fo(i,eYe),284).a||d!=WXb(Fo(i,dYe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;$Bc(1569,1,KSe,mCd);_.Bd=function nCd(a){lCd(this,WXb(a,61))};_.a=null;$Bc(1570,236,KSe,pCd);_.wg=function qCd(a){var b;b=WXb(fG(a),333);hCd(WXb(Fo(b,eYe),284).a,WXb(Fo(b,dYe),284).a)};$Bc(1571,1,{227:1,232:1,393:1},sCd);_.a=null;$Bc(1572,238,KSe,vCd);_.xg=function wCd(a){uCd(this,WXb(a,58))};_.a=null;$Bc(1573,238,KSe,zCd);_.xg=function ACd(a){yCd(this,WXb(a,58))};_.a=null;_.b=null;$Bc(1574,1,KSe,DCd);_.Bd=function ECd(a){CCd(this,WXb(a,61))};_.a=null;$Bc(1575,1205,{},GCd);_.rm=function HCd(a){if(YXb(a,382)){mEc(Okd(jOf,jOf)+NUe+Okd(t8f,t8f))&&fCd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{lEc(Okd(OMg,OMg)+NUe+a.ld());rb(Okd(OMg,OMg),a)}};_.Je=function ICd(a){var b;UY(this.a,null);b=new V_c;b.Vd(qIf,(PSc(),PSc(),OSc));this.a.d.Em(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;$Bc(2263,1,qUe);_.Nk=function Xve(){mZ(new iCd(this.a.o,this.a.o.Am().q,this.a.a))};var pic=ETc(Pig,PMg,1568),iic=ETc(Pig,QMg,1569),jic=ETc(Pig,RMg,1570),kic=ETc(Pig,SMg,1571),lic=ETc(Pig,TMg,1572),mic=ETc(Pig,UMg,1573),nic=ETc(Pig,VMg,1574),oic=ETc(Pig,WMg,1575),x8b=ETc(axg,Uwg,789);JUe(VKb)(2);