function lBd(a){this.a=a}
function exe(a){this.a=a}
function kBd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function gBd(a,b){this.a=a;this.b=b}
function dBd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function _Ad(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function dxe(a){mZ(new ZAd(a.a.a.o,a.a.a.o.Am(),a.a.a.b))}
function cBd(a){var b,c;UY(a.a,null);a.b.Dm(Okd(M3f,M3f));b=Fld();c=new gBd(a.b,a.d);a.c?fmd(b,a.d,c):ind(b,a.d,WXb(y9(a.e),1),c)}
function ind(b,c,d,e){var g,i,j;i=new jJc(b,MCf,XMg);try{j=iJc(i,OCf,2);xIc(j,tIc(j,SCf));xIc(j,tIc(j,yxf));yIc(j,c);xIc(j,tIc(j,d));hJc(i,e,(BJc(),AJc))}catch(a){a=bBc(a);if(YXb(a,256)){g=a;x4c(e,g)}else throw a}}
function YAd(a,b){var c;b>1?(c=Pkd(YMg,ZMg,MXb(Qzc,ASe,1,[_Ue+b]))):WXb(Fo(WXb(a.i.Nl(0),351),xBf),304).be(BIf)?(c=Pkd($Mg,_Mg,MXb(Qzc,ASe,1,[WXb(Fo(a.q,Z2e),1)]))):(c=Pkd(O8f,P8f,MXb(Qzc,ASe,1,[WXb(Fo(a.q,Z2e),1)])));return c}
function ZAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,aNg);!!this.G&&sk(ik(this.G,zcf),aNg);kZ(this,false);this.a=new eib;cU(this.a,Okd(JOf,JOf));this.a.Ab=false;Hx(this.a,false);Px(this.a,bNg);MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new FLc;p=new FLc;for(k=b.i.de();k.je();){j=WXb(k.ke(),351);NXb(o.c,o.d++,j);tLc(p,WXb(Fo(j,XAf),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),X_e),false);g.Ab=false;this.b=AFd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$(cNg+Okd($1f,_1f)+dNg));nT(this.a,r)}i=o.d;bq(this.b.H.e,new _Ad(this,b,i,g,r,c,s));if(c){n=Okd(Q8f,eNg);nT(this.a,new I$(n));dU(this,(isd(),hsd(),esd))}q=new jY(Okd(a4f,a4f),new dBd(this,a,c,p,r));e=new jY(Okd(c4f,c4f),new lBd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var kNg='620',lNg='70%',dNg=': <br />',cNg='<br />',fNg='<br /><br />',eNg='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',mNg='DeleteActionItem$1$1',nNg='DeleteItemWindow',oNg='DeleteItemWindow$1',pNg='DeleteItemWindow$2',qNg='DeleteItemWindow$2$1',rNg='DeleteItemWindow$3',_Mg='Do you really want to remove the selected PAGE {0}?',ZMg='Do you really want to remove the {0} selected resources?',aNg='Informations',bNg='JahiaGxtDeleteItem',jNg='This node is still used by:',hNg='Those nodes are still used in:',XMg='markForDeletion',YMg='message.remove.multiple.confirm',gNg='message.remove.multiple.usage',$Mg='message.remove.single.page.confirm',iNg='message.remove.single.usage';$Bc(1551,365,rTe,ZAd);_.a=null;_.b=null;$Bc(1552,226,KSe,_Ad);_.rg=function aBd(a){var b,c,d;b=WXb(a.c,304);c=b.Yd();d=YAd(this.c,this.d);if(c>0){d+=fNg+(this.d>1?Okd(gNg,hNg):Okd(iNg,jNg))}else{wT(this.a.a,this.b);hz(this.f,kNg,lNg);if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;$Bc(1553,238,KSe,dBd);_.xg=function eBd(a){cBd(this,WXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;$Bc(1554,1205,{},gBd);_.rm=function hBd(a){this.a.Cm();rb(a.md(),a);H2(Okd(bEf,wAf),a.md(),null)};_.Je=function iBd(a){var b,c;this.a.Cm();c=null;YXb(this.a,431)?(c=WXb(this.a,431).c.t):YXb(this.a,418)&&(c=WXb(this.a,418));b=new V_c;!!c&&yLc(this.b,WXb(Fo(c.o.g,XAf),1),0)!=-1?b.Vd(nIf,c.o.g):b.Vd(pIf,(PSc(),PSc(),OSc));this.a.Em(b);this.a.Fm(null)};_.a=null;_.b=null;$Bc(1555,238,KSe,lBd);_.xg=function mBd(a){kBd(this,WXb(a,58))};_.a=null;$Bc(2280,1,qUe);_.Nk=function bxe(){var a,b,c,d,e;c=this.a.o.Am();if(!c.i.Td()){b=new FLc;for(e=c.i.de();e.je();){d=WXb(e.ke(),351);tLc(b,WXb(Fo(d,XAf),1))}a=Fld();Smd(a,b,new exe(this))}};$Bc(2281,1205,{},exe);_.rm=function fxe(a){lEc(V5f+a.md())};_.Je=function gxe(a){dxe(this,WXb(a,304))};_.a=null;var buc=ETc(Sjg,mNg,2281),Xhc=ETc(Pig,nNg,1551),Thc=ETc(Pig,oNg,1552),Vhc=ETc(Pig,pNg,1553),Uhc=ETc(Pig,qNg,1554),Whc=ETc(Pig,rNg,1555);JUe(VKb)(3);