function uPb(){}
function szd(){}
function pzd(a){this.a=a}
function vzd(a){this.a=a}
function yzd(a){this.a=a}
function Gzd(a){this.a=a}
function ozd(a){a.a.a=false}
function xzd(a){HY(a.a,null)}
function mLc(a,b){a.a.Gl(a,b)}
function Czd(a,b){this.a=a;this.b=b}
function nLc(a,b){mLc(a,(azc(),new Zyc(b)))}
function tPb(){tPb=TAe;sPb=new hPb(BPe,new uPb)}
function oLc(){jLc();kLc(this,new ILc(this));this.cd[GFe]=TPe}
function izd(a,b,c,d,e,g,i,j){eid(Hhd(),b,c,d,e,g,i,j,new Jzd(a,b,c,d,e,g,i))}
function Jzd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function Fzd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){kzd(VWb(t9(a.a.i),286).Il(),VWb(t9(a.a.b),286).Il());!!a.a.f&&$cb(a.a.f)}}
function kzd(b,c){try{var d=$wnd.jQuery(dbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function jzd(b){thisic=b;$wnd.jQuery(dbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Bzd(a){VWb(t9(a.a.i),286).Il()>0&&VWb(t9(a.a.b),286).Il()>0&&izd(a.a,VWb(No(a.b,DTe),1),VWb(a.a.e.le(),1),VWb(t9(a.a.g),286).Il(),VWb(t9(a.a.c),286).Il(),VWb(t9(a.a.i),286).Il(),VWb(t9(a.a.b),286).Il(),false)}
function eid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new KFc(b,SUe,'cropImage');try{q=JFc(p,TUe,7);YEc(q,UEc(q,gRe));YEc(q,UEc(q,gRe));YEc(q,UEc(q,zUe));YEc(q,UEc(q,zUe));YEc(q,UEc(q,zUe));YEc(q,UEc(q,zUe));YEc(q,UEc(q,VUe));YEc(q,UEc(q,c));YEc(q,UEc(q,d));uFc(q.a,tDe+e);uFc(q.a,tDe+g);uFc(q.a,tDe+i);uFc(q.a,tDe+j);uFc(q.a,k?wHe:gGe);IFc(p,n,(aGc(),_Fc))}catch(a){a=yxc(a);if(XWb(a,255)){o=a;M0c(n,o)}else throw a}}
function lzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,Rgd(ebf,ebf));this.Cc=fbf;!!this.uc&&(ix(this).id=fbf,undefined);p=new Szb(RGe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),aHe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,KEe,gbf):(y.Sc+=hbf);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(ibf);Rx(this.e,ibf);C9(this.e,Rgd('newName.label','New name'));n=VWb(No(c,dIe),1).lastIndexOf(hGe);if(n>0){k=eSc(VWb(No(c,dIe),1),n);this.e.Qi(bSc(VWb(No(c,dIe),1),k,jbf+k))}else{this.e.Qi(VWb(No(c,dIe),1)+jbf)}Uw(this.e,(NE(),VC),new pzd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,KEe,gbf):(z.Sc+=hbf);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,kbc);this.b=new dkb;Ujb(this.b,kbc);v=VWb(No(c,LTe),1);t=VWb(No(c,MTe),1);u=0;s=0;try{u=v!=null?pPc(v,10,-2147483648,2147483647):0;s=t!=null?pPc(t,10,-2147483648,2147483647):0}catch(a){a=yxc(a);if(!XWb(a,287))throw a}if(!!d&&!d.Rd()){C=new eIc;for(j=d.be();j.he();){i=VWb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+G0e+i[1];E=new X1c(w,w);Qo(E,XEe,i[0]);Qo(E,WEe,i[1]);MWb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,$Ee);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new szd);ecb(this.f,Rgd(kbf,lbf));bT(B,this.f,new szb(0.6))}}C9(this.i,Rgd(A0e,B0e));E9(this.i,XEe);Rx(this.i,XEe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,IEe,gbf):(x.Sc+='paddingLeft:10px;');q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,Rgd(E0e,F0e));E9(this.b,WEe);Rx(this.b,WEe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(RGe));r=new oLc;Aw(r,new vzd(this),(tPb(),tPb(),sPb));r.cd.id='cropbox';nLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,kbc);E9(this.g,GEe);Rx(this.g,GEe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,kbc);E9(this.c,FEe);Rx(this.c,FEe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(Rgd(P$e,P$e),new yzd(this));D=new YX(Rgd(O$e,O$e),new Czd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new Gzd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var dbf='#cropbox',jbf='-crop',gbf='10px',fbf='JahiaGxtImageCrop',mbf='failure.crop.label',ebf='label.crop',hbf='paddingRight:10px;';vyc(787,775,{},uPb);_.Hk=function vPb(a){jzd(VWb(VWb(a,226),391).a)};_.Kk=function wPb(){return sPb};var sPb;vyc(1032,183,rBe,oLc);vyc(1033,1034,{});_.Gl=function DLc(a,b){kLc(a,new ILc(a));a.a.Gl(a,b)};vyc(1036,1034,{});_.Gl=function MLc(a,b){!!a.a&&(a.a.Dl(a)[UPe]=tDe,undefined);HMb(a.cd,b.a)};vyc(1578,364,RBe,lzd);_.Dm=function mzd(a,b,c,d){var e,g,i;jcb(this.c,RQc(a));jcb(this.g,RQc(b));H9(this.i,tDe+c);H9(this.b,tDe+d);if(this.a){g=VWb(this.e.le(),1);e=ZRc(g,oSc(46));this.e.Qi(fSc(g,0,g.lastIndexOf(jbf))+jbf+c+CHe+d+(e!=-1?fSc(g,e,g.length):tDe))}i=this.f?VWb(hdb(this.f),331):null;!!i&&(c!=VWb(No(i,XEe),283).a||d!=VWb(No(i,WEe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;vyc(1579,1,kBe,pzd);_.Ad=function qzd(a){ozd(this,VWb(a,62))};_.a=null;vyc(1580,235,kBe,szd);_.sg=function tzd(a){var b;b=VWb(XF(a),331);kzd(VWb(No(b,XEe),283).a,VWb(No(b,WEe),283).a)};vyc(1581,1,{226:1,231:1,391:1},vzd);_.a=null;vyc(1582,237,kBe,yzd);_.tg=function zzd(a){xzd(this,VWb(a,59))};_.a=null;vyc(1583,237,kBe,Czd);_.tg=function Dzd(a){Bzd(this,VWb(a,59))};_.a=null;_.b=null;vyc(1584,1,kBe,Gzd);_.Ad=function Hzd(a){Fzd(this,VWb(a,62))};_.a=null;vyc(1585,1201,{},Jzd);_.Xl=function Kzd(a){if(XWb(a,380)){PAc(Rgd(C_e,C_e)+jDe+Rgd(g8e,g8e))&&izd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{OAc(Rgd(mbf,mbf)+jDe+a.kd());rb(Rgd(mbf,mbf),a)}};_.He=function Lzd(a){var b;HY(this.a,null);b=new iYc;b.Td(aZe,(cPc(),cPc(),bPc));vBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;vyc(2130,1,PCe);_.Ck=function Tee(){$Y(new lzd(this.a.o,this.a.o.n.q,this.a.a))};var xhc=TPc(B9e,'ImageCrop',1578),qhc=TPc(B9e,'ImageCrop$1',1579),rhc=TPc(B9e,'ImageCrop$2',1580),shc=TPc(B9e,'ImageCrop$3',1581),thc=TPc(B9e,'ImageCrop$4',1582),uhc=TPc(B9e,'ImageCrop$5',1583),vhc=TPc(B9e,'ImageCrop$6',1584),whc=TPc(B9e,'ImageCrop$7',1585),x7b=TPc(maf,Uaf,787);fDe(EKb)(2);