function pQb(){}
function zCd(){}
function wCd(a){this.b=a}
function CCd(a){this.b=a}
function FCd(a){this.b=a}
function NCd(a){this.b=a}
function vCd(a){a.b.b=false}
function ECd(a){UY(a.b,null)}
function JCd(a,b){this.b=a;this.c=b}
function hPc(a,b){gPc(a,(TCc(),new QCc(b)))}
function oQb(){oQb=CSe;nQb=new cQb(N5e,new pQb)}
function pCd(a,b,c,d,e,g,i,j){mmd(Pld(),b,c,d,e,g,i,j,new QCd(a,b,c,d,e,g,i))}
function QCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function rCd(b,c){try{var d=$wnd.jQuery(yuf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function MCd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){rCd(gYb(y9(a.b.j),287).jm(),gYb(y9(a.b.c),287).jm());!!a.b.g&&ddb(a.b.g)}}
function qCd(b){thisic=b;$wnd.jQuery(yuf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Um(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function ICd(a){gYb(y9(a.b.j),287).jm()>0&&gYb(y9(a.b.c),287).jm()>0&&pCd(a.b,gYb(Eo(a.c,Z9e),1),gYb(a.b.f.oe(),1),gYb(y9(a.b.i),287).jm(),gYb(y9(a.b.d),287).jm(),gYb(y9(a.b.j),287).jm(),gYb(y9(a.b.c),287).jm(),false)}
function mmd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new BJc(b,obf,'cropImage');try{q=AJc(p,pbf,7);PIc(q,LIc(q,B7e));PIc(q,LIc(q,B7e));PIc(q,LIc(q,Xaf));PIc(q,LIc(q,Xaf));PIc(q,LIc(q,Xaf));PIc(q,LIc(q,Xaf));PIc(q,LIc(q,rbf));PIc(q,LIc(q,c));PIc(q,LIc(q,d));lJc(q.b,hVe+e);lJc(q.b,hVe+g);lJc(q.b,hVe+i);lJc(q.b,hVe+j);lJc(q.b,k?lZe:XXe);zJc(p,n,(TJc(),SJc))}catch(a){a=pBc(a);if(iYb(a,256)){o=a;H4c(n,o)}else throw a}}
function sCd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,Ykd(zuf,zuf));this.Ec=Auf;!!this.wc&&(gx(this).id=Auf,undefined);p=new _zb(GYe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),RYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,xWe,Buf):(y.Uc+=Cuf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(Duf);Px(this.f,Duf);H9(this.f,Ykd('newName.label','New name'));n=gYb(Eo(c,VZe),1).lastIndexOf(YXe);if(n>0){k=aWc(gYb(Eo(c,VZe),1),n);this.f._i(YVc(gYb(Eo(c,VZe),1),k,Euf+k))}else{this.f._i(gYb(Eo(c,VZe),1)+Euf)}Sw(this.f,(RE(),ZC),new wCd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,xWe,Buf):(z.Uc+=Cuf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,Bcc);this.c=new ikb;Zjb(this.c,Bcc);v=gYb(Eo(c,eaf),1);t=gYb(Eo(c,faf),1);u=0;s=0;try{u=v!=null?jTc(v,10,-2147483648,2147483647):0;s=t!=null?jTc(t,10,-2147483648,2147483647):0}catch(a){a=pBc(a);if(!iYb(a,288))throw a}if(!!d&&!d.Ud()){C=new XLc;for(j=d.ee();j.ke();){i=gYb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+Xif+i[1];E=new W5c(w,w);Ho(E,KWe,i[0]);Ho(E,JWe,i[1]);ZXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,NWe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new zCd);kcb(this.g,Ykd(Fuf,Guf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,Ykd(Rif,Sif));J9(this.j,KWe);Px(this.j,KWe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,vWe,Buf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,Ykd(Vif,Wif));J9(this.c,JWe);Px(this.c,JWe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(GYe));r=new iPc;yw(r,new CCd(this),(oQb(),oQb(),nQb));r.ed.id='cropbox';hPc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,Bcc);J9(this.i,rWe);Px(this.i,rWe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,Bcc);J9(this.d,qWe);Px(this.d,qWe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(Ykd(Wgf,Wgf),new FCd(this));D=new jY(Ykd(_gf,_gf),new JCd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new NCd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var yuf='#cropbox',Euf='-crop',Buf='10px',Auf='JahiaGxtImageCrop',Huf='failure.crop.label',zuf='label.crop',Cuf='paddingRight:10px;';mCc(790,778,{},pQb);_.$k=function qQb(a){qCd(gYb(gYb(a,227),393).b)};_.bl=function rQb(){return nQb};var nQb;mCc(1563,364,CTe,sCd);_.Um=function tCd(a,b,c,d){var e,g,i;ocb(this.d,LUc(a));ocb(this.i,LUc(b));M9(this.j,hVe+c);M9(this.c,hVe+d);if(this.b){g=gYb(this.f.oe(),1);e=TVc(g,kWc(46));this.f._i(bWc(g,0,g.lastIndexOf(Euf))+Euf+c+rZe+d+(e!=-1?bWc(g,e,g.length):hVe))}i=this.g?gYb(mdb(this.g),333):null;!!i&&(c!=gYb(Eo(i,KWe),284).b||d!=gYb(Eo(i,JWe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;mCc(1564,1,VSe,wCd);_.Cd=function xCd(a){vCd(this,gYb(a,61))};_.b=null;mCc(1565,235,VSe,zCd);_.xg=function ACd(a){var b;b=gYb(fG(a),333);rCd(gYb(Eo(b,KWe),284).b,gYb(Eo(b,JWe),284).b)};mCc(1566,1,{227:1,232:1,393:1},CCd);_.b=null;mCc(1567,237,VSe,FCd);_.yg=function GCd(a){ECd(this,gYb(a,58))};_.b=null;mCc(1568,237,VSe,JCd);_.yg=function KCd(a){ICd(this,gYb(a,58))};_.b=null;_.c=null;mCc(1569,1,VSe,NCd);_.Cd=function OCd(a){MCd(this,gYb(a,61))};_.b=null;mCc(1570,1200,{},QCd);_.ym=function RCd(a){if(iYb(a,382)){HEc(Ykd(lif,lif)+ZUe+Ykd(zrf,zrf))&&pCd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{GEc(Ykd(Huf,Huf)+ZUe+a.md());rb(Ykd(Huf,Huf),a)}};_.Ke=function SCd(a){var b;UY(this.b,null);b=new d0c;b.Wd(kff,(YSc(),YSc(),XSc));this.b.e.Lm(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;mCc(2258,1,CUe);_.Sk=function gwe(){mZ(new sCd(this.b.p,this.b.p.Hm().r,this.b.b))};var Dic=NTc(_sf,'ImageCrop',1563),wic=NTc(_sf,'ImageCrop$1',1564),xic=NTc(_sf,'ImageCrop$2',1565),yic=NTc(_sf,'ImageCrop$3',1566),zic=NTc(_sf,'ImageCrop$4',1567),Aic=NTc(_sf,'ImageCrop$5',1568),Bic=NTc(_sf,'ImageCrop$6',1569),Cic=NTc(_sf,'ImageCrop$7',1570),Q8b=NTc(Ltf,Ktf,790);VUe(eLb)(2);