function vBd(a){this.b=a}
function pxe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function uBd(a){UY(a.b,null)}
function qBd(a,b){this.b=a;this.c=b}
function nBd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function jBd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function oxe(a){mZ(new hBd(a.b.b.p,a.b.b.p.Hm(),a.b.b.c))}
function mBd(a){var b,c;UY(a.b,null);a.c.Km(Ykd(Spf,Spf));b=Pld();c=new qBd(a.c,a.e);a.d?pmd(b,a.e,c):snd(b,a.e,gYb(y9(a.f),1),c)}
function snd(b,c,d,e){var g,i,j;i=new BJc(b,obf,'markForDeletion');try{j=AJc(i,pbf,2);PIc(j,LIc(j,qbf));PIc(j,LIc(j,B7e));QIc(j,c);PIc(j,LIc(j,d));zJc(i,e,(TJc(),SJc))}catch(a){a=pBc(a);if(iYb(a,256)){g=a;H4c(e,g)}else throw a}}
function gBd(a,b){var c;b>1?(c=Zkd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',YXb(cAc,LSe,1,[hVe+b]))):gYb(Eo(gYb(a.j.Ul(0),351),vaf),304).ce(vff)?(c=Zkd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',YXb(cAc,LSe,1,[gYb(Eo(a.r,VZe),1)]))):(c=Zkd(Hrf,Irf,YXb(cAc,LSe,1,[gYb(Eo(a.r,VZe),1)])));return c}
function hBd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,Iuf);!!this.H&&sk(ik(this.H,v0e),Iuf);kZ(this,false);this.b=new eib;cU(this.b,Ykd(xif,xif));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new XLc;p=new XLc;for(k=b.j.ee();k.ke();){j=gYb(k.le(),351);ZXb(o.d,o.e++,j);LLc(p,gYb(Eo(j,Z9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),RYe),false);g.Bb=false;this.c=KFd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+Ykd($of,_of)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new jBd(this,b,i,g,r,c,s));if(c){n=Ykd(Jrf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(ssd(),rsd(),osd))}q=new jY(Ykd(Vpf,Vpf),new nBd(this,a,c,p,r));e=new jY(Ykd(Wpf,Wpf),new vBd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var Iuf='Informations';mCc(1546,364,CTe,hBd);_.b=null;_.c=null;mCc(1547,225,VSe,jBd);_.sg=function kBd(a){var b,c,d;b=gYb(a.d,304);c=b.Zd();d=gBd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Ykd('message.remove.multiple.usage','Those nodes are still used in:'):Ykd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;mCc(1548,237,VSe,nBd);_.yg=function oBd(a){mBd(this,gYb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;mCc(1549,1200,{},qBd);_.ym=function rBd(a){this.b.Jm();rb(a.nd(),a);H2(Ykd(ubf,F9e),a.nd(),null)};_.Ke=function sBd(a){var b,c;this.b.Jm();c=null;iYb(this.b,431)?(c=gYb(this.b,431).d.u):iYb(this.b,418)&&(c=gYb(this.b,418));b=new d0c;!!c&&QLc(this.c,gYb(Eo(c.p.i,Z9e),1),0)!=-1?b.Wd(hff,c.p.i):b.Wd(jff,(YSc(),YSc(),XSc));this.b.Lm(b);this.b.Mm(null)};_.b=null;_.c=null;mCc(1550,237,VSe,vBd);_.yg=function wBd(a){uBd(this,gYb(a,58))};_.b=null;mCc(2275,1,CUe);_.Sk=function mxe(){var a,b,c,d,e;c=this.b.p.Hm();if(!c.j.Ud()){b=new XLc;for(e=c.j.ee();e.ke();){d=gYb(e.le(),351);LLc(b,gYb(Eo(d,Z9e),1))}a=Pld();and(a,b,new pxe(this))}};mCc(2276,1200,{},pxe);_.ym=function qxe(a){GEc(Fqf+a.nd())};_.Ke=function rxe(a){oxe(this,gYb(a,304))};_.b=null;var puc=NTc(etf,'DeleteActionItem$1$1',2276),jic=NTc(_sf,'DeleteItemWindow',1546),fic=NTc(_sf,'DeleteItemWindow$1',1547),hic=NTc(_sf,'DeleteItemWindow$2',1548),gic=NTc(_sf,'DeleteItemWindow$2$1',1549),iic=NTc(_sf,'DeleteItemWindow$3',1550);VUe(eLb)(3);