function uPb(){}
function Nzd(){}
function Kzd(a){this.a=a}
function Qzd(a){this.a=a}
function Tzd(a){this.a=a}
function _zd(a){this.a=a}
function Jzd(a){a.a.a=false}
function Szd(a){HY(a.a,null)}
function HLc(a,b){a.a.Pl(a,b)}
function Xzd(a,b){this.a=a;this.b=b}
function ILc(a,b){HLc(a,(vzc(),new szc(b)))}
function tPb(){tPb=mBe;sPb=new hPb(jQe,new uPb)}
function JLc(){ELc();FLc(this,new bMc(this));this.cd[_Fe]=BQe}
function Dzd(a,b,c,d,e,g,i,j){zid(aid(),b,c,d,e,g,i,j,new cAd(a,b,c,d,e,g,i))}
function cAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function $zd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){Fzd(nXb(t9(a.a.i),286).Rl(),nXb(t9(a.a.b),286).Rl());!!a.a.f&&$cb(a.a.f)}}
function Fzd(b,c){try{var d=$wnd.jQuery(Rbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Ezd(b){thisic=b;$wnd.jQuery(Rbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Wzd(a){nXb(t9(a.a.i),286).Rl()>0&&nXb(t9(a.a.b),286).Rl()>0&&Dzd(a.a,nXb(No(a.b,mUe),1),nXb(a.a.e.le(),1),nXb(t9(a.a.g),286).Rl(),nXb(t9(a.a.c),286).Rl(),nXb(t9(a.a.i),286).Rl(),nXb(t9(a.a.b),286).Rl(),false)}
function zid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new dGc(b,BVe,'cropImage');try{q=cGc(p,CVe,7);rFc(q,nFc(q,QRe));rFc(q,nFc(q,QRe));rFc(q,nFc(q,iVe));rFc(q,nFc(q,iVe));rFc(q,nFc(q,iVe));rFc(q,nFc(q,iVe));rFc(q,nFc(q,EVe));rFc(q,nFc(q,c));rFc(q,nFc(q,d));PFc(q.a,ODe+e);PFc(q.a,ODe+g);PFc(q.a,ODe+i);PFc(q.a,ODe+j);PFc(q.a,k?RHe:BGe);bGc(p,n,(vGc(),uGc))}catch(a){a=Txc(a);if(pXb(a,255)){o=a;f1c(n,o)}else throw a}}
function Gzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,khd(Sbf,Sbf));this.Cc=Tbf;!!this.uc&&(ix(this).id=Tbf,undefined);p=new Szb(kHe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),vHe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,dFe,Ubf):(y.Sc+=Vbf);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(Wbf);Rx(this.e,Wbf);C9(this.e,khd('newName.label','New name'));n=nXb(No(c,yIe),1).lastIndexOf(CGe);if(n>0){k=zSc(nXb(No(c,yIe),1),n);this.e.Qi(wSc(nXb(No(c,yIe),1),k,Xbf+k))}else{this.e.Qi(nXb(No(c,yIe),1)+Xbf)}Uw(this.e,(NE(),VC),new Kzd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,dFe,Ubf):(z.Sc+=Vbf);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Fbc);this.b=new dkb;Ujb(this.b,Fbc);v=nXb(No(c,uUe),1);t=nXb(No(c,vUe),1);u=0;s=0;try{u=v!=null?KPc(v,10,-2147483648,2147483647):0;s=t!=null?KPc(t,10,-2147483648,2147483647):0}catch(a){a=Txc(a);if(!pXb(a,287))throw a}if(!!d&&!d.Rd()){C=new zIc;for(j=d.be();j.he();){i=nXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+p1e+i[1];E=new q2c(w,w);Qo(E,qFe,i[0]);Qo(E,pFe,i[1]);eXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,tFe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new Nzd);ecb(this.f,khd(Ybf,Zbf));bT(B,this.f,new szb(0.6))}}C9(this.i,khd(j1e,k1e));E9(this.i,qFe);Rx(this.i,qFe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,bFe,Ubf):(x.Sc+='paddingLeft:10px;');q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,khd(n1e,o1e));E9(this.b,pFe);Rx(this.b,pFe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(kHe));r=new JLc;Aw(r,new Qzd(this),(tPb(),tPb(),sPb));r.cd.id='cropbox';ILc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Fbc);E9(this.g,_Ee);Rx(this.g,_Ee);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Fbc);E9(this.c,$Ee);Rx(this.c,$Ee);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(khd(y_e,y_e),new Tzd(this));D=new YX(khd(x_e,x_e),new Xzd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new _zd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var Rbf='#cropbox',Xbf='-crop',Ubf='10px',Tbf='JahiaGxtImageCrop',$bf='failure.crop.label',Sbf='label.crop',Vbf='paddingRight:10px;';Qyc(787,775,{},uPb);_.Hk=function vPb(a){Ezd(nXb(nXb(a,226),391).a)};_.Kk=function wPb(){return sPb};var sPb;Qyc(1033,183,MBe,JLc);Qyc(1034,1035,{});_.Pl=function YLc(a,b){FLc(a,new bMc(a));a.a.Pl(a,b)};Qyc(1037,1035,{});_.Pl=function fMc(a,b){!!a.a&&(a.a.Ml(a)[CQe]=ODe,undefined);HMb(a.cd,b.a)};Qyc(1579,364,kCe,Gzd);_.Mm=function Hzd(a,b,c,d){var e,g,i;jcb(this.c,kRc(a));jcb(this.g,kRc(b));H9(this.i,ODe+c);H9(this.b,ODe+d);if(this.a){g=nXb(this.e.le(),1);e=sSc(g,JSc(46));this.e.Qi(ASc(g,0,g.lastIndexOf(Xbf))+Xbf+c+XHe+d+(e!=-1?ASc(g,e,g.length):ODe))}i=this.f?nXb(hdb(this.f),331):null;!!i&&(c!=nXb(No(i,qFe),283).a||d!=nXb(No(i,pFe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;Qyc(1580,1,FBe,Kzd);_.Ad=function Lzd(a){Jzd(this,nXb(a,62))};_.a=null;Qyc(1581,235,FBe,Nzd);_.sg=function Ozd(a){var b;b=nXb(XF(a),331);Fzd(nXb(No(b,qFe),283).a,nXb(No(b,pFe),283).a)};Qyc(1582,1,{226:1,231:1,391:1},Qzd);_.a=null;Qyc(1583,237,FBe,Tzd);_.tg=function Uzd(a){Szd(this,nXb(a,59))};_.a=null;Qyc(1584,237,FBe,Xzd);_.tg=function Yzd(a){Wzd(this,nXb(a,59))};_.a=null;_.b=null;Qyc(1585,1,FBe,_zd);_.Ad=function aAd(a){$zd(this,nXb(a,62))};_.a=null;Qyc(1586,1202,{},cAd);_.em=function dAd(a){if(pXb(a,380)){iBc(khd(l0e,l0e)+EDe+khd(U8e,U8e))&&Dzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{hBc(khd($bf,$bf)+EDe+a.kd());rb(khd($bf,$bf),a)}};_.He=function eAd(a){var b;HY(this.a,null);b=new DYc;b.Td(LZe,(xPc(),xPc(),wPc));QBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;Qyc(2131,1,iDe);_.Ck=function mfe(){$Y(new Gzd(this.a.o,this.a.o.n.q,this.a.a))};var Shc=mQc(naf,'ImageCrop',1579),Lhc=mQc(naf,'ImageCrop$1',1580),Mhc=mQc(naf,'ImageCrop$2',1581),Nhc=mQc(naf,'ImageCrop$3',1582),Ohc=mQc(naf,'ImageCrop$4',1583),Phc=mQc(naf,'ImageCrop$5',1584),Qhc=mQc(naf,'ImageCrop$6',1585),Rhc=mQc(naf,'ImageCrop$7',1586),R7b=mQc($af,Gbf,787);ADe(EKb)(2);