function Eyd(a){this.a=a}
function Jyd(a){this.a=a}
function vge(a){this.a=a}
function Iyd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function uge(a){$Y(new vyd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function Byd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function xyd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Ayd(a){var b,c;HY(a.a,null);MBd(a.b,khd(m7e,m7e));b=aid();c=new Eyd(a.b);a.c?Cid(b,a.d,c):Cjd(b,a.d,nXb(t9(a.e),1),c)}
function Cjd(b,c,d,e){var g,i,j;i=new dGc(b,BVe,'markForDeletion');try{j=cGc(i,CVe,2);rFc(j,nFc(j,DVe));rFc(j,nFc(j,QRe));sFc(j,c);rFc(j,nFc(j,d));bGc(i,e,(vGc(),uGc))}catch(a){a=Txc(a);if(pXb(a,255)){g=a;f1c(e,g)}else throw a}}
function uyd(a,b){var c;b>1?(c=lhd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',dXb(Gwc,vBe,1,[ODe+b]))):nXb(No(nXb(a.i.Bl(0),349),IUe),303)._d(SZe)?(c=lhd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',dXb(Gwc,vBe,1,[nXb(No(a.q,yIe),1)]))):(c=lhd(G3e,H3e,dXb(Gwc,vBe,1,[nXb(No(a.q,yIe),1)])));return c}
function vyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,_bf);!!this.G&&Bk(rk(this.G,$Ke),_bf);YY(this,false);this.a=new _hb;RT(this.a,khd(m_e,m_e));this.a.zb=false;Jx(this.a,false);Rx(this.a,'JahiaGxtDeleteItem');BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new zIc;p=new zIc;for(k=b.i.be();k.he();){j=nXb(k.ie(),349);eXb(o.c,o.d++,j);nIc(p,nXb(No(j,mUe),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),vHe),false);g.zb=false;this.b=XCd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$('<br />'+khd(s6e,t6e)+': <br />'));aT(this.a,r)}i=o.d;jq(this.b.H.e,new xyd(this,b,i,g,r,c,s));if(c){n=khd($8e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.a,new q$(n));ST(this,(pod(),ood(),lod))}q=new YX(khd(p7e,p7e),new Byd(this,a,c,p,r));e=new YX(khd(q7e,q7e),new Jyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var _bf='Informations';Qyc(1562,364,kCe,vyd);_.a=null;_.b=null;Qyc(1563,226,FBe,xyd);_.og=function yyd(a){var b,c,d;b=nXb(a.c,303);c=b.Wd();d=uyd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?khd('message.remove.multiple.usage','Those nodes are still used in:'):khd('message.remove.single.usage','This node is still used by:'))}else{jT(this.a.a,this.b);jz(this.f,'620','70%');if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;Qyc(1564,237,FBe,Byd);_.tg=function Cyd(a){Ayd(this,nXb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;Qyc(1565,1202,{},Eyd);_.em=function Fyd(a){LBd(this.a);rb(a.ld(),a);j2(khd(IVe,UTe),a.ld(),null)};_.He=function Gyd(a){var b;LBd(this.a);b=new DYc;b.Td(KZe,(xPc(),xPc(),wPc));QBd(this.a,b);TBd(this.a)};_.a=null;Qyc(1566,237,FBe,Jyd);_.tg=function Kyd(a){Iyd(this,nXb(a,59))};_.a=null;Qyc(2148,1,iDe);_.Ck=function sge(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new zIc;for(e=c.i.be();e.he();){d=nXb(e.ie(),349);nIc(b,nXb(No(d,mUe),1))}a=aid();jjd(a,b,new vge(this))}};Qyc(2149,1202,{},vge);_.em=function wge(a){hBc(c8e+a.ld())};_.He=function xge(a){uge(this,nXb(a,303))};_.a=null;var Uqc=mQc(saf,'DeleteActionItem$1$1',2149),yhc=mQc(naf,'DeleteItemWindow',1562),uhc=mQc(naf,'DeleteItemWindow$1',1563),whc=mQc(naf,'DeleteItemWindow$2',1564),vhc=mQc(naf,'DeleteItemWindow$2$1',1565),xhc=mQc(naf,'DeleteItemWindow$3',1566);ADe(EKb)(3);