function mPb(){}
function Izd(){}
function Fzd(a){this.b=a}
function Lzd(a){this.b=a}
function Ozd(a){this.b=a}
function Wzd(a){this.b=a}
function Ezd(a){a.b.b=false}
function Nzd(a){HY(a.b,null)}
function CLc(a,b){a.b.Ql(a,b)}
function Szd(a,b){this.b=a;this.c=b}
function DLc(a,b){CLc(a,(nzc(),new kzc(b)))}
function lPb(){lPb=hBe;kPb=new _Ob(fQe,new mPb)}
function ELc(){zLc();ALc(this,new YLc(this));this.dd[WFe]=GQe}
function yzd(a,b,c,d,e,g,i,j){uid(Xhd(),b,c,d,e,g,i,j,new Zzd(a,b,c,d,e,g,i))}
function Zzd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function Azd(b,c){try{var d=$wnd.jQuery(Pbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Vzd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){Azd(fXb(t9(a.b.j),286).Sl(),fXb(t9(a.b.c),286).Sl());!!a.b.g&&$cb(a.b.g)}}
function zzd(b){thisic=b;$wnd.jQuery(Pbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Rzd(a){fXb(t9(a.b.j),286).Sl()>0&&fXb(t9(a.b.c),286).Sl()>0&&yzd(a.b,fXb(Mo(a.c,oUe),1),fXb(a.b.f.me(),1),fXb(t9(a.b.i),286).Sl(),fXb(t9(a.b.d),286).Sl(),fXb(t9(a.b.j),286).Sl(),fXb(t9(a.b.c),286).Sl(),false)}
function uid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new WFc(b,DVe,'cropImage');try{q=VFc(p,EVe,7);iFc(q,eFc(q,URe));iFc(q,eFc(q,URe));iFc(q,eFc(q,kVe));iFc(q,eFc(q,kVe));iFc(q,eFc(q,kVe));iFc(q,eFc(q,kVe));iFc(q,eFc(q,GVe));iFc(q,eFc(q,c));iFc(q,eFc(q,d));GFc(q.b,JDe+e);GFc(q.b,JDe+g);GFc(q.b,JDe+i);GFc(q.b,JDe+j);GFc(q.b,k?MHe:wGe);UFc(p,n,(mGc(),lGc))}catch(a){a=Lxc(a);if(hXb(a,255)){o=a;a1c(n,o)}else throw a}}
function Bzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,fhd(Qbf,Qbf));this.Dc=Rbf;!!this.vc&&(ix(this).id=Rbf,undefined);p=new Szb(fHe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),pHe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,$Ee,Sbf):(y.Tc+=Tbf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(Ubf);Rx(this.f,Ubf);C9(this.f,fhd('newName.label','New name'));n=fXb(Mo(c,uIe),1).lastIndexOf(xGe);if(n>0){k=uSc(fXb(Mo(c,uIe),1),n);this.f.Ri(rSc(fXb(Mo(c,uIe),1),k,Vbf+k))}else{this.f.Ri(fXb(Mo(c,uIe),1)+Vbf)}Uw(this.f,(NE(),VC),new Fzd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,$Ee,Sbf):(z.Tc+=Tbf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,xbc);this.c=new dkb;Ujb(this.c,xbc);v=fXb(Mo(c,wUe),1);t=fXb(Mo(c,xUe),1);u=0;s=0;try{u=v!=null?FPc(v,10,-2147483648,2147483647):0;s=t!=null?FPc(t,10,-2147483648,2147483647):0}catch(a){a=Lxc(a);if(!hXb(a,287))throw a}if(!!d&&!d.Sd()){C=new qIc;for(j=d.ce();j.ie();){i=fXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+p1e+i[1];E=new l2c(w,w);Po(E,lFe,i[0]);Po(E,kFe,i[1]);YWb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,oFe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new Izd);ecb(this.g,fhd(Wbf,Xbf));bT(B,this.g,new szb(0.6))}}C9(this.j,fhd(j1e,k1e));E9(this.j,lFe);Rx(this.j,lFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,YEe,Sbf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,fhd(n1e,o1e));E9(this.c,kFe);Rx(this.c,kFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(fHe));r=new ELc;Aw(r,new Lzd(this),(lPb(),lPb(),kPb));r.dd.id='cropbox';DLc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,xbc);E9(this.i,WEe);Rx(this.i,WEe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,xbc);E9(this.d,VEe);Rx(this.d,VEe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(fhd(y_e,y_e),new Ozd(this));D=new YX(fhd(x_e,x_e),new Szd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new Wzd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var Pbf='#cropbox',Vbf='-crop',Sbf='10px',Rbf='JahiaGxtImageCrop',Ybf='failure.crop.label',Qbf='label.crop',Tbf='paddingRight:10px;';Iyc(785,773,{},mPb);_.Hk=function nPb(a){zzd(fXb(fXb(a,226),391).b)};_.Kk=function oPb(){return kPb};var kPb;Iyc(1029,182,HBe,ELc);Iyc(1030,1031,{});_.Ql=function TLc(a,b){ALc(a,new YLc(a));a.b.Ql(a,b)};Iyc(1033,1031,{});_.Ql=function aMc(a,b){!!a.b&&(a.b.Nl(a)[HQe]=JDe,undefined);IMb(a.dd,b.b)};Iyc(1573,363,fCe,Bzd);_.Nm=function Czd(a,b,c,d){var e,g,i;jcb(this.d,fRc(a));jcb(this.i,fRc(b));H9(this.j,JDe+c);H9(this.c,JDe+d);if(this.b){g=fXb(this.f.me(),1);e=nSc(g,ESc(46));this.f.Ri(vSc(g,0,g.lastIndexOf(Vbf))+Vbf+c+SHe+d+(e!=-1?vSc(g,e,g.length):JDe))}i=this.g?fXb(hdb(this.g),331):null;!!i&&(c!=fXb(Mo(i,lFe),283).b||d!=fXb(Mo(i,kFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;Iyc(1574,1,ABe,Fzd);_.Bd=function Gzd(a){Ezd(this,fXb(a,62))};_.b=null;Iyc(1575,234,ABe,Izd);_.tg=function Jzd(a){var b;b=fXb(XF(a),331);Azd(fXb(Mo(b,lFe),283).b,fXb(Mo(b,kFe),283).b)};Iyc(1576,1,{226:1,231:1,391:1},Lzd);_.b=null;Iyc(1577,236,ABe,Ozd);_.ug=function Pzd(a){Nzd(this,fXb(a,59))};_.b=null;Iyc(1578,236,ABe,Szd);_.ug=function Tzd(a){Rzd(this,fXb(a,59))};_.b=null;_.c=null;Iyc(1579,1,ABe,Wzd);_.Bd=function Xzd(a){Vzd(this,fXb(a,62))};_.b=null;Iyc(1580,1196,{},Zzd);_.fm=function $zd(a){if(hXb(a,380)){aBc(fhd(l0e,l0e)+zDe+fhd(T8e,T8e))&&yzd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{_Ac(fhd(Ybf,Ybf)+zDe+a.ld());rb(fhd(Ybf,Ybf),a)}};_.Ie=function _zd(a){var b;HY(this.b,null);b=new yYc;b.Ud(MZe,(sPc(),sPc(),rPc));LBd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;Iyc(2125,1,dDe);_.Dk=function hfe(){$Y(new Bzd(this.b.p,this.b.p.o.r,this.b.b))};var Khc=hQc(maf,'ImageCrop',1573),Dhc=hQc(maf,'ImageCrop$1',1574),Ehc=hQc(maf,'ImageCrop$2',1575),Fhc=hQc(maf,'ImageCrop$3',1576),Ghc=hQc(maf,'ImageCrop$4',1577),Hhc=hQc(maf,'ImageCrop$5',1578),Ihc=hQc(maf,'ImageCrop$6',1579),Jhc=hQc(maf,'ImageCrop$7',1580),K7b=hQc(Xaf,Dbf,785);vDe(EKb)(2);