function zyd(a){this.b=a}
function Eyd(a){this.b=a}
function qge(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function Dyd(a){HY(a.b,null)}
function pge(a){$Y(new qyd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function wyd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function syd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function vyd(a){var b,c;HY(a.b,null);HBd(a.c,fhd(l7e,l7e));b=Xhd();c=new zyd(a.c);a.d?xid(b,a.e,c):xjd(b,a.e,fXb(t9(a.f),1),c)}
function xjd(b,c,d,e){var g,i,j;i=new WFc(b,DVe,'markForDeletion');try{j=VFc(i,EVe,2);iFc(j,eFc(j,FVe));iFc(j,eFc(j,URe));jFc(j,c);iFc(j,eFc(j,d));UFc(i,e,(mGc(),lGc))}catch(a){a=Lxc(a);if(hXb(a,255)){g=a;a1c(e,g)}else throw a}}
function pyd(a,b){var c;b>1?(c=ghd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',XWb(ywc,qBe,1,[JDe+b]))):fXb(Mo(fXb(a.j.Cl(0),349),KUe),303).ae(TZe)?(c=ghd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',XWb(ywc,qBe,1,[fXb(Mo(a.r,uIe),1)]))):(c=ghd(F3e,G3e,XWb(ywc,qBe,1,[fXb(Mo(a.r,uIe),1)])));return c}
function qyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,Zbf);!!this.H&&Bk(rk(this.H,UKe),Zbf);YY(this,false);this.b=new _hb;RT(this.b,fhd(m_e,m_e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new qIc;p=new qIc;for(k=b.j.ce();k.ie();){j=fXb(k.je(),349);YWb(o.d,o.e++,j);eIc(p,fXb(Mo(j,oUe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),pHe),false);g.Ab=false;this.c=SCd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+fhd(r6e,s6e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new syd(this,b,i,g,r,c,s));if(c){n=fhd(Z8e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(kod(),jod(),god))}q=new YX(fhd(o7e,o7e),new wyd(this,a,c,p,r));e=new YX(fhd(p7e,p7e),new Eyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var Zbf='Informations';Iyc(1556,363,fCe,qyd);_.b=null;_.c=null;Iyc(1557,225,ABe,syd);_.pg=function tyd(a){var b,c,d;b=fXb(a.d,303);c=b.Xd();d=pyd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?fhd('message.remove.multiple.usage','Those nodes are still used in:'):fhd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;Iyc(1558,236,ABe,wyd);_.ug=function xyd(a){vyd(this,fXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;Iyc(1559,1196,{},zyd);_.fm=function Ayd(a){GBd(this.b);rb(a.md(),a);j2(fhd(KVe,WNe),a.md(),null)};_.Ie=function Byd(a){var b;GBd(this.b);b=new yYc;b.Ud(LZe,(sPc(),sPc(),rPc));LBd(this.b,b);OBd(this.b)};_.b=null;Iyc(1560,236,ABe,Eyd);_.ug=function Fyd(a){Dyd(this,fXb(a,59))};_.b=null;Iyc(2142,1,dDe);_.Dk=function nge(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new qIc;for(e=c.j.ce();e.ie();){d=fXb(e.je(),349);eIc(b,fXb(Mo(d,oUe),1))}a=Xhd();ejd(a,b,new qge(this))}};Iyc(2143,1196,{},qge);_.fm=function rge(a){_Ac(b8e+a.md())};_.Ie=function sge(a){pge(this,fXb(a,303))};_.b=null;var Mqc=hQc(raf,'DeleteActionItem$1$1',2143),qhc=hQc(maf,'DeleteItemWindow',1556),mhc=hQc(maf,'DeleteItemWindow$1',1557),ohc=hQc(maf,'DeleteItemWindow$2',1558),nhc=hQc(maf,'DeleteItemWindow$2$1',1559),phc=hQc(maf,'DeleteItemWindow$3',1560);vDe(EKb)(3);