function mPb(){}
function lzd(){}
function izd(a){this.b=a}
function ozd(a){this.b=a}
function rzd(a){this.b=a}
function zzd(a){this.b=a}
function hzd(a){a.b.b=false}
function qzd(a){HY(a.b,null)}
function fLc(a,b){a.b.Gl(a,b)}
function vzd(a,b){this.b=a;this.c=b}
function gLc(a,b){fLc(a,(Syc(),new Pyc(b)))}
function lPb(){lPb=MAe;kPb=new _Ob(zPe,new mPb)}
function hLc(){cLc();dLc(this,new BLc(this));this.dd[zFe]=$Pe}
function bzd(a,b,c,d,e,g,i,j){Zhd(Ahd(),b,c,d,e,g,i,j,new Czd(a,b,c,d,e,g,i))}
function Czd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function dzd(b,c){try{var d=$wnd.jQuery(hbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function yzd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){dzd(LWb(t9(a.b.j),286).Il(),LWb(t9(a.b.c),286).Il());!!a.b.g&&$cb(a.b.g)}}
function czd(b){thisic=b;$wnd.jQuery(hbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function uzd(a){LWb(t9(a.b.j),286).Il()>0&&LWb(t9(a.b.c),286).Il()>0&&bzd(a.b,LWb(Mo(a.c,ITe),1),LWb(a.b.f.me(),1),LWb(t9(a.b.i),286).Il(),LWb(t9(a.b.d),286).Il(),LWb(t9(a.b.j),286).Il(),LWb(t9(a.b.c),286).Il(),false)}
function Zhd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new zFc(b,XUe,'cropImage');try{q=yFc(p,YUe,7);NEc(q,JEc(q,mRe));NEc(q,JEc(q,mRe));NEc(q,JEc(q,EUe));NEc(q,JEc(q,EUe));NEc(q,JEc(q,EUe));NEc(q,JEc(q,EUe));NEc(q,JEc(q,$Ue));NEc(q,JEc(q,c));NEc(q,JEc(q,d));jFc(q.b,mDe+e);jFc(q.b,mDe+g);jFc(q.b,mDe+i);jFc(q.b,mDe+j);jFc(q.b,k?pHe:_Fe);xFc(p,n,(RFc(),QFc))}catch(a){a=oxc(a);if(NWb(a,255)){o=a;F0c(n,o)}else throw a}}
function ezd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,Kgd(ibf,ibf));this.Dc=jbf;!!this.vc&&(ix(this).id=jbf,undefined);p=new Szb(KGe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),UGe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,DEe,kbf):(y.Tc+=lbf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(mbf);Rx(this.f,mbf);C9(this.f,Kgd('newName.label','New name'));n=LWb(Mo(c,ZHe),1).lastIndexOf(aGe);if(n>0){k=ZRc(LWb(Mo(c,ZHe),1),n);this.f.Ri(WRc(LWb(Mo(c,ZHe),1),k,nbf+k))}else{this.f.Ri(LWb(Mo(c,ZHe),1)+nbf)}Uw(this.f,(NE(),VC),new izd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,DEe,kbf):(z.Tc+=lbf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,abc);this.c=new dkb;Ujb(this.c,abc);v=LWb(Mo(c,QTe),1);t=LWb(Mo(c,RTe),1);u=0;s=0;try{u=v!=null?iPc(v,10,-2147483648,2147483647):0;s=t!=null?iPc(t,10,-2147483648,2147483647):0}catch(a){a=oxc(a);if(!NWb(a,287))throw a}if(!!d&&!d.Sd()){C=new VHc;for(j=d.ce();j.ie();){i=LWb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+L0e+i[1];E=new Q1c(w,w);Po(E,QEe,i[0]);Po(E,PEe,i[1]);CWb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,TEe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new lzd);ecb(this.g,Kgd(obf,pbf));bT(B,this.g,new szb(0.6))}}C9(this.j,Kgd(F0e,G0e));E9(this.j,QEe);Rx(this.j,QEe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,BEe,kbf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,Kgd(J0e,K0e));E9(this.c,PEe);Rx(this.c,PEe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(KGe));r=new hLc;Aw(r,new ozd(this),(lPb(),lPb(),kPb));r.dd.id='cropbox';gLc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,abc);E9(this.i,zEe);Rx(this.i,zEe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,abc);E9(this.d,yEe);Rx(this.d,yEe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(Kgd(U$e,U$e),new rzd(this));D=new YX(Kgd(T$e,T$e),new vzd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new zzd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var hbf='#cropbox',nbf='-crop',kbf='10px',jbf='JahiaGxtImageCrop',qbf='failure.crop.label',ibf='label.crop',lbf='paddingRight:10px;';lyc(785,773,{},mPb);_.Hk=function nPb(a){czd(LWb(LWb(a,226),391).b)};_.Kk=function oPb(){return kPb};var kPb;lyc(1028,182,kBe,hLc);lyc(1029,1030,{});_.Gl=function wLc(a,b){dLc(a,new BLc(a));a.b.Gl(a,b)};lyc(1032,1030,{});_.Gl=function FLc(a,b){!!a.b&&(a.b.Dl(a)[_Pe]=mDe,undefined);IMb(a.dd,b.b)};lyc(1572,363,KBe,ezd);_.Dm=function fzd(a,b,c,d){var e,g,i;jcb(this.d,KQc(a));jcb(this.i,KQc(b));H9(this.j,mDe+c);H9(this.c,mDe+d);if(this.b){g=LWb(this.f.me(),1);e=SRc(g,hSc(46));this.f.Ri($Rc(g,0,g.lastIndexOf(nbf))+nbf+c+vHe+d+(e!=-1?$Rc(g,e,g.length):mDe))}i=this.g?LWb(hdb(this.g),331):null;!!i&&(c!=LWb(Mo(i,QEe),283).b||d!=LWb(Mo(i,PEe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;lyc(1573,1,dBe,izd);_.Bd=function jzd(a){hzd(this,LWb(a,62))};_.b=null;lyc(1574,234,dBe,lzd);_.tg=function mzd(a){var b;b=LWb(XF(a),331);dzd(LWb(Mo(b,QEe),283).b,LWb(Mo(b,PEe),283).b)};lyc(1575,1,{226:1,231:1,391:1},ozd);_.b=null;lyc(1576,236,dBe,rzd);_.ug=function szd(a){qzd(this,LWb(a,59))};_.b=null;lyc(1577,236,dBe,vzd);_.ug=function wzd(a){uzd(this,LWb(a,59))};_.b=null;_.c=null;lyc(1578,1,dBe,zzd);_.Bd=function Azd(a){yzd(this,LWb(a,62))};_.b=null;lyc(1579,1195,{},Czd);_.Xl=function Dzd(a){if(NWb(a,380)){FAc(Kgd(H_e,H_e)+cDe+Kgd(l8e,l8e))&&bzd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{EAc(Kgd(qbf,qbf)+cDe+a.ld());rb(Kgd(qbf,qbf),a)}};_.Ie=function Ezd(a){var b;HY(this.b,null);b=new bYc;b.Ud(fZe,(XOc(),XOc(),WOc));oBd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;lyc(2124,1,ICe);_.Dk=function Mee(){$Y(new ezd(this.b.p,this.b.p.o.r,this.b.b))};var nhc=MPc(G9e,'ImageCrop',1572),ghc=MPc(G9e,'ImageCrop$1',1573),hhc=MPc(G9e,'ImageCrop$2',1574),ihc=MPc(G9e,'ImageCrop$3',1575),jhc=MPc(G9e,'ImageCrop$4',1576),khc=MPc(G9e,'ImageCrop$5',1577),lhc=MPc(G9e,'ImageCrop$6',1578),mhc=MPc(G9e,'ImageCrop$7',1579),o7b=MPc(paf,Xaf,785);$Ce(EKb)(2);