function cyd(a){this.b=a}
function hyd(a){this.b=a}
function Vfe(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function gyd(a){HY(a.b,null)}
function Ufe(a){$Y(new Vxd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function _xd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function Xxd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function $xd(a){var b,c;HY(a.b,null);kBd(a.c,Kgd(F6e,F6e));b=Ahd();c=new cyd(a.c);a.d?aid(b,a.e,c):ajd(b,a.e,LWb(t9(a.f),1),c)}
function ajd(b,c,d,e){var g,i,j;i=new zFc(b,XUe,'markForDeletion');try{j=yFc(i,YUe,2);NEc(j,JEc(j,ZUe));NEc(j,JEc(j,mRe));OEc(j,c);NEc(j,JEc(j,d));xFc(i,e,(RFc(),QFc))}catch(a){a=oxc(a);if(NWb(a,255)){g=a;F0c(e,g)}else throw a}}
function Uxd(a,b){var c;b>1?(c=Lgd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',BWb(bwc,VAe,1,[mDe+b]))):LWb(Mo(LWb(a.j.sl(0),349),cUe),303).ae(mZe)?(c=Lgd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',BWb(bwc,VAe,1,[LWb(Mo(a.r,ZHe),1)]))):(c=Lgd($2e,_2e,BWb(bwc,VAe,1,[LWb(Mo(a.r,ZHe),1)])));return c}
function Vxd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,rbf);!!this.H&&Bk(rk(this.H,yKe),rbf);YY(this,false);this.b=new _hb;RT(this.b,Kgd(I$e,I$e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new VHc;p=new VHc;for(k=b.j.ce();k.ie();){j=LWb(k.je(),349);CWb(o.d,o.e++,j);JHc(p,LWb(Mo(j,ITe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),UGe),false);g.Ab=false;this.c=vCd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+Kgd(L5e,M5e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new Xxd(this,b,i,g,r,c,s));if(c){n=Kgd(r8e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(Pnd(),Ond(),Lnd))}q=new YX(Kgd(I6e,I6e),new _xd(this,a,c,p,r));e=new YX(Kgd(J6e,J6e),new hyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var rbf='Informations';lyc(1555,363,KBe,Vxd);_.b=null;_.c=null;lyc(1556,225,dBe,Xxd);_.pg=function Yxd(a){var b,c,d;b=LWb(a.d,303);c=b.Xd();d=Uxd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Kgd('message.remove.multiple.usage','Those nodes are still used in:'):Kgd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;lyc(1557,236,dBe,_xd);_.ug=function ayd(a){$xd(this,LWb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;lyc(1558,1195,{},cyd);_.Xl=function dyd(a){jBd(this.b);rb(a.md(),a);j2(Kgd(cVe,yNe),a.md(),null)};_.Ie=function eyd(a){var b;jBd(this.b);b=new bYc;b.Ud(eZe,(XOc(),XOc(),WOc));oBd(this.b,b);rBd(this.b)};_.b=null;lyc(1559,236,dBe,hyd);_.ug=function iyd(a){gyd(this,LWb(a,59))};_.b=null;lyc(2141,1,ICe);_.Dk=function Sfe(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new VHc;for(e=c.j.ce();e.ie();){d=LWb(e.je(),349);JHc(b,LWb(Mo(d,ITe),1))}a=Ahd();Jid(a,b,new Vfe(this))}};lyc(2142,1195,{},Vfe);_.Xl=function Wfe(a){EAc(v7e+a.md())};_.Ie=function Xfe(a){Ufe(this,LWb(a,303))};_.b=null;var pqc=MPc(L9e,'DeleteActionItem$1$1',2142),Vgc=MPc(G9e,'DeleteItemWindow',1555),Rgc=MPc(G9e,'DeleteItemWindow$1',1556),Tgc=MPc(G9e,'DeleteItemWindow$2',1557),Sgc=MPc(G9e,'DeleteItemWindow$2$1',1558),Ugc=MPc(G9e,'DeleteItemWindow$3',1559);$Ce(EKb)(3);