function EPb(){}
function yzd(){}
function vzd(a){this.b=a}
function Bzd(a){this.b=a}
function Ezd(a){this.b=a}
function Mzd(a){this.b=a}
function uzd(a){a.b.b=false}
function Dzd(a){HY(a.b,null)}
function sLc(a,b){a.b.Kl(a,b)}
function Izd(a,b){this.b=a;this.c=b}
function tLc(a,b){sLc(a,(izc(),new fzc(b)))}
function DPb(){DPb=ZAe;CPb=new rPb(NPe,new EPb)}
function uLc(){pLc();qLc(this,new OLc(this));this.dd[NFe]=pQe}
function ozd(a,b,c,d,e,g,i,j){kid(Nhd(),b,c,d,e,g,i,j,new Pzd(a,b,c,d,e,g,i))}
function Pzd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function qzd(b,c){try{var d=$wnd.jQuery(ybf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Lzd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){qzd(bXb(t9(a.b.j),286).Ml(),bXb(t9(a.b.c),286).Ml());!!a.b.g&&$cb(a.b.g)}}
function pzd(b){thisic=b;$wnd.jQuery(ybf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Hm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Hzd(a){bXb(t9(a.b.j),286).Ml()>0&&bXb(t9(a.b.c),286).Ml()>0&&ozd(a.b,bXb(Mo(a.c,ZTe),1),bXb(a.b.f.me(),1),bXb(t9(a.b.i),286).Ml(),bXb(t9(a.b.d),286).Ml(),bXb(t9(a.b.j),286).Ml(),bXb(t9(a.b.c),286).Ml(),false)}
function kid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new QFc(b,mVe,'cropImage');try{q=PFc(p,nVe,7);cFc(q,$Ec(q,DRe));cFc(q,$Ec(q,DRe));cFc(q,$Ec(q,VUe));cFc(q,$Ec(q,VUe));cFc(q,$Ec(q,VUe));cFc(q,$Ec(q,VUe));cFc(q,$Ec(q,pVe));cFc(q,$Ec(q,c));cFc(q,$Ec(q,d));AFc(q.b,ADe+e);AFc(q.b,ADe+g);AFc(q.b,ADe+i);AFc(q.b,ADe+j);AFc(q.b,k?DHe:nGe);OFc(p,n,(gGc(),fGc))}catch(a){a=Gxc(a);if(dXb(a,255)){o=a;S0c(n,o)}else throw a}}
function rzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,Xgd(zbf,zbf));this.Dc=Abf;!!this.vc&&(ix(this).id=Abf,undefined);p=new Szb(YGe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),gHe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,REe,Bbf):(y.Tc+=Cbf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(Dbf);Rx(this.f,Dbf);C9(this.f,Xgd('newName.label','New name'));n=bXb(Mo(c,lIe),1).lastIndexOf(oGe);if(n>0){k=kSc(bXb(Mo(c,lIe),1),n);this.f.Ri(hSc(bXb(Mo(c,lIe),1),k,Ebf+k))}else{this.f.Ri(bXb(Mo(c,lIe),1)+Ebf)}Uw(this.f,(NE(),VC),new vzd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,REe,Bbf):(z.Tc+=Cbf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,sbc);this.c=new dkb;Ujb(this.c,sbc);v=bXb(Mo(c,fUe),1);t=bXb(Mo(c,gUe),1);u=0;s=0;try{u=v!=null?vPc(v,10,-2147483648,2147483647):0;s=t!=null?vPc(t,10,-2147483648,2147483647):0}catch(a){a=Gxc(a);if(!dXb(a,287))throw a}if(!!d&&!d.Sd()){C=new kIc;for(j=d.ce();j.ie();){i=bXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+a1e+i[1];E=new b2c(w,w);Po(E,cFe,i[0]);Po(E,bFe,i[1]);UWb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,fFe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new yzd);ecb(this.g,Xgd(Fbf,Gbf));bT(B,this.g,new szb(0.6))}}C9(this.j,Xgd(W0e,X0e));E9(this.j,cFe);Rx(this.j,cFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,PEe,Bbf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,Xgd($0e,_0e));E9(this.c,bFe);Rx(this.c,bFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(YGe));r=new uLc;Aw(r,new Bzd(this),(DPb(),DPb(),CPb));r.dd.id='cropbox';tLc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,sbc);E9(this.i,NEe);Rx(this.i,NEe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,sbc);E9(this.d,MEe);Rx(this.d,MEe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(Xgd(j_e,j_e),new Ezd(this));D=new YX(Xgd(i_e,i_e),new Izd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new Mzd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var ybf='#cropbox',Ebf='-crop',Bbf='10px',Abf='JahiaGxtImageCrop',Hbf='failure.crop.label',zbf='label.crop',Cbf='paddingRight:10px;';Dyc(786,774,{},EPb);_.Lk=function FPb(a){pzd(bXb(bXb(a,226),391).b)};_.Ok=function GPb(){return CPb};var CPb;Dyc(1029,182,xBe,uLc);Dyc(1030,1031,{});_.Kl=function JLc(a,b){qLc(a,new OLc(a));a.b.Kl(a,b)};Dyc(1033,1031,{});_.Kl=function SLc(a,b){!!a.b&&(a.b.Hl(a)[qQe]=ADe,undefined);UMb(a.dd,b.b)};Dyc(1573,363,XBe,rzd);_.Hm=function szd(a,b,c,d){var e,g,i;jcb(this.d,XQc(a));jcb(this.i,XQc(b));H9(this.j,ADe+c);H9(this.c,ADe+d);if(this.b){g=bXb(this.f.me(),1);e=dSc(g,uSc(46));this.f.Ri(lSc(g,0,g.lastIndexOf(Ebf))+Ebf+c+JHe+d+(e!=-1?lSc(g,e,g.length):ADe))}i=this.g?bXb(hdb(this.g),331):null;!!i&&(c!=bXb(Mo(i,cFe),283).b||d!=bXb(Mo(i,bFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;Dyc(1574,1,qBe,vzd);_.Bd=function wzd(a){uzd(this,bXb(a,62))};_.b=null;Dyc(1575,234,qBe,yzd);_.tg=function zzd(a){var b;b=bXb(XF(a),331);qzd(bXb(Mo(b,cFe),283).b,bXb(Mo(b,bFe),283).b)};Dyc(1576,1,{226:1,231:1,391:1},Bzd);_.b=null;Dyc(1577,236,qBe,Ezd);_.ug=function Fzd(a){Dzd(this,bXb(a,59))};_.b=null;Dyc(1578,236,qBe,Izd);_.ug=function Jzd(a){Hzd(this,bXb(a,59))};_.b=null;_.c=null;Dyc(1579,1,qBe,Mzd);_.Bd=function Nzd(a){Lzd(this,bXb(a,62))};_.b=null;Dyc(1580,1196,{},Pzd);_._l=function Qzd(a){if(dXb(a,380)){VAc(Xgd(Y_e,Y_e)+qDe+Xgd(C8e,C8e))&&ozd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{UAc(Xgd(Hbf,Hbf)+qDe+a.ld());rb(Xgd(Hbf,Hbf),a)}};_.Ie=function Rzd(a){var b;HY(this.b,null);b=new oYc;b.Ud(wZe,(iPc(),iPc(),hPc));BBd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;Dyc(2125,1,WCe);_.Hk=function Zee(){$Y(new rzd(this.b.p,this.b.p.o.r,this.b.b))};var Fhc=ZPc(X9e,'ImageCrop',1573),yhc=ZPc(X9e,'ImageCrop$1',1574),zhc=ZPc(X9e,'ImageCrop$2',1575),Ahc=ZPc(X9e,'ImageCrop$3',1576),Bhc=ZPc(X9e,'ImageCrop$4',1577),Chc=ZPc(X9e,'ImageCrop$5',1578),Dhc=ZPc(X9e,'ImageCrop$6',1579),Ehc=ZPc(X9e,'ImageCrop$7',1580),I7b=ZPc(Gaf,mbf,786);mDe(OKb)(2);