function pyd(a){this.b=a}
function uyd(a){this.b=a}
function gge(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function tyd(a){HY(a.b,null)}
function fge(a){$Y(new gyd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function myd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function iyd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function lyd(a){var b,c;HY(a.b,null);xBd(a.c,Xgd(W6e,W6e));b=Nhd();c=new pyd(a.c);a.d?nid(b,a.e,c):njd(b,a.e,bXb(t9(a.f),1),c)}
function njd(b,c,d,e){var g,i,j;i=new QFc(b,mVe,'markForDeletion');try{j=PFc(i,nVe,2);cFc(j,$Ec(j,oVe));cFc(j,$Ec(j,DRe));dFc(j,c);cFc(j,$Ec(j,d));OFc(i,e,(gGc(),fGc))}catch(a){a=Gxc(a);if(dXb(a,255)){g=a;S0c(e,g)}else throw a}}
function fyd(a,b){var c;b>1?(c=Ygd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',TWb(twc,gBe,1,[ADe+b]))):bXb(Mo(bXb(a.j.wl(0),349),tUe),303).ae(DZe)?(c=Ygd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',TWb(twc,gBe,1,[bXb(Mo(a.r,lIe),1)]))):(c=Ygd(p3e,q3e,TWb(twc,gBe,1,[bXb(Mo(a.r,lIe),1)])));return c}
function gyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,Ibf);!!this.H&&Bk(rk(this.H,NKe),Ibf);YY(this,false);this.b=new _hb;RT(this.b,Xgd(Z$e,Z$e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new kIc;p=new kIc;for(k=b.j.ce();k.ie();){j=bXb(k.je(),349);UWb(o.d,o.e++,j);$Hc(p,bXb(Mo(j,ZTe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),gHe),false);g.Ab=false;this.c=ICd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+Xgd(a6e,b6e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new iyd(this,b,i,g,r,c,s));if(c){n=Xgd(I8e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(aod(),_nd(),Ynd))}q=new YX(Xgd(Z6e,Z6e),new myd(this,a,c,p,r));e=new YX(Xgd($6e,$6e),new uyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var Ibf='Informations';Dyc(1556,363,XBe,gyd);_.b=null;_.c=null;Dyc(1557,225,qBe,iyd);_.pg=function jyd(a){var b,c,d;b=bXb(a.d,303);c=b.Xd();d=fyd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?Xgd('message.remove.multiple.usage','Those nodes are still used in:'):Xgd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;Dyc(1558,236,qBe,myd);_.ug=function nyd(a){lyd(this,bXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;Dyc(1559,1196,{},pyd);_._l=function qyd(a){wBd(this.b);rb(a.md(),a);j2(Xgd(tVe,NNe),a.md(),null)};_.Ie=function ryd(a){var b;wBd(this.b);b=new oYc;b.Ud(vZe,(iPc(),iPc(),hPc));BBd(this.b,b);EBd(this.b)};_.b=null;Dyc(1560,236,qBe,uyd);_.ug=function vyd(a){tyd(this,bXb(a,59))};_.b=null;Dyc(2142,1,WCe);_.Hk=function dge(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new kIc;for(e=c.j.ce();e.ie();){d=bXb(e.je(),349);$Hc(b,bXb(Mo(d,ZTe),1))}a=Nhd();Wid(a,b,new gge(this))}};Dyc(2143,1196,{},gge);_._l=function hge(a){UAc(M7e+a.md())};_.Ie=function ige(a){fge(this,bXb(a,303))};_.b=null;var Hqc=ZPc(aaf,'DeleteActionItem$1$1',2143),lhc=ZPc(X9e,'DeleteItemWindow',1556),hhc=ZPc(X9e,'DeleteItemWindow$1',1557),jhc=ZPc(X9e,'DeleteItemWindow$2',1558),ihc=ZPc(X9e,'DeleteItemWindow$2$1',1559),khc=ZPc(X9e,'DeleteItemWindow$3',1560);mDe(OKb)(3);