function $Pb(){}
function $zd(){}
function Xzd(a){this.b=a}
function bAd(a){this.b=a}
function eAd(a){this.b=a}
function mAd(a){this.b=a}
function Wzd(a){a.b.b=false}
function dAd(a){HY(a.b,null)}
function TLc(a,b){a.b.Ol(a,b)}
function iAd(a,b){this.b=a;this.c=b}
function ULc(a,b){TLc(a,(Izc(),new Fzc(b)))}
function ZPb(){ZPb=zBe;YPb=new NPb(pQe,new $Pb)}
function VLc(){QLc();RLc(this,new nMc(this));this.dd[nGe]=QQe}
function Qzd(a,b,c,d,e,g,i,j){Mid(nid(),b,c,d,e,g,i,j,new pAd(a,b,c,d,e,g,i))}
function pAd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function lAd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){Szd(xXb(t9(a.b.j),286).Ql(),xXb(t9(a.b.c),286).Ql());!!a.b.g&&$cb(a.b.g)}}
function Szd(b,c){try{var d=$wnd.jQuery(Ybf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Rzd(b){thisic=b;$wnd.jQuery(Ybf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Lm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function hAd(a){xXb(t9(a.b.j),286).Ql()>0&&xXb(t9(a.b.c),286).Ql()>0&&Qzd(a.b,xXb(Mo(a.c,yUe),1),xXb(a.b.f.me(),1),xXb(t9(a.b.i),286).Ql(),xXb(t9(a.b.d),286).Ql(),xXb(t9(a.b.j),286).Ql(),xXb(t9(a.b.c),286).Ql(),false)}
function Mid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new pGc(b,NVe,'cropImage');try{q=oGc(p,OVe,7);DFc(q,zFc(q,cSe));DFc(q,zFc(q,cSe));DFc(q,zFc(q,uVe));DFc(q,zFc(q,uVe));DFc(q,zFc(q,uVe));DFc(q,zFc(q,uVe));DFc(q,zFc(q,QVe));DFc(q,zFc(q,c));DFc(q,zFc(q,d));_Fc(q.b,aEe+e);_Fc(q.b,aEe+g);_Fc(q.b,aEe+i);_Fc(q.b,aEe+j);_Fc(q.b,k?dIe:PGe);nGc(p,n,(HGc(),GGc))}catch(a){a=eyc(a);if(zXb(a,255)){o=a;s1c(n,o)}else throw a}}
function Tzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,xhd(Zbf,Zbf));this.Dc=$bf;!!this.vc&&(ix(this).id=$bf,undefined);p=new Szb(yHe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),IHe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,rFe,_bf):(y.Tc+=acf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(bcf);Rx(this.f,bcf);C9(this.f,xhd('newName.label','New name'));n=xXb(Mo(c,NIe),1).lastIndexOf(QGe);if(n>0){k=MSc(xXb(Mo(c,NIe),1),n);this.f.Ri(JSc(xXb(Mo(c,NIe),1),k,ccf+k))}else{this.f.Ri(xXb(Mo(c,NIe),1)+ccf)}Uw(this.f,(NE(),VC),new Xzd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,rFe,_bf):(z.Tc+=acf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,Sbc);this.c=new dkb;Ujb(this.c,Sbc);v=xXb(Mo(c,GUe),1);t=xXb(Mo(c,HUe),1);u=0;s=0;try{u=v!=null?WPc(v,10,-2147483648,2147483647):0;s=t!=null?WPc(t,10,-2147483648,2147483647):0}catch(a){a=eyc(a);if(!zXb(a,287))throw a}if(!!d&&!d.Sd()){C=new LIc;for(j=d.ce();j.ie();){i=xXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+B1e+i[1];E=new D2c(w,w);Po(E,EFe,i[0]);Po(E,DFe,i[1]);oXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,HFe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new $zd);ecb(this.g,xhd(dcf,ecf));bT(B,this.g,new szb(0.6))}}C9(this.j,xhd(v1e,w1e));E9(this.j,EFe);Rx(this.j,EFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,pFe,_bf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,xhd(z1e,A1e));E9(this.c,DFe);Rx(this.c,DFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(yHe));r=new VLc;Aw(r,new bAd(this),(ZPb(),ZPb(),YPb));r.dd.id='cropbox';ULc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,Sbc);E9(this.i,nFe);Rx(this.i,nFe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,Sbc);E9(this.d,mFe);Rx(this.d,mFe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(xhd(K_e,K_e),new eAd(this));D=new YX(xhd(J_e,J_e),new iAd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new mAd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var Ybf='#cropbox',ccf='-crop',_bf='10px',$bf='JahiaGxtImageCrop',fcf='failure.crop.label',Zbf='label.crop',acf='paddingRight:10px;';bzc(790,778,{},$Pb);_.Pk=function _Pb(a){Rzd(xXb(xXb(a,226),391).b)};_.Sk=function aQb(){return YPb};var YPb;bzc(1031,182,ZBe,VLc);bzc(1032,1033,{});_.Ol=function iMc(a,b){RLc(a,new nMc(a));a.b.Ol(a,b)};bzc(1035,1033,{});_.Ol=function rMc(a,b){!!a.b&&(a.b.Ll(a)[RQe]=aEe,undefined);nNb(a.dd,b.b)};bzc(1575,363,xCe,Tzd);_.Lm=function Uzd(a,b,c,d){var e,g,i;jcb(this.d,wRc(a));jcb(this.i,wRc(b));H9(this.j,aEe+c);H9(this.c,aEe+d);if(this.b){g=xXb(this.f.me(),1);e=ESc(g,WSc(46));this.f.Ri(NSc(g,0,g.lastIndexOf(ccf))+ccf+c+jIe+d+(e!=-1?NSc(g,e,g.length):aEe))}i=this.g?xXb(hdb(this.g),331):null;!!i&&(c!=xXb(Mo(i,EFe),283).b||d!=xXb(Mo(i,DFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;bzc(1576,1,SBe,Xzd);_.Bd=function Yzd(a){Wzd(this,xXb(a,62))};_.b=null;bzc(1577,234,SBe,$zd);_.tg=function _zd(a){var b;b=xXb(XF(a),331);Szd(xXb(Mo(b,EFe),283).b,xXb(Mo(b,DFe),283).b)};bzc(1578,1,{226:1,231:1,391:1},bAd);_.b=null;bzc(1579,236,SBe,eAd);_.ug=function fAd(a){dAd(this,xXb(a,59))};_.b=null;bzc(1580,236,SBe,iAd);_.ug=function jAd(a){hAd(this,xXb(a,59))};_.b=null;_.c=null;bzc(1581,1,SBe,mAd);_.Bd=function nAd(a){lAd(this,xXb(a,62))};_.b=null;bzc(1582,1198,{},pAd);_.dm=function qAd(a){if(zXb(a,380)){vBc(xhd(x0e,x0e)+SDe+xhd(a9e,a9e))&&Qzd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{uBc(xhd(fcf,fcf)+SDe+a.ld());rb(xhd(fcf,fcf),a)}};_.Ie=function rAd(a){var b;HY(this.b,null);b=new QYc;b.Ud(XZe,(JPc(),JPc(),IPc));bCd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;bzc(2127,1,wDe);_.Hk=function zfe(){$Y(new Tzd(this.b.p,this.b.p.o.r,this.b.b))};var dic=yQc(vaf,'ImageCrop',1575),Yhc=yQc(vaf,'ImageCrop$1',1576),Zhc=yQc(vaf,'ImageCrop$2',1577),$hc=yQc(vaf,'ImageCrop$3',1578),_hc=yQc(vaf,'ImageCrop$4',1579),aic=yQc(vaf,'ImageCrop$5',1580),bic=yQc(vaf,'ImageCrop$6',1581),cic=yQc(vaf,'ImageCrop$7',1582),g8b=yQc(ebf,Mbf,790);ODe(PKb)(2);