function Ryd(a){this.b=a}
function Wyd(a){this.b=a}
function Ige(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function Vyd(a){HY(a.b,null)}
function Hge(a){$Y(new Iyd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function Oyd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function Kyd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Nyd(a){var b,c;HY(a.b,null);ZBd(a.c,xhd(u7e,u7e));b=nid();c=new Ryd(a.c);a.d?Pid(b,a.e,c):Pjd(b,a.e,xXb(t9(a.f),1),c)}
function Pjd(b,c,d,e){var g,i,j;i=new pGc(b,NVe,'markForDeletion');try{j=oGc(i,OVe,2);DFc(j,zFc(j,PVe));DFc(j,zFc(j,cSe));EFc(j,c);DFc(j,zFc(j,d));nGc(i,e,(HGc(),GGc))}catch(a){a=eyc(a);if(zXb(a,255)){g=a;s1c(e,g)}else throw a}}
function Hyd(a,b){var c;b>1?(c=yhd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',nXb(Twc,IBe,1,[aEe+b]))):xXb(Mo(xXb(a.j.Al(0),349),UUe),303).ae(c$e)?(c=yhd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',nXb(Twc,IBe,1,[xXb(Mo(a.r,NIe),1)]))):(c=yhd(Q3e,R3e,nXb(Twc,IBe,1,[xXb(Mo(a.r,NIe),1)])));return c}
function Iyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,gcf);!!this.H&&Bk(rk(this.H,mLe),gcf);YY(this,false);this.b=new _hb;RT(this.b,xhd(y_e,y_e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new LIc;p=new LIc;for(k=b.j.ce();k.ie();){j=xXb(k.je(),349);oXb(o.d,o.e++,j);zIc(p,xXb(Mo(j,yUe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),IHe),false);g.Ab=false;this.c=iDd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+xhd(A6e,B6e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new Kyd(this,b,i,g,r,c,s));if(c){n=xhd(g9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(Cod(),Bod(),yod))}q=new YX(xhd(x7e,x7e),new Oyd(this,a,c,p,r));e=new YX(xhd(y7e,y7e),new Wyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var gcf='Informations';bzc(1558,363,xCe,Iyd);_.b=null;_.c=null;bzc(1559,225,SBe,Kyd);_.pg=function Lyd(a){var b,c,d;b=xXb(a.d,303);c=b.Xd();d=Hyd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?xhd('message.remove.multiple.usage','Those nodes are still used in:'):xhd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;bzc(1560,236,SBe,Oyd);_.ug=function Pyd(a){Nyd(this,xXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;bzc(1561,1198,{},Ryd);_.dm=function Syd(a){YBd(this.b);rb(a.md(),a);j2(xhd(UVe,nOe),a.md(),null)};_.Ie=function Tyd(a){var b;YBd(this.b);b=new QYc;b.Ud(WZe,(JPc(),JPc(),IPc));bCd(this.b,b);eCd(this.b)};_.b=null;bzc(1562,236,SBe,Wyd);_.ug=function Xyd(a){Vyd(this,xXb(a,59))};_.b=null;bzc(2144,1,wDe);_.Hk=function Fge(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new LIc;for(e=c.j.ce();e.ie();){d=xXb(e.je(),349);zIc(b,xXb(Mo(d,yUe),1))}a=nid();wjd(a,b,new Ige(this))}};bzc(2145,1198,{},Ige);_.dm=function Jge(a){uBc(k8e+a.md())};_.Ie=function Kge(a){Hge(this,xXb(a,303))};_.b=null;var frc=yQc(Aaf,'DeleteActionItem$1$1',2145),Lhc=yQc(vaf,'DeleteItemWindow',1558),Hhc=yQc(vaf,'DeleteItemWindow$1',1559),Jhc=yQc(vaf,'DeleteItemWindow$2',1560),Ihc=yQc(vaf,'DeleteItemWindow$2$1',1561),Khc=yQc(vaf,'DeleteItemWindow$3',1562);ODe(PKb)(3);