function pQb(){}
function BCd(){}
function yCd(a){this.b=a}
function ECd(a){this.b=a}
function HCd(a){this.b=a}
function PCd(a){this.b=a}
function xCd(a){a.b.b=false}
function GCd(a){UY(a.b,null)}
function LCd(a,b){this.b=a;this.c=b}
function jPc(a,b){iPc(a,(VCc(),new SCc(b)))}
function oQb(){oQb=ESe;nQb=new cQb(I5e,new pQb)}
function rCd(a,b,c,d,e,g,i,j){omd(Rld(),b,c,d,e,g,i,j,new SCd(a,b,c,d,e,g,i))}
function SCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function tCd(b,c){try{var d=$wnd.jQuery(tuf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function OCd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){tCd(iYb(y9(a.b.j),287).km(),iYb(y9(a.b.c),287).km());!!a.b.g&&ddb(a.b.g)}}
function sCd(b){thisic=b;$wnd.jQuery(tuf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Vm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function KCd(a){iYb(y9(a.b.j),287).km()>0&&iYb(y9(a.b.c),287).km()>0&&rCd(a.b,iYb(Eo(a.c,U9e),1),iYb(a.b.f.oe(),1),iYb(y9(a.b.i),287).km(),iYb(y9(a.b.d),287).km(),iYb(y9(a.b.j),287).km(),iYb(y9(a.b.c),287).km(),false)}
function omd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new DJc(b,jbf,'cropImage');try{q=CJc(p,kbf,7);RIc(q,NIc(q,w7e));RIc(q,NIc(q,w7e));RIc(q,NIc(q,Saf));RIc(q,NIc(q,Saf));RIc(q,NIc(q,Saf));RIc(q,NIc(q,Saf));RIc(q,NIc(q,mbf));RIc(q,NIc(q,c));RIc(q,NIc(q,d));nJc(q.b,jVe+e);nJc(q.b,jVe+g);nJc(q.b,jVe+i);nJc(q.b,jVe+j);nJc(q.b,k?nZe:ZXe);BJc(p,n,(VJc(),UJc))}catch(a){a=rBc(a);if(kYb(a,256)){o=a;J4c(n,o)}else throw a}}
function uCd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,$kd(uuf,uuf));this.Ec=vuf;!!this.wc&&(gx(this).id=vuf,undefined);p=new _zb(IYe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),TYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,zWe,wuf):(y.Uc+=xuf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(yuf);Px(this.f,yuf);H9(this.f,$kd('newName.label','New name'));n=iYb(Eo(c,XZe),1).lastIndexOf($Xe);if(n>0){k=cWc(iYb(Eo(c,XZe),1),n);this.f._i($Vc(iYb(Eo(c,XZe),1),k,zuf+k))}else{this.f._i(iYb(Eo(c,XZe),1)+zuf)}Sw(this.f,(RE(),ZC),new yCd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,zWe,wuf):(z.Uc+=xuf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,Dcc);this.c=new ikb;Zjb(this.c,Dcc);v=iYb(Eo(c,_9e),1);t=iYb(Eo(c,aaf),1);u=0;s=0;try{u=v!=null?lTc(v,10,-2147483648,2147483647):0;s=t!=null?lTc(t,10,-2147483648,2147483647):0}catch(a){a=rBc(a);if(!kYb(a,288))throw a}if(!!d&&!d.Ud()){C=new ZLc;for(j=d.ee();j.ke();){i=iYb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+Rif+i[1];E=new Y5c(w,w);Ho(E,MWe,i[0]);Ho(E,LWe,i[1]);_Xb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,PWe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new BCd);kcb(this.g,$kd(Auf,Buf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,$kd(Lif,Mif));J9(this.j,MWe);Px(this.j,MWe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,xWe,wuf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,$kd(Pif,Qif));J9(this.c,LWe);Px(this.c,LWe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(IYe));r=new kPc;yw(r,new ECd(this),(oQb(),oQb(),nQb));r.ed.id='cropbox';jPc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,Dcc);J9(this.i,tWe);Px(this.i,tWe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,Dcc);J9(this.d,sWe);Px(this.d,sWe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY($kd(Qgf,Qgf),new HCd(this));D=new jY($kd(Vgf,Vgf),new LCd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new PCd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var tuf='#cropbox',zuf='-crop',wuf='10px',vuf='JahiaGxtImageCrop',Cuf='failure.crop.label',uuf='label.crop',xuf='paddingRight:10px;';oCc(790,778,{},pQb);_.$k=function qQb(a){sCd(iYb(iYb(a,227),393).b)};_.bl=function rQb(){return nQb};var nQb;oCc(1563,364,ETe,uCd);_.Vm=function vCd(a,b,c,d){var e,g,i;ocb(this.d,NUc(a));ocb(this.i,NUc(b));M9(this.j,jVe+c);M9(this.c,jVe+d);if(this.b){g=iYb(this.f.oe(),1);e=VVc(g,mWc(46));this.f._i(dWc(g,0,g.lastIndexOf(zuf))+zuf+c+tZe+d+(e!=-1?dWc(g,e,g.length):jVe))}i=this.g?iYb(mdb(this.g),333):null;!!i&&(c!=iYb(Eo(i,MWe),284).b||d!=iYb(Eo(i,LWe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;oCc(1564,1,XSe,yCd);_.Cd=function zCd(a){xCd(this,iYb(a,61))};_.b=null;oCc(1565,235,XSe,BCd);_.xg=function CCd(a){var b;b=iYb(fG(a),333);tCd(iYb(Eo(b,MWe),284).b,iYb(Eo(b,LWe),284).b)};oCc(1566,1,{227:1,232:1,393:1},ECd);_.b=null;oCc(1567,237,XSe,HCd);_.yg=function ICd(a){GCd(this,iYb(a,58))};_.b=null;oCc(1568,237,XSe,LCd);_.yg=function MCd(a){KCd(this,iYb(a,58))};_.b=null;_.c=null;oCc(1569,1,XSe,PCd);_.Cd=function QCd(a){OCd(this,iYb(a,61))};_.b=null;oCc(1570,1200,{},SCd);_.zm=function TCd(a){if(kYb(a,382)){JEc($kd(fif,fif)+_Ue+$kd(urf,urf))&&rCd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{IEc($kd(Cuf,Cuf)+_Ue+a.md());rb($kd(Cuf,Cuf),a)}};_.Ke=function UCd(a){var b;UY(this.b,null);b=new f0c;b.Wd(fff,($Sc(),$Sc(),ZSc));this.b.e.Mm(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;oCc(2258,1,EUe);_.Sk=function iwe(){mZ(new uCd(this.b.p,this.b.p.Im().r,this.b.b))};var Fic=PTc(Wsf,'ImageCrop',1563),yic=PTc(Wsf,'ImageCrop$1',1564),zic=PTc(Wsf,'ImageCrop$2',1565),Aic=PTc(Wsf,'ImageCrop$3',1566),Bic=PTc(Wsf,'ImageCrop$4',1567),Cic=PTc(Wsf,'ImageCrop$5',1568),Dic=PTc(Wsf,'ImageCrop$6',1569),Eic=PTc(Wsf,'ImageCrop$7',1570),S8b=PTc(Gtf,Ftf,790);XUe(eLb)(2);