function xBd(a){this.b=a}
function rxe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function wBd(a){UY(a.b,null)}
function sBd(a,b){this.b=a;this.c=b}
function pBd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function lBd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function qxe(a){mZ(new jBd(a.b.b.p,a.b.b.p.Im(),a.b.b.c))}
function oBd(a){var b,c;UY(a.b,null);a.c.Lm($kd(Npf,Npf));b=Rld();c=new sBd(a.c,a.e);a.d?rmd(b,a.e,c):und(b,a.e,iYb(y9(a.f),1),c)}
function und(b,c,d,e){var g,i,j;i=new DJc(b,jbf,'markForDeletion');try{j=CJc(i,kbf,2);RIc(j,NIc(j,lbf));RIc(j,NIc(j,w7e));SIc(j,c);RIc(j,NIc(j,d));BJc(i,e,(VJc(),UJc))}catch(a){a=rBc(a);if(kYb(a,256)){g=a;J4c(e,g)}else throw a}}
function iBd(a,b){var c;b>1?(c=_kd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',$Xb(eAc,NSe,1,[jVe+b]))):iYb(Eo(iYb(a.j.Vl(0),351),qaf),304).ce(qff)?(c=_kd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',$Xb(eAc,NSe,1,[iYb(Eo(a.r,XZe),1)]))):(c=_kd(Crf,Drf,$Xb(eAc,NSe,1,[iYb(Eo(a.r,XZe),1)])));return c}
function jBd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,Duf);!!this.H&&sk(ik(this.H,v0e),Duf);kZ(this,false);this.b=new eib;cU(this.b,$kd(rif,rif));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new ZLc;p=new ZLc;for(k=b.j.ee();k.ke();){j=iYb(k.le(),351);_Xb(o.d,o.e++,j);NLc(p,iYb(Eo(j,U9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),TYe),false);g.Bb=false;this.c=MFd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+$kd(Vof,Wof)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new lBd(this,b,i,g,r,c,s));if(c){n=$kd(Erf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(usd(),tsd(),qsd))}q=new jY($kd(Qpf,Qpf),new pBd(this,a,c,p,r));e=new jY($kd(Rpf,Rpf),new xBd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var Duf='Informations';oCc(1546,364,ETe,jBd);_.b=null;_.c=null;oCc(1547,225,XSe,lBd);_.sg=function mBd(a){var b,c,d;b=iYb(a.d,304);c=b.Zd();d=iBd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?$kd('message.remove.multiple.usage','Those nodes are still used in:'):$kd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;oCc(1548,237,XSe,pBd);_.yg=function qBd(a){oBd(this,iYb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;oCc(1549,1200,{},sBd);_.zm=function tBd(a){this.b.Km();rb(a.nd(),a);H2($kd(pbf,A9e),a.nd(),null)};_.Ke=function uBd(a){var b,c;this.b.Km();c=null;kYb(this.b,431)?(c=iYb(this.b,431).d.u):kYb(this.b,418)&&(c=iYb(this.b,418));b=new f0c;!!c&&SLc(this.c,iYb(Eo(c.p.i,U9e),1),0)!=-1?b.Wd(cff,c.p.i):b.Wd(eff,($Sc(),$Sc(),ZSc));this.b.Mm(b);this.b.Nm(null)};_.b=null;_.c=null;oCc(1550,237,XSe,xBd);_.yg=function yBd(a){wBd(this,iYb(a,58))};_.b=null;oCc(2275,1,EUe);_.Sk=function oxe(){var a,b,c,d,e;c=this.b.p.Im();if(!c.j.Ud()){b=new ZLc;for(e=c.j.ee();e.ke();){d=iYb(e.le(),351);NLc(b,iYb(Eo(d,U9e),1))}a=Rld();cnd(a,b,new rxe(this))}};oCc(2276,1200,{},rxe);_.zm=function sxe(a){IEc(Aqf+a.nd())};_.Ke=function txe(a){qxe(this,iYb(a,304))};_.b=null;var ruc=PTc(_sf,'DeleteActionItem$1$1',2276),lic=PTc(Wsf,'DeleteItemWindow',1546),hic=PTc(Wsf,'DeleteItemWindow$1',1547),jic=PTc(Wsf,'DeleteItemWindow$2',1548),iic=PTc(Wsf,'DeleteItemWindow$2$1',1549),kic=PTc(Wsf,'DeleteItemWindow$3',1550);XUe(eLb)(3);