function _Pb(){}
function nCd(){}
function kCd(a){this.a=a}
function qCd(a){this.a=a}
function tCd(a){this.a=a}
function BCd(a){this.a=a}
function jCd(a){a.a.a=false}
function sCd(a){UY(a.a,null)}
function xCd(a,b){this.a=a;this.b=b}
function POc(a,b){OOc(a,(DCc(),new ACc(b)))}
function $Pb(){$Pb=pSe;ZPb=new OPb(Etf,new _Pb)}
function dCd(a,b,c,d,e,g,i,j){amd(Dld(),b,c,d,e,g,i,j,new ECd(a,b,c,d,e,g,i))}
function ECd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function fCd(b,c){try{var d=$wnd.jQuery(BMg).data(CMg);var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function ACd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){fCd(UXb(y9(a.a.i),287).bm(),UXb(y9(a.a.b),287).bm());!!a.a.f&&ddb(a.a.f)}}
function eCd(b){thisic=b;$wnd.jQuery(BMg).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function wCd(a){UXb(y9(a.a.i),287).bm()>0&&UXb(y9(a.a.b),287).bm()>0&&dCd(a.a,UXb(Fo(a.b,YAf),1),UXb(a.a.e.ne(),1),UXb(y9(a.a.g),287).bm(),UXb(y9(a.a.c),287).bm(),UXb(y9(a.a.i),287).bm(),UXb(y9(a.a.b),287).bm(),false)}
function amd(b,c,d,e,g,i,j,k,n){var o,p,q;p=new hJc(b,NCf,AMg);try{q=gJc(p,PCf,7);vIc(q,rIc(q,zxf));vIc(q,rIc(q,zxf));vIc(q,rIc(q,sCf));vIc(q,rIc(q,sCf));vIc(q,rIc(q,sCf));vIc(q,rIc(q,sCf));vIc(q,rIc(q,YCf));vIc(q,rIc(q,c));vIc(q,rIc(q,d));TIc(q.a,ZUe+e);TIc(q.a,ZUe+g);TIc(q.a,ZUe+i);TIc(q.a,ZUe+j);TIc(q.a,k?F0e:h$e);fJc(p,n,(zJc(),yJc))}catch(a){a=_Ac(a);if(WXb(a,256)){o=a;v4c(n,o)}else throw a}}
function gCd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,Mkd(DMg,DMg));this.Dc=EMg;!!this.vc&&(gx(this).id=EMg,undefined);p=new _zb(u_e);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),V_e),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,QXe,FMg):(y.Tc+=GMg);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(HMg);Px(this.e,HMg);H9(this.e,Mkd(IMg,JMg));n=UXb(Fo(c,X2e),1).lastIndexOf(i$e);if(n>0){k=QVc(UXb(Fo(c,X2e),1),n);this.e.$i(MVc(UXb(Fo(c,X2e),1),k,KMg+k))}else{this.e.$i(UXb(Fo(c,X2e),1)+KMg)}Sw(this.e,(RE(),ZC),new kCd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,QXe,FMg):(z.Tc+=GMg);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,lcc);this.b=new ikb;Zjb(this.b,lcc);v=UXb(Fo(c,eBf),1);t=UXb(Fo(c,fBf),1);u=0;s=0;try{u=v!=null?$Sc(v,10,-2147483648,2147483647):0;s=t!=null?$Sc(t,10,-2147483648,2147483647):0}catch(a){a=_Ac(a);if(!WXb(a,288))throw a}if(!!d&&!d.Td()){C=new DLc;for(j=d.de();j.je();){i=UXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+GPf+i[1];E=new K5c(w,w);Io(E,cYe,i[0]);Io(E,bYe,i[1]);LXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,gYe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new nCd);kcb(this.f,Mkd(LMg,MMg));oT(B,this.f,new Bzb(0.6))}}H9(this.i,Mkd(yPf,zPf));J9(this.i,cYe);Px(this.i,cYe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,OXe,FMg):(x.Tc+=NMg);q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,Mkd(DPf,EPf));J9(this.b,bYe);Px(this.b,bYe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(u_e));r=new QOc;yw(r,new qCd(this),($Pb(),$Pb(),ZPb));r.dd.id=OMg;POc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,lcc);J9(this.g,KXe);Px(this.g,KXe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,lcc);J9(this.c,JXe);Px(this.c,JXe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(Mkd(jLf,jLf),new tCd(this));D=new jY(Mkd(tLf,tLf),new xCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new BCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var BMg='#cropbox',KMg='-crop',FMg='10px',QMg='ImageCrop',RMg='ImageCrop$1',SMg='ImageCrop$2',TMg='ImageCrop$3',UMg='ImageCrop$4',VMg='ImageCrop$5',WMg='ImageCrop$6',XMg='ImageCrop$7',EMg='JahiaGxtImageCrop',CMg='Jcrop',JMg='New name',AMg='cropImage',OMg='cropbox',PMg='failure.crop.label',DMg='label.crop',IMg='newName.label',NMg='paddingLeft:10px;',GMg='paddingRight:10px;';YBc(789,777,{},_Pb);_.Sk=function aQb(a){eCd(UXb(UXb(a,227),393).a)};_.Vk=function bQb(){return ZPb};var ZPb;YBc(1568,365,pTe,gCd);_.Mm=function hCd(a,b,c,d){var e,g,i;ocb(this.c,AUc(a));ocb(this.g,AUc(b));M9(this.i,ZUe+c);M9(this.b,ZUe+d);if(this.a){g=UXb(this.e.ne(),1);e=IVc(g,$Vc(46));this.e.$i(RVc(g,0,g.lastIndexOf(KMg))+KMg+c+Y0e+d+(e!=-1?RVc(g,e,g.length):ZUe))}i=this.f?UXb(mdb(this.f),333):null;!!i&&(c!=UXb(Fo(i,cYe),284).a||d!=UXb(Fo(i,bYe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;YBc(1569,1,ISe,kCd);_.Bd=function lCd(a){jCd(this,UXb(a,61))};_.a=null;YBc(1570,236,ISe,nCd);_.wg=function oCd(a){var b;b=UXb(fG(a),333);fCd(UXb(Fo(b,cYe),284).a,UXb(Fo(b,bYe),284).a)};YBc(1571,1,{227:1,232:1,393:1},qCd);_.a=null;YBc(1572,238,ISe,tCd);_.xg=function uCd(a){sCd(this,UXb(a,58))};_.a=null;YBc(1573,238,ISe,xCd);_.xg=function yCd(a){wCd(this,UXb(a,58))};_.a=null;_.b=null;YBc(1574,1,ISe,BCd);_.Bd=function CCd(a){ACd(this,UXb(a,61))};_.a=null;YBc(1575,1205,{},ECd);_.qm=function FCd(a){if(WXb(a,382)){kEc(Mkd(lOf,lOf)+LUe+Mkd(u8f,u8f))&&dCd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{jEc(Mkd(PMg,PMg)+LUe+a.ld());rb(Mkd(PMg,PMg),a)}};_.Je=function GCd(a){var b;UY(this.a,null);b=new T_c;b.Vd(rIf,(NSc(),NSc(),MSc));this.a.d.Dm(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;YBc(2263,1,oUe);_.Nk=function Vve(){mZ(new gCd(this.a.o,this.a.o.zm().q,this.a.a))};var nic=CTc(Qig,QMg,1568),gic=CTc(Qig,RMg,1569),hic=CTc(Qig,SMg,1570),iic=CTc(Qig,TMg,1571),jic=CTc(Qig,UMg,1572),kic=CTc(Qig,VMg,1573),lic=CTc(Qig,WMg,1574),mic=CTc(Qig,XMg,1575),v8b=CTc(bxg,Vwg,789);HUe(VKb)(2);