function jBd(a){this.a=a}
function cxe(a){this.a=a}
function iBd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function eBd(a,b){this.a=a;this.b=b}
function bBd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function ZAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function bxe(a){mZ(new XAd(a.a.a.o,a.a.a.o.zm(),a.a.a.b))}
function aBd(a){var b,c;UY(a.a,null);a.b.Cm(Mkd(N3f,N3f));b=Dld();c=new eBd(a.b,a.d);a.c?dmd(b,a.d,c):gnd(b,a.d,UXb(y9(a.e),1),c)}
function gnd(b,c,d,e){var g,i,j;i=new hJc(b,NCf,YMg);try{j=gJc(i,PCf,2);vIc(j,rIc(j,TCf));vIc(j,rIc(j,zxf));wIc(j,c);vIc(j,rIc(j,d));fJc(i,e,(zJc(),yJc))}catch(a){a=_Ac(a);if(WXb(a,256)){g=a;v4c(e,g)}else throw a}}
function WAd(a,b){var c;b>1?(c=Nkd(ZMg,$Mg,KXb(Ozc,ySe,1,[ZUe+b]))):UXb(Fo(UXb(a.i.Ml(0),351),yBf),304).be(CIf)?(c=Nkd(_Mg,aNg,KXb(Ozc,ySe,1,[UXb(Fo(a.q,X2e),1)]))):(c=Nkd(P8f,Q8f,KXb(Ozc,ySe,1,[UXb(Fo(a.q,X2e),1)])));return c}
function XAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,bNg);!!this.G&&sk(ik(this.G,ycf),bNg);kZ(this,false);this.a=new eib;cU(this.a,Mkd(LOf,LOf));this.a.Ab=false;Hx(this.a,false);Px(this.a,cNg);MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new DLc;p=new DLc;for(k=b.i.de();k.je();){j=UXb(k.ke(),351);LXb(o.c,o.d++,j);rLc(p,UXb(Fo(j,YAf),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),V_e),false);g.Ab=false;this.b=yFd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$(dNg+Mkd(_1f,a2f)+eNg));nT(this.a,r)}i=o.d;bq(this.b.H.e,new ZAd(this,b,i,g,r,c,s));if(c){n=Mkd(R8f,fNg);nT(this.a,new I$(n));dU(this,(gsd(),fsd(),csd))}q=new jY(Mkd(b4f,b4f),new bBd(this,a,c,p,r));e=new jY(Mkd(d4f,d4f),new jBd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var lNg='620',mNg='70%',eNg=': <br />',dNg='<br />',gNg='<br /><br />',fNg='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',nNg='DeleteActionItem$1$1',oNg='DeleteItemWindow',pNg='DeleteItemWindow$1',qNg='DeleteItemWindow$2',rNg='DeleteItemWindow$2$1',sNg='DeleteItemWindow$3',aNg='Do you really want to remove the selected PAGE {0}?',$Mg='Do you really want to remove the {0} selected resources?',bNg='Informations',cNg='JahiaGxtDeleteItem',kNg='This node is still used by:',iNg='Those nodes are still used in:',YMg='markForDeletion',ZMg='message.remove.multiple.confirm',hNg='message.remove.multiple.usage',_Mg='message.remove.single.page.confirm',jNg='message.remove.single.usage';YBc(1551,365,pTe,XAd);_.a=null;_.b=null;YBc(1552,226,ISe,ZAd);_.rg=function $Ad(a){var b,c,d;b=UXb(a.c,304);c=b.Yd();d=WAd(this.c,this.d);if(c>0){d+=gNg+(this.d>1?Mkd(hNg,iNg):Mkd(jNg,kNg))}else{wT(this.a.a,this.b);hz(this.f,lNg,mNg);if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;YBc(1553,238,ISe,bBd);_.xg=function cBd(a){aBd(this,UXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;YBc(1554,1205,{},eBd);_.qm=function fBd(a){this.a.Bm();rb(a.md(),a);H2(Mkd(cEf,xAf),a.md(),null)};_.Je=function gBd(a){var b,c;this.a.Bm();c=null;WXb(this.a,431)?(c=UXb(this.a,431).c.t):WXb(this.a,418)&&(c=UXb(this.a,418));b=new T_c;!!c&&wLc(this.b,UXb(Fo(c.o.g,YAf),1),0)!=-1?b.Vd(oIf,c.o.g):b.Vd(qIf,(NSc(),NSc(),MSc));this.a.Dm(b);this.a.Em(null)};_.a=null;_.b=null;YBc(1555,238,ISe,jBd);_.xg=function kBd(a){iBd(this,UXb(a,58))};_.a=null;YBc(2280,1,oUe);_.Nk=function _we(){var a,b,c,d,e;c=this.a.o.zm();if(!c.i.Td()){b=new DLc;for(e=c.i.de();e.je();){d=UXb(e.ke(),351);rLc(b,UXb(Fo(d,YAf),1))}a=Dld();Qmd(a,b,new cxe(this))}};YBc(2281,1205,{},cxe);_.qm=function dxe(a){jEc(W5f+a.md())};_.Je=function exe(a){bxe(this,UXb(a,304))};_.a=null;var _tc=CTc(Tjg,nNg,2281),Vhc=CTc(Qig,oNg,1551),Rhc=CTc(Qig,pNg,1552),Thc=CTc(Qig,qNg,1553),Shc=CTc(Qig,rNg,1554),Uhc=CTc(Qig,sNg,1555);HUe(VKb)(3);