function VPb(){}
function $Bd(){}
function XBd(a){this.b=a}
function bCd(a){this.b=a}
function eCd(a){this.b=a}
function mCd(a){this.b=a}
function WBd(a){a.b.b=false}
function dCd(a){UY(a.b,null)}
function iCd(a,b){this.b=a;this.c=b}
function JOc(a,b){IOc(a,(tCc(),new qCc(b)))}
function UPb(){UPb=bSe;TPb=new IPb(k5e,new VPb)}
function QBd(a,b,c,d,e,g,i,j){Nld(old(),b,c,d,e,g,i,j,new pCd(a,b,c,d,e,g,i))}
function pCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function SBd(b,c){try{var d=$wnd.jQuery($tf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function lCd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){SBd(MXb(y9(a.b.j),287).fm(),MXb(y9(a.b.c),287).fm());!!a.b.g&&ddb(a.b.g)}}
function RBd(b){thisic=b;$wnd.jQuery($tf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Qm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function hCd(a){MXb(y9(a.b.j),287).fm()>0&&MXb(y9(a.b.c),287).fm()>0&&QBd(a.b,MXb(Eo(a.c,z9e),1),MXb(a.b.f.oe(),1),MXb(y9(a.b.i),287).fm(),MXb(y9(a.b.d),287).fm(),MXb(y9(a.b.j),287).fm(),MXb(y9(a.b.c),287).fm(),false)}
function Nld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new bJc(b,Qaf,'cropImage');try{q=aJc(p,Raf,7);pIc(q,lIc(q,b7e));pIc(q,lIc(q,b7e));pIc(q,lIc(q,xaf));pIc(q,lIc(q,xaf));pIc(q,lIc(q,xaf));pIc(q,lIc(q,xaf));pIc(q,lIc(q,Taf));pIc(q,lIc(q,c));pIc(q,lIc(q,d));NIc(q.b,IUe+e);NIc(q.b,IUe+g);NIc(q.b,IUe+i);NIc(q.b,IUe+j);NIc(q.b,k?MYe:wXe);_Ic(p,n,(tJc(),sJc))}catch(a){a=RAc(a);if(OXb(a,256)){o=a;g4c(n,o)}else throw a}}
function TBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,xkd(_tf,_tf));this.Ec=auf;!!this.wc&&(gx(this).id=auf,undefined);p=new _zb(fYe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),qYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,YVe,buf):(y.Uc+=cuf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(duf);Px(this.f,duf);H9(this.f,xkd('newName.label','New name'));n=MXb(Eo(c,uZe),1).lastIndexOf(xXe);if(n>0){k=BVc(MXb(Eo(c,uZe),1),n);this.f._i(xVc(MXb(Eo(c,uZe),1),k,euf+k))}else{this.f._i(MXb(Eo(c,uZe),1)+euf)}Sw(this.f,(RE(),ZC),new XBd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,YVe,buf):(z.Uc+=cuf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,bcc);this.c=new ikb;Zjb(this.c,bcc);v=MXb(Eo(c,G9e),1);t=MXb(Eo(c,H9e),1);u=0;s=0;try{u=v!=null?LSc(v,10,-2147483648,2147483647):0;s=t!=null?LSc(t,10,-2147483648,2147483647):0}catch(a){a=RAc(a);if(!OXb(a,288))throw a}if(!!d&&!d.Ud()){C=new xLc;for(j=d.ee();j.ke();){i=MXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+xif+i[1];E=new v5c(w,w);Ho(E,jWe,i[0]);Ho(E,iWe,i[1]);DXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,mWe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new $Bd);kcb(this.g,xkd(fuf,guf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,xkd(rif,sif));J9(this.j,jWe);Px(this.j,jWe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,WVe,buf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,xkd(vif,wif));J9(this.c,iWe);Px(this.c,iWe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(fYe));r=new KOc;yw(r,new bCd(this),(UPb(),UPb(),TPb));r.ed.id='cropbox';JOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,bcc);J9(this.i,SVe);Px(this.i,SVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,bcc);J9(this.d,RVe);Px(this.d,RVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(xkd(wgf,wgf),new eCd(this));D=new jY(xkd(Bgf,Bgf),new iCd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new mCd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var $tf='#cropbox',euf='-crop',buf='10px',auf='JahiaGxtImageCrop',huf='failure.crop.label',_tf='label.crop',cuf='paddingRight:10px;';OBc(786,774,{},VPb);_.Wk=function WPb(a){RBd(MXb(MXb(a,227),393).b)};_.Zk=function XPb(){return TPb};var TPb;OBc(1561,364,bTe,TBd);_.Qm=function UBd(a,b,c,d){var e,g,i;ocb(this.d,lUc(a));ocb(this.i,lUc(b));M9(this.j,IUe+c);M9(this.c,IUe+d);if(this.b){g=MXb(this.f.oe(),1);e=tVc(g,LVc(46));this.f._i(CVc(g,0,g.lastIndexOf(euf))+euf+c+SYe+d+(e!=-1?CVc(g,e,g.length):IUe))}i=this.g?MXb(mdb(this.g),333):null;!!i&&(c!=MXb(Eo(i,jWe),284).b||d!=MXb(Eo(i,iWe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;OBc(1562,1,uSe,XBd);_.Cd=function YBd(a){WBd(this,MXb(a,61))};_.b=null;OBc(1563,235,uSe,$Bd);_.xg=function _Bd(a){var b;b=MXb(fG(a),333);SBd(MXb(Eo(b,jWe),284).b,MXb(Eo(b,iWe),284).b)};OBc(1564,1,{227:1,232:1,393:1},bCd);_.b=null;OBc(1565,237,uSe,eCd);_.yg=function fCd(a){dCd(this,MXb(a,58))};_.b=null;OBc(1566,237,uSe,iCd);_.yg=function jCd(a){hCd(this,MXb(a,58))};_.b=null;_.c=null;OBc(1567,1,uSe,mCd);_.Cd=function nCd(a){lCd(this,MXb(a,61))};_.b=null;OBc(1568,1198,{},pCd);_.um=function qCd(a){if(OXb(a,382)){fEc(xkd(Nhf,Nhf)+yUe+xkd(_qf,_qf))&&QBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{eEc(xkd(huf,huf)+yUe+a.md());rb(xkd(huf,huf),a)}};_.Ke=function rCd(a){var b;UY(this.b,null);b=new E_c;b.Wd(Mef,(ySc(),ySc(),xSc));this.b.e.Hm(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;OBc(2256,1,bUe);_.Sk=function Hve(){mZ(new TBd(this.b.p,this.b.p.Dm().r,this.b.b))};var dic=nTc(Bsf,'ImageCrop',1561),Yhc=nTc(Bsf,'ImageCrop$1',1562),Zhc=nTc(Bsf,'ImageCrop$2',1563),$hc=nTc(Bsf,'ImageCrop$3',1564),_hc=nTc(Bsf,'ImageCrop$4',1565),aic=nTc(Bsf,'ImageCrop$5',1566),bic=nTc(Bsf,'ImageCrop$6',1567),cic=nTc(Bsf,'ImageCrop$7',1568),q8b=nTc(ltf,ktf,786);uUe(dLb)(2);