function WAd(a){this.b=a}
function Qwe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function VAd(a){UY(a.b,null)}
function RAd(a,b){this.b=a;this.c=b}
function OAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function KAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Pwe(a){mZ(new IAd(a.b.b.p,a.b.b.p.Dm(),a.b.b.c))}
function NAd(a){var b,c;UY(a.b,null);a.c.Gm(xkd(spf,spf));b=old();c=new RAd(a.c,a.e);a.d?Qld(b,a.e,c):Tmd(b,a.e,MXb(y9(a.f),1),c)}
function Tmd(b,c,d,e){var g,i,j;i=new bJc(b,Qaf,'markForDeletion');try{j=aJc(i,Raf,2);pIc(j,lIc(j,Saf));pIc(j,lIc(j,b7e));qIc(j,c);pIc(j,lIc(j,d));_Ic(i,e,(tJc(),sJc))}catch(a){a=RAc(a);if(OXb(a,256)){g=a;g4c(e,g)}else throw a}}
function HAd(a,b){var c;b>1?(c=ykd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',CXb(Ezc,kSe,1,[IUe+b]))):MXb(Eo(MXb(a.j.Ql(0),351),X9e),304).ce(Xef)?(c=ykd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',CXb(Ezc,kSe,1,[MXb(Eo(a.r,uZe),1)]))):(c=ykd(hrf,irf,CXb(Ezc,kSe,1,[MXb(Eo(a.r,uZe),1)])));return c}
function IAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,iuf);!!this.H&&sk(ik(this.H,X_e),iuf);kZ(this,false);this.b=new eib;cU(this.b,xkd(Zhf,Zhf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new xLc;p=new xLc;for(k=b.j.ee();k.ke();){j=MXb(k.le(),351);DXb(o.d,o.e++,j);lLc(p,MXb(Eo(j,z9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),qYe),false);g.Bb=false;this.c=jFd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+xkd(Aof,Bof)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new KAd(this,b,i,g,r,c,s));if(c){n=xkd(jrf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(Trd(),Srd(),Prd))}q=new jY(xkd(vpf,vpf),new OAd(this,a,c,p,r));e=new jY(xkd(wpf,wpf),new WAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var iuf='Informations';OBc(1544,364,bTe,IAd);_.b=null;_.c=null;OBc(1545,225,uSe,KAd);_.sg=function LAd(a){var b,c,d;b=MXb(a.d,304);c=b.Zd();d=HAd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?xkd('message.remove.multiple.usage','Those nodes are still used in:'):xkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;OBc(1546,237,uSe,OAd);_.yg=function PAd(a){NAd(this,MXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;OBc(1547,1198,{},RAd);_.um=function SAd(a){this.b.Fm();rb(a.nd(),a);H2(xkd(Waf,f9e),a.nd(),null)};_.Ke=function TAd(a){var b,c;this.b.Fm();c=null;OXb(this.b,431)?(c=MXb(this.b,431).d.u):OXb(this.b,418)&&(c=MXb(this.b,418));b=new E_c;!!c&&qLc(this.c,MXb(Eo(c.p.i,z9e),1),0)!=-1?b.Wd(Jef,c.p.i):b.Wd(Lef,(ySc(),ySc(),xSc));this.b.Hm(b);this.b.Im(null)};_.b=null;_.c=null;OBc(1548,237,uSe,WAd);_.yg=function XAd(a){VAd(this,MXb(a,58))};_.b=null;OBc(2273,1,bUe);_.Sk=function Nwe(){var a,b,c,d,e;c=this.b.p.Dm();if(!c.j.Ud()){b=new xLc;for(e=c.j.ee();e.ke();){d=MXb(e.le(),351);lLc(b,MXb(Eo(d,z9e),1))}a=old();Bmd(a,b,new Qwe(this))}};OBc(2274,1198,{},Qwe);_.um=function Rwe(a){eEc(fqf+a.nd())};_.Ke=function Swe(a){Pwe(this,MXb(a,304))};_.b=null;var Rtc=nTc(Gsf,'DeleteActionItem$1$1',2274),Lhc=nTc(Bsf,'DeleteItemWindow',1544),Hhc=nTc(Bsf,'DeleteItemWindow$1',1545),Jhc=nTc(Bsf,'DeleteItemWindow$2',1546),Ihc=nTc(Bsf,'DeleteItemWindow$2$1',1547),Khc=nTc(Bsf,'DeleteItemWindow$3',1548);uUe(dLb)(3);