function DPb(){}
function OBd(){}
function LBd(a){this.b=a}
function RBd(a){this.b=a}
function UBd(a){this.b=a}
function aCd(a){this.b=a}
function KBd(a){a.b.b=false}
function TBd(a){UY(a.b,null)}
function YBd(a,b){this.b=a;this.c=b}
function xOc(a,b){wOc(a,(dCc(),new aCc(b)))}
function CPb(){CPb=RRe;BPb=new qPb(S4e,new DPb)}
function EBd(a,b,c,d,e,g,i,j){Bld(cld(),b,c,d,e,g,i,j,new dCd(a,b,c,d,e,g,i))}
function dCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function GBd(b,c){try{var d=$wnd.jQuery(Dtf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function _Bd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){GBd(wXb(y9(a.b.j),287).cm(),wXb(y9(a.b.c),287).cm());!!a.b.g&&ddb(a.b.g)}}
function FBd(b){thisic=b;$wnd.jQuery(Dtf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function XBd(a){wXb(y9(a.b.j),287).cm()>0&&wXb(y9(a.b.c),287).cm()>0&&EBd(a.b,wXb(Eo(a.c,c9e),1),wXb(a.b.f.oe(),1),wXb(y9(a.b.i),287).cm(),wXb(y9(a.b.d),287).cm(),wXb(y9(a.b.j),287).cm(),wXb(y9(a.b.c),287).cm(),false)}
function Bld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new NIc(b,taf,'cropImage');try{q=MIc(p,uaf,7);_Hc(q,XHc(q,G6e));_Hc(q,XHc(q,G6e));_Hc(q,XHc(q,aaf));_Hc(q,XHc(q,aaf));_Hc(q,XHc(q,aaf));_Hc(q,XHc(q,aaf));_Hc(q,XHc(q,waf));_Hc(q,XHc(q,c));_Hc(q,XHc(q,d));xIc(q.b,vUe+e);xIc(q.b,vUe+g);xIc(q.b,vUe+i);xIc(q.b,vUe+j);xIc(q.b,k?zYe:jXe);LIc(p,n,(dJc(),cJc))}catch(a){a=BAc(a);if(yXb(a,256)){o=a;W3c(n,o)}else throw a}}
function HBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,lkd(Etf,Etf));this.Ec=Ftf;!!this.wc&&(gx(this).id=Ftf,undefined);p=new _zb(UXe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),dYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,LVe,Gtf):(y.Uc+=Htf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(Itf);Px(this.f,Itf);H9(this.f,lkd('newName.label','New name'));n=wXb(Eo(c,hZe),1).lastIndexOf(kXe);if(n>0){k=pVc(wXb(Eo(c,hZe),1),n);this.f._i(lVc(wXb(Eo(c,hZe),1),k,Jtf+k))}else{this.f._i(wXb(Eo(c,hZe),1)+Jtf)}Sw(this.f,(RE(),ZC),new LBd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,LVe,Gtf):(z.Uc+=Htf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,Nbc);this.c=new ikb;Zjb(this.c,Nbc);v=wXb(Eo(c,j9e),1);t=wXb(Eo(c,k9e),1);u=0;s=0;try{u=v!=null?zSc(v,10,-2147483648,2147483647):0;s=t!=null?zSc(t,10,-2147483648,2147483647):0}catch(a){a=BAc(a);if(!yXb(a,288))throw a}if(!!d&&!d.Ud()){C=new hLc;for(j=d.ee();j.ke();){i=wXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+_hf+i[1];E=new j5c(w,w);Ho(E,YVe,i[0]);Ho(E,XVe,i[1]);nXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,_Ve);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new OBd);kcb(this.g,lkd(Ktf,Ltf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,lkd(Vhf,Whf));J9(this.j,YVe);Px(this.j,YVe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,JVe,Gtf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,lkd(Zhf,$hf));J9(this.c,XVe);Px(this.c,XVe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(UXe));r=new yOc;yw(r,new RBd(this),(CPb(),CPb(),BPb));r.ed.id='cropbox';xOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,Nbc);J9(this.i,FVe);Px(this.i,FVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,Nbc);J9(this.d,EVe);Px(this.d,EVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(lkd($ff,$ff),new UBd(this));D=new jY(lkd(dgf,dgf),new YBd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new aCd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var Dtf='#cropbox',Jtf='-crop',Gtf='10px',Ftf='JahiaGxtImageCrop',Mtf='failure.crop.label',Etf='label.crop',Htf='paddingRight:10px;';yBc(785,773,{},DPb);_.Sk=function EPb(a){FBd(wXb(wXb(a,227),393).b)};_.Vk=function FPb(){return BPb};var BPb;yBc(1560,364,RSe,HBd);_.Nm=function IBd(a,b,c,d){var e,g,i;ocb(this.d,_Tc(a));ocb(this.i,_Tc(b));M9(this.j,vUe+c);M9(this.c,vUe+d);if(this.b){g=wXb(this.f.oe(),1);e=hVc(g,zVc(46));this.f._i(qVc(g,0,g.lastIndexOf(Jtf))+Jtf+c+FYe+d+(e!=-1?qVc(g,e,g.length):vUe))}i=this.g?wXb(mdb(this.g),333):null;!!i&&(c!=wXb(Eo(i,YVe),284).b||d!=wXb(Eo(i,XVe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;yBc(1561,1,iSe,LBd);_.Cd=function MBd(a){KBd(this,wXb(a,61))};_.b=null;yBc(1562,235,iSe,OBd);_.xg=function PBd(a){var b;b=wXb(fG(a),333);GBd(wXb(Eo(b,YVe),284).b,wXb(Eo(b,XVe),284).b)};yBc(1563,1,{227:1,232:1,393:1},RBd);_.b=null;yBc(1564,237,iSe,UBd);_.yg=function VBd(a){TBd(this,wXb(a,58))};_.b=null;yBc(1565,237,iSe,YBd);_.yg=function ZBd(a){XBd(this,wXb(a,58))};_.b=null;_.c=null;yBc(1566,1,iSe,aCd);_.Cd=function bCd(a){_Bd(this,wXb(a,61))};_.b=null;yBc(1567,1197,{},dCd);_.rm=function eCd(a){if(yXb(a,382)){TDc(lkd(phf,phf)+lUe+lkd(Eqf,Eqf))&&EBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{SDc(lkd(Mtf,Mtf)+lUe+a.md());rb(lkd(Mtf,Mtf),a)}};_.Ke=function fCd(a){var b;UY(this.b,null);b=new s_c;b.Wd(pef,(mSc(),mSc(),lSc));this.b.e.Em(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;yBc(2255,1,QTe);_.Ok=function vve(){mZ(new HBd(this.b.p,this.b.p.Am().r,this.b.b))};var Phc=bTc(esf,'ImageCrop',1560),Ihc=bTc(esf,'ImageCrop$1',1561),Jhc=bTc(esf,'ImageCrop$2',1562),Khc=bTc(esf,'ImageCrop$3',1563),Lhc=bTc(esf,'ImageCrop$4',1564),Mhc=bTc(esf,'ImageCrop$5',1565),Nhc=bTc(esf,'ImageCrop$6',1566),Ohc=bTc(esf,'ImageCrop$7',1567),$7b=bTc(Qsf,Psf,785);hUe(VKb)(2);