function KAd(a){this.b=a}
function Ewe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function JAd(a){UY(a.b,null)}
function FAd(a,b){this.b=a;this.c=b}
function CAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function yAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Dwe(a){mZ(new wAd(a.b.b.p,a.b.b.p.Am(),a.b.b.c))}
function BAd(a){var b,c;UY(a.b,null);a.c.Dm(lkd(Xof,Xof));b=cld();c=new FAd(a.c,a.e);a.d?Eld(b,a.e,c):Hmd(b,a.e,wXb(y9(a.f),1),c)}
function Hmd(b,c,d,e){var g,i,j;i=new NIc(b,taf,'markForDeletion');try{j=MIc(i,uaf,2);_Hc(j,XHc(j,vaf));_Hc(j,XHc(j,G6e));aIc(j,c);_Hc(j,XHc(j,d));LIc(i,e,(dJc(),cJc))}catch(a){a=BAc(a);if(yXb(a,256)){g=a;W3c(e,g)}else throw a}}
function vAd(a,b){var c;b>1?(c=mkd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',mXb(ozc,$Re,1,[vUe+b]))):wXb(Eo(wXb(a.j.Nl(0),351),A9e),304).ce(Aef)?(c=mkd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',mXb(ozc,$Re,1,[wXb(Eo(a.r,hZe),1)]))):(c=mkd(Mqf,Nqf,mXb(ozc,$Re,1,[wXb(Eo(a.r,hZe),1)])));return c}
function wAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,Ntf);!!this.H&&sk(ik(this.H,H_e),Ntf);kZ(this,false);this.b=new eib;cU(this.b,lkd(Bhf,Bhf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new hLc;p=new hLc;for(k=b.j.ee();k.ke();){j=wXb(k.le(),351);nXb(o.d,o.e++,j);XKc(p,wXb(Eo(j,c9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),dYe),false);g.Bb=false;this.c=ZEd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+lkd(dof,eof)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new yAd(this,b,i,g,r,c,s));if(c){n=lkd(Oqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(Hrd(),Grd(),Drd))}q=new jY(lkd($of,$of),new CAd(this,a,c,p,r));e=new jY(lkd(_of,_of),new KAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var Ntf='Informations';yBc(1543,364,RSe,wAd);_.b=null;_.c=null;yBc(1544,225,iSe,yAd);_.sg=function zAd(a){var b,c,d;b=wXb(a.d,304);c=b.Zd();d=vAd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?lkd('message.remove.multiple.usage','Those nodes are still used in:'):lkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;yBc(1545,237,iSe,CAd);_.yg=function DAd(a){BAd(this,wXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;yBc(1546,1197,{},FAd);_.rm=function GAd(a){this.b.Cm();rb(a.nd(),a);H2(lkd(zaf,K8e),a.nd(),null)};_.Ke=function HAd(a){var b,c;this.b.Cm();c=null;yXb(this.b,431)?(c=wXb(this.b,431).d.u):yXb(this.b,418)&&(c=wXb(this.b,418));b=new s_c;!!c&&aLc(this.c,wXb(Eo(c.p.i,c9e),1),0)!=-1?b.Wd(mef,c.p.i):b.Wd(oef,(mSc(),mSc(),lSc));this.b.Em(b);this.b.Fm(null)};_.b=null;_.c=null;yBc(1547,237,iSe,KAd);_.yg=function LAd(a){JAd(this,wXb(a,58))};_.b=null;yBc(2272,1,QTe);_.Ok=function Bwe(){var a,b,c,d,e;c=this.b.p.Am();if(!c.j.Ud()){b=new hLc;for(e=c.j.ee();e.ke();){d=wXb(e.le(),351);XKc(b,wXb(Eo(d,c9e),1))}a=cld();pmd(a,b,new Ewe(this))}};yBc(2273,1197,{},Ewe);_.rm=function Fwe(a){SDc(Kpf+a.nd())};_.Ke=function Gwe(a){Dwe(this,wXb(a,304))};_.b=null;var Btc=bTc(jsf,'DeleteActionItem$1$1',2273),vhc=bTc(esf,'DeleteItemWindow',1543),rhc=bTc(esf,'DeleteItemWindow$1',1544),thc=bTc(esf,'DeleteItemWindow$2',1545),shc=bTc(esf,'DeleteItemWindow$2$1',1546),uhc=bTc(esf,'DeleteItemWindow$3',1547);hUe(VKb)(3);