function rPb(){}
function uzd(){}
function rzd(a){this.a=a}
function xzd(a){this.a=a}
function Azd(a){this.a=a}
function Izd(a){this.a=a}
function qzd(a){a.a.a=false}
function zzd(a){HY(a.a,null)}
function oLc(a,b){a.a.Gl(a,b)}
function Ezd(a,b){this.a=a;this.b=b}
function pLc(a,b){oLc(a,(Yyc(),new Vyc(b)))}
function qPb(){qPb=VAe;pPb=new ePb(DPe,new rPb)}
function qLc(){lLc();mLc(this,new KLc(this));this.cd[IFe]=eQe}
function kzd(a,b,c,d,e,g,i,j){gid(Jhd(),b,c,d,e,g,i,j,new Lzd(a,b,c,d,e,g,i))}
function Lzd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function Hzd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){mzd(SWb(t9(a.a.i),286).Il(),SWb(t9(a.a.b),286).Il());!!a.a.f&&$cb(a.a.f)}}
function mzd(b,c){try{var d=$wnd.jQuery(obf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function lzd(b){thisic=b;$wnd.jQuery(obf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Dzd(a){SWb(t9(a.a.i),286).Il()>0&&SWb(t9(a.a.b),286).Il()>0&&kzd(a.a,SWb(Mo(a.b,PTe),1),SWb(a.a.e.le(),1),SWb(t9(a.a.g),286).Il(),SWb(t9(a.a.c),286).Il(),SWb(t9(a.a.i),286).Il(),SWb(t9(a.a.b),286).Il(),false)}
function gid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new MFc(b,cVe,'cropImage');try{q=LFc(p,dVe,7);$Ec(q,WEc(q,sRe));$Ec(q,WEc(q,sRe));$Ec(q,WEc(q,LUe));$Ec(q,WEc(q,LUe));$Ec(q,WEc(q,LUe));$Ec(q,WEc(q,LUe));$Ec(q,WEc(q,fVe));$Ec(q,WEc(q,c));$Ec(q,WEc(q,d));wFc(q.a,vDe+e);wFc(q.a,vDe+g);wFc(q.a,vDe+i);wFc(q.a,vDe+j);wFc(q.a,k?yHe:iGe);KFc(p,n,(cGc(),bGc))}catch(a){a=uxc(a);if(UWb(a,255)){o=a;O0c(n,o)}else throw a}}
function nzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,Tgd(pbf,pbf));this.Cc=qbf;!!this.uc&&(ix(this).id=qbf,undefined);p=new Szb(TGe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),bHe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,MEe,rbf):(y.Sc+=sbf);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(tbf);Rx(this.e,tbf);C9(this.e,Tgd('newName.label','New name'));n=SWb(Mo(c,eIe),1).lastIndexOf(jGe);if(n>0){k=gSc(SWb(Mo(c,eIe),1),n);this.e.Qi(dSc(SWb(Mo(c,eIe),1),k,ubf+k))}else{this.e.Qi(SWb(Mo(c,eIe),1)+ubf)}Uw(this.e,(NE(),VC),new rzd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,MEe,rbf):(z.Sc+=sbf);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,gbc);this.b=new dkb;Ujb(this.b,gbc);v=SWb(Mo(c,XTe),1);t=SWb(Mo(c,YTe),1);u=0;s=0;try{u=v!=null?rPc(v,10,-2147483648,2147483647):0;s=t!=null?rPc(t,10,-2147483648,2147483647):0}catch(a){a=uxc(a);if(!UWb(a,287))throw a}if(!!d&&!d.Rd()){C=new gIc;for(j=d.be();j.he();){i=SWb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+S0e+i[1];E=new Z1c(w,w);Po(E,ZEe,i[0]);Po(E,YEe,i[1]);JWb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,aFe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new uzd);ecb(this.f,Tgd(vbf,wbf));bT(B,this.f,new szb(0.6))}}C9(this.i,Tgd(M0e,N0e));E9(this.i,ZEe);Rx(this.i,ZEe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,KEe,rbf):(x.Sc+='paddingLeft:10px;');q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,Tgd(Q0e,R0e));E9(this.b,YEe);Rx(this.b,YEe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(TGe));r=new qLc;Aw(r,new xzd(this),(qPb(),qPb(),pPb));r.cd.id='cropbox';pLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,gbc);E9(this.g,IEe);Rx(this.g,IEe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,gbc);E9(this.c,HEe);Rx(this.c,HEe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(Tgd(_$e,_$e),new Azd(this));D=new YX(Tgd($$e,$$e),new Ezd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new Izd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var obf='#cropbox',ubf='-crop',rbf='10px',qbf='JahiaGxtImageCrop',xbf='failure.crop.label',pbf='label.crop',sbf='paddingRight:10px;';ryc(787,775,{},rPb);_.Hk=function sPb(a){lzd(SWb(SWb(a,226),391).a)};_.Kk=function tPb(){return pPb};var pPb;ryc(1034,182,tBe,qLc);ryc(1035,1036,{});_.Gl=function FLc(a,b){mLc(a,new KLc(a));a.a.Gl(a,b)};ryc(1038,1036,{});_.Gl=function OLc(a,b){!!a.a&&(a.a.Dl(a)[fQe]=vDe,undefined);HMb(a.cd,b.a)};ryc(1578,363,TBe,nzd);_.Dm=function ozd(a,b,c,d){var e,g,i;jcb(this.c,TQc(a));jcb(this.g,TQc(b));H9(this.i,vDe+c);H9(this.b,vDe+d);if(this.a){g=SWb(this.e.le(),1);e=_Rc(g,qSc(46));this.e.Qi(hSc(g,0,g.lastIndexOf(ubf))+ubf+c+EHe+d+(e!=-1?hSc(g,e,g.length):vDe))}i=this.f?SWb(hdb(this.f),331):null;!!i&&(c!=SWb(Mo(i,ZEe),283).a||d!=SWb(Mo(i,YEe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;ryc(1579,1,mBe,rzd);_.Ad=function szd(a){qzd(this,SWb(a,62))};_.a=null;ryc(1580,234,mBe,uzd);_.sg=function vzd(a){var b;b=SWb(XF(a),331);mzd(SWb(Mo(b,ZEe),283).a,SWb(Mo(b,YEe),283).a)};ryc(1581,1,{226:1,231:1,391:1},xzd);_.a=null;ryc(1582,236,mBe,Azd);_.tg=function Bzd(a){zzd(this,SWb(a,59))};_.a=null;ryc(1583,236,mBe,Ezd);_.tg=function Fzd(a){Dzd(this,SWb(a,59))};_.a=null;_.b=null;ryc(1584,1,mBe,Izd);_.Ad=function Jzd(a){Hzd(this,SWb(a,62))};_.a=null;ryc(1585,1201,{},Lzd);_.Xl=function Mzd(a){if(UWb(a,380)){LAc(Tgd(O_e,O_e)+lDe+Tgd(s8e,s8e))&&kzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{KAc(Tgd(xbf,xbf)+lDe+a.kd());rb(Tgd(xbf,xbf),a)}};_.He=function Nzd(a){var b;HY(this.a,null);b=new kYc;b.Td(mZe,(ePc(),ePc(),dPc));xBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;ryc(2130,1,RCe);_.Ck=function Vee(){$Y(new nzd(this.a.o,this.a.o.n.q,this.a.a))};var thc=VPc(N9e,'ImageCrop',1578),mhc=VPc(N9e,'ImageCrop$1',1579),nhc=VPc(N9e,'ImageCrop$2',1580),ohc=VPc(N9e,'ImageCrop$3',1581),phc=VPc(N9e,'ImageCrop$4',1582),qhc=VPc(N9e,'ImageCrop$5',1583),rhc=VPc(N9e,'ImageCrop$6',1584),shc=VPc(N9e,'ImageCrop$7',1585),t7b=VPc(xaf,dbf,787);hDe(EKb)(2);