function lyd(a){this.a=a}
function qyd(a){this.a=a}
function cge(a){this.a=a}
function pyd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function bge(a){$Y(new cyd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function iyd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function eyd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function hyd(a){var b,c;HY(a.a,null);tBd(a.b,Tgd(M6e,M6e));b=Jhd();c=new lyd(a.b);a.c?jid(b,a.d,c):jjd(b,a.d,SWb(t9(a.e),1),c)}
function jjd(b,c,d,e){var g,i,j;i=new MFc(b,cVe,'markForDeletion');try{j=LFc(i,dVe,2);$Ec(j,WEc(j,eVe));$Ec(j,WEc(j,sRe));_Ec(j,c);$Ec(j,WEc(j,d));KFc(i,e,(cGc(),bGc))}catch(a){a=uxc(a);if(UWb(a,255)){g=a;O0c(e,g)}else throw a}}
function byd(a,b){var c;b>1?(c=Ugd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',IWb(hwc,cBe,1,[vDe+b]))):SWb(Mo(SWb(a.i.sl(0),349),jUe),303)._d(tZe)?(c=Ugd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',IWb(hwc,cBe,1,[SWb(Mo(a.q,eIe),1)]))):(c=Ugd(f3e,g3e,IWb(hwc,cBe,1,[SWb(Mo(a.q,eIe),1)])));return c}
function cyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,ybf);!!this.G&&Bk(rk(this.G,FKe),ybf);YY(this,false);this.a=new _hb;RT(this.a,Tgd(P$e,P$e));this.a.zb=false;Jx(this.a,false);Rx(this.a,'JahiaGxtDeleteItem');BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new gIc;p=new gIc;for(k=b.i.be();k.he();){j=SWb(k.ie(),349);JWb(o.c,o.d++,j);WHc(p,SWb(Mo(j,PTe),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),bHe),false);g.zb=false;this.b=ECd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$('<br />'+Tgd(S5e,T5e)+': <br />'));aT(this.a,r)}i=o.d;iq(this.b.H.e,new eyd(this,b,i,g,r,c,s));if(c){n=Tgd(y8e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.a,new q$(n));ST(this,(Ynd(),Xnd(),Und))}q=new YX(Tgd(P6e,P6e),new iyd(this,a,c,p,r));e=new YX(Tgd(Q6e,Q6e),new qyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var ybf='Informations';ryc(1561,363,TBe,cyd);_.a=null;_.b=null;ryc(1562,225,mBe,eyd);_.og=function fyd(a){var b,c,d;b=SWb(a.c,303);c=b.Wd();d=byd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?Tgd('message.remove.multiple.usage','Those nodes are still used in:'):Tgd('message.remove.single.usage','This node is still used by:'))}else{jT(this.a.a,this.b);jz(this.f,'620','70%');if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;ryc(1563,236,mBe,iyd);_.tg=function jyd(a){hyd(this,SWb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;ryc(1564,1201,{},lyd);_.Xl=function myd(a){sBd(this.a);rb(a.ld(),a);j2(Tgd(jVe,ENe),a.ld(),null)};_.He=function nyd(a){var b;sBd(this.a);b=new kYc;b.Td(lZe,(ePc(),ePc(),dPc));xBd(this.a,b);ABd(this.a)};_.a=null;ryc(1565,236,mBe,qyd);_.tg=function ryd(a){pyd(this,SWb(a,59))};_.a=null;ryc(2147,1,RCe);_.Ck=function _fe(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new gIc;for(e=c.i.be();e.he();){d=SWb(e.ie(),349);WHc(b,SWb(Mo(d,PTe),1))}a=Jhd();Sid(a,b,new cge(this))}};ryc(2148,1201,{},cge);_.Xl=function dge(a){KAc(C7e+a.ld())};_.He=function ege(a){bge(this,SWb(a,303))};_.a=null;var vqc=VPc(S9e,'DeleteActionItem$1$1',2148),_gc=VPc(N9e,'DeleteItemWindow',1561),Xgc=VPc(N9e,'DeleteItemWindow$1',1562),Zgc=VPc(N9e,'DeleteItemWindow$2',1563),Ygc=VPc(N9e,'DeleteItemWindow$2$1',1564),$gc=VPc(N9e,'DeleteItemWindow$3',1565);hDe(EKb)(3);