function rPb(){}
function Rzd(){}
function Ozd(a){this.a=a}
function Uzd(a){this.a=a}
function Xzd(a){this.a=a}
function dAd(a){this.a=a}
function Nzd(a){a.a.a=false}
function Wzd(a){HY(a.a,null)}
function LLc(a,b){a.a.Ql(a,b)}
function _zd(a,b){this.a=a;this.b=b}
function MLc(a,b){LLc(a,(tzc(),new qzc(b)))}
function qPb(){qPb=qBe;pPb=new ePb(jQe,new rPb)}
function NLc(){ILc();JLc(this,new fMc(this));this.cd[dGe]=MQe}
function Hzd(a,b,c,d,e,g,i,j){Did(eid(),b,c,d,e,g,i,j,new gAd(a,b,c,d,e,g,i))}
function gAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function cAd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){Jzd(mXb(t9(a.a.i),286).Sl(),mXb(t9(a.a.b),286).Sl());!!a.a.f&&$cb(a.a.f)}}
function Jzd(b,c){try{var d=$wnd.jQuery(Wbf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Izd(b){thisic=b;$wnd.jQuery(Wbf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function $zd(a){mXb(t9(a.a.i),286).Sl()>0&&mXb(t9(a.a.b),286).Sl()>0&&Hzd(a.a,mXb(Mo(a.b,vUe),1),mXb(a.a.e.le(),1),mXb(t9(a.a.g),286).Sl(),mXb(t9(a.a.c),286).Sl(),mXb(t9(a.a.i),286).Sl(),mXb(t9(a.a.b),286).Sl(),false)}
function Did(b,c,d,e,g,i,j,k,n){var o,p,q;p=new hGc(b,KVe,'cropImage');try{q=gGc(p,LVe,7);vFc(q,rFc(q,$Re));vFc(q,rFc(q,$Re));vFc(q,rFc(q,rVe));vFc(q,rFc(q,rVe));vFc(q,rFc(q,rVe));vFc(q,rFc(q,rVe));vFc(q,rFc(q,NVe));vFc(q,rFc(q,c));vFc(q,rFc(q,d));TFc(q.a,SDe+e);TFc(q.a,SDe+g);TFc(q.a,SDe+i);TFc(q.a,SDe+j);TFc(q.a,k?VHe:FGe);fGc(p,n,(zGc(),yGc))}catch(a){a=Rxc(a);if(oXb(a,255)){o=a;j1c(n,o)}else throw a}}
function Kzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,ohd(Xbf,Xbf));this.Cc=Ybf;!!this.uc&&(ix(this).id=Ybf,undefined);p=new Szb(oHe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),yHe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,hFe,Zbf):(y.Sc+=$bf);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni(_bf);Rx(this.e,_bf);C9(this.e,ohd('newName.label','New name'));n=mXb(Mo(c,BIe),1).lastIndexOf(GGe);if(n>0){k=DSc(mXb(Mo(c,BIe),1),n);this.e.Qi(ASc(mXb(Mo(c,BIe),1),k,acf+k))}else{this.e.Qi(mXb(Mo(c,BIe),1)+acf)}Uw(this.e,(NE(),VC),new Ozd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,hFe,Zbf):(z.Sc+=$bf);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Dbc);this.b=new dkb;Ujb(this.b,Dbc);v=mXb(Mo(c,DUe),1);t=mXb(Mo(c,EUe),1);u=0;s=0;try{u=v!=null?OPc(v,10,-2147483648,2147483647):0;s=t!=null?OPc(t,10,-2147483648,2147483647):0}catch(a){a=Rxc(a);if(!oXb(a,287))throw a}if(!!d&&!d.Rd()){C=new DIc;for(j=d.be();j.he();){i=mXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+w1e+i[1];E=new u2c(w,w);Po(E,uFe,i[0]);Po(E,tFe,i[1]);dXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,xFe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new Rzd);ecb(this.f,ohd(bcf,ccf));bT(B,this.f,new szb(0.6))}}C9(this.i,ohd(q1e,r1e));E9(this.i,uFe);Rx(this.i,uFe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,fFe,Zbf):(x.Sc+='paddingLeft:10px;');q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,ohd(u1e,v1e));E9(this.b,tFe);Rx(this.b,tFe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(oHe));r=new NLc;Aw(r,new Uzd(this),(qPb(),qPb(),pPb));r.cd.id='cropbox';MLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Dbc);E9(this.g,dFe);Rx(this.g,dFe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Dbc);E9(this.c,cFe);Rx(this.c,cFe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(ohd(F_e,F_e),new Xzd(this));D=new YX(ohd(E_e,E_e),new _zd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new dAd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var Wbf='#cropbox',acf='-crop',Zbf='10px',Ybf='JahiaGxtImageCrop',dcf='failure.crop.label',Xbf='label.crop',$bf='paddingRight:10px;';Oyc(787,775,{},rPb);_.Hk=function sPb(a){Izd(mXb(mXb(a,226),391).a)};_.Kk=function tPb(){return pPb};var pPb;Oyc(1035,182,QBe,NLc);Oyc(1036,1037,{});_.Ql=function aMc(a,b){JLc(a,new fMc(a));a.a.Ql(a,b)};Oyc(1039,1037,{});_.Ql=function jMc(a,b){!!a.a&&(a.a.Nl(a)[NQe]=SDe,undefined);HMb(a.cd,b.a)};Oyc(1579,363,oCe,Kzd);_.Nm=function Lzd(a,b,c,d){var e,g,i;jcb(this.c,oRc(a));jcb(this.g,oRc(b));H9(this.i,SDe+c);H9(this.b,SDe+d);if(this.a){g=mXb(this.e.le(),1);e=wSc(g,NSc(46));this.e.Qi(ESc(g,0,g.lastIndexOf(acf))+acf+c+_He+d+(e!=-1?ESc(g,e,g.length):SDe))}i=this.f?mXb(hdb(this.f),331):null;!!i&&(c!=mXb(Mo(i,uFe),283).a||d!=mXb(Mo(i,tFe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;Oyc(1580,1,JBe,Ozd);_.Ad=function Pzd(a){Nzd(this,mXb(a,62))};_.a=null;Oyc(1581,234,JBe,Rzd);_.sg=function Szd(a){var b;b=mXb(XF(a),331);Jzd(mXb(Mo(b,uFe),283).a,mXb(Mo(b,tFe),283).a)};Oyc(1582,1,{226:1,231:1,391:1},Uzd);_.a=null;Oyc(1583,236,JBe,Xzd);_.tg=function Yzd(a){Wzd(this,mXb(a,59))};_.a=null;Oyc(1584,236,JBe,_zd);_.tg=function aAd(a){$zd(this,mXb(a,59))};_.a=null;_.b=null;Oyc(1585,1,JBe,dAd);_.Ad=function eAd(a){cAd(this,mXb(a,62))};_.a=null;Oyc(1586,1202,{},gAd);_.fm=function hAd(a){if(oXb(a,380)){gBc(ohd(s0e,s0e)+IDe+ohd($8e,$8e))&&Hzd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{fBc(ohd(dcf,dcf)+IDe+a.kd());rb(ohd(dcf,dcf),a)}};_.He=function iAd(a){var b;HY(this.a,null);b=new HYc;b.Td(TZe,(BPc(),BPc(),APc));UBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;Oyc(2131,1,mDe);_.Ck=function qfe(){$Y(new Kzd(this.a.o,this.a.o.n.q,this.a.a))};var Qhc=qQc(taf,'ImageCrop',1579),Jhc=qQc(taf,'ImageCrop$1',1580),Khc=qQc(taf,'ImageCrop$2',1581),Lhc=qQc(taf,'ImageCrop$3',1582),Mhc=qQc(taf,'ImageCrop$4',1583),Nhc=qQc(taf,'ImageCrop$5',1584),Ohc=qQc(taf,'ImageCrop$6',1585),Phc=qQc(taf,'ImageCrop$7',1586),P7b=qQc(dbf,Lbf,787);EDe(EKb)(2);