function Iyd(a){this.a=a}
function Nyd(a){this.a=a}
function zge(a){this.a=a}
function Myd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function yge(a){$Y(new zyd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function Fyd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function Byd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Eyd(a){var b,c;HY(a.a,null);QBd(a.b,ohd(s7e,s7e));b=eid();c=new Iyd(a.b);a.c?Gid(b,a.d,c):Gjd(b,a.d,mXb(t9(a.e),1),c)}
function Gjd(b,c,d,e){var g,i,j;i=new hGc(b,KVe,'markForDeletion');try{j=gGc(i,LVe,2);vFc(j,rFc(j,MVe));vFc(j,rFc(j,$Re));wFc(j,c);vFc(j,rFc(j,d));fGc(i,e,(zGc(),yGc))}catch(a){a=Rxc(a);if(oXb(a,255)){g=a;j1c(e,g)}else throw a}}
function yyd(a,b){var c;b>1?(c=phd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',cXb(Ewc,zBe,1,[SDe+b]))):mXb(Mo(mXb(a.i.Cl(0),349),RUe),303)._d($Ze)?(c=phd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',cXb(Ewc,zBe,1,[mXb(Mo(a.q,BIe),1)]))):(c=phd(M3e,N3e,cXb(Ewc,zBe,1,[mXb(Mo(a.q,BIe),1)])));return c}
function zyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,ecf);!!this.G&&Bk(rk(this.G,_Ke),ecf);YY(this,false);this.a=new _hb;RT(this.a,ohd(t_e,t_e));this.a.zb=false;Jx(this.a,false);Rx(this.a,'JahiaGxtDeleteItem');BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new DIc;p=new DIc;for(k=b.i.be();k.he();){j=mXb(k.ie(),349);dXb(o.c,o.d++,j);rIc(p,mXb(Mo(j,vUe),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),yHe),false);g.zb=false;this.b=_Cd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$('<br />'+ohd(y6e,z6e)+': <br />'));aT(this.a,r)}i=o.d;iq(this.b.H.e,new Byd(this,b,i,g,r,c,s));if(c){n=ohd(e9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.a,new q$(n));ST(this,(tod(),sod(),pod))}q=new YX(ohd(v7e,v7e),new Fyd(this,a,c,p,r));e=new YX(ohd(w7e,w7e),new Nyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var ecf='Informations';Oyc(1562,363,oCe,zyd);_.a=null;_.b=null;Oyc(1563,225,JBe,Byd);_.og=function Cyd(a){var b,c,d;b=mXb(a.c,303);c=b.Wd();d=yyd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?ohd('message.remove.multiple.usage','Those nodes are still used in:'):ohd('message.remove.single.usage','This node is still used by:'))}else{jT(this.a.a,this.b);jz(this.f,'620','70%');if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;Oyc(1564,236,JBe,Fyd);_.tg=function Gyd(a){Eyd(this,mXb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;Oyc(1565,1202,{},Iyd);_.fm=function Jyd(a){PBd(this.a);rb(a.ld(),a);j2(ohd(RVe,aOe),a.ld(),null)};_.He=function Kyd(a){var b;PBd(this.a);b=new HYc;b.Td(SZe,(BPc(),BPc(),APc));UBd(this.a,b);XBd(this.a)};_.a=null;Oyc(1566,236,JBe,Nyd);_.tg=function Oyd(a){Myd(this,mXb(a,59))};_.a=null;Oyc(2148,1,mDe);_.Ck=function wge(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new DIc;for(e=c.i.be();e.he();){d=mXb(e.ie(),349);rIc(b,mXb(Mo(d,vUe),1))}a=eid();njd(a,b,new zge(this))}};Oyc(2149,1202,{},zge);_.fm=function Age(a){fBc(i8e+a.ld())};_.He=function Bge(a){yge(this,mXb(a,303))};_.a=null;var Sqc=qQc(yaf,'DeleteActionItem$1$1',2149),whc=qQc(taf,'DeleteItemWindow',1562),shc=qQc(taf,'DeleteItemWindow$1',1563),uhc=qQc(taf,'DeleteItemWindow$2',1564),thc=qQc(taf,'DeleteItemWindow$2$1',1565),vhc=qQc(taf,'DeleteItemWindow$3',1566);EDe(EKb)(3);