function MPb(){}
function BBd(){}
function yBd(a){this.a=a}
function EBd(a){this.a=a}
function HBd(a){this.a=a}
function PBd(a){this.a=a}
function xBd(a){a.a.a=false}
function GBd(a){UY(a.a,null)}
function LBd(a,b){this.a=a;this.b=b}
function kOc(a,b){jOc(a,(TBc(),new QBc(b)))}
function LPb(){LPb=ERe;KPb=new zPb(t4e,new MPb)}
function rBd(a,b,c,d,e,g,i,j){old(Rkd(),b,c,d,e,g,i,j,new SBd(a,b,c,d,e,g,i))}
function SBd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function tBd(b,c){try{var d=$wnd.jQuery(Ysf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function OBd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){tBd(lXb(y9(a.a.i),287).Ul(),lXb(y9(a.a.b),287).Ul());!!a.a.f&&ddb(a.a.f)}}
function sBd(b){thisic=b;$wnd.jQuery(Ysf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function KBd(a){lXb(y9(a.a.i),287).Ul()>0&&lXb(y9(a.a.b),287).Ul()>0&&rBd(a.a,lXb(Fo(a.b,y8e),1),lXb(a.a.e.ne(),1),lXb(y9(a.a.g),287).Ul(),lXb(y9(a.a.c),287).Ul(),lXb(y9(a.a.i),287).Ul(),lXb(y9(a.a.b),287).Ul(),false)}
function old(b,c,d,e,g,i,j,k,n){var o,p,q;p=new EIc(b,P9e,'cropImage');try{q=DIc(p,Q9e,7);SHc(q,OHc(q,_5e));SHc(q,OHc(q,_5e));SHc(q,OHc(q,w9e));SHc(q,OHc(q,w9e));SHc(q,OHc(q,w9e));SHc(q,OHc(q,w9e));SHc(q,OHc(q,S9e));SHc(q,OHc(q,c));SHc(q,OHc(q,d));oIc(q.a,iUe+e);oIc(q.a,iUe+g);oIc(q.a,iUe+i);oIc(q.a,iUe+j);oIc(q.a,k?mYe:YWe);CIc(p,n,(WIc(),VIc))}catch(a){a=pAc(a);if(nXb(a,256)){o=a;J3c(n,o)}else throw a}}
function uBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,$jd(Zsf,Zsf));this.Dc=$sf;!!this.vc&&(gx(this).id=$sf,undefined);p=new _zb(HXe);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),TXe),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,yVe,_sf):(y.Tc+=atf);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(btf);Px(this.e,btf);H9(this.e,$jd('newName.label','New name'));n=lXb(Fo(c,XYe),1).lastIndexOf(ZWe);if(n>0){k=cVc(lXb(Fo(c,XYe),1),n);this.e.$i($Uc(lXb(Fo(c,XYe),1),k,ctf+k))}else{this.e.$i(lXb(Fo(c,XYe),1)+ctf)}Sw(this.e,(RE(),ZC),new yBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,yVe,_sf):(z.Tc+=atf);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,Bbc);this.b=new ikb;Zjb(this.b,Bbc);v=lXb(Fo(c,F8e),1);t=lXb(Fo(c,G8e),1);u=0;s=0;try{u=v!=null?mSc(v,10,-2147483648,2147483647):0;s=t!=null?mSc(t,10,-2147483648,2147483647):0}catch(a){a=pAc(a);if(!nXb(a,288))throw a}if(!!d&&!d.Td()){C=new $Kc;for(j=d.de();j.je();){i=lXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+vhf+i[1];E=new Y4c(w,w);Io(E,LVe,i[0]);Io(E,KVe,i[1]);cXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,OVe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new BBd);kcb(this.f,$jd(dtf,etf));oT(B,this.f,new Bzb(0.6))}}H9(this.i,$jd(phf,qhf));J9(this.i,LVe);Px(this.i,LVe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,wVe,_sf):(x.Tc+='paddingLeft:10px;');q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,$jd(thf,uhf));J9(this.b,KVe);Px(this.b,KVe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(HXe));r=new lOc;yw(r,new EBd(this),(LPb(),LPb(),KPb));r.dd.id='cropbox';kOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,Bbc);J9(this.g,sVe);Px(this.g,sVe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,Bbc);J9(this.c,rVe);Px(this.c,rVe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY($jd(uff,uff),new HBd(this));D=new jY($jd(zff,zff),new LBd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new PBd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var Ysf='#cropbox',ctf='-crop',_sf='10px',$sf='JahiaGxtImageCrop',ftf='failure.crop.label',Zsf='label.crop',atf='paddingRight:10px;';mBc(787,775,{},MPb);_.Sk=function NPb(a){sBd(lXb(lXb(a,227),393).a)};_.Vk=function OPb(){return KPb};var KPb;mBc(1565,365,ESe,uBd);_.Dm=function vBd(a,b,c,d){var e,g,i;ocb(this.c,OTc(a));ocb(this.g,OTc(b));M9(this.i,iUe+c);M9(this.b,iUe+d);if(this.a){g=lXb(this.e.ne(),1);e=WUc(g,mVc(46));this.e.$i(dVc(g,0,g.lastIndexOf(ctf))+ctf+c+sYe+d+(e!=-1?dVc(g,e,g.length):iUe))}i=this.f?lXb(mdb(this.f),333):null;!!i&&(c!=lXb(Fo(i,LVe),284).a||d!=lXb(Fo(i,KVe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;mBc(1566,1,XRe,yBd);_.Bd=function zBd(a){xBd(this,lXb(a,61))};_.a=null;mBc(1567,236,XRe,BBd);_.wg=function CBd(a){var b;b=lXb(fG(a),333);tBd(lXb(Fo(b,LVe),284).a,lXb(Fo(b,KVe),284).a)};mBc(1568,1,{227:1,232:1,393:1},EBd);_.a=null;mBc(1569,238,XRe,HBd);_.xg=function IBd(a){GBd(this,lXb(a,58))};_.a=null;mBc(1570,238,XRe,LBd);_.xg=function MBd(a){KBd(this,lXb(a,58))};_.a=null;_.b=null;mBc(1571,1,XRe,PBd);_.Bd=function QBd(a){OBd(this,lXb(a,61))};_.a=null;mBc(1572,1202,{},SBd);_.hm=function TBd(a){if(nXb(a,382)){HDc($jd(Lgf,Lgf)+$Te+$jd(Ypf,Ypf))&&rBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{GDc($jd(ftf,ftf)+$Te+a.ld());rb($jd(ftf,ftf),a)}};_.Je=function UBd(a){var b;UY(this.a,null);b=new f_c;b.Vd(Ldf,(_Rc(),_Rc(),$Rc));this.a.d.um(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;mBc(2260,1,DTe);_.Nk=function ive(){mZ(new uBd(this.a.o,this.a.o.qm().q,this.a.a))};var Dhc=QSc(zrf,'ImageCrop',1565),whc=QSc(zrf,'ImageCrop$1',1566),xhc=QSc(zrf,'ImageCrop$2',1567),yhc=QSc(zrf,'ImageCrop$3',1568),zhc=QSc(zrf,'ImageCrop$4',1569),Ahc=QSc(zrf,'ImageCrop$5',1570),Bhc=QSc(zrf,'ImageCrop$6',1571),Chc=QSc(zrf,'ImageCrop$7',1572),O7b=QSc(ksf,jsf,787);WTe(VKb)(2);