function xAd(a){this.a=a}
function rwe(a){this.a=a}
function wAd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function sAd(a,b){this.a=a;this.b=b}
function pAd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function lAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function qwe(a){mZ(new jAd(a.a.a.o,a.a.a.o.qm(),a.a.a.b))}
function oAd(a){var b,c;UY(a.a,null);a.b.tm($jd(pof,pof));b=Rkd();c=new sAd(a.b,a.d);a.c?rld(b,a.d,c):umd(b,a.d,lXb(y9(a.e),1),c)}
function umd(b,c,d,e){var g,i,j;i=new EIc(b,P9e,'markForDeletion');try{j=DIc(i,Q9e,2);SHc(j,OHc(j,R9e));SHc(j,OHc(j,_5e));THc(j,c);SHc(j,OHc(j,d));CIc(i,e,(WIc(),VIc))}catch(a){a=pAc(a);if(nXb(a,256)){g=a;J3c(e,g)}else throw a}}
function iAd(a,b){var c;b>1?(c=_jd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',bXb(czc,NRe,1,[iUe+b]))):lXb(Fo(lXb(a.i.Dl(0),351),W8e),304).be(Wdf)?(c=_jd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',bXb(czc,NRe,1,[lXb(Fo(a.q,XYe),1)]))):(c=_jd(eqf,fqf,bXb(czc,NRe,1,[lXb(Fo(a.q,XYe),1)])));return c}
function jAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,gtf);!!this.G&&sk(ik(this.G,w_e),gtf);kZ(this,false);this.a=new eib;cU(this.a,$jd(Xgf,Xgf));this.a.Ab=false;Hx(this.a,false);Px(this.a,'JahiaGxtDeleteItem');MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new $Kc;p=new $Kc;for(k=b.i.de();k.je();){j=lXb(k.ke(),351);cXb(o.c,o.d++,j);OKc(p,lXb(Fo(j,y8e),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),TXe),false);g.Ab=false;this.b=MEd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$('<br />'+$jd(xnf,ynf)+': <br />'));nT(this.a,r)}i=o.d;bq(this.b.H.e,new lAd(this,b,i,g,r,c,s));if(c){n=$jd(gqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.a,new I$(n));dU(this,(urd(),trd(),qrd))}q=new jY($jd(sof,sof),new pAd(this,a,c,p,r));e=new jY($jd(tof,tof),new xAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var gtf='Informations';mBc(1548,365,ESe,jAd);_.a=null;_.b=null;mBc(1549,226,XRe,lAd);_.rg=function mAd(a){var b,c,d;b=lXb(a.c,304);c=b.Yd();d=iAd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?$jd('message.remove.multiple.usage','Those nodes are still used in:'):$jd('message.remove.single.usage','This node is still used by:'))}else{wT(this.a.a,this.b);hz(this.f,'620','70%');if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;mBc(1550,238,XRe,pAd);_.xg=function qAd(a){oAd(this,lXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;mBc(1551,1202,{},sAd);_.hm=function tAd(a){this.a.sm();rb(a.md(),a);H2($jd(V9e,d8e),a.md(),null)};_.Je=function uAd(a){var b,c;this.a.sm();c=null;nXb(this.a,431)?(c=lXb(this.a,431).c.t):nXb(this.a,418)&&(c=lXb(this.a,418));b=new f_c;!!c&&TKc(this.b,lXb(Fo(c.o.g,y8e),1),0)!=-1?b.Vd(Idf,c.o.g):b.Vd(Kdf,(_Rc(),_Rc(),$Rc));this.a.um(b);this.a.vm(null)};_.a=null;_.b=null;mBc(1552,238,XRe,xAd);_.xg=function yAd(a){wAd(this,lXb(a,58))};_.a=null;mBc(2277,1,DTe);_.Nk=function owe(){var a,b,c,d,e;c=this.a.o.qm();if(!c.i.Td()){b=new $Kc;for(e=c.i.de();e.je();){d=lXb(e.ke(),351);OKc(b,lXb(Fo(d,y8e),1))}a=Rkd();cmd(a,b,new rwe(this))}};mBc(2278,1202,{},rwe);_.hm=function swe(a){GDc(cpf+a.md())};_.Je=function twe(a){qwe(this,lXb(a,304))};_.a=null;var ptc=QSc(Erf,'DeleteActionItem$1$1',2278),jhc=QSc(zrf,'DeleteItemWindow',1548),fhc=QSc(zrf,'DeleteItemWindow$1',1549),hhc=QSc(zrf,'DeleteItemWindow$2',1550),ghc=QSc(zrf,'DeleteItemWindow$2$1',1551),ihc=QSc(zrf,'DeleteItemWindow$3',1552);WTe(VKb)(3);