function MPb(){}
function YBd(){}
function VBd(a){this.a=a}
function _Bd(a){this.a=a}
function cCd(a){this.a=a}
function kCd(a){this.a=a}
function UBd(a){a.a.a=false}
function bCd(a){UY(a.a,null)}
function gCd(a,b){this.a=a;this.b=b}
function HOc(a,b){GOc(a,(oCc(),new lCc(b)))}
function LPb(){LPb=_Re;KPb=new zPb($4e,new MPb)}
function OBd(a,b,c,d,e,g,i,j){Lld(mld(),b,c,d,e,g,i,j,new nCd(a,b,c,d,e,g,i))}
function nCd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function jCd(a){if(y9(a.a.i)!=null&&y9(a.a.b)!=null){QBd(HXb(y9(a.a.i),287).cm(),HXb(y9(a.a.b),287).cm());!!a.a.f&&ddb(a.a.f)}}
function QBd(b,c){try{var d=$wnd.jQuery(Ftf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function PBd(b){thisic=b;$wnd.jQuery(Ftf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Nm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function fCd(a){HXb(y9(a.a.i),287).cm()>0&&HXb(y9(a.a.b),287).cm()>0&&OBd(a.a,HXb(Fo(a.b,d9e),1),HXb(a.a.e.ne(),1),HXb(y9(a.a.g),287).cm(),HXb(y9(a.a.c),287).cm(),HXb(y9(a.a.i),287).cm(),HXb(y9(a.a.b),287).cm(),false)}
function Lld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new _Ic(b,uaf,'cropImage');try{q=$Ic(p,vaf,7);nIc(q,jIc(q,G6e));nIc(q,jIc(q,G6e));nIc(q,jIc(q,baf));nIc(q,jIc(q,baf));nIc(q,jIc(q,baf));nIc(q,jIc(q,baf));nIc(q,jIc(q,xaf));nIc(q,jIc(q,c));nIc(q,jIc(q,d));LIc(q.a,FUe+e);LIc(q.a,FUe+g);LIc(q.a,FUe+i);LIc(q.a,FUe+j);LIc(q.a,k?JYe:tXe);ZIc(p,n,(rJc(),qJc))}catch(a){a=MAc(a);if(JXb(a,256)){o=a;e4c(n,o)}else throw a}}
function RBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.d=b;fZ(this,vkd(Gtf,Gtf));this.Dc=Htf;!!this.vc&&(gx(this).id=Htf,undefined);p=new _zb(cYe);o=new eib;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&jk(Yk(gx(o),oYe),false);o.O=70;B=new xT;MS(B,new Dzb);y=new xT;y.Mc?Ak(y.vc,VVe,Itf):(y.Tc+=Jtf);MS(y,new jAb((Bib(),yib)));this.e=new qcb;this.e.Xi(Ktf);Px(this.e,Ktf);H9(this.e,vkd('newName.label','New name'));n=HXb(Fo(c,sZe),1).lastIndexOf(uXe);if(n>0){k=zVc(HXb(Fo(c,sZe),1),n);this.e.$i(vVc(HXb(Fo(c,sZe),1),k,Ltf+k))}else{this.e.$i(HXb(Fo(c,sZe),1)+Ltf)}Sw(this.e,(RE(),ZC),new VBd(this));oT(y,this.e,p);z=new xT;z.Mc?Ak(z.vc,VVe,Itf):(z.Tc+=Jtf);q=new jAb(zib);q.j=40;MS(z,q);oT(o,y,new Bzb(0.6));this.i=new ikb;Zjb(this.i,Ybc);this.b=new ikb;Zjb(this.b,Ybc);v=HXb(Fo(c,k9e),1);t=HXb(Fo(c,l9e),1);u=0;s=0;try{u=v!=null?JSc(v,10,-2147483648,2147483647):0;s=t!=null?JSc(t,10,-2147483648,2147483647):0}catch(a){a=MAc(a);if(!JXb(a,288))throw a}if(!!d&&!d.Td()){C=new vLc;for(j=d.de();j.je();){i=HXb(j.ke(),285);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+aif+i[1];E=new t5c(w,w);Io(E,gWe,i[0]);Io(E,fWe,i[1]);yXb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Mdb;Ddb(this.f,jWe);Gdb(this.f,new ZM);this.f.f=true;this.f.E=0;this.f.Vb=true;KM(this.f.A,C);adb(this.f,new YBd);kcb(this.f,vkd(Mtf,Ntf));oT(B,this.f,new Bzb(0.6))}}H9(this.i,vkd(Whf,Xhf));J9(this.i,gWe);Px(this.i,gWe);oT(z,this.i,p);x=new xT;x.Mc?Ak(x.vc,TVe,Itf):(x.Tc+='paddingLeft:10px;');q=new jAb(zib);q.j=40;MS(x,q);H9(this.b,vkd($hf,_hf));J9(this.b,fWe);Px(this.b,fWe);oT(x,this.b,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(cYe));r=new IOc;yw(r,new _Bd(this),(LPb(),LPb(),KPb));r.dd.id='cropbox';HOc(r,c.v);rT(o,r,o.Kb.d);this.g=new ikb;Zjb(this.g,Ybc);J9(this.g,PVe);Px(this.g,PVe);Xx(this.g,false);nT(o,this.g);this.c=new ikb;Zjb(this.c,Ybc);J9(this.c,OVe);Px(this.c,OVe);Xx(this.c,false);nT(o,this.c);e=new O8;g=new jY(vkd(_ff,_ff),new cCd(this));D=new jY(vkd(egf,egf),new gCd(this,c));A8(e,D,e.Kb.d);A8(e,g,e.Kb.d);aU(this,(ie(),fe));_T(this,e);A=new kCd(this);Sw(this.i,ZC,A);Sw(this.b,ZC,A);ES(this,o,this.Kb.d);this.P=true;this.Ab=true;this.t=false}
var Ftf='#cropbox',Ltf='-crop',Itf='10px',Htf='JahiaGxtImageCrop',Otf='failure.crop.label',Gtf='label.crop',Jtf='paddingRight:10px;';JBc(787,775,{},MPb);_.Sk=function NPb(a){PBd(HXb(HXb(a,227),393).a)};_.Vk=function OPb(){return KPb};var KPb;JBc(1566,365,_Se,RBd);_.Nm=function SBd(a,b,c,d){var e,g,i;ocb(this.c,jUc(a));ocb(this.g,jUc(b));M9(this.i,FUe+c);M9(this.b,FUe+d);if(this.a){g=HXb(this.e.ne(),1);e=rVc(g,JVc(46));this.e.$i(AVc(g,0,g.lastIndexOf(Ltf))+Ltf+c+PYe+d+(e!=-1?AVc(g,e,g.length):FUe))}i=this.f?HXb(mdb(this.f),333):null;!!i&&(c!=HXb(Fo(i,gWe),284).a||d!=HXb(Fo(i,fWe),284).a)&&ddb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;JBc(1567,1,sSe,VBd);_.Bd=function WBd(a){UBd(this,HXb(a,61))};_.a=null;JBc(1568,236,sSe,YBd);_.wg=function ZBd(a){var b;b=HXb(fG(a),333);QBd(HXb(Fo(b,gWe),284).a,HXb(Fo(b,fWe),284).a)};JBc(1569,1,{227:1,232:1,393:1},_Bd);_.a=null;JBc(1570,238,sSe,cCd);_.xg=function dCd(a){bCd(this,HXb(a,58))};_.a=null;JBc(1571,238,sSe,gCd);_.xg=function hCd(a){fCd(this,HXb(a,58))};_.a=null;_.b=null;JBc(1572,1,sSe,kCd);_.Bd=function lCd(a){jCd(this,HXb(a,61))};_.a=null;JBc(1573,1203,{},nCd);_.rm=function oCd(a){if(JXb(a,382)){cEc(vkd(qhf,qhf)+vUe+vkd(Fqf,Fqf))&&OBd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{bEc(vkd(Otf,Otf)+vUe+a.ld());rb(vkd(Otf,Otf),a)}};_.Je=function pCd(a){var b;UY(this.a,null);b=new C_c;b.Vd(qef,(wSc(),wSc(),vSc));this.a.d.Em(b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;JBc(2261,1,$Te);_.Nk=function Fve(){mZ(new RBd(this.a.o,this.a.o.Am().q,this.a.a))};var $hc=lTc(gsf,'ImageCrop',1566),Thc=lTc(gsf,'ImageCrop$1',1567),Uhc=lTc(gsf,'ImageCrop$2',1568),Vhc=lTc(gsf,'ImageCrop$3',1569),Whc=lTc(gsf,'ImageCrop$4',1570),Xhc=lTc(gsf,'ImageCrop$5',1571),Yhc=lTc(gsf,'ImageCrop$6',1572),Zhc=lTc(gsf,'ImageCrop$7',1573),i8b=lTc(Tsf,Ssf,787);rUe(VKb)(2);