function UAd(a){this.a=a}
function Owe(a){this.a=a}
function TAd(a){UY(a.a,null)}
function dU(a,b){r$(a.xb,b)}
function PAd(a,b){this.a=a;this.b=b}
function MAd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function IAd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function Nwe(a){mZ(new GAd(a.a.a.o,a.a.a.o.Am(),a.a.a.b))}
function LAd(a){var b,c;UY(a.a,null);a.b.Dm(vkd(Yof,Yof));b=mld();c=new PAd(a.b,a.d);a.c?Old(b,a.d,c):Rmd(b,a.d,HXb(y9(a.e),1),c)}
function Rmd(b,c,d,e){var g,i,j;i=new _Ic(b,uaf,'markForDeletion');try{j=$Ic(i,vaf,2);nIc(j,jIc(j,waf));nIc(j,jIc(j,G6e));oIc(j,c);nIc(j,jIc(j,d));ZIc(i,e,(rJc(),qJc))}catch(a){a=MAc(a);if(JXb(a,256)){g=a;e4c(e,g)}else throw a}}
function FAd(a,b){var c;b>1?(c=wkd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',xXb(zzc,iSe,1,[FUe+b]))):HXb(Fo(HXb(a.i.Nl(0),351),B9e),304).be(Bef)?(c=wkd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',xXb(zzc,iSe,1,[HXb(Fo(a.q,sZe),1)]))):(c=wkd(Nqf,Oqf,xXb(zzc,iSe,1,[HXb(Fo(a.q,sZe),1)])));return c}
function GAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.xb,Ptf);!!this.G&&sk(ik(this.G,S_e),Ptf);kZ(this,false);this.a=new eib;cU(this.a,vkd(Chf,Chf));this.a.Ab=false;Hx(this.a,false);Px(this.a,'JahiaGxtDeleteItem');MS(this.a,new Jzb(0));gz(this.a,650,500);s=new H$;nT(this.a,s);o=new vLc;p=new vLc;for(k=b.i.de();k.je();){j=HXb(k.ke(),351);yXb(o.c,o.d++,j);jLc(p,HXb(Fo(j,d9e),1))}g=new gU;MS(g,new Zxb);g.kc=0;g.Mc&&jk(Yk(gx(g),oYe),false);g.Ab=false;this.b=hFd(o);gz(this.b,650,200);nT(g,this.b);nT(this.a,g);r=new Olb;gz(r,620,100);if(!c){nT(this.a,new I$('<br />'+vkd(eof,fof)+': <br />'));nT(this.a,r)}i=o.d;bq(this.b.H.e,new IAd(this,b,i,g,r,c,s));if(c){n=vkd(Pqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.a,new I$(n));dU(this,(Rrd(),Qrd(),Nrd))}q=new jY(vkd(_of,_of),new MAd(this,a,c,p,r));e=new jY(vkd(apf,apf),new UAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Kb.d);A8(d,e,d.Kb.d);nT(this.a,d);_T(this,d);tS(this,this.a)}
var Ptf='Informations';JBc(1549,365,_Se,GAd);_.a=null;_.b=null;JBc(1550,226,sSe,IAd);_.rg=function JAd(a){var b,c,d;b=HXb(a.c,304);c=b.Yd();d=FAd(this.c,this.d);if(c>0){d+='<br /><br />'+(this.d>1?vkd('message.remove.multiple.usage','Those nodes are still used in:'):vkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.a.a,this.b);hz(this.f,'620','70%');if(this.e){gz(this.a,-1,130);gz(this.a.a,-1,130)}}G$(this.g,d);FS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;JBc(1551,238,sSe,MAd);_.xg=function NAd(a){LAd(this,HXb(a,58))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;JBc(1552,1203,{},PAd);_.rm=function QAd(a){this.a.Cm();rb(a.md(),a);H2(vkd(Aaf,K8e),a.md(),null)};_.Je=function RAd(a){var b,c;this.a.Cm();c=null;JXb(this.a,431)?(c=HXb(this.a,431).c.t):JXb(this.a,418)&&(c=HXb(this.a,418));b=new C_c;!!c&&oLc(this.b,HXb(Fo(c.o.g,d9e),1),0)!=-1?b.Vd(nef,c.o.g):b.Vd(pef,(wSc(),wSc(),vSc));this.a.Em(b);this.a.Fm(null)};_.a=null;_.b=null;JBc(1553,238,sSe,UAd);_.xg=function VAd(a){TAd(this,HXb(a,58))};_.a=null;JBc(2278,1,$Te);_.Nk=function Lwe(){var a,b,c,d,e;c=this.a.o.Am();if(!c.i.Td()){b=new vLc;for(e=c.i.de();e.je();){d=HXb(e.ke(),351);jLc(b,HXb(Fo(d,d9e),1))}a=mld();zmd(a,b,new Owe(this))}};JBc(2279,1203,{},Owe);_.rm=function Pwe(a){bEc(Lpf+a.md())};_.Je=function Qwe(a){Nwe(this,HXb(a,304))};_.a=null;var Mtc=lTc(lsf,'DeleteActionItem$1$1',2279),Ghc=lTc(gsf,'DeleteItemWindow',1549),Chc=lTc(gsf,'DeleteItemWindow$1',1550),Ehc=lTc(gsf,'DeleteItemWindow$2',1551),Dhc=lTc(gsf,'DeleteItemWindow$2$1',1552),Fhc=lTc(gsf,'DeleteItemWindow$3',1553);rUe(VKb)(3);