function EPb(){}
function Tzd(){}
function Qzd(a){this.b=a}
function Wzd(a){this.b=a}
function Zzd(a){this.b=a}
function fAd(a){this.b=a}
function Pzd(a){a.b.b=false}
function Yzd(a){HY(a.b,null)}
function NLc(a,b){a.b.Tl(a,b)}
function bAd(a,b){this.b=a;this.c=b}
function OLc(a,b){NLc(a,(Dzc(),new Azc(b)))}
function DPb(){DPb=sBe;CPb=new rPb(vQe,new EPb)}
function PLc(){KLc();LLc(this,new hMc(this));this.dd[gGe]=ZQe}
function Jzd(a,b,c,d,e,g,i,j){Fid(gid(),b,c,d,e,g,i,j,new iAd(a,b,c,d,e,g,i))}
function iAd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function eAd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){Lzd(vXb(t9(a.b.j),286).Vl(),vXb(t9(a.b.c),286).Vl());!!a.b.g&&$cb(a.b.g)}}
function Lzd(b,c){try{var d=$wnd.jQuery(kcf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Kzd(b){thisic=b;$wnd.jQuery(kcf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Qm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function aAd(a){vXb(t9(a.b.j),286).Vl()>0&&vXb(t9(a.b.c),286).Vl()>0&&Jzd(a.b,vXb(Mo(a.c,IUe),1),vXb(a.b.f.me(),1),vXb(t9(a.b.i),286).Vl(),vXb(t9(a.b.d),286).Vl(),vXb(t9(a.b.j),286).Vl(),vXb(t9(a.b.c),286).Vl(),false)}
function Fid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new jGc(b,XVe,'cropImage');try{q=iGc(p,YVe,7);xFc(q,tFc(q,lSe));xFc(q,tFc(q,lSe));xFc(q,tFc(q,EVe));xFc(q,tFc(q,EVe));xFc(q,tFc(q,EVe));xFc(q,tFc(q,EVe));xFc(q,tFc(q,$Ve));xFc(q,tFc(q,c));xFc(q,tFc(q,d));VFc(q.b,VDe+e);VFc(q.b,VDe+g);VFc(q.b,VDe+i);VFc(q.b,VDe+j);VFc(q.b,k?YHe:IGe);hGc(p,n,(BGc(),AGc))}catch(a){a=_xc(a);if(xXb(a,255)){o=a;l1c(n,o)}else throw a}}
function Mzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,qhd(lcf,lcf));this.Dc=mcf;!!this.vc&&(ix(this).id=mcf,undefined);p=new Szb(rHe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),BHe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,kFe,ncf):(y.Tc+=ocf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(pcf);Rx(this.f,pcf);C9(this.f,qhd('newName.label','New name'));n=vXb(Mo(c,GIe),1).lastIndexOf(JGe);if(n>0){k=FSc(vXb(Mo(c,GIe),1),n);this.f.Ri(CSc(vXb(Mo(c,GIe),1),k,qcf+k))}else{this.f.Ri(vXb(Mo(c,GIe),1)+qcf)}Uw(this.f,(NE(),VC),new Qzd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,kFe,ncf):(z.Tc+=ocf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,Nbc);this.c=new dkb;Ujb(this.c,Nbc);v=vXb(Mo(c,QUe),1);t=vXb(Mo(c,RUe),1);u=0;s=0;try{u=v!=null?QPc(v,10,-2147483648,2147483647):0;s=t!=null?QPc(t,10,-2147483648,2147483647):0}catch(a){a=_xc(a);if(!xXb(a,287))throw a}if(!!d&&!d.Sd()){C=new FIc;for(j=d.ce();j.ie();){i=vXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+L1e+i[1];E=new w2c(w,w);Po(E,xFe,i[0]);Po(E,wFe,i[1]);mXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,AFe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new Tzd);ecb(this.g,qhd(rcf,scf));bT(B,this.g,new szb(0.6))}}C9(this.j,qhd(F1e,G1e));E9(this.j,xFe);Rx(this.j,xFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,iFe,ncf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,qhd(J1e,K1e));E9(this.c,wFe);Rx(this.c,wFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(rHe));r=new PLc;Aw(r,new Wzd(this),(DPb(),DPb(),CPb));r.dd.id='cropbox';OLc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,Nbc);E9(this.i,gFe);Rx(this.i,gFe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,Nbc);E9(this.d,fFe);Rx(this.d,fFe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(qhd(U_e,U_e),new Zzd(this));D=new YX(qhd(T_e,T_e),new bAd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new fAd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var kcf='#cropbox',qcf='-crop',ncf='10px',mcf='JahiaGxtImageCrop',tcf='failure.crop.label',lcf='label.crop',ocf='paddingRight:10px;';Yyc(786,774,{},EPb);_.Lk=function FPb(a){Kzd(vXb(vXb(a,226),391).b)};_.Ok=function GPb(){return CPb};var CPb;Yyc(1030,182,SBe,PLc);Yyc(1031,1032,{});_.Tl=function cMc(a,b){LLc(a,new hMc(a));a.b.Tl(a,b)};Yyc(1034,1032,{});_.Tl=function lMc(a,b){!!a.b&&(a.b.Ql(a)[$Qe]=VDe,undefined);UMb(a.dd,b.b)};Yyc(1574,363,qCe,Mzd);_.Qm=function Nzd(a,b,c,d){var e,g,i;jcb(this.d,qRc(a));jcb(this.i,qRc(b));H9(this.j,VDe+c);H9(this.c,VDe+d);if(this.b){g=vXb(this.f.me(),1);e=ySc(g,PSc(46));this.f.Ri(GSc(g,0,g.lastIndexOf(qcf))+qcf+c+cIe+d+(e!=-1?GSc(g,e,g.length):VDe))}i=this.g?vXb(hdb(this.g),331):null;!!i&&(c!=vXb(Mo(i,xFe),283).b||d!=vXb(Mo(i,wFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;Yyc(1575,1,LBe,Qzd);_.Bd=function Rzd(a){Pzd(this,vXb(a,62))};_.b=null;Yyc(1576,234,LBe,Tzd);_.tg=function Uzd(a){var b;b=vXb(XF(a),331);Lzd(vXb(Mo(b,xFe),283).b,vXb(Mo(b,wFe),283).b)};Yyc(1577,1,{226:1,231:1,391:1},Wzd);_.b=null;Yyc(1578,236,LBe,Zzd);_.ug=function $zd(a){Yzd(this,vXb(a,59))};_.b=null;Yyc(1579,236,LBe,bAd);_.ug=function cAd(a){aAd(this,vXb(a,59))};_.b=null;_.c=null;Yyc(1580,1,LBe,fAd);_.Bd=function gAd(a){eAd(this,vXb(a,62))};_.b=null;Yyc(1581,1197,{},iAd);_.im=function jAd(a){if(xXb(a,380)){oBc(qhd(H0e,H0e)+LDe+qhd(o9e,o9e))&&Jzd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{nBc(qhd(tcf,tcf)+LDe+a.ld());rb(qhd(tcf,tcf),a)}};_.Ie=function kAd(a){var b;HY(this.b,null);b=new JYc;b.Ud(f$e,(DPc(),DPc(),CPc));WBd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;Yyc(2126,1,pDe);_.Hk=function sfe(){$Y(new Mzd(this.b.p,this.b.p.o.r,this.b.b))};var $hc=sQc(Jaf,'ImageCrop',1574),Thc=sQc(Jaf,'ImageCrop$1',1575),Uhc=sQc(Jaf,'ImageCrop$2',1576),Vhc=sQc(Jaf,'ImageCrop$3',1577),Whc=sQc(Jaf,'ImageCrop$4',1578),Xhc=sQc(Jaf,'ImageCrop$5',1579),Yhc=sQc(Jaf,'ImageCrop$6',1580),Zhc=sQc(Jaf,'ImageCrop$7',1581),a8b=sQc(sbf,$bf,786);HDe(OKb)(2);