function Kyd(a){this.b=a}
function Pyd(a){this.b=a}
function Bge(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function Oyd(a){HY(a.b,null)}
function Age(a){$Y(new Byd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function Hyd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function Dyd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Gyd(a){var b,c;HY(a.b,null);SBd(a.c,qhd(I7e,I7e));b=gid();c=new Kyd(a.c);a.d?Iid(b,a.e,c):Ijd(b,a.e,vXb(t9(a.f),1),c)}
function Ijd(b,c,d,e){var g,i,j;i=new jGc(b,XVe,'markForDeletion');try{j=iGc(i,YVe,2);xFc(j,tFc(j,ZVe));xFc(j,tFc(j,lSe));yFc(j,c);xFc(j,tFc(j,d));hGc(i,e,(BGc(),AGc))}catch(a){a=_xc(a);if(xXb(a,255)){g=a;l1c(e,g)}else throw a}}
function Ayd(a,b){var c;b>1?(c=rhd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',lXb(Owc,BBe,1,[VDe+b]))):vXb(Mo(vXb(a.j.Fl(0),349),cVe),303).ae(m$e)?(c=rhd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',lXb(Owc,BBe,1,[vXb(Mo(a.r,GIe),1)]))):(c=rhd(a4e,b4e,lXb(Owc,BBe,1,[vXb(Mo(a.r,GIe),1)])));return c}
function Byd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,ucf);!!this.H&&Bk(rk(this.H,hLe),ucf);YY(this,false);this.b=new _hb;RT(this.b,qhd(I_e,I_e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new FIc;p=new FIc;for(k=b.j.ce();k.ie();){j=vXb(k.je(),349);mXb(o.d,o.e++,j);tIc(p,vXb(Mo(j,IUe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),BHe),false);g.Ab=false;this.c=bDd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+qhd(O6e,P6e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new Dyd(this,b,i,g,r,c,s));if(c){n=qhd(u9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(vod(),uod(),rod))}q=new YX(qhd(L7e,L7e),new Hyd(this,a,c,p,r));e=new YX(qhd(M7e,M7e),new Pyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var ucf='Informations';Yyc(1557,363,qCe,Byd);_.b=null;_.c=null;Yyc(1558,225,LBe,Dyd);_.pg=function Eyd(a){var b,c,d;b=vXb(a.d,303);c=b.Xd();d=Ayd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?qhd('message.remove.multiple.usage','Those nodes are still used in:'):qhd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;Yyc(1559,236,LBe,Hyd);_.ug=function Iyd(a){Gyd(this,vXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;Yyc(1560,1197,{},Kyd);_.im=function Lyd(a){RBd(this.b);rb(a.md(),a);j2(qhd(cWe,pUe),a.md(),null)};_.Ie=function Myd(a){var b;RBd(this.b);b=new JYc;b.Ud(e$e,(DPc(),DPc(),CPc));WBd(this.b,b);ZBd(this.b)};_.b=null;Yyc(1561,236,LBe,Pyd);_.ug=function Qyd(a){Oyd(this,vXb(a,59))};_.b=null;Yyc(2143,1,pDe);_.Hk=function yge(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new FIc;for(e=c.j.ce();e.ie();){d=vXb(e.je(),349);tIc(b,vXb(Mo(d,IUe),1))}a=gid();pjd(a,b,new Bge(this))}};Yyc(2144,1197,{},Bge);_.im=function Cge(a){nBc(y8e+a.md())};_.Ie=function Dge(a){Age(this,vXb(a,303))};_.b=null;var arc=sQc(Oaf,'DeleteActionItem$1$1',2144),Ghc=sQc(Jaf,'DeleteItemWindow',1557),Chc=sQc(Jaf,'DeleteItemWindow$1',1558),Ehc=sQc(Jaf,'DeleteItemWindow$2',1559),Dhc=sQc(Jaf,'DeleteItemWindow$2$1',1560),Fhc=sQc(Jaf,'DeleteItemWindow$3',1561);HDe(OKb)(3);