function DPb(){}
function MBd(){}
function JBd(a){this.b=a}
function PBd(a){this.b=a}
function SBd(a){this.b=a}
function $Bd(a){this.b=a}
function IBd(a){a.b.b=false}
function RBd(a){UY(a.b,null)}
function WBd(a,b){this.b=a;this.c=b}
function vOc(a,b){uOc(a,(bCc(),new $Bc(b)))}
function CPb(){CPb=PRe;BPb=new qPb(X4e,new DPb)}
function CBd(a,b,c,d,e,g,i,j){zld(ald(),b,c,d,e,g,i,j,new bCd(a,b,c,d,e,g,i))}
function bCd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function EBd(b,c){try{var d=$wnd.jQuery(Itf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function ZBd(a){if(y9(a.b.j)!=null&&y9(a.b.c)!=null){EBd(uXb(y9(a.b.j),287).bm(),uXb(y9(a.b.c),287).bm());!!a.b.g&&ddb(a.b.g)}}
function DBd(b){thisic=b;$wnd.jQuery(Itf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Mm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function VBd(a){uXb(y9(a.b.j),287).bm()>0&&uXb(y9(a.b.c),287).bm()>0&&CBd(a.b,uXb(Eo(a.c,h9e),1),uXb(a.b.f.oe(),1),uXb(y9(a.b.i),287).bm(),uXb(y9(a.b.d),287).bm(),uXb(y9(a.b.j),287).bm(),uXb(y9(a.b.c),287).bm(),false)}
function zld(b,c,d,e,g,i,j,k,n){var o,p,q;p=new LIc(b,yaf,'cropImage');try{q=KIc(p,zaf,7);ZHc(q,VHc(q,L6e));ZHc(q,VHc(q,L6e));ZHc(q,VHc(q,faf));ZHc(q,VHc(q,faf));ZHc(q,VHc(q,faf));ZHc(q,VHc(q,faf));ZHc(q,VHc(q,Baf));ZHc(q,VHc(q,c));ZHc(q,VHc(q,d));vIc(q.b,tUe+e);vIc(q.b,tUe+g);vIc(q.b,tUe+i);vIc(q.b,tUe+j);vIc(q.b,k?xYe:hXe);JIc(p,n,(bJc(),aJc))}catch(a){a=zAc(a);if(wXb(a,256)){o=a;U3c(n,o)}else throw a}}
function FBd(b,c,d){Rw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;oZ.call(this);MS(this,new Zxb);gz(this,712,550);this.e=b;fZ(this,jkd(Jtf,Jtf));this.Ec=Ktf;!!this.wc&&(gx(this).id=Ktf,undefined);p=new _zb(SXe);o=new eib;o.xb=false;o.Bb=false;o.lc=0;o.Nc&&jk(Yk(gx(o),bYe),false);o.P=70;B=new xT;MS(B,new Dzb);y=new xT;y.Nc?Ak(y.wc,JVe,Ltf):(y.Uc+=Mtf);MS(y,new jAb((Bib(),yib)));this.f=new qcb;this.f.Yi(Ntf);Px(this.f,Ntf);H9(this.f,jkd('newName.label','New name'));n=uXb(Eo(c,fZe),1).lastIndexOf(iXe);if(n>0){k=nVc(uXb(Eo(c,fZe),1),n);this.f._i(jVc(uXb(Eo(c,fZe),1),k,Otf+k))}else{this.f._i(uXb(Eo(c,fZe),1)+Otf)}Sw(this.f,(RE(),ZC),new JBd(this));oT(y,this.f,p);z=new xT;z.Nc?Ak(z.wc,JVe,Ltf):(z.Uc+=Mtf);q=new jAb(zib);q.k=40;MS(z,q);oT(o,y,new Bzb(0.6));this.j=new ikb;Zjb(this.j,Lbc);this.c=new ikb;Zjb(this.c,Lbc);v=uXb(Eo(c,o9e),1);t=uXb(Eo(c,p9e),1);u=0;s=0;try{u=v!=null?xSc(v,10,-2147483648,2147483647):0;s=t!=null?xSc(t,10,-2147483648,2147483647):0}catch(a){a=zAc(a);if(!wXb(a,288))throw a}if(!!d&&!d.Ud()){C=new fLc;for(j=d.ee();j.ke();){i=uXb(j.le(),285);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+fif+i[1];E=new h5c(w,w);Ho(E,WVe,i[0]);Ho(E,VVe,i[1]);lXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Mdb;Ddb(this.g,ZVe);Gdb(this.g,new ZM);this.g.g=true;this.g.F=0;this.g.Wb=true;KM(this.g.B,C);adb(this.g,new MBd);kcb(this.g,jkd(Ptf,Qtf));oT(B,this.g,new Bzb(0.6))}}H9(this.j,jkd(_hf,aif));J9(this.j,WVe);Px(this.j,WVe);oT(z,this.j,p);x=new xT;x.Nc?Ak(x.wc,HVe,Ltf):(x.Uc+='paddingLeft:10px;');q=new jAb(zib);q.k=40;MS(x,q);H9(this.c,jkd(dif,eif));J9(this.c,VVe);Px(this.c,VVe);oT(x,this.c,p);oT(B,z,new Bzb(0.2));oT(B,x,new Bzb(0.2));oT(o,B,new _zb(SXe));r=new wOc;yw(r,new PBd(this),(CPb(),CPb(),BPb));r.ed.id='cropbox';vOc(r,c.z);rT(o,r,o.Lb.e);this.i=new ikb;Zjb(this.i,Lbc);J9(this.i,DVe);Px(this.i,DVe);Xx(this.i,false);nT(o,this.i);this.d=new ikb;Zjb(this.d,Lbc);J9(this.d,CVe);Px(this.d,CVe);Xx(this.d,false);nT(o,this.d);e=new O8;g=new jY(jkd(egf,egf),new SBd(this));D=new jY(jkd(jgf,jgf),new WBd(this,c));A8(e,D,e.Lb.e);A8(e,g,e.Lb.e);aU(this,(ie(),fe));_T(this,e);A=new $Bd(this);Sw(this.j,ZC,A);Sw(this.c,ZC,A);ES(this,o,this.Lb.e);this.Q=true;this.Bb=true;this.u=false}
var Itf='#cropbox',Otf='-crop',Ltf='10px',Ktf='JahiaGxtImageCrop',Rtf='failure.crop.label',Jtf='label.crop',Mtf='paddingRight:10px;';wBc(785,773,{},DPb);_.Sk=function EPb(a){DBd(uXb(uXb(a,227),393).b)};_.Vk=function FPb(){return BPb};var BPb;wBc(1560,364,PSe,FBd);_.Mm=function GBd(a,b,c,d){var e,g,i;ocb(this.d,ZTc(a));ocb(this.i,ZTc(b));M9(this.j,tUe+c);M9(this.c,tUe+d);if(this.b){g=uXb(this.f.oe(),1);e=fVc(g,xVc(46));this.f._i(oVc(g,0,g.lastIndexOf(Otf))+Otf+c+DYe+d+(e!=-1?oVc(g,e,g.length):tUe))}i=this.g?uXb(mdb(this.g),333):null;!!i&&(c!=uXb(Eo(i,WVe),284).b||d!=uXb(Eo(i,VVe),284).b)&&ddb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;wBc(1561,1,gSe,JBd);_.Cd=function KBd(a){IBd(this,uXb(a,61))};_.b=null;wBc(1562,235,gSe,MBd);_.xg=function NBd(a){var b;b=uXb(fG(a),333);EBd(uXb(Eo(b,WVe),284).b,uXb(Eo(b,VVe),284).b)};wBc(1563,1,{227:1,232:1,393:1},PBd);_.b=null;wBc(1564,237,gSe,SBd);_.yg=function TBd(a){RBd(this,uXb(a,58))};_.b=null;wBc(1565,237,gSe,WBd);_.yg=function XBd(a){VBd(this,uXb(a,58))};_.b=null;_.c=null;wBc(1566,1,gSe,$Bd);_.Cd=function _Bd(a){ZBd(this,uXb(a,61))};_.b=null;wBc(1567,1197,{},bCd);_.qm=function cCd(a){if(wXb(a,382)){RDc(jkd(vhf,vhf)+jUe+jkd(Jqf,Jqf))&&CBd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{QDc(jkd(Rtf,Rtf)+jUe+a.md());rb(jkd(Rtf,Rtf),a)}};_.Ke=function dCd(a){var b;UY(this.b,null);b=new q_c;b.Wd(uef,(kSc(),kSc(),jSc));this.b.e.Dm(b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;wBc(2255,1,OTe);_.Ok=function tve(){mZ(new FBd(this.b.p,this.b.p.zm().r,this.b.b))};var Nhc=_Sc(jsf,'ImageCrop',1560),Ghc=_Sc(jsf,'ImageCrop$1',1561),Hhc=_Sc(jsf,'ImageCrop$2',1562),Ihc=_Sc(jsf,'ImageCrop$3',1563),Jhc=_Sc(jsf,'ImageCrop$4',1564),Khc=_Sc(jsf,'ImageCrop$5',1565),Lhc=_Sc(jsf,'ImageCrop$6',1566),Mhc=_Sc(jsf,'ImageCrop$7',1567),Y7b=_Sc(Vsf,Usf,785);fUe(VKb)(2);