function IAd(a){this.b=a}
function Cwe(a){this.b=a}
function dU(a,b){r$(a.yb,b)}
function HAd(a){UY(a.b,null)}
function DAd(a,b){this.b=a;this.c=b}
function AAd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function wAd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Bwe(a){mZ(new uAd(a.b.b.p,a.b.b.p.zm(),a.b.b.c))}
function zAd(a){var b,c;UY(a.b,null);a.c.Cm(jkd(apf,apf));b=ald();c=new DAd(a.c,a.e);a.d?Cld(b,a.e,c):Fmd(b,a.e,uXb(y9(a.f),1),c)}
function Fmd(b,c,d,e){var g,i,j;i=new LIc(b,yaf,'markForDeletion');try{j=KIc(i,zaf,2);ZHc(j,VHc(j,Aaf));ZHc(j,VHc(j,L6e));$Hc(j,c);ZHc(j,VHc(j,d));JIc(i,e,(bJc(),aJc))}catch(a){a=zAc(a);if(wXb(a,256)){g=a;U3c(e,g)}else throw a}}
function tAd(a,b){var c;b>1?(c=kkd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',kXb(mzc,YRe,1,[tUe+b]))):uXb(Eo(uXb(a.j.Ml(0),351),F9e),304).ce(Fef)?(c=kkd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',kXb(mzc,YRe,1,[uXb(Eo(a.r,fZe),1)]))):(c=kkd(Rqf,Sqf,kXb(mzc,YRe,1,[uXb(Eo(a.r,fZe),1)])));return c}
function uAd(a,b,c){Rw();var d,e,g,i,j,k,n,o,p,q,r,s;oZ.call(this);gz(this,650,500);q$(this.yb,Stf);!!this.H&&sk(ik(this.H,H_e),Stf);kZ(this,false);this.b=new eib;cU(this.b,jkd(Hhf,Hhf));this.b.Bb=false;Hx(this.b,false);Px(this.b,'JahiaGxtDeleteItem');MS(this.b,new Jzb(0));gz(this.b,650,500);s=new H$;nT(this.b,s);o=new fLc;p=new fLc;for(k=b.j.ee();k.ke();){j=uXb(k.le(),351);lXb(o.d,o.e++,j);VKc(p,uXb(Eo(j,h9e),1))}g=new gU;MS(g,new Zxb);g.lc=0;g.Nc&&jk(Yk(gx(g),bYe),false);g.Bb=false;this.c=XEd(o);gz(this.c,650,200);nT(g,this.c);nT(this.b,g);r=new Olb;gz(r,620,100);if(!c){nT(this.b,new I$('<br />'+jkd(iof,jof)+': <br />'));nT(this.b,r)}i=o.e;aq(this.c.I.f,new wAd(this,b,i,g,r,c,s));if(c){n=jkd(Tqf,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');nT(this.b,new I$(n));dU(this,(Frd(),Erd(),Brd))}q=new jY(jkd(dpf,dpf),new AAd(this,a,c,p,r));e=new jY(jkd(epf,epf),new IAd(this));d=new O8;D8(d,(ie(),fe));A8(d,q,d.Lb.e);A8(d,e,d.Lb.e);nT(this.b,d);_T(this,d);tS(this,this.b)}
var Stf='Informations';wBc(1543,364,PSe,uAd);_.b=null;_.c=null;wBc(1544,225,gSe,wAd);_.sg=function xAd(a){var b,c,d;b=uXb(a.d,304);c=b.Zd();d=tAd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?jkd('message.remove.multiple.usage','Those nodes are still used in:'):jkd('message.remove.single.usage','This node is still used by:'))}else{wT(this.b.b,this.c);hz(this.g,'620','70%');if(this.f){gz(this.b,-1,130);gz(this.b.b,-1,130)}}G$(this.i,d);FS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;wBc(1545,237,gSe,AAd);_.yg=function BAd(a){zAd(this,uXb(a,58))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;wBc(1546,1197,{},DAd);_.qm=function EAd(a){this.b.Bm();rb(a.nd(),a);H2(jkd(Eaf,P8e),a.nd(),null)};_.Ke=function FAd(a){var b,c;this.b.Bm();c=null;wXb(this.b,431)?(c=uXb(this.b,431).d.u):wXb(this.b,418)&&(c=uXb(this.b,418));b=new q_c;!!c&&$Kc(this.c,uXb(Eo(c.p.i,h9e),1),0)!=-1?b.Wd(ref,c.p.i):b.Wd(tef,(kSc(),kSc(),jSc));this.b.Dm(b);this.b.Em(null)};_.b=null;_.c=null;wBc(1547,237,gSe,IAd);_.yg=function JAd(a){HAd(this,uXb(a,58))};_.b=null;wBc(2272,1,OTe);_.Ok=function zwe(){var a,b,c,d,e;c=this.b.p.zm();if(!c.j.Ud()){b=new fLc;for(e=c.j.ee();e.ke();){d=uXb(e.le(),351);VKc(b,uXb(Eo(d,h9e),1))}a=ald();nmd(a,b,new Cwe(this))}};wBc(2273,1197,{},Cwe);_.qm=function Dwe(a){QDc(Ppf+a.nd())};_.Ke=function Ewe(a){Bwe(this,uXb(a,304))};_.b=null;var ztc=_Sc(osf,'DeleteActionItem$1$1',2273),thc=_Sc(jsf,'DeleteItemWindow',1543),phc=_Sc(jsf,'DeleteItemWindow$1',1544),rhc=_Sc(jsf,'DeleteItemWindow$2',1545),qhc=_Sc(jsf,'DeleteItemWindow$2$1',1546),shc=_Sc(jsf,'DeleteItemWindow$3',1547);fUe(VKb)(3);