function JPb(){}
function Mzd(){}
function Jzd(a){this.a=a}
function Pzd(a){this.a=a}
function Szd(a){this.a=a}
function $zd(a){this.a=a}
function Izd(a){a.a.a=false}
function Rzd(a){HY(a.a,null)}
function xLc(a,b){a.a.Gl(a,b)}
function Wzd(a,b){this.a=a;this.b=b}
function yLc(a,b){xLc(a,(rzc(),new ozc(b)))}
function IPb(){IPb=kBe;HPb=new wPb(fcf,new JPb)}
function zLc(){uLc();vLc(this,new TLc(this));this.cd[gIe]=bef}
function Czd(a,b,c,d,e,g,i,j){yid(_hd(),b,c,d,e,g,i,j,new bAd(a,b,c,d,e,g,i))}
function bAd(a,b,c,d,e,g,i){this.a=a;this.d=b;this.e=c;this.f=d;this.c=e;this.g=g;this.b=i}
function Ezd(b,c){try{var d=$wnd.jQuery(Uvg).data(Vvg);var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Zzd(a){if(t9(a.a.i)!=null&&t9(a.a.b)!=null){Ezd(iXb(t9(a.a.i),286).Il(),iXb(t9(a.a.b),286).Il());!!a.a.f&&$cb(a.a.f)}}
function Dzd(b){thisic=b;$wnd.jQuery(Uvg).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Dm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function Vzd(a){iXb(t9(a.a.i),286).Il()>0&&iXb(t9(a.a.b),286).Il()>0&&Czd(a.a,iXb(No(a.b,zjf),1),iXb(a.a.e.le(),1),iXb(t9(a.a.g),286).Il(),iXb(t9(a.a.c),286).Il(),iXb(t9(a.a.i),286).Il(),iXb(t9(a.a.b),286).Il(),false)}
function yid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new VFc(b,plf,Tvg);try{q=UFc(p,rlf,7);hFc(q,dFc(q,agf));hFc(q,dFc(q,agf));hFc(q,dFc(q,Wkf));hFc(q,dFc(q,Wkf));hFc(q,dFc(q,Wkf));hFc(q,dFc(q,Wkf));hFc(q,dFc(q,Blf));hFc(q,dFc(q,c));hFc(q,dFc(q,d));FFc(q.a,QDe+e);FFc(q.a,QDe+g);FFc(q.a,QDe+i);FFc(q.a,QDe+j);FFc(q.a,k?xLe:aJe);TFc(p,n,(lGc(),kGc))}catch(a){a=Pxc(a);if(kXb(a,255)){o=a;e1c(n,o)}else throw a}}
function Fzd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.d=b;TY(this,jhd(Wvg,Wvg));this.Cc=Xvg;!!this.uc&&(ix(this).id=Xvg,undefined);p=new Szb(nKe);o=new _hb;o.vb=false;o.zb=false;o.jc=0;o.Lc&&sk(fl(ix(o),NKe),false);o.O=70;B=new kT;BS(B,new uzb);y=new kT;y.Lc?Jk(y.uc,KGe,Yvg):(y.Sc+=Zvg);BS(y,new aAb((wib(),tib)));this.e=new lcb;this.e.Ni($vg);Rx(this.e,$vg);C9(this.e,jhd(_vg,awg));n=iXb(No(c,QNe),1).lastIndexOf(bJe);if(n>0){k=ySc(iXb(No(c,QNe),1),n);this.e.Qi(vSc(iXb(No(c,QNe),1),k,bwg+k))}else{this.e.Qi(iXb(No(c,QNe),1)+bwg)}Uw(this.e,(NE(),VC),new Jzd(this));bT(y,this.e,p);z=new kT;z.Lc?Jk(z.uc,KGe,Yvg):(z.Sc+=Zvg);q=new aAb(uib);q.j=40;BS(z,q);bT(o,y,new szb(0.6));this.i=new dkb;Ujb(this.i,Bbc);this.b=new dkb;Ujb(this.b,Bbc);v=iXb(No(c,Ijf),1);t=iXb(No(c,Jjf),1);u=0;s=0;try{u=v!=null?JPc(v,10,-2147483648,2147483647):0;s=t!=null?JPc(t,10,-2147483648,2147483647):0}catch(a){a=Pxc(a);if(!kXb(a,287))throw a}if(!!d&&!d.Rd()){C=new pIc;for(j=d.be();j.he();){i=iXb(j.ie(),284);if((u==0||u>i[0].a)&&(s==0||s>i[1].a)){w=i[0]+lzf+i[1];E=new p2c(w,w);Qo(E,YGe,i[0]);Qo(E,XGe,i[1]);_Wb(C.c,C.d++,E)}}if(C.d!=0){this.f=new Hdb;ydb(this.f,aHe);Bdb(this.f,new RM);this.f.f=true;this.f.E=0;this.f.Ub=true;CM(this.f.A,C);Xcb(this.f,new Mzd);ecb(this.f,jhd(cwg,dwg));bT(B,this.f,new szb(0.6))}}C9(this.i,jhd(dzf,ezf));E9(this.i,YGe);Rx(this.i,YGe);bT(z,this.i,p);x=new kT;x.Lc?Jk(x.uc,IGe,Yvg):(x.Sc+=ewg);q=new aAb(uib);q.j=40;BS(x,q);C9(this.b,jhd(izf,jzf));E9(this.b,XGe);Rx(this.b,XGe);bT(x,this.b,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(nKe));r=new zLc;Aw(r,new Pzd(this),(IPb(),IPb(),HPb));r.cd.id=fwg;yLc(r,c.v);eT(o,r,o.Jb.d);this.g=new dkb;Ujb(this.g,Bbc);E9(this.g,GGe);Rx(this.g,GGe);Zx(this.g,false);aT(o,this.g);this.c=new dkb;Ujb(this.c,Bbc);E9(this.c,FGe);Rx(this.c,FGe);Zx(this.c,false);aT(o,this.c);e=new J8;g=new YX(jhd(nuf,nuf),new Szd(this));D=new YX(jhd(muf,muf),new Wzd(this,c));v8(e,D,e.Jb.d);v8(e,g,e.Jb.d);PT(this,(ie(),fe));OT(this,e);A=new $zd(this);Uw(this.i,VC,A);Uw(this.b,VC,A);tS(this,o,this.Jb.d);this.P=true;this.zb=true;this.t=false}
var Uvg='#cropbox',bwg='-crop',Yvg='10px',hwg='ImageCrop',iwg='ImageCrop$1',jwg='ImageCrop$2',kwg='ImageCrop$3',lwg='ImageCrop$4',mwg='ImageCrop$5',nwg='ImageCrop$6',owg='ImageCrop$7',Xvg='JahiaGxtImageCrop',Vvg='Jcrop',awg='New name',Tvg='cropImage',fwg='cropbox',gwg='failure.crop.label',Wvg='label.crop',_vg='newName.label',ewg='paddingLeft:10px;',Zvg='paddingRight:10px;';Myc(789,777,{},JPb);_.Hk=function KPb(a){Dzd(iXb(iXb(a,226),391).a)};_.Kk=function LPb(){return HPb};var HPb;Myc(1033,183,KBe,zLc);Myc(1034,1035,{});_.Gl=function OLc(a,b){vLc(a,new TLc(a));a.a.Gl(a,b)};Myc(1037,1035,{});_.Gl=function XLc(a,b){!!a.a&&(a.a.Dl(a)[cef]=QDe,undefined);kNb(a.cd,b.a)};Myc(1580,364,iCe,Fzd);_.Dm=function Gzd(a,b,c,d){var e,g,i;jcb(this.c,jRc(a));jcb(this.g,jRc(b));H9(this.i,QDe+c);H9(this.b,QDe+d);if(this.a){g=iXb(this.e.le(),1);e=rSc(g,ISc(46));this.e.Qi(zSc(g,0,g.lastIndexOf(bwg))+bwg+c+QLe+d+(e!=-1?zSc(g,e,g.length):QDe))}i=this.f?iXb(hdb(this.f),331):null;!!i&&(c!=iXb(No(i,YGe),283).a||d!=iXb(No(i,XGe),283).a)&&$cb(this.f)};_.a=true;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;Myc(1581,1,DBe,Jzd);_.Ad=function Kzd(a){Izd(this,iXb(a,62))};_.a=null;Myc(1582,235,DBe,Mzd);_.sg=function Nzd(a){var b;b=iXb(XF(a),331);Ezd(iXb(No(b,YGe),283).a,iXb(No(b,XGe),283).a)};Myc(1583,1,{226:1,231:1,391:1},Pzd);_.a=null;Myc(1584,237,DBe,Szd);_.tg=function Tzd(a){Rzd(this,iXb(a,59))};_.a=null;Myc(1585,237,DBe,Wzd);_.tg=function Xzd(a){Vzd(this,iXb(a,59))};_.a=null;_.b=null;Myc(1586,1,DBe,$zd);_.Ad=function _zd(a){Zzd(this,iXb(a,62))};_.a=null;Myc(1587,1203,{},bAd);_.Xl=function cAd(a){if(kXb(a,380)){$Ac(jhd(mxf,mxf)+CDe+jhd(_Sf,_Sf))&&Czd(this.a,this.d,this.e,this.f,this.c,this.g,this.b,true)}else{ZAc(jhd(gwg,gwg)+CDe+a.kd());rb(jhd(gwg,gwg),a)}};_.He=function dAd(a){var b;HY(this.a,null);b=new CYc;b.Td(nrf,(wPc(),wPc(),vPc));PBd(this.a.d,b)};_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=0;_.g=0;Myc(2132,1,gDe);_.Ck=function kfe(){$Y(new Fzd(this.a.o,this.a.o.n.q,this.a.a))};var Ohc=lQc(q0f,hwg,1580),Hhc=lQc(q0f,iwg,1581),Ihc=lQc(q0f,jwg,1582),Jhc=lQc(q0f,kwg,1583),Khc=lQc(q0f,lwg,1584),Lhc=lQc(q0f,mwg,1585),Mhc=lQc(q0f,nwg,1586),Nhc=lQc(q0f,owg,1587),M7b=lQc(eeg,eqg,789);yDe(EKb)(2);