function Dyd(a){this.a=a}
function Iyd(a){this.a=a}
function tge(a){this.a=a}
function Hyd(a){HY(a.a,null)}
function ST(a,b){c$(a.wb,b)}
function sge(a){$Y(new uyd(a.a.a.o,a.a.a.o.n,a.a.a.b))}
function Ayd(a,b,c,d,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e}
function wyd(a,b,c,d,e,g,i){this.a=a;this.c=b;this.d=c;this.b=d;this.f=e;this.e=g;this.g=i}
function zyd(a){var b,c;HY(a.a,null);LBd(a.b,jhd(vOf,vOf));b=_hd();c=new Dyd(a.b);a.c?Bid(b,a.d,c):Bjd(b,a.d,iXb(t9(a.e),1),c)}
function Bjd(b,c,d,e){var g,i,j;i=new VFc(b,plf,pwg);try{j=UFc(i,rlf,2);hFc(j,dFc(j,vlf));hFc(j,dFc(j,agf));iFc(j,c);hFc(j,dFc(j,d));TFc(i,e,(lGc(),kGc))}catch(a){a=Pxc(a);if(kXb(a,255)){g=a;e1c(e,g)}else throw a}}
function tyd(a,b){var c;b>1?(c=khd(qwg,rwg,$Wb(Cwc,tBe,1,[QDe+b]))):iXb(No(iXb(a.i.sl(0),349),akf),303)._d(wrf)?(c=khd(swg,twg,$Wb(Cwc,tBe,1,[iXb(No(a.q,QNe),1)]))):(c=khd(REf,SEf,$Wb(Cwc,tBe,1,[iXb(No(a.q,QNe),1)])));return c}
function uyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.wb,uwg);!!this.G&&Bk(rk(this.G,oXe),uwg);YY(this,false);this.a=new _hb;RT(this.a,jhd(Stf,Stf));this.a.zb=false;Jx(this.a,false);Rx(this.a,vwg);BS(this.a,new Azb(0));iz(this.a,650,500);s=new p$;aT(this.a,s);o=new pIc;p=new pIc;for(k=b.i.be();k.he();){j=iXb(k.ie(),349);_Wb(o.c,o.d++,j);dIc(p,iXb(No(j,zjf),1))}g=new VT;BS(g,new Jxb);g.jc=0;g.Lc&&sk(fl(ix(g),NKe),false);g.zb=false;this.b=WCd(o);iz(this.b,650,200);aT(g,this.b);aT(this.a,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.a,new q$(wwg+jhd(GMf,HMf)+xwg));aT(this.a,r)}i=o.d;jq(this.b.H.e,new wyd(this,b,i,g,r,c,s));if(c){n=jhd(sTf,ywg);aT(this.a,new q$(n));ST(this,(ood(),nod(),kod))}q=new YX(jhd(LOf,LOf),new Ayd(this,a,c,p,r));e=new YX(jhd(MOf,MOf),new Iyd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Jb.d);v8(d,e,d.Jb.d);aT(this.a,d);OT(this,d);iS(this,this.a)}
var Ewg='620',Fwg='70%',xwg=': <br />',wwg='<br />',zwg='<br /><br />',ywg='<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>',Gwg='DeleteActionItem$1$1',Hwg='DeleteItemWindow',Iwg='DeleteItemWindow$1',Jwg='DeleteItemWindow$2',Kwg='DeleteItemWindow$2$1',Lwg='DeleteItemWindow$3',twg='Do you really want to remove the selected PAGE {0}?',rwg='Do you really want to remove the {0} selected resources?',uwg='Informations',vwg='JahiaGxtDeleteItem',Dwg='This node is still used by:',Bwg='Those nodes are still used in:',pwg='markForDeletion',qwg='message.remove.multiple.confirm',Awg='message.remove.multiple.usage',swg='message.remove.single.page.confirm',Cwg='message.remove.single.usage';Myc(1563,364,iCe,uyd);_.a=null;_.b=null;Myc(1564,226,DBe,wyd);_.og=function xyd(a){var b,c,d;b=iXb(a.c,303);c=b.Wd();d=tyd(this.c,this.d);if(c>0){d+=zwg+(this.d>1?jhd(Awg,Bwg):jhd(Cwg,Dwg))}else{jT(this.a.a,this.b);jz(this.f,Ewg,Fwg);if(this.e){iz(this.a,-1,130);iz(this.a.a,-1,130)}}o$(this.g,d);uS(this.a.a,false)};_.a=null;_.b=null;_.c=null;_.d=0;_.e=false;_.f=null;_.g=null;Myc(1565,237,DBe,Ayd);_.tg=function Byd(a){zyd(this,iXb(a,59))};_.a=null;_.b=null;_.c=false;_.d=null;_.e=null;Myc(1566,1203,{},Dyd);_.Xl=function Eyd(a){KBd(this.a);rb(a.ld(),a);j2(jhd(Nmf,t3e),a.ld(),null)};_.He=function Fyd(a){var b;KBd(this.a);b=new CYc;b.Td(mrf,(wPc(),wPc(),vPc));PBd(this.a,b);SBd(this.a)};_.a=null;Myc(1567,237,DBe,Iyd);_.tg=function Jyd(a){Hyd(this,iXb(a,59))};_.a=null;Myc(2149,1,gDe);_.Ck=function qge(){var a,b,c,d,e;c=this.a.o.n;if(!c.i.Rd()){b=new pIc;for(e=c.i.be();e.he();){d=iXb(e.ie(),349);dIc(b,iXb(No(d,zjf),1))}a=_hd();ijd(a,b,new tge(this))}};Myc(2150,1203,{},tge);_.Xl=function uge(a){ZAc(CQf+a.ld())};_.He=function vge(a){sge(this,iXb(a,303))};_.a=null;var Qqc=lQc(t1f,Gwg,2150),uhc=lQc(q0f,Hwg,1563),qhc=lQc(q0f,Iwg,1564),shc=lQc(q0f,Jwg,1565),rhc=lQc(q0f,Kwg,1566),thc=lQc(q0f,Lwg,1567);yDe(EKb)(3);