function EPb(){}
function Vzd(){}
function Szd(a){this.b=a}
function Yzd(a){this.b=a}
function _zd(a){this.b=a}
function hAd(a){this.b=a}
function Rzd(a){a.b.b=false}
function $zd(a){HY(a.b,null)}
function PLc(a,b){a.b.Ul(a,b)}
function dAd(a,b){this.b=a;this.c=b}
function QLc(a,b){PLc(a,(Fzc(),new Czc(b)))}
function DPb(){DPb=uBe;CPb=new rPb(tQe,new EPb)}
function RLc(){MLc();NLc(this,new jMc(this));this.dd[iGe]=XQe}
function Lzd(a,b,c,d,e,g,i,j){Hid(iid(),b,c,d,e,g,i,j,new kAd(a,b,c,d,e,g,i))}
function kAd(a,b,c,d,e,g,i){this.b=a;this.e=b;this.f=c;this.g=d;this.d=e;this.i=g;this.c=i}
function gAd(a){if(t9(a.b.j)!=null&&t9(a.b.c)!=null){Nzd(xXb(t9(a.b.j),286).Wl(),xXb(t9(a.b.c),286).Wl());!!a.b.g&&$cb(a.b.g)}}
function Nzd(b,c){try{var d=$wnd.jQuery(ecf).data('Jcrop');var e=d.tellSelect();d.setSelect([e.x,e.y,e.x+b,e.y+c])}catch(a){}}
function Mzd(b){thisic=b;$wnd.jQuery(ecf).Jcrop({boxWidth:700,boxHeight:400,onChange:function(a){thisic.Rm(Math.round(a.x),Math.round(a.y),Math.round(a.w),Math.round(a.h))}})}
function cAd(a){xXb(t9(a.b.j),286).Wl()>0&&xXb(t9(a.b.c),286).Wl()>0&&Lzd(a.b,xXb(Mo(a.c,FUe),1),xXb(a.b.f.me(),1),xXb(t9(a.b.i),286).Wl(),xXb(t9(a.b.d),286).Wl(),xXb(t9(a.b.j),286).Wl(),xXb(t9(a.b.c),286).Wl(),false)}
function Hid(b,c,d,e,g,i,j,k,n){var o,p,q;p=new lGc(b,UVe,'cropImage');try{q=kGc(p,VVe,7);zFc(q,vFc(q,jSe));zFc(q,vFc(q,jSe));zFc(q,vFc(q,BVe));zFc(q,vFc(q,BVe));zFc(q,vFc(q,BVe));zFc(q,vFc(q,BVe));zFc(q,vFc(q,XVe));zFc(q,vFc(q,c));zFc(q,vFc(q,d));XFc(q.b,XDe+e);XFc(q.b,XDe+g);XFc(q.b,XDe+i);XFc(q.b,XDe+j);XFc(q.b,k?$He:KGe);jGc(p,n,(DGc(),CGc))}catch(a){a=byc(a);if(zXb(a,255)){o=a;n1c(n,o)}else throw a}}
function Ozd(b,c,d){Tw();var e,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E;aZ.call(this);BS(this,new Jxb);iz(this,712,550);this.e=b;TY(this,shd(fcf,fcf));this.Dc=gcf;!!this.vc&&(ix(this).id=gcf,undefined);p=new Szb(tHe);o=new _hb;o.wb=false;o.Ab=false;o.kc=0;o.Mc&&sk(fl(ix(o),DHe),false);o.P=70;B=new kT;BS(B,new uzb);y=new kT;y.Mc?Jk(y.vc,mFe,hcf):(y.Tc+=icf);BS(y,new aAb((wib(),tib)));this.f=new lcb;this.f.Oi(jcf);Rx(this.f,jcf);C9(this.f,shd('newName.label','New name'));n=xXb(Mo(c,IIe),1).lastIndexOf(LGe);if(n>0){k=HSc(xXb(Mo(c,IIe),1),n);this.f.Ri(ESc(xXb(Mo(c,IIe),1),k,kcf+k))}else{this.f.Ri(xXb(Mo(c,IIe),1)+kcf)}Uw(this.f,(NE(),VC),new Szd(this));bT(y,this.f,p);z=new kT;z.Mc?Jk(z.vc,mFe,hcf):(z.Tc+=icf);q=new aAb(uib);q.k=40;BS(z,q);bT(o,y,new szb(0.6));this.j=new dkb;Ujb(this.j,Pbc);this.c=new dkb;Ujb(this.c,Pbc);v=xXb(Mo(c,NUe),1);t=xXb(Mo(c,OUe),1);u=0;s=0;try{u=v!=null?SPc(v,10,-2147483648,2147483647):0;s=t!=null?SPc(t,10,-2147483648,2147483647):0}catch(a){a=byc(a);if(!zXb(a,287))throw a}if(!!d&&!d.Sd()){C=new HIc;for(j=d.ce();j.ie();){i=xXb(j.je(),284);if((u==0||u>i[0].b)&&(s==0||s>i[1].b)){w=i[0]+G1e+i[1];E=new y2c(w,w);Po(E,zFe,i[0]);Po(E,yFe,i[1]);oXb(C.d,C.e++,E)}}if(C.e!=0){this.g=new Hdb;ydb(this.g,CFe);Bdb(this.g,new RM);this.g.g=true;this.g.F=0;this.g.Vb=true;CM(this.g.B,C);Xcb(this.g,new Vzd);ecb(this.g,shd(lcf,mcf));bT(B,this.g,new szb(0.6))}}C9(this.j,shd(A1e,B1e));E9(this.j,zFe);Rx(this.j,zFe);bT(z,this.j,p);x=new kT;x.Mc?Jk(x.vc,kFe,hcf):(x.Tc+='paddingLeft:10px;');q=new aAb(uib);q.k=40;BS(x,q);C9(this.c,shd(E1e,F1e));E9(this.c,yFe);Rx(this.c,yFe);bT(x,this.c,p);bT(B,z,new szb(0.2));bT(B,x,new szb(0.2));bT(o,B,new Szb(tHe));r=new RLc;Aw(r,new Yzd(this),(DPb(),DPb(),CPb));r.dd.id='cropbox';QLc(r,c.z);eT(o,r,o.Kb.e);this.i=new dkb;Ujb(this.i,Pbc);E9(this.i,iFe);Rx(this.i,iFe);Zx(this.i,false);aT(o,this.i);this.d=new dkb;Ujb(this.d,Pbc);E9(this.d,hFe);Rx(this.d,hFe);Zx(this.d,false);aT(o,this.d);e=new J8;g=new YX(shd(P_e,P_e),new _zd(this));D=new YX(shd(O_e,O_e),new dAd(this,c));v8(e,D,e.Kb.e);v8(e,g,e.Kb.e);PT(this,(ie(),fe));OT(this,e);A=new hAd(this);Uw(this.j,VC,A);Uw(this.c,VC,A);tS(this,o,this.Kb.e);this.Q=true;this.Ab=true;this.u=false}
var ecf='#cropbox',kcf='-crop',hcf='10px',gcf='JahiaGxtImageCrop',ncf='failure.crop.label',fcf='label.crop',icf='paddingRight:10px;';$yc(786,774,{},EPb);_.Lk=function FPb(a){Mzd(xXb(xXb(a,226),391).b)};_.Ok=function GPb(){return CPb};var CPb;$yc(1030,182,UBe,RLc);$yc(1031,1032,{});_.Ul=function eMc(a,b){NLc(a,new jMc(a));a.b.Ul(a,b)};$yc(1034,1032,{});_.Ul=function nMc(a,b){!!a.b&&(a.b.Rl(a)[YQe]=XDe,undefined);UMb(a.dd,b.b)};$yc(1574,363,sCe,Ozd);_.Rm=function Pzd(a,b,c,d){var e,g,i;jcb(this.d,sRc(a));jcb(this.i,sRc(b));H9(this.j,XDe+c);H9(this.c,XDe+d);if(this.b){g=xXb(this.f.me(),1);e=ASc(g,RSc(46));this.f.Ri(ISc(g,0,g.lastIndexOf(kcf))+kcf+c+eIe+d+(e!=-1?ISc(g,e,g.length):XDe))}i=this.g?xXb(hdb(this.g),331):null;!!i&&(c!=xXb(Mo(i,zFe),283).b||d!=xXb(Mo(i,yFe),283).b)&&$cb(this.g)};_.b=true;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;_.i=null;_.j=null;$yc(1575,1,NBe,Szd);_.Bd=function Tzd(a){Rzd(this,xXb(a,62))};_.b=null;$yc(1576,234,NBe,Vzd);_.tg=function Wzd(a){var b;b=xXb(XF(a),331);Nzd(xXb(Mo(b,zFe),283).b,xXb(Mo(b,yFe),283).b)};$yc(1577,1,{226:1,231:1,391:1},Yzd);_.b=null;$yc(1578,236,NBe,_zd);_.ug=function aAd(a){$zd(this,xXb(a,59))};_.b=null;$yc(1579,236,NBe,dAd);_.ug=function eAd(a){cAd(this,xXb(a,59))};_.b=null;_.c=null;$yc(1580,1,NBe,hAd);_.Bd=function iAd(a){gAd(this,xXb(a,62))};_.b=null;$yc(1581,1197,{},kAd);_.jm=function lAd(a){if(zXb(a,380)){qBc(shd(C0e,C0e)+NDe+shd(i9e,i9e))&&Lzd(this.b,this.e,this.f,this.g,this.d,this.i,this.c,true)}else{pBc(shd(ncf,ncf)+NDe+a.ld());rb(shd(ncf,ncf),a)}};_.Ie=function mAd(a){var b;HY(this.b,null);b=new LYc;b.Ud(b$e,(FPc(),FPc(),EPc));YBd(this.b.e,b)};_.b=null;_.c=0;_.d=0;_.e=null;_.f=null;_.g=0;_.i=0;$yc(2126,1,rDe);_.Hk=function ufe(){$Y(new Ozd(this.b.p,this.b.p.o.r,this.b.b))};var aic=uQc(Daf,'ImageCrop',1574),Vhc=uQc(Daf,'ImageCrop$1',1575),Whc=uQc(Daf,'ImageCrop$2',1576),Xhc=uQc(Daf,'ImageCrop$3',1577),Yhc=uQc(Daf,'ImageCrop$4',1578),Zhc=uQc(Daf,'ImageCrop$5',1579),$hc=uQc(Daf,'ImageCrop$6',1580),_hc=uQc(Daf,'ImageCrop$7',1581),c8b=uQc(mbf,Ubf,786);JDe(OKb)(2);