function Myd(a){this.b=a}
function Ryd(a){this.b=a}
function Dge(a){this.b=a}
function ST(a,b){c$(a.xb,b)}
function Qyd(a){HY(a.b,null)}
function Cge(a){$Y(new Dyd(a.b.b.p,a.b.b.p.o,a.b.b.c))}
function Jyd(a,b,c,d,e){this.b=a;this.c=b;this.d=c;this.e=d;this.f=e}
function Fyd(a,b,c,d,e,g,i){this.b=a;this.d=b;this.e=c;this.c=d;this.g=e;this.f=g;this.i=i}
function Iyd(a){var b,c;HY(a.b,null);UBd(a.c,shd(C7e,C7e));b=iid();c=new Myd(a.c);a.d?Kid(b,a.e,c):Kjd(b,a.e,xXb(t9(a.f),1),c)}
function Kjd(b,c,d,e){var g,i,j;i=new lGc(b,UVe,'markForDeletion');try{j=kGc(i,VVe,2);zFc(j,vFc(j,WVe));zFc(j,vFc(j,jSe));AFc(j,c);zFc(j,vFc(j,d));jGc(i,e,(DGc(),CGc))}catch(a){a=byc(a);if(zXb(a,255)){g=a;n1c(e,g)}else throw a}}
function Cyd(a,b){var c;b>1?(c=thd('message.remove.multiple.confirm','Do you really want to remove the {0} selected resources?',nXb(Qwc,DBe,1,[XDe+b]))):xXb(Mo(xXb(a.j.Gl(0),349),_Ue),303).ae(i$e)?(c=thd('message.remove.single.page.confirm','Do you really want to remove the selected PAGE {0}?',nXb(Qwc,DBe,1,[xXb(Mo(a.r,IIe),1)]))):(c=thd(W3e,X3e,nXb(Qwc,DBe,1,[xXb(Mo(a.r,IIe),1)])));return c}
function Dyd(a,b,c){Tw();var d,e,g,i,j,k,n,o,p,q,r,s;aZ.call(this);iz(this,650,500);b$(this.xb,ocf);!!this.H&&Bk(rk(this.H,hLe),ocf);YY(this,false);this.b=new _hb;RT(this.b,shd(D_e,D_e));this.b.Ab=false;Jx(this.b,false);Rx(this.b,'JahiaGxtDeleteItem');BS(this.b,new Azb(0));iz(this.b,650,500);s=new p$;aT(this.b,s);o=new HIc;p=new HIc;for(k=b.j.ce();k.ie();){j=xXb(k.je(),349);oXb(o.d,o.e++,j);vIc(p,xXb(Mo(j,FUe),1))}g=new VT;BS(g,new Jxb);g.kc=0;g.Mc&&sk(fl(ix(g),DHe),false);g.Ab=false;this.c=dDd(o);iz(this.c,650,200);aT(g,this.c);aT(this.b,g);r=new Jlb;iz(r,620,100);if(!c){aT(this.b,new q$('<br />'+shd(I6e,J6e)+': <br />'));aT(this.b,r)}i=o.e;iq(this.c.I.f,new Fyd(this,b,i,g,r,c,s));if(c){n=shd(o9e,'<br/><span style="font-style:bold;color:red;">Warning: this will erase the content definitively from the repository<br/>So it will not be displayed anymore anywere<\/span>');aT(this.b,new q$(n));ST(this,(xod(),wod(),tod))}q=new YX(shd(F7e,F7e),new Jyd(this,a,c,p,r));e=new YX(shd(G7e,G7e),new Ryd(this));d=new J8;y8(d,(ie(),fe));v8(d,q,d.Kb.e);v8(d,e,d.Kb.e);aT(this.b,d);OT(this,d);iS(this,this.b)}
var ocf='Informations';$yc(1557,363,sCe,Dyd);_.b=null;_.c=null;$yc(1558,225,NBe,Fyd);_.pg=function Gyd(a){var b,c,d;b=xXb(a.d,303);c=b.Xd();d=Cyd(this.d,this.e);if(c>0){d+='<br /><br />'+(this.e>1?shd('message.remove.multiple.usage','Those nodes are still used in:'):shd('message.remove.single.usage','This node is still used by:'))}else{jT(this.b.b,this.c);jz(this.g,'620','70%');if(this.f){iz(this.b,-1,130);iz(this.b.b,-1,130)}}o$(this.i,d);uS(this.b.b,false)};_.b=null;_.c=null;_.d=null;_.e=0;_.f=false;_.g=null;_.i=null;$yc(1559,236,NBe,Jyd);_.ug=function Kyd(a){Iyd(this,xXb(a,59))};_.b=null;_.c=null;_.d=false;_.e=null;_.f=null;$yc(1560,1197,{},Myd);_.jm=function Nyd(a){TBd(this.b);rb(a.md(),a);j2(shd(_Ve,jOe),a.md(),null)};_.Ie=function Oyd(a){var b;TBd(this.b);b=new LYc;b.Ud(a$e,(FPc(),FPc(),EPc));YBd(this.b,b);_Bd(this.b)};_.b=null;$yc(1561,236,NBe,Ryd);_.ug=function Syd(a){Qyd(this,xXb(a,59))};_.b=null;$yc(2143,1,rDe);_.Hk=function Age(){var a,b,c,d,e;c=this.b.p.o;if(!c.j.Sd()){b=new HIc;for(e=c.j.ce();e.ie();){d=xXb(e.je(),349);vIc(b,xXb(Mo(d,FUe),1))}a=iid();rjd(a,b,new Dge(this))}};$yc(2144,1197,{},Dge);_.jm=function Ege(a){pBc(s8e+a.md())};_.Ie=function Fge(a){Cge(this,xXb(a,303))};_.b=null;var crc=uQc(Iaf,'DeleteActionItem$1$1',2144),Ihc=uQc(Daf,'DeleteItemWindow',1557),Ehc=uQc(Daf,'DeleteItemWindow$1',1558),Ghc=uQc(Daf,'DeleteItemWindow$2',1559),Fhc=uQc(Daf,'DeleteItemWindow$2$1',1560),Hhc=uQc(Daf,'DeleteItemWindow$3',1561);JDe(OKb)(3);